### ISSUE TITLE
Using Vue.set in a store mutation incorrectly logs warning in tests

### ISSUE THREAD

**Issue by danielelkington** [vuejs/vue-test-utils#1002]
### Version
1.0.0-beta.25

### Reproduction link
[https://codesandbox.io/s/p5m0zjoqlm](https://codesandbox.io/s/p5m0zjoqlm)

### Steps to reproduce
Run the tests in the code sandbox. When a store mutation calls Vue.set to manipulate the state, the warning `Error in callback for watcher "function () { return this._data.$$state }": "Error: [vuex] Do not mutate vuex store state outside mutation handlers.` gets logged.

### What is expected?
No warning logged because we are mutating the vuex store state inside a mutation handler.

### What is actually happening?
Warning incorrectly logged.

---
This doesn't happen if you set the property directly (which is a bad idea because we might be adding a new property to the object) or when running the code outside of tests.

**Comment by aholzner** [comment]
@danielelkington I'm not sure what are you trying to do, but you probably aren't using 'Vue.set' correctly.


```
import Vue from "vue";
export const state = {
  people: {}
};

export const mutations = {
  setPersonUsingVueSetMethod(state, payload) {
    Vue.set(state.people, "id", payload.id);
    Vue.set(state.people, "person", payload.person);
    console.log(state.people);
  },
};
```

```
import { createLocalVue } from "@vue/test-utils";
import Vuex from "vuex";
import { state, mutations } from "./store";

describe("store", () => {
  it("setPersonUsingVueSetMethod throws warning", () => {
    createLocalVue().use(Vuex);
    const store = new Vuex.Store({ state, mutations });
    store.commit("setPersonUsingVueSetMethod", {
      id: 1,
      person: { name: "Jim" }
    });
  });
});
```

Also using it like this, doesn't log any warning,

```
import { createLocalVue } from "@vue/test-utils";
import Vuex from "vuex";
import { state, mutations } from "./store";

describe("store", () => {
  it("setPersonUsingVueSetMethod throws warning", () => {
    createLocalVue().use(Vuex);
    const store = new Vuex.Store({ state, mutations });
    store.commit("setPersonUsingVueSetMethod", {
      id: 1,
      person: { name: "Jim" }
    });
  });

  // it("setPersonWithoutUsingVueSetMethod does not throw warning", () => {
  //   createLocalVue().use(Vuex);
  //   const store = new Vuex.Store({ state, mutations, strict: true });
  //   store.commit("setPersonWithoutUsingVueSetMethod", {
  //     id: 1,
  //     person: { name: "Jim" }
  //   });
  // });
});
```

```
import Vue from "vue";
export const state = {
  people: {}
};

export const mutations = {
  setPersonUsingVueSetMethod(state, payload) {
    Vue.set(state.people, payload.id.toString(), payload.person);
  }
  // setPersonWithoutUsingVueSetMethod(state, payload) {
  //   state.people[payload.id.toString()] = payload.person;
  // }
};

```

**Comment by danielelkington** [comment]
Thanks for the investigation @aholzner and noting that commenting out the second test stops the warning.  In a project I'm working on this problem is reproducible with a single test calling the store mutation once, however I'm unable to reproduce it in an isolated example, so I'll close this issue for now.
