### ISSUE TITLE
shallowMount : TypeError: Cannot read property 'breakpoint' of undefined

### ISSUE THREAD

**Issue by chauriya** [vuejs/vue-test-utils#1013]
### Version
1.0.0-beta.25

### Reproduction link
[https://codesandbox.io/s/8xrrjpy349](https://codesandbox.io/s/8xrrjpy349)

### Steps to reproduce
1. Copy sample code setup from `https://codesandbox.io/s/8xrrjpy349`
1. Run `npm install`
2. Run `npm run test` test execution will start and it will throw an error `TypeError: Cannot read property 'breakpoint' of undefined`

### What is expected?
Test should run without error as given in documents `https://vue-test-utils.vuejs.org/api/shallowMount.html`

### What is actually happening?
Returning TypeError

---
1. project is setup using nuxt and vuetify.js
2. Added package.json in code setup with will give competed jest and vue-test-utils configuration information
3. Only bare minimum files are added to code sample

**Comment by eddyerburgh** [comment]
Only components are stubbed by `shallowMount`.

You're accessing `$vuetify.breakpoint` in the template of your component, which isn't stubbed by Vue Test Utils. 

You need to add instance method, you need to use the `mocks` mounting option:

```js
const wrapper = shallowMount(Titlebar, {
  mocks: {
    $vuetify: { breakpoint: {} }
  }
})
```

**Comment by chauriya** [comment]
@eddyerburgh Thanks!!

**Comment by MannyDiera** [comment]
I'm working on a project with Vuetify and Typescript and no matter what I try, I always get
`TypeError: Cannot read property 'smAndUp' of undefined.`

Have added the vue.use(Vuetify);

Also tried adding the $vuetify object inside mocks but no luck. Anyone run into this issue?

**Comment by sophiews-up** [comment]
Hey @MannyDiera have a look at vuetify's docks on mocking https://vuetifyjs.com/en/getting-started/unit-testing/#mocking-vuetify.
This worked for me:
``` javascript
let vuetify = new Vuetify({
   mocks: {
        $vuetify: {
            breakpoint: {
                smAndUp: true
            },
        },
    }
})
const wrapper = shallowMount(Titlebar, {
    vuetify
})
```

**Comment by eng1n88r** [comment]
We are getting `TypeError: Cannot read property 'mobileBreakpoint' of undefined` in **shallowMount**.

**Comment by hodovani** [comment]
@exbarboss Could you please try to add `vuetify` to the `mock`

```javascript
import Vuetify from 'vuetify';

const vuetify = new Vuetify();

const wrapper = shallowMount(VueComponentName, {
  mocks: {
    ...
  },
  vuetify,
});
```

This works for me.

**Comment by eng1n88r** [comment]
@hodovani Hi! Just tried and it is not recognizing any Vuetify components, but I think I was able to make it work:

```javascript
import { shallowMount } from '@vue/test-utils';
import Vue from 'vue';
import Vuetify from 'vuetify';
import SideNav from '@/components/layout/SideNav.vue';

const vuetify = new Vuetify();

Vue.use(Vuetify); // <= Tried to pass here constant from above and tests are failing

describe('SideNav.vue component tests', () => {
	test('is rendering correctly', () => {
		const wrapper = shallowMount(SideNav, {
			propsData: {
				show: true,
			},
			vuetify,
		});
		expect(wrapper.element).toMatchSnapshot();
	});

	it('is Vue component', () => {
		const wrapper = shallowMount(SideNav, {
			propsData: {
				show: true,
			},
			vuetify,
		});

		expect(wrapper.isVueInstance());
	});
});
```


@hodovani Thanks!

**Comment by dipesh-wadhwa** [comment]
@hodovani @exbarboss Thanks. Your suggestion works for me.

**Comment by michaelbrawn** [comment]
> @exbarboss Could you please try to add `vuetify` to the `mock`
> 
> ```js
> import Vuetify from 'vuetify';
> 
> const vuetify = new Vuetify();
> 
> const wrapper = shallowMount(VueComponentName, {
>   mocks: {
>     ...
>   },
>   vuetify,
> });
> ```
> 
> This works for me.

If we're using a setup file, why is this required? 

```json
// jest.config.js
...
setupFilesAfterEnv: [
    '<rootDir>tests/unit/setup.js',
  ],
...
```

```js
// tests/unit/setup.js

import Vue from 'vue';
import Vuetify from 'vuetify';

Vue.use(Vuetify);
```

### **Answer**

Importing vuetify is required as it's needed for the wrapper. 

```js
import { shallowMount } from '@vue/test-utils';
import Vuetify from 'vuetify';
import Titlebar from 'src/components/Titlebar.vue';

const vuetify = new Vuetify();

test('displays message', () => {
  // shallowMount() returns a wrapped Vue component we can interact with
  const wrapper = shallowMount(Titlebar, {
    propsData: {
      appName: 'Hello world',
    },
    vuetify,
  });
  
  // Assert the rendered text of the component
  expect(wrapper.text()).toContain('Hello world');
});
```
