### ISSUE TITLE
Global filters aren't loaded in localVue

### ISSUE THREAD

**Issue by LouWii** [vuejs/vue-test-utils#1019]
### Version
1.0.0-beta.25

### Reproduction link
[https://github.com/LouWii/filter-bug-vue-test-utils](https://github.com/LouWii/filter-bug-vue-test-utils)

### Steps to reproduce
In a test, register a global filter in the localVue

```
const localVue = createLocalVue();

localVue.filter(toShortDate);

const wrapper = mount(TestComponent, {localVue})
```

Run the test.

### What is expected?
Test is passing, no error nor warning is thrown.

### What is actually happening?
An error in logged

```
ERROR LOG: '[Vue warn]: Failed to resolve filter: toShortDate

(found in <TestComponent> at src/Components/TestComponent.vue)'
```

**Comment by shannonarcher** [comment]
You failed to give the filter a name when you registered it to your localVue.

```
const localVue = createLocalVue();

localVue.filter('toShortDate', toShortDate); // <- need to give it a name like you did in testApp.js Vue.filter('toShortDate', toShortDate);

const wrapper = mount(TestComponent, {localVue});
```

will get rid of the warning message that you are seeing.

**Comment by LouWii** [comment]
Ugh, right! It fixed it. Dumb mistake on my end. Thanks!
