### ISSUE TITLE
Testing computed props

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/vue-test-utils#103]
Hey,

Is there a good way to test computed properties? I have something like

``` js
// MyComponent.vue
<template>
  <div :class="computedClass">
  </div>
</div>

export default {
  props: {
    customClass: {
      type: String
    },
  },

  computed: { 
    computedClass () { return this.props.customClass }
  }
}
```

Test

``` js
const wrapper = shallow(MyComponent, {
  propsData() { customClass: 'aaa' }
})

wrapper.vm.setProps({ customClass: 'bbb' })

const actual = wrapper.vm.$options.computed.computedClass()
expect(actual).toEqual('bbb')
```

In all cases, the prop is `undefined`. I can dig deeper if needed, I haven't looked at the source much yet. If I do {{ computedClass }} in the template it does indeed work fine.

Any good option to test computed methods? Or I can look to add something.

Thanks!

**Comment by blocka** [comment]
You check it as you would check any data property on the component

**Comment by lmiller1990** [comment]
So you do. Thanks.
