### ISSUE TITLE
Re-render does not occur synchronously when reactive data is changed in mounted life-cycle hook

### ISSUE THREAD

**Issue by Aaron-Pool** [vuejs/vue-test-utils#1035]
### Version
1.0.0-beta.25

### Reproduction link
[https://github.com/Aaron-Pool/vue-test-utils-jest-example](https://github.com/Aaron-Pool/vue-test-utils-jest-example)

### Steps to reproduce
1. clone reproduction repo
2. `Run yarn`
3. run `yarn jest`

### What is expected?
Test should pass, because reactive data changed in the mount component, so the scoped slot function should have been called again on re-render.

### What is actually happening?
No re-render occurs, even though the data updates as expected.

---
I assume this has something to do with async vs. sync paradigm that is happening in the test-utils.

It works correctly if I run the test like so:

```js
it('should initialize with dimension data', done => {
  const mockSlot = jest.fn();
  const comp = factory(mockSlot);
  comp.vm.$nextTick(() => {
    expect(mockSlot.mock.calls).toEqual([[{ width: null, height: null }], [{ width: 500, height: 500 }]]);
    done();
  })
});
```

**Comment by pgoshulak** [comment]
recognizing this doesn't directly address the synchronicity issue, I found a slightly more elegant temporary workaround is to make the test `async`, then run as:
```js
const comp = factory(mockSlot)
await comp.vm.$nextTick()
expect(........)
```

**Comment by Aaron-Pool** [comment]
@pgoshulak Thanks for the heads up on that 👍 I may implement that as a stopgap as well, to make things cleaner.
