### ISSUE TITLE
Created hook fired multiple times for mixins when mounted using Vue test utils

### ISSUE THREAD

**Issue by jimmaaay** [vuejs/vue-test-utils#1037]
### Version
1.0.0-beta.25

### Reproduction link
[https://github.com/jimmaaay/vue-test-utils-created-hook-issue](https://github.com/jimmaaay/vue-test-utils-created-hook-issue)

### Steps to reproduce
1. Clone repo
2. Run `npm run test:unit`

### What is expected?
A console.log output of:

Mixin1: Created
Mixin2: Created
App: Created

### What is actually happening?
A console.log output of (minus unnecessary lines):

Mixin1: Created
Mixin2: Created
Mixin1: Created
Mixin2: Created
App: Created

---
If you run `npm run serve` and check the console in the browser you'll see the console output that I expect to see in the unit tests

**Comment by untier** [comment]
I have a similar problem with the "mounted"-hook.

**Comment by eddyerburgh** [comment]
This is fixed in Vue 2.5.18+
