### ISSUE TITLE
Can you provide an example of Mocha test asyn behavior?

### ISSUE THREAD

**Issue by weihongyu12** [vuejs/vue-test-utils#1043]
### What problem does this feature solve?
The current documentation example is based on Jest. I don't know if Mocha provides a mock method to test HTTP, so I would like to ask if there is any better solution for the official.

### What does the proposed API look like?
Update document example

**Comment by reginsmol** [comment]
Have you tried using nock or sinon? 
https://github.com/nock/nock
https://sinonjs.org/releases/v7.2.2/fake-xhr-and-server/

**Comment by eddyerburgh** [comment]
There are only so many guides that we will add to the docs, and I don't think we should add more info on testing async behavior.
