### ISSUE TITLE
Invalid html when mounting a certain html structure

### ISSUE THREAD

**Issue by adi-zz** [vuejs/vue-test-utils#1070]
### Version
1.0.0-beta.27

### Reproduction link
[https://codesandbox.io/s/0pvmr5wj9p](https://codesandbox.io/s/0pvmr5wj9p)

### Steps to reproduce
- Open https://codesandbox.io/s/0pvmr5wj9p
- After the "browser" inside codesandbox.io loads, notice there's no error in codesandbox's Console tab.
- Click on codesandbox's Tests tab. The one test I wrote will run.
- See Console.

### What is expected?
- wrapper.html() shoud return a string containing `<div class="component-1">Component 1</div>` - the content of Component.vue

### What is actually happening?
- a warning `Unknown custom element: <Component1> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`. Not sure why this appears when test runs.
- wrapper.html() returns a string containing `<component1></component1>`

---
If you remote the `<v-container>` from Parent.vue, test runs as expected.

**Comment by ChuckBorris33** [comment]
We have exactly same issue using vueBootstrap and localVue in tests. 

[https://codesandbox.io/s/ywr3vw3oxx](https://codesandbox.io/s/ywr3vw3oxx)

This issue exists in version 1.0.0-beta.26 and 1.0.0-beta.27. Reverting to version 1.0.0-beta.25 solves issue.

**Comment by BeniRupp** [comment]
I have a similar problem using vuetify and 1.0.0-beta.27: https://codesandbox.io/s/4jqkrk42j7

If there is a custom component which contains any vuetify component, the custom component cannot be found (`Unknown custom element`) and therefore is not rendered. Removing the vuetify component will cause the expected rendering.
