### ISSUE TITLE
Provide chai assertions

### ISSUE THREAD

**Issue by jdoubleu** [vuejs/vue-test-utils#1072]
### What problem does this feature solve?
It would be nice to be able to access vue-test-utils assertions (e.g. [`Wrapper.exists()`](https://vue-test-utils.vuejs.org/api/wrapper/#exists)) via chai, just like [sinon-chai](https://github.com/domenic/sinon-chai).

Yet I have to use several assertions with chai's [`.to.be.true` chain](https://www.chaijs.com/api/bdd/#method_true).
When the test fails it is harder to read what went wrong and it is not easy to read.

Chai is recommended [here in the docs](https://vue-test-utils.vuejs.org/guides/#testing-single-file-components-with-karma).

### What does the proposed API look like?
When passing the [`Wrapper`](https://vue-test-utils.vuejs.org/api/wrapper) to chai's [`expect`](https://www.chaijs.com/api/bdd/) it is possible to use new chains very similar to the [methods of the `Wrapper`](https://vue-test-utils.vuejs.org/api/wrapper/#methods):
```
expect(wrapper).to.find('.btn').exists
expect(wrapper).to.contain('.btn')
// instead of
expect(wrapper.find('.btn').exists()).to.be.true
expect(wrapper.contains('.btn').to.be.true

expect(wrapper).to.have.emitted('some-event')
// instead of
expect(wrapper.emitted('some-event')).to.be.true

...
```

**Comment by eddyerburgh** [comment]
This should be added to an external package, rather than core. Feel free to make a package, and we can link to it in the docs :)

**Comment by jdoubleu** [comment]
I published a package which extends chai with assertions for vue-test-utils:
https://www.npmjs.com/package/vue-test-chai
