### ISSUE TITLE
Prop declared in mixin is not recognized when using shallowMount

### ISSUE THREAD

**Issue by lzhoucs** [vuejs/vue-test-utils#1094]
When `shallowMount` a component which passes down a boolean prop to a child component, such prop is SOMETIMES `undefined`. `mount` works as expected. Please see my demo repo tests for details.

### Version
1.0.0-beta.28

### Reproduction link
https://github.com/lzhoucs/vue-test-utils-bugreport/tree/1094-shallowMount-boolean-prop-issue

### Steps to reproduce
```
git clone git@github.com:lzhoucs/vue-test-utils-bugreport.git
git checkout 1094-shallowMount-boolean-prop-issue

yarn install
yarn test:unit
```

### What is expected?
All 3 tests pass

### What is actually happening?
the one with vuetify's `V-Btn` fails

---
Not sure if this is a vuetify issue or vue-test-utils one. Filed it here for now.

**Comment by lzhoucs** [comment]
I think this is the same issue as https://github.com/vuejs/vue-test-utils/issues/1096. VBtn's `disabled` prop is in one of its mixin too.

**Comment by eddyerburgh** [comment]
Thanks for investigating further. You're correct, this is the same issue as https://github.com/vuejs/vue-test-utils/issues/1096
