### ISSUE TITLE
Support stubbing unregistered components

### ISSUE THREAD

**Issue by panganibanpj** [vuejs/vue-test-utils#110]
### What problem does this feature solve?
Cannot currently stub components that aren't registered. Since `babel-plugin-transform-vue-jsx` [highlights that u don't need to register your components](https://github.com/vuejs/babel-plugin-transform-vue-jsx/blob/master/README.md#component-tip), people (like me!) may be inclined to use it this way and have trouble when it comes to testing higher level components without stubs. Currently I'm working around this using proxyquire to stub in a mock component. At the very least mention this as a limitation in the docs

### What does the proposed API look like?
Ideally there would be no change
Trying to do something like:

```javascript
// Parent
import Child
export default { render() { return <Child />; } };

// Child
export default { render() { return <div/>; } };

// Test
import Parent;
import Child;
shallow(Parent);
// maybe
shallow(Parent, { stubs: { [Child]: '<span/>' } });
```
Currently, this will render the `<div/>`

Another idea is maybe make the `stub` option also look into component `name`s so you'd simply have to
```javascript
// Child
export default { name: 'Child', render() { ... } };

// Test
shallow(Parent, { stubs: ['Child'] });
```

I know I'm using JSX here but seems to be an issue w vanilla Vue too:
```javascript
const Child = { render(h) { return h('div'); } };
const Parent = { render(h) { return h(Child); } };
```

**Comment by panganibanpj** [comment]
Oops! Meant to name this "Support *stubbing* registered components". Sorry! On my phone and don't know how to change it!

**Comment by blocka** [comment]
Ultimately, I think the solution for this is make shallow _actually_ do a
shallow render. I'm pretty sure that's what enzyme does. Enzyme also has a
concept called diving which allows you to "dive" into the next layer

**Comment by eddyerburgh** [comment]
This is now supported in beta.27 (from #1038)
