### ISSUE TITLE
wrapper.props() includes unset properties

### ISSUE THREAD

**Issue by lusarz** [vuejs/vue-test-utils#1104]
### Version
1.0.0-beta.28

### Reproduction link
[https://github.com/lusarz/vue-test-utils-examples/commit/15caf10869fcf6ffe5d04a9a2dbb2111ffc79a9e](https://github.com/lusarz/vue-test-utils-examples/commit/15caf10869fcf6ffe5d04a9a2dbb2111ffc79a9e)

### Steps to reproduce
1) Create [child component with two props](https://github.com/lusarz/vue-test-utils-examples/blob/15caf10869fcf6ffe5d04a9a2dbb2111ffc79a9e/src/components/Child.vue#L8-L9)
2) Pass [one property](https://github.com/lusarz/vue-test-utils-examples/blob/15caf10869fcf6ffe5d04a9a2dbb2111ffc79a9e/src/components/Parent.vue#L3-L5) to child component in template
3) Check [wrapper.find(Child).props()](https://github.com/lusarz/vue-test-utils-examples/blob/15caf10869fcf6ffe5d04a9a2dbb2111ffc79a9e/test/unit/specs/Parent.spec.js#L15)

### What is expected?
When property is not set in template, object returned by `wrapper.props()` method [not include it (even as undefined)](https://github.com/lusarz/vue-test-utils-examples/blob/15caf10869fcf6ffe5d04a9a2dbb2111ffc79a9e/test/unit/specs/Parent.spec.js#L9)

### What is actually happening?
Object returned by `wrapper.props()` contains not set prop.
![output](https://user-images.githubusercontent.com/10059264/51309193-26a5a900-1a44-11e9-8a21-b65c1a94de3b.png)

**Comment by eddyerburgh** [comment]
Since the `$props` object contains props, even if they are undefined, we'll keep the existing behavior
