### ISSUE TITLE
How to mock CKEDITOR in vue-jest

### ISSUE THREAD

**Issue by Sakthi002** [vuejs/vue-test-utils#1120]
### What problem does this feature solve?
 i want to achive 100% test coverage

**Comment by eddyerburgh** [comment]
Hi, sorry that you're having issues with Vue Test Utils, but the issue tracker is reserved for bugs and feature requests. Your question would best be answered on StackOverflow.

If you think you found a bug, please create a minimal reproduction and open a new issue.
