### ISSUE TITLE
Testing with Apollo mocks

### ISSUE THREAD

**Issue by ferllings** [vuejs/vue-test-utils#113]
Hello,

I’m trying to test my app using Jest and apollo-test-utils to mock my graphql api.

But I don’t understand to link the Apollo client and the component instance.

```
describe('products.vue', () => {
  let cmp;
  beforeEach(() => {
    const networkInterface = mockNetworkInterface(...GraphQLMocks);
    const apolloClient = new ApolloClient({
      networkInterface,
      addTypename: false
    });

    cmp = shallow(Products, {
       apolloClient ???
    });
  });
  test('should render correct contents', () => {
    expect(cmp.element).toMatchSnapshot();
  });
```

Thanks for your help.

**Comment by eddyerburgh** [comment]
Hi, thanks for the issue, but you should ask this on StackOverflow or the Vue discord channel.

The issue tracker is for feature requests and bug reports.

*it looks like you need to install Vue appolo on the Vue constructor. You can link the apollo client to the Vue instance the way you are doing in your example.*
