### ISSUE TITLE
server-test-utils: render() returns Cheerio not string (d.ts)

### ISSUE THREAD

**Issue by wiese** [vuejs/vue-test-utils#1131]
### Version
1.0.0-beta.29

### Reproduction link
[https://codesandbox.io/s/4xvk5l7mo9](https://codesandbox.io/s/4xvk5l7mo9)

### Steps to reproduce
[index.d.ts](https://github.com/vuejs/vue-test-utils/blob/v1.0.0-beta.29/packages/server-test-utils/types/index.d.ts#L58) declares `render()` as returning `string` while the [documentation](https://vue-test-utils.vuejs.org/api/render.html#render) states that it is indeed "CheerioWrapper" (`Cheerio`) - the latter is also what can be observed when inspecting the result.

(f3dfb1e81f43c05d8ae871dba9184d83a3b3548e, for #571, may have been an impediment for this in the past but is long fixed.)

### What is expected?
`render()` type definition declares `Cheerio` return value.

### What is actually happening?
`render()` type definition declares `string` return value.

---
We created [a hack around this](https://gerrit.wikimedia.org/r/c/wikibase/termbox/+/487887/1/tests/unit/components/Sectionedit.spec.ts#14) using [@types/cheerio](https://www.npmjs.com/package/@types/cheerio).

**Comment by eddyerburgh** [comment]
Thanks for the bug report, would you like to make the change to the types file—https://github.com/vuejs/vue-test-utils/blob/dev/packages/server-test-utils/types/index.d.ts?

**Comment by wiese** [comment]
Thanks for triaging. Will provide a PR during the course of this week.
