### ISSUE TITLE
Always store selector in Wrapper created by wrapper.find(...)

### ISSUE THREAD

**Issue by ghost** [vuejs/vue-test-utils#1135]
### What problem does this feature solve?

When using `wrapper.find(...)`, the returned new wrapper only knows the selector if nothing was found. This makes it difficult to debug tests with dynamic selectors and to create custom matchers like `expect(wrapper.find('.something')).toExist()`.

### What does the proposed API look like?

Make Wrapper always have a `selector` property when created with `.find(...)`—not only `ErrorWrapper` ( https://github.com/vuejs/vue-test-utils/blob/36adbf357fe2e6085d826e143b32d0fa37b6d938/packages/test-utils/src/error-wrapper.js#L9 ).

**Comment by eddyerburgh** [comment]
This is a great idea :)

Would you like to implement it @gitlab-winnie ?

**Comment by ghost** [comment]
> Would you like to implement it @gitlab-winnie ?

I can't make any Promise yet but have to await my workload for the next month. Definitely interested in getting my feet wet at the Vue test utils beach though. 🏖

**Comment by winniehell** [comment]
I started working on this in https://github.com/vuejs/vue-test-utils/pull/1248.
