### ISSUE TITLE
Components Mocks are undefined

### ISSUE THREAD

**Issue by AtofStryker** [vuejs/vue-test-utils#1136]
### Version
1.0.0-beta.28

### Reproduction link
[https://codesandbox.io/s/006nwoxz0](https://codesandbox.io/s/006nwoxz0)

### Steps to reproduce
with a fresh package-lock and install, try to mock $i18n or $route injection. The injections will show up as undefined. 

### What is expected?
the injected mocks show up as defined

### What is actually happening?
the injections are undefined

---
This was working for me before I purged my package locks and node_modules and prompted a reinstall. Is it possible a nested dependency is broken. This was also seen in beta 25

**Comment by eddyerburgh** [comment]
Can you create a reproduction in a GitHub repo? I can't reproduce this on CodeSandbox or locally

**Comment by AtofStryker** [comment]
@eddyerburgh I figured  that would be the case. let me work on something today and I'll get back to you.

**Comment by AtofStryker** [comment]
@eddyerburgh try this:
https://github.com/AtofStryker/vuetestUtilsBug 
let me know if you have any problems. Access should be good to go

I should also mention I'm on versions:
node v8.10.0
npm v5.6.0

**Comment by steven87vt** [comment]
+1 for this. I've been trying to work around the localVue/router creating a read only $route property so I have tried to use the code from the guide (https://vue-test-utils.vuejs.org/guides/#mocking-route-and-router) but $route is undefined.

**Comment by eddyerburgh** [comment]
@AtofStryker your reproduction can be fixed by either passing in `i18n` to the mounting options:

```js
const i18n = new VueI18n({})
const TestComponent = {
    template: `<h1> test</h1>`,
    mixins: [i18nMixin.default()]
}
var comp =  mount(TestComponent, {
    localVue,
    i18n
})
```

Or by not passing `localVue` and using the `mocks` option:

```js
const TestComponent = {
    template: `<h1> test</h1>`,
    mixins: [i18nMixin.default()]
}
var comp =  mount(TestComponent, {
    mocks: {
        $i18n: {
            mergeLocaleMessage() {}
        }
    }
})
```

**Comment by AtofStryker** [comment]
@eddyerburgh  sorry for the delayed response. Been a busy few weeks! I went with option A. We still have some pain points with Vuetify's plugin registry n the global instance, so this seems to be the proper approach for now until 2.0 comes out. Thanks for the help!
