### ISSUE TITLE
Functional component mount().element equals #comment

### ISSUE THREAD

**Issue by rssfrncs** [vuejs/vue-test-utils#114]
I have a functional component which accepts a "data" prop. This props is not required and by default returns an empty array,

![image](https://user-images.githubusercontent.com/7808978/31809631-8048ad5c-b570-11e7-82ce-47d1677efc60.png)

I have the following basic test to assert that an <svg /> is rendered,

![image](https://user-images.githubusercontent.com/7808978/31809613-70b2bebe-b570-11e7-954a-2e6926e9d9ac.png)

When i run the test it fails with the following message,

![image](https://user-images.githubusercontent.com/7808978/31809654-95ae56c4-b570-11e7-998c-b48f86160c75.png)

When I change the component to not being functional, the same test passes.

**Comment by blake-newman** [comment]
This most likely relates to #73

**Comment by blake-newman** [comment]
This will be fixed with #115 

Closing: Releasing Monday
