### ISSUE TITLE
[Question] how test action with promise

### ISSUE THREAD

**Issue by Ceda** [vuejs/vue-test-utils#1149]
### Version
1.0.0-beta.29

### Reproduction link
[https://codesandbox.io/s/7z1r734oq6](https://codesandbox.io/s/7z1r734oq6)

### Steps to reproduce
When click to button, it call promise and set variable after timeout.
In test i expect value from promise, but not get :/

### What is expected?
Expect value from promise

### What is actually happening?
Assert return empty value

---
Can anybody help me how can test async function?

**Comment by eddyerburgh** [comment]
You can read our guide on [testing asynchronous behavior](https://vue-test-utils.vuejs.org/guides/testing-async-components.html), but otherwise you should ask these kinds of questions on StackOverflow
