### ISSUE TITLE
请问怎么测试复制和粘贴？

### ISSUE THREAD

**Issue by BTCB** [vuejs/vue-test-utils#1151]
### What problem does this feature solve?
使用vue-clipboard2点击复制，但不知道怎么测试粘贴功能，请问复制粘贴有必要用Jest测试吗？
使用Jest测试的时候，只能获取到复制失败回调，并不能复制成功。

### What does the proposed API look like?
希望能提供复制的Jest测试功能

**Comment by BTCB** [comment]
How to test copy and paste?

Use vue-clipboard 2 to click on copy, but do not know how to test the paste function. Is it necessary to use Jest test for copy and paste?

When using Jest test, only replication failure callbacks can be obtained, not replication success.

Hope to provide replicated Jest test function.

**Comment by Jinjiang** [comment]
I suggest you mocking these clipboard APIs manually. Because the APIs are not Vue-related, and vue-test-utils is just utils for Vue-related features.

**Comment by Jinjiang** [comment]
And for Jest, it's only a testing framework, not mocker for a certain API. Maybe you can try https://sinonjs.org.
