### ISSUE TITLE
describe.only() not work

### ISSUE THREAD

**Issue by huangshuwei** [vuejs/vue-test-utils#1153]
### Version
1.0.0-beta.29

### Reproduction link
[https://codesandbox.io/s/6jx7wnxjqz](https://codesandbox.io/s/6jx7wnxjqz)

### Steps to reproduce
I have two test suites(Test1.spec.js、Test2.spec.js),and I want to run only one test suite.
I set up one of the suites by "describe.only()",but It dones't works

### What is expected?
only one test suites run

### What is actually happening?
all test suites run

**Comment by eddyerburgh** [comment]
This is how Jest behaves—https://github.com/facebook/jest/issues/4414

It's unfortunate behavior. I recommend running tests in watch mode so that you can run a single test after the initial tests run

**Comment by huangshuwei** [comment]
thx
