### ISSUE TITLE
Conditional rendering not respected?

### ISSUE THREAD

**Issue by chulman444** [vuejs/vue-test-utils#1155]
### Version
1.0.0-beta.20

### Reproduction link
[https://github.com/chulman444/vue-conditional-rendering-bug-demo](https://github.com/chulman444/vue-conditional-rendering-bug-demo)

### Steps to reproduce
run `npm run test:unit`

Please read:
* https://github.com/chulman444/vue-conditional-rendering-bug-demo/blob/master/src/components/IfElse.vue
  * Component
* https://github.com/chulman444/vue-conditional-rendering-bug-demo/blob/master/tests/unit/example.spec.js
  * Test

### What is expected?
Expect both logs to be:

```
// [Expected output]
[Before] reassigning value []
[After] reassigning value. Should be same as [Before] []
expect(vm.$refs["see-me"]).to.be.undefined undefined
$nextTick callback false ["see-me"]
```

### What is actually happening?
Getting the `[Expected output]` from the browser

Getting:

```
  Test
Before `vm.toggle()` []
[Before] reassigning value []
[After] reassigning value. Should be same as [Before] [ 'see-me' ]
expect(vm.$refs["see-me"]).to.be.undefined HTMLDivElement {}
After `vm.toggle()` [ 'see-me' ]
    1) test
$nextTick callback false [ 'see-me' ]
```

for the test.

---
Shouldn't side effect of changing the value that affects the conditional rendering happen in `this.$nextTick`?

**Comment by eddyerburgh** [comment]
Vue < beta.30 runs in sync mode by default. You can turn it off:

```js
shallowMount(TestComponent, { sync: false })
```

Future versions of Vue Test Utils (from beta.30 that will be released soon) will no longer run in sync mode, so will behave as you expected.

**Comment by chulman444** [comment]
With the `{ sync: false }` it works as expected. Updated my demo repo including both 'wrong', or more like shallowMount without the options, and one with the option.

Can't believe I missed this option. I swear I googled everywhere and read the documentations ... except that section:

* https://vue-test-utils.vuejs.org/api/options.html#sync
