### ISSUE TITLE
Can't set `which` when triggering `keydown` event

### ISSUE THREAD

**Issue by eostrom** [vuejs/vue-test-utils#1162]
### Version
1.0.0-beta.29

### Reproduction link
[https://codesandbox.io/s/8k2z89m41j?fontsize=14](https://codesandbox.io/s/8k2z89m41j?fontsize=14)

### Steps to reproduce
1. Open CodeSandbox URL.
2. Open Tests tab.

### What is expected?
The tests should pass. (The component and tests are copied from https://vue-test-utils.vuejs.org/guides/#testing-key-mouse-and-other-dom-events.)

### What is actually happening?
An error: "Cannot assign to read only property 'which' of object '#<KeyboardEvent>'"

---
I ran into this bug while trying to follow the guide to test keyboard events in my component.

**Comment by eostrom** [comment]
MDN says [`which` is deprecated and read-only](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/which), so maybe the problem is just that the documentation example is not widely supported. Following links, it seems that the appropriate non-deprecated property is `key`, and this [passes for me](https://codesandbox.io/s/xo6rmnnp8w). I'd be happy to submit a doc PR.

**Comment by eddyerburgh** [comment]
A PR to update the docs would be great :)
