### ISSUE TITLE
Functional component context is undefined if not defined in mount() option argument

### ISSUE THREAD

**Issue by rssfrncs** [vuejs/vue-test-utils#117]
Version: 1.0.0-beta.2

If you mount a functional component without passing a context object in the options argument,
```
it('Example mocha test', () => {
  const wrapper = mount(FunctionalComp)
  // assertions
})
```

when mocha executes the test case, context is undefined ,
![image](https://user-images.githubusercontent.com/7808978/31879833-8d9063f2-b7d6-11e7-9595-df9e560a4c43.png)

Passing `{ context: {} }` to the options of mount() is a workaround but not ideal.

**Comment by eddyerburgh** [comment]
Hi, this is in my list of todos. Would you be able to make a PR that implements this? If not, I'll be adding this feature at some point this week

**Comment by rssfrncs** [comment]
@eddyerburgh sure i'll take a look this evening

**Comment by rssfrncs** [comment]
@eddyerburgh Evening, I'm having a few issues running the test scripts.

run test:unit / test:unit:karma issue
![image](https://user-images.githubusercontent.com/7808978/31903152-30bde61a-b81f-11e7-812e-0343e14fd07a.png)

and run test issue

![image](https://user-images.githubusercontent.com/7808978/31903239-76c5df78-b81f-11e7-949a-a85fe684de28.png)

**Comment by eddyerburgh** [comment]
Yes let's talk about it in a PR. There's a Vue version mismatch. Confusing because the circle tests are passing. Potentially clearing your npm cache will solve the issue
