### ISSUE TITLE
Emitt event is not capture in watcher when value is empty string ''

### ISSUE THREAD

**Issue by ebisbe** [vuejs/vue-test-utils#1173]
### Version
1.0.0-beta.29

### Reproduction link
[https://codesandbox.io/s/lrr31y4vw9?fontsize=14](https://codesandbox.io/s/lrr31y4vw9?fontsize=14)

### Steps to reproduce
Trying to emit an event when the value assigned to a watched property is '' will cause the test to fail

### What is expected?
Emitted() should capture the event and the expected(wrapper.emitted().event).toBeTruthy() should pass.

### What is actually happening?
Wrapper.emitted() is {}

**Comment by eddyerburgh** [comment]
It's because the reactive property value is not changing when you set it to `''`. If `msg` is initialized with a different value, setting it to `''` will cause the watcher to trigger
