### ISSUE TITLE
Any consideration to exposing createStubFromComponent for usage outside the library?

### ISSUE THREAD

**Issue by scottadamsmith** [vuejs/vue-test-utils#1175]
### What problem does this feature solve?
I have some scenarios where I need (or want) to manually stub a vue component definition so that the definition coming from the import is already a stub. Would exporting this function be something that is worth considering? I think it would be incredibly useful. I also have some legacy tests that use Avoriaz for the time being and in those tests, I actually wrote an unfortunately complex function to build Vue mocks. Exposing this function would allow me to leverage this feature of vue-test-utils right away before I am able to fully transition all those tests to jest/vue-test-utils.

### What does the proposed API look like?
I am guessing this is an oversimplification and there are some dependencies I am not seeing, but my hope is the effort is just to export this createStubFromComponent function from the library.

**Comment by ebisbe** [comment]
https://github.com/vuejs/vue-test-utils/issues/1564#issuecomment-1424857260
