### ISSUE TITLE
Can't test async behaviour in component

### ISSUE THREAD

**Issue by Fifciu** [vuejs/vue-test-utils#1176]
### Version
1.0.0-beta.29

### Reproduction link
[https://codesandbox.io/s/j308154m1v](https://codesandbox.io/s/j308154m1v)

### Steps to reproduce
1. Install vue with unit test on your local machine.
2. Select Mocha   Chai
3. Copy AsyncBtn component end test
4. Run npm run test:unit

### What is expected?
By $nextTick I want to test async behaviour of component. 

### What is actually happening?
NextTick doesn't wait for DOM update. "Expect" compares old value(before async operation) of data.bestPlayer with request string.

---
I tried async functions, returning promise, using done callback. Nothing works. Only setting timeout for 4/5 seconds works however, I think it is really bad solution.

**Comment by steven87vt** [comment]
I typically us jest for tests but I think jest and mocha share some common functionality in that you can set things before tests in an async manner as well as executing tests: https://mochajs.org/#working-with-promises

In general I would recommend the following things:

1. If you plan to use the wrapper in multiple tests inside the parent describe then reassign it using before each or remove it and mount inside the test. I tend to find test setup changes test to test so if you plan on needing different computed/store/options then do so per test or reassign the wrapper in the specific test you need it in.
2. In jest for the test you need async functionality in you pass it an async function with an optional done callback. In this case for mocha you I think you just pass it done. For most cases you dont need to worry about the done callback but assuming you need to wait for something before the test can close, pass the done callback to the function and act on it when needed in a setTimeout

```
import flushPromises from 'flush-promises'
....

describe("AsyncBtn.vue", () => {
  let wrapper 
  beforeEach(()=>{
    wrapper = shallowMount(AsyncBtn);
  })
  it.only("behaviour", (done) => {
    const bestPlayer = "Eden Hazard";
    wrapper.find("button").trigger("click");
    flushPromises().then(() =>{
      expect(wrapper.vm.bestPlayer).to.equal(bestPlayer)
      done()
    })
  });

// in jest
 test("stop test from existing before long running node process exits", async (done) => {
    let spy = jest.spyOn(wrapper.vm, 'someLongAction')
    wrapper.vm.someLongAction({someData: 'data'})
    await new Promise((resolve) => {
      setTimeout(500, () =>{
        expect(wrapper.vm.someActionResult).toBe('done')
        resolve()   
      })  
    }).then(done())
  });
});
```

**Comment by eddyerburgh** [comment]
You're make an HTTP request in your test with `axios.get`. You should stub `axios.get` to return a promises.

In Jest you can use `jest.mock`, but in mocha it's more complicated. I wrote a blog post on mocking modules in 2017: https://eddyerburgh.me/stub-file-dependencies-vue-unit-tests.

This question isn't an issue with vue test utils, so I'm going to close it. But I encourage you to ask a question on StackOverflow to help you stub axios in your tests.
