### ISSUE TITLE
Testing Vue components OL with jest isn't working

### ISSUE THREAD

**Issue by ArtyomBist** [vuejs/vue-test-utils#1181]
### Version
1.0.0-beta.27

### Reproduction link
[https://github.com/openlayers/openlayers/issues/9317](https://github.com/openlayers/openlayers/issues/9317)

### Steps to reproduce
Add OL to project

### What is expected?
complete any tests

### What is actually happening?
crashed after start  unit testing

---
I created topic in Open Layers repository https://github.com/openlayers/openlayers/issues/9317 but it's problem possibly in low  jest's version

**Comment by eddyerburgh** [comment]
Please provide a reproduction in a GitHub repository that I can run to debug

**Comment by ArtyomBist** [comment]
@eddyerburgh  https://github.com/skortabeast/jest_openLayers    look there,  yarn  for install dependencies

**Comment by eddyerburgh** [comment]
This is an issue with your Jest setup:

1. You need to set Jest to transform node_modules
2. OL uses HTMLCanvasElement `getContext` which isn't implemented by JSDOM

Solve it by telling Jest to transform files from the ol package:

```js
// jest.config.js
module.exports = {
  // ..
  transformIgnorePatterns: [
    'node_modules/(?!(ol)/)'
  ]
  // ..
};
```

And add a `mocks.js` file that patches `getContext`:

```js
// mocks.js
HTMLCanvasElement.prototype.getContext = () => {}
```
```js
import './mocks'; // Must be imported before the tested file
import { mount } from '@vue/test-utils'
```

**Comment by ArtyomBist** [comment]
thx
