### ISSUE TITLE
duplicate keys warning may caused by sync when run test on cypress

### ISSUE THREAD

**Issue by maple-leaf** [vuejs/vue-test-utils#1182]
### Version
1.0.0-beta.29

### Reproduction link
[https://github.com/maple-leaf/cypress-vue-test/tree/test-utils-duplicate-keys-warning-bug](https://github.com/maple-leaf/cypress-vue-test/tree/test-utils-duplicate-keys-warning-bug)

### Steps to reproduce
1. clone the repo: `git clone https://github.com/maple-leaf/cypress-vue-test.git`
2. checkout to branch: test-utils-duplicate-keys-warning-bug
3. install deps: `npm i`
4. run test: `npm run cy:open`
5: select `app.cypress.spec.js` to run test suites which contain bug test
6. open chrome devtool
7. you will see duplicate key warning message on console

### What is expected?
not warning

### What is actually happening?
duplicate key warning thrown

**Comment by maple-leaf** [comment]
The warning message will not show up when run similar test with jest because it's run on node.

**Comment by eddyerburgh** [comment]
`sync` will be removed in the next release, so you should set `sync` to `false` for now.

**Comment by maple-leaf** [comment]
@eddyerburgh Is there any example on how to write test code when `sync` is `false`? all examples on https://vue-test-utils.vuejs.org seem based on `sync` ?

**Comment by eddyerburgh** [comment]
There are some initial guides here—https://github.com/vuejs/vue-test-utils/pull/1156/files

**Comment by maple-leaf** [comment]
Got it. Close.
