### ISSUE TITLE
shallowMount stub behavior is inconsistent between options object component and constructor one

### ISSUE THREAD

**Issue by ktsn** [vuejs/vue-test-utils#1186]
### Version
1.0.0-beta.29

### Reproduction link
[https://github.com/ktsn/vue-test-utils-shallow-stub-issue](https://github.com/ktsn/vue-test-utils-shallow-stub-issue)

### Steps to reproduce
1. `yarn install`
2. `yarn test`
3. You will see the inconsistency of stub behavior between options object component and constructor component.

### What is expected?
Both `shallowMount`ed component renders the same html.

### What is actually happening?
The child of stubbed component (GrandChild) is stubbed if Child is passed as options object while not stubbed if Child is constructor.

---
I'm not sure which behavior is intended but I think the behavior with options object stub is more useful. Because sometimes I want to control which child components should be stubs or not by passing the component itself to `stubs` option. And in that case, I will not expect the child component be rendered entirely (grandchildren components should be replaced with stubs).

**Comment by eddyerburgh** [comment]
This is actually undefined behavior that I should have considered. 

I think the behavior of the constructor is more intuitive, but it might require changing the current shallow rendering logic.

**Comment by ebisbe** [comment]
https://github.com/vuejs/vue-test-utils/issues/1564#issuecomment-1424857260
