### ISSUE TITLE
RouterLinkStub not outputting href onto the rendered link

### ISSUE THREAD

**Issue by joelworsham** [vuejs/vue-test-utils#1189]
### Version
1.0.0-beta.28

### Reproduction link
[https://codesandbox.io/s/4z3y52zyl9](https://codesandbox.io/s/4z3y52zyl9)

### Steps to reproduce
Follow code sandbox link.
Run the test.
Note that finding tag `href` returns `undefined` instead of the prop from `to`

### What is expected?
The RouterLinkStub renders a link with the valid href tag.

### What is actually happening?
The RouterLinkStub renders a link withOUT the valid href tag.

**Comment by eddyerburgh** [comment]
RouterLinkStub doesn't render the `href`. This was by design. It's intended to be used as a stub component, so you can check that it receives the correct props, but you don't have to check the implementation:

```js
test("href should exist on generated link", () => {
  expect(wrapper.find("a").props("to")).toBe("/link")
})
```

Potentially we could render `to` as an `href`, if it would save confusion.

**Comment by joelworsham** [comment]
Thank you for the clarification. I was testing the HTML against what I expect in the browser, which is the `href` containing the `to` prop.

However, the implementation you just mentioned will probably be thorough enough, as we, of course, aren't concerned too much with the RouterLinkStub implementation.

Thanks!

**Comment by buchatsky** [comment]
@eddyerburgh, property "to" is not rendered either by RouterLinkStub. What is rendered is:
`<a class="nav-link" exact="true">`
Neither "href" nor "to", so I cannot verify links for resulting DOM elements.
@vue/test-utils: 2.0.0-rc.9
The working snippet for me was:
```
test("href should exist on generated link", () => {
  expect(wrapper.findComponent(RouterLinkStub).props("to")).toBe("/link")
})
```
