### ISSUE TITLE
Can't trigger while using render()

### ISSUE THREAD

**Issue by Joris-Fonck** [vuejs/vue-test-utils#1195]
### Version
1.0.0-beta.29

### Steps to reproduce
let wrapper;
beforeEach(async () => {
    wrapper = await render(MyComponent, {});
  });

it('My test', () => {
    // Not working 
    wrapper.trigger('my_event');
});

Error in console when i run tests :

    TypeError: wrapper.trigger is not a function

### What is expected?
The trigger correctly work and wrapper.emitted('focus') return true.

### What is actually happening?
wrapper.trigger('focus') return error

**Comment by eddyerburgh** [comment]
`render` only returns a cheerio wrapper around a rendered string. It doesn't support methods like `trigger`.
