### ISSUE TITLE
Fix for Dynamic imports not present

### ISSUE THREAD

**Issue by segundaestrella** [vuejs/vue-test-utils#1197]
### What problem does this feature solve?
The fix https://github.com/vuejs/vue-test-utils/pull/864 for dynamic imports seems lost.

On the repo changelog is listed in the release 1.0.0-beta.22 (2018-07-29)
https://github.com/vuejs/vue-test-utils/blob/dev/CHANGELOG.md

On the vue-test-utils package changelog is not listed
https://github.com/vuejs/vue-test-utils/blob/dev/packages/test-utils/CHANGELOG.md

And with the latest release a test with dynamic import still fails
```
      [Vue warn]: Failed to resolve async component: function vsMobileCalendarOverview() {
        return import('./MobileCalendarOverview.vue');
      }
      Reason: Error: Not supported
    console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Failed to resolve async component: function vsMobileCalendarDaily() {
        return import('./MobileCalendarDaily.vue');
      }
      Reason: Error: Not supported
```

### What does the proposed API look like?
I don't understand what is going on:)

**Comment by Ic3m4n34** [comment]
Why is this closed? I have the same issue. If someone knows how to fix this, please let me know.
