### ISSUE TITLE
Problems with trigger and async

### ISSUE THREAD

**Issue by jsodeman** [vuejs/vue-test-utils#1200]
### Version
1.0.0-beta.29

### Reproduction link
[https://github.com/jsodeman/vueasynctests](https://github.com/jsodeman/vueasynctests)

### Steps to reproduce
yarn run test:unit

### What is expected?
One of the tests using .trigger() will pass

### What is actually happening?
Only the test calling the component's method directly passes.

---
I've tried every variation I could find in the docs and issues for testing a component using trigger when the triggered method is async. None of them work, though calling the method directly does work.

**Comment by eddyerburgh** [comment]
The issue isn't with `trigger`. The method is called correctly as a result of `trigger` dispatching a click event on the element. 

The problem is that your test is making an async HTTP request. You can fix this by mocking `request-promise` with Jest:

```js
jest.mock('request-promise')
```
