### ISSUE TITLE
Getting a select box's value whose value is an object returns the string [object Object] instead of the object

### ISSUE THREAD

**Issue by annethereshewent** [vuejs/vue-test-utils#1201]
### Version
1.0.0-beta.29

### Reproduction link
[https://jsfiddle.net/6a8cm1zn/3/](https://jsfiddle.net/6a8cm1zn/3/)

### Steps to reproduce
Use the above component, then in a unit test using vue-test-utils and jest do the following:

wrapper = mount(Component)
wrapper.find('select').element.value
console.log(select)

it will return [object Object] instead of the object as expected

### What is expected?
To get the object

### What is actually happening?
Getting the string [object Object]

---
Trying to write unit tests for my existing code

So I have a dropdown whose option values are objects, and this generally works fine within vue. however, when I try to get the select box's value using vue-test-utils, I get the string [object Object] instead of the actual object.

Is there a way around this? If not, is there a way to get the selected option's text instead of its value? This would be a decent workaround if there was no way around the [object Object] issue.

**Comment by annethereshewent** [comment]
Found it!
So if you do `wrapper.find('select').vm.$data.localValue` it will give you the object. Going to go ahead and close as this resolves this "bug" for now, feel free to reopen

**Comment by dospunk** [comment]
It would be nice to have a cleaner API for this, especially because this method doesn't work in typescript
