### ISSUE TITLE
Cannot mock $route param even when *not* using VueRouter in localVue

### ISSUE THREAD

**Issue by annethereshewent** [vuejs/vue-test-utils#1202]
### Version
1.0.0-beta.29

### Reproduction link
[https://codesandbox.io/s/oxvvn2r96](https://codesandbox.io/s/oxvvn2r96)

### Steps to reproduce
Run the unit test in my codesandbox, notice that it passes as route is undefined. also note the error.

### What is expected?
$route should be defined and usable

### What is actually happening?
I get an error saying $route is read only

---
It seems that for some reason if you use Vue.use(VueRouter) anywhere (note its usage in my main.js file), it will mess up mocking the  $route param even when using localVue in unit tests.

---

The problem here is that I'm using Vue.use(VueRouter) in one of my src non-test files, yet somehow using an instance of localVue doesn't work around this.

**Comment by eddyerburgh** [comment]
This looks like an issue with how CodeSandbox runs tests. If you remove the code in main.js that installs VueRouter the test passes as expected.

**Comment by annethereshewent** [comment]
it's not an issue with codesandbox. I'm having the same problem with my own code outside of the sandbox. 

The issue is that I'm using Vue.use(VueRouter) within my main.js file because I *need* it for my project. I can't just remove it. 

I thought using localVue would allow you to use a separate instance of Vue with Vue router that wouldn't interfere with the main;js one. This is still a bug.

**Comment by raphael-jolimoi** [comment]
I have the same problem, I am only loading vue-router in my main.js file. I am using a localVue the same way it is described in the doc and in StackOverflow questions about this topic. 

When I try to log the $route that is preventing my override, it comes up as undefined.

**Comment by eddyerburgh** [comment]
Can someone provide a GitHub reproduction of the issue?

**Comment by raphael-jolimoi** [comment]
I was importing vue-router indirectly in a dependency, that's what was causing the conflict when vue-test-utils was trying to mock $route. 

Once I removed that dependency, everything worked as it should.

**Comment by ricardovanlaarhoven** [comment]
Is there another solution then just removing the dependency? 

I've got an global error handler that uses the router to redirect to a 403 page or to logout on a 401. I can't remove that..
Or is there e better solution then using the router?
