### ISSUE TITLE
Translate docs in Brazilian Portuguese

### ISSUE THREAD

**Issue by mestihudson** [vuejs/vue-test-utils#1204]
### What problem does this feature solve?
1. Create a docs version in Brazilian Portuguese.
2. I have been doing this work at my fork of repo, but a still mess may.
3. Maybe anyone already done that job.
4. I wanna to know if yes to 3.
5. If not to 4, I will continue 2.

### What does the proposed API look like?
Just translate docs.

**Comment by eddyerburgh** [comment]
We had to remove Portugese translations because they weren't kept in sync with the docs, so it's better if you continue to work on your fork

**Comment by afontcu** [comment]
Hi! I'm gonna close this issue since it hasn't been any activity for the last 6 months, but feel free to reopen it or create a new one (or a PR) if you end up translating the docs 😃 

Thanks!
