### ISSUE TITLE
Dynamic components are not stubbed by stubs provided in mounting options

### ISSUE THREAD

**Issue by peterkajan** [vuejs/vue-test-utils#1206]
### Version
1.0.0-beta.29

### Reproduction link
[https://codesandbox.io/s/54j8o43z3l?fontsize=14&module=%2Ftest%2Fshallow-mount.spec.js](https://codesandbox.io/s/54j8o43z3l?fontsize=14&module=%2Ftest%2Fshallow-mount.spec.js)

### Steps to reproduce
Open the reproduction link and see the failing test

### What is expected?
ChildComponent to be stubbed with the stub provided in Mounting options:

```html
<div>
  <div class="stubFromOptions" />
</div>
```

### What is actually happening?
ChildComponent is stubbed by the automatic stub:

```html
<div>
  <childcomponent-stub></childcomponent-stub>
</div>
```

**Comment by dsseng** [comment]
@peterkajan it'll work if you set `dataComponent: 'ChildComponent'`, not pass component directly to data. If you set it in data, you should stub it yourself after mount.

**Comment by peterkajan** [comment]
Thanks, this works. Not sure if this is only a workaround or the solution. Maybe little more detailed explanation would help.

**Comment by dcrystalj** [comment]
@peterkajan @sh7dm can you show solution. I was not able to fix your example

**Comment by peterkajan** [comment]
Here there is fixed version of the test: https://codesandbox.io/s/54j8o43z3l?fontsize=14&module=%2Ftest%2Fshallow-mount-fixed.spec.js

The change is on line 19:
dataComponent: ChildComponent -> dataComponent: "ChildComponent"

**Comment by M3psipax** [comment]
Would like to bump this. I encountered this issue as well and it's not feasible for me to change the component assignments to strings. Can we get an update on whether this is going to be fixed any time soon?

**Comment by ebisbe** [comment]
https://github.com/vuejs/vue-test-utils/issues/1564#issuecomment-1424857260
