### ISSUE TITLE
Clarify attachedToDocument meaning in docs

### ISSUE THREAD

**Issue by maksnester** [vuejs/vue-test-utils#1207]
### Version
1.0.0-beta.29

### Reproduction link
[https://vue-test-utils.vuejs.org/api/wrapper/#properties](https://vue-test-utils.vuejs.org/api/wrapper/#properties)

### Steps to reproduce
visit https://vue-test-utils.vuejs.org/api/wrapper/#properties

### What is expected?
Clear description of options

### What is actually happening?
See vague description of options

---
Can't find any meaningful description of what does `attachedToDocument` option for.

**Comment by maksnester** [comment]
That's still completely unclear. It looks like a comment for such code snippet:
```
// sum `a` with `b` and save in `c`
let c = a + b
```
I actually wondered what does it mean at all? What is this `attachedToDocument` for? It's a public API, but how can I use it? For which scenario? Why do I need that at all? I couldn't find any meaningful information about it in docs and I still can't.

**Comment by sarahdayan** [comment]
Hey @Alendorff! There's already a definition for `attachedToDocument` [here](https://vue-test-utils.vuejs.org/api/options.html#attachtodocument). When `true`, the component is attached to the DOM (`jsdom` when using Jest). This, I guess, lets you perform DOM API requests (but I'll let @eddyerburgh confirm), but it also means the DOM is mutated (so you have to `destroy` the component after each test for them to remain deterministic).

I've opened a PR to add a link to this definition: https://github.com/vuejs/vue-test-utils/pull/1432
