### ISSUE TITLE
Error with "$refs" inside child component 

### ISSUE THREAD

**Issue by ndabAP** [vuejs/vue-test-utils#1219]
### Version
1.0.0-beta.29

### Reproduction link
[https://github.com/ndabAP/vue-command/blob/test/unit-tests/tests/unit/vue-command.spec.js#L21](https://github.com/ndabAP/vue-command/blob/test/unit-tests/tests/unit/vue-command.spec.js#L21)

### Steps to reproduce
1. Clone the repository
2. Switch to branch "test/unit-tests"
3. Run `yarn`
4. Execute `yarn test`

### What is expected?
`this.$refs.input.scrollIntoView` behaves like normal Vue.js usage.

### What is actually happening?
Error:

>Error in mounted hook: "TypeError: this.$refs.input.scrollIntoView is not a function"

---
I tried to mock `$refs` but it didn't work.

**Comment by eddyerburgh** [comment]
Thank you for the bug report, but that reproduction is too large. Are you able to provide a minimal reproduction?

**Comment by ndabAP** [comment]
Hey @eddyerburgh,

thanks for your answer. I just have been told at [Reddit](https://www.reddit.com/r/vuejs/comments/bh9f6s/vuetestutils_error_with_refs_inside_child/) that this is an issue coming from [JSDom](https://github.com/jsdom/jsdom/pull/2332). That would mean that every project that uses `scrollIntoView` would fail.

I can create a repository where this function is used. Can you confirm that this is possible at all?

**Comment by eddyerburgh** [comment]
Ah yes, you'll need to implement your own `scrollIntoView` mock function because JSDOM doesn't currently support it.

You can mock it with:

```js
Element.prototype.scrollIntoView = () => {}
```

**Comment by ndabAP** [comment]
Thanks!
