### ISSUE TITLE
Attribute with value from computed doesn't appear in attributes()

### ISSUE THREAD

**Issue by iogrt** [vuejs/vue-test-utils#1220]
### Version
1.0.0-beta.29

### Reproduction link
[https://codesandbox.io/s/r4yz361w5n](https://codesandbox.io/s/r4yz361w5n)

### Steps to reproduce
- Run the tests
- See the output

### What is expected?
wrapper.attributes() shows current attributes with corresponding values

### What is actually happening?
wrapper.attributes() only shows values that come from props or static attributes

**Comment by eddyerburgh** [comment]
The problem is the `checked` attribute, which Vue adds as a DOM prop (by setting `element.checked = true`, rather than an attribute. This means it's not available on the element `attributes`.

A workaround is to check the value directly:

```js
wrapper.element.checked // true
```

**Comment by iogrt** [comment]
Thanks, could this be added to the docs then? Something along the lines: 
>attributes() doesn't retrieve dom props, for example the checked prop on a checkbox. you can get dom props from the htmlElement directly with: `wrapper.element.propName`

Maybe with a good link to DOM props aswell (I was unaware of them)

**Comment by eddyerburgh** [comment]
Yes definitely, would you like to make a PR adding it?
