### ISSUE TITLE
Wrapper.find() does not work in IE11 without polyfill

### ISSUE THREAD

**Issue by markbrouch** [vuejs/vue-test-utils#1223]
### Version
1.0.0-beta.29

### Reproduction link
[https://github.com/eddyerburgh/vue-test-utils-karma-example](https://github.com/eddyerburgh/vue-test-utils-karma-example)

### Steps to reproduce
Using Karma test runner in IE11 environment, run the Counter.spec.js test.

### What is expected?
`wrapper.find('button')` should return a wrapper of the matching element.

### What is actually happening?
No match is returned and an error is thrown that `trigger` must be provided a non-empty wrapper.

---
This is due to IE11 not supporting `Element.matches()`. Intead IE11 has the non-standard `Element.msMatchesSelector()`. MDN has a [simple polyfill](https://developer.mozilla.org/en-US/docs/Web/API/Element/matches#Polyfill) that should be implemented and solves this problem:
```js
if (!Element.prototype.matches) {
  Element.prototype.matches = Element.prototype.msMatchesSelector || Element.prototype.webkitMatchesSelector;
}
```

I'm happy to open a PR to fix this, I just don't know where the correct place to install this polyfill would be.

**Comment by eddyerburgh** [comment]
Thank you for raising this issue. Yes please raise a PR adding the polyfilll in
