### ISSUE TITLE
Cannot run repo locally without yarn - BLOCKING CONTRIBUTIONS

### ISSUE THREAD

**Issue by TheJaredWilcurt** [vuejs/vue-test-utils#1235]
### Version
`dev` branch

### Reproduction link
[https://github.com/vuejs/vue-test-utils/blob/dev/.github/CONTRIBUTING.md](https://github.com/vuejs/vue-test-utils/blob/dev/.github/CONTRIBUTING.md)

### Steps to reproduce
On a computer with the latest Node and npm versions installed, and **without** Yarn installed, attempt to run the repo locally following the Contributor Guideline instructions.

### What is expected?
You should be able to run the repo locally without having to globally install any non-standard tools.

### What is actually happening?
Crashes looking for yarn. If you change the lerna json to not require Yarn, it will stop crashing on install, but cannot run unit tests because of missing dependencies.

---
The link to Lerna's website in the docs is wrong.

**Comment by TheJaredWilcurt** [comment]
I wanted to make a PR to add in `wrapper.find({ test: 'pageTitle' })` to be part of this proposal https://github.com/vuejs/vue-test-utils/issues/1234. But after 40 minutes of fighting with this repo I gave up. I feel as though, if the repo was set up like every other repo I've ever dealt with in the last 5 years and only required a `npm install && npm start` I probably could have implemented the code changes for the PR.

**Comment by TheJaredWilcurt** [comment]
Changing the docs to say "use yarn", does not fix this issue. But apparently Yarn and TS are "the norm" for official Vue repos. So the barrier for entry has been set. I see Vue as a project that goes very far out of its way to be accommodating to anyone that wants to use it. It's a true shame that philosophy is not extended to those that want to contribute to it.

I will continue making issues and waiting for years for them to be implemented, instead of contributing.

**Comment by dobromir-hristov** [comment]
Yarn is required because we use "workspaces", to build the monorepo. Adding yarn to your local env is not hard, but surely we cant force you to.

Everyone is doing this for free, in our own free time. We all spend nights and weekends resolving issues.

Sorry that you feel this way, but it is the way it is.
