### ISSUE TITLE
Feature request: wrapper.destroy()

### ISSUE THREAD

**Issue by mmieluch** [vuejs/vue-test-utils#124]
Hi, I'm curious if you guys would be interested in migrating the `wrapper.destroy()` method from Avoriaz. Can't speak for others, but personally I found it quite useful. Of course, I can call `$destroy` on a VM, but that doesn't remove the component node from DOM. So every time I need to get rid of a component I do the following:

1. Go up to parent node (if it exists), and then call `removeChild` on it, passing in `vm.$el`.
2. Call `wrapper.vm.$destroy()` to clean up internals.

Avoriaz has dealt with that particular issue very nicely :) I think it would be a nice addition to an already fantastic library. I'd be happy to submit a PR.

Thanks!

**Comment by eddyerburgh** [comment]
I omitted `destroy` because, like you said, you can call it on the vm directly. 

I forgot that the method also removes the parent node if it exists.

I'd be happy to accept a PR to add `destroy` 🙂

**Comment by mmieluch** [comment]
I can see a PR has already been submitted by @vouill in #129. Thanks guys!
