### ISSUE TITLE
.text() reacting to carriage return in HTML code ?

### ISSUE THREAD

**Issue by Samuelfaure** [vuejs/vue-test-utils#1250]
### Version
1.0.0-beta.29

### Reproduction link
[https://github.com/etalab/entreprise.data.gouv.fr.git](https://github.com/etalab/entreprise.data.gouv.fr.git)

### Steps to reproduce
Sorry, the reproduction is not minimal, the build seems necessary.

0/ git clone reproduction folder,

Go to commit: `git checkout 64c7f97e674fa21665a5bb39ff1bb56f37e21a4c`

run `npm install`,

run `npm run test:unit -t EtablissementHeaderTimestamp`, the tests are passing

1/ Go to file `/src/components/etablissement/etablissementHeader/EtablissementHeaderTimestamp.vue`

2/ Line 5: break the line by adding a space, from this :

Line 5: `Dernière mise à jour SIRENE : {{ resultSirene.updated_at | frenchDateFormat }}`

to this : 

Line 5: `Dernière mise à jour SIRENE :`

Line 6: `{{ resultSirene.updated_at | frenchDateFormat }}`

3/ run test again : `npm run test:unit -t EtablissementHeaderTimestamp`

4/ The test does not pass anymore

### What is expected?
A carriage return in the HTML code should not change the result of the text content of the node.
```
<p>

Lorem ipsum

<p> 
```

=> .text()

=> "Lorem ipsum"
```
<p>

Lorem

ipsum

</p>
```
=> .text()

=> "Lorem ipsum"

### What is actually happening?
```
<p>

Lorem ipsum

<p> 
```
=> .text()

=> "Lorem ipsum"
```
<p>

Lorem  

ipsum

</p>
```
=> .text()

=> "Lorem  

ipsum"

---
I'm not sure this is a bug or a feature, it seems weird to me that going to next line in HTML code would format the text content of a node.

**Comment by eddyerburgh** [comment]
Thanks for your question. 

This is expected behavior because of how the template is compiled, and how `text` works. `text` just returns the `textContent` of the DOM node. In your example, a DOM node is created with the string `Lorem\n\nipsum` ([see the compiled output here](https://vue-template.egoist.moe/?encoded=DwBwfAUBAyD2BOBTAtlAliAzgV1RYA9OEA%3D%3D)).
