### ISSUE TITLE
Jasmine / Jest matchers

### ISSUE THREAD

**Issue by winniehell** [vuejs/vue-test-utils#1254]
### What problem does this feature solve?
Custom matchers help to make tests more readable and can provide easier to understand error messages.

### What does the proposed API look like?
Instead of

```javascript
expect(wrapper.exists()).toBe(true)
```

use

```javascript
expect(wrapper).toExist()
```

for example. After https://github.com/vuejs/vue-test-utils/issues/1135 is resolved, this could provide the selector in the error message if the assertion fails.

---

Documenting the use of custom matchers was previously discussed in https://github.com/vuejs/vue-test-utils/issues/634. However here I want to suggest providing matchers as part of vue-test-utils rather than documenting how to do it yourself.

---

See also

- https://jestjs.io/docs/en/mock-functions#custom-matchers
- https://jasmine.github.io/tutorials/custom_matcher
- https://github.com/velesin/jasmine-jquery

**Comment by winniehell** [comment]
@eddyerburgh Do you think custom matchers for common test frameworks (Jasmine and Jest?) could be a package inside vue-test-utils? This would ensure the matchers are always compatible with the latest version of the library.

**Comment by eddyerburgh** [comment]
Maybe they could be included in the future, but for now we should focus on getting v1 released with the current API.

**Comment by winniehell** [comment]
@eddyerburgh Would it make sense to you if I develop them in a separate package already that we can then merge after v1 got released?

EDIT: This will not happen as I have stopped using Vue in my projects.

**Comment by eddyerburgh** [comment]
Yes that's a good idea

**Comment by winniehell** [comment]
there is https://github.com/hmsk/jest-matcher-vue-test-utils which is also in the docs now thanks to https://github.com/vuejs/vue-test-utils/pull/1372 :slightly_smiling_face:
