### ISSUE TITLE
Stubs don't behave correctly with augmented options

### ISSUE THREAD

**Issue by strutcode** [vuejs/vue-test-utils#1260]
### Version
1.0.0-beta.29

### Reproduction link
[https://codepen.io/strutcode/pen/YoGXeW?editors=0010](https://codepen.io/strutcode/pen/YoGXeW?editors=0010)

### Steps to reproduce
View the console output

### What is expected?
In the console:
```
Permissions in component-a: some other value
Permissions in component-b: some value
```

The global mixin should be called with the original component's options

### What is actually happening?
In the console:
```
Permissions in undefined: undefined
Permissions in component-a: some other value
Permissions in component-b: undefined
```

The mixin is called three times in spite of only two components being in use. The options passed to the stub mixin are filtered unnecessarily.

---
The code base I'm currently working on uses a global mixin that provides a new option for components, but the stubbing functionality of shallowMount is filtering the component options here:

https://github.com/vuejs/vue-test-utils/blob/dev/packages/create-instance/create-component-stubs.js#L37

Is there a purpose to that function? It's causing a considerable number of issues for me in testing.

**Comment by ebisbe** [comment]
https://github.com/vuejs/vue-test-utils/issues/1564#issuecomment-1424857260
