### ISSUE TITLE
Destroying vm doesn't remove DOM elements

### ISSUE THREAD

**Issue by gplusdotgr** [vuejs/vue-test-utils#1265]
### Version
1.0.0-beta.29

### Reproduction link
[https://codesandbox.io/s/vue-template-yq43f](https://codesandbox.io/s/vue-template-yq43f)

### Steps to reproduce
Try to assert that a DOM element is there after wrapper.destroy(); in a Component using the Options API. 

### What is expected?
The element is not there

### What is actually happening?
The element is there

**Comment by JessicaSachs** [comment]
Hi @gkatsanos! I'm hoping you can provide a reproduction that includes the test cases. I'm having a hard time finding the issue.
