### ISSUE TITLE
emitted does not work

### ISSUE THREAD

**Issue by bbsteventill** [vuejs/vue-test-utils#1269]
### Version
1.0.0-beta.29

### Reproduction link
[https://jsfiddle.net/79cLyqv2/](https://jsfiddle.net/79cLyqv2/)

### Steps to reproduce
have a component with something like this
```html
<div id="test" @click="$emit('test')"></div>
```
your test is
wrapper.find('#test').trigger('click')
expect(wrapper.emitted().test.length).to.eql(1)

this fails BUT
```html
<div id="test" @click="$emit('test', $event)"></div>
```
WORKS

### What is expected?
the click event should be added to the emitted event stack

### What is actually happening?
the event is not being added to the event stack UNLESS there are arguments to the emit event

**Comment by germanp** [comment]
I think trigger is for native DOM events, you should use wrapper.vm.$emit('eventName') to simulate a Vue event.

**Comment by justindra** [comment]
I am having the same issue. So the DOM trigger is actually occurring as I add/remove one of the class names on the wrapper to detect the click trigger. But `wrapper.emitted()` is just an empty object.

**Comment by aholzner** [comment]
When you emit an event, the event you are emitting is added as a key and the value is added to the array.

Using Jest
```
test('to emit an event', () => {
  wrapper.find('#test').trigger('click');

  expect(wrapper.emitted()).toHaveProperty('test');
});
```

This test will pass.

**Comment by isnifer** [comment]
@aholzner nope, it won't work.
@justindra check this, It will work:
```js
setTimeout(() => {
  expect(wrapper.emitted()).toHaveProperty('test')
  done()
}, 0)
```

**Comment by JessicaSachs** [comment]
I believe there is no issue and everything is working as expected. I've written a test case testing the two versions you described. I get events emitted for both components. 

Please let me know if this is not the use case you're talking about. If you're still seeing an issue, please create a GitHub repo with both the failing test cases and the src code. The JSFiddle only contains the source code. :-(

```js
describe('#wrapper.emitted', () => {
    const wrapper1 = shallowMount(Div1); // <div id="div1" @click="$emit('my value')"/>
    const wrapper2 = shallowMount(Div2); // <div id="div2" @click="$emit('my value', $event)"/>

    // trigger the clicks
    wrapper1.find('#div1').trigger('click');
    wrapper2.find('#div2').trigger('click');

    // Contains the key "my value" with the number of times it was called and the arguments
    // { 'my value': [ [] ] }
    console.log('emitted1', wrapper1.emitted());

    // Contains the key "my value" with the MouseEvent in the arguments and the number of times it was called
    // { 'my value': [ [ [MouseEvent] ] ] }
    console.log('emitted2', wrapper2.emitted());
})
```
