### ISSUE TITLE
Feature idea: `pretty` print for `html()`

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/vue-test-utils#1273]
### Version
1.0.0-beta.29

### Reproduction link
[https://github.com/vuejs/test-utils](https://github.com/vuejs/test-utils)

### Steps to reproduce
I think it would be nice to be able to pretty-print the output of `html`. The API could be:

```js
console.log(wrapper.html({ pretty: true }))
```

I find the `html` feature is super useful for debugging project that I am new to, or teaching other people about testing. At the moment we import another package to format the HTML, but it might be a nice feature to have in core.

If you think it's not necessary, just close this one off. I'd be happy to make a PR with this feature.

### What is expected?
Format nicely

### What is actually happening?
Not formatted nicely

**Comment by anthonygore** [comment]
Duplicate of [this](https://github.com/vuejs/vue-test-utils/issues/1147)?

**Comment by lmiller1990** [comment]
So it is - and looks like the idea was approved. Might look into making a PR for this!
