### ISSUE TITLE
Test coverage report not working

### ISSUE THREAD

**Issue by xereda** [vuejs/vue-test-utils#1274]
### Version
1.0.0-beta.29

### Reproduction link
[https://github.com/xereda/vue-3.0](https://github.com/xereda/vue-3.0)

### Steps to reproduce
Clone repository and execute:

```
npm run test:unit -- --coverage 
```

### What is expected?
Access to coverage reports.

### What is actually happening?
Reports are not being generated.

---
The test coverage report is not working. Terminal details and html report, both are not being generated.

I created a project with vue cli 3.0 to do the tests. Available in github: https://github.com/xereda/vue-3.0

Commands executed:

```
npm run test:unit -- --coverage  
// vue-cli-service test:unit "--coverage"
```

![DeepinScreenshot_select-area_20190711140344](https://user-images.githubusercontent.com/14337850/61070432-1663fa80-a3e5-11e9-96ef-2ce914746365.png)

```
npm run test:unit -- --coverage --watch
//  vue-cli-service test:unit "--coverage" "--watch"
```

![DeepinScreenshot_select-area_20190711140449](https://user-images.githubusercontent.com/14337850/61070436-1b28ae80-a3e5-11e9-819e-3b2b064ca0c6.png)

Report not generated:

![DeepinScreenshot_select-area_20190711140636](https://user-images.githubusercontent.com/14337850/61070518-4c08e380-a3e5-11e9-92a0-e82ee2d2719e.png)

**Comment by JessicaSachs** [comment]
Hi @xereda! Thank you for opening an issue and providing a reproduction. The default code coverage options for jest do not include `.vue` files.

You'll need to add the following to either your `jest.config.js` or the jest section of your `package.json` (this is covered in the docs in more detail [here](https://vue-test-utils.vuejs.org/guides/#testing-single-file-components-with-jest))
```js
// jest.config.js
module.exports = {
  // ... other options
  collectCoverage: true,
  collectCoverageFrom: ["**/*.{js,vue}", "!**/node_modules/**"]
}
```

Let me know if that works for you!
