### ISSUE TITLE
vue-test-utils using vulnerable version of lodash

### ISSUE THREAD

**Issue by Sumeshkumar** [vuejs/vue-test-utils#1275]
### Version
1.0.0-beta.29

### Reproduction link
[https://github.com/vuejs/vue-test-utils](https://github.com/vuejs/vue-test-utils)

### Steps to reproduce
https://snyk.io/vuln/SNYK-JS-LODASH-73638

### What is expected?
Update to stable version >= 4.17.13

### What is actually happening?
Vulnerable package is using

**Comment by brandonburkett** [comment]
Has this update actually be published? 1.0.0-beta.29 still has the older version of lodash.
