### ISSUE TITLE
Mounted component with import of main.js send "Cannot find element: #app"

### ISSUE THREAD

**Issue by JawedHook** [vuejs/vue-test-utils#1277]
Hello ! 

I have a component which import my api file. 
In this API file, I import main.js to execute my mutations in my store by using vm.$store.
And now I have this warning during my tests:

`[Vue warn]: Cannot find element: #app`

I tried to import my store in my API file, but it's even worse, I just get a lot of errors "Cannot read property 'getters' of undefined" from getters not even in my component I want to test.

My API file looks like this : 
```javascript
import {instance} from '@/api/api'
import { SET_RESULTS, ERROR, SEND_QUERY } from '../../../store/modules/queries/action-types'
import vm from '@/main'

const baseRoute = '/data'

const moduleApi = {
aFunction () {
    instance().get(baseRoute)
      .then( res => {
        vm.$store.commit('SET_DATA', {res})
      })
      .catch( err => console.log(err))
  }
}

export default moduleApi
```

My component looks like this : 
```javascript
<template>
    <div>
        <button @click="runMethod"/>
    </div>
</template>

<script>
 	import moduleApi from '@/api/modules/moduleApi'
        export default{
        methods:{
                runMethod: () => {
                        moduleApi.aFunction()
                }
        }
        }
</script>
```

My main.js looks like this : 
```javascript
import Vue from 'vue'
import App from './App'
import router from './router'
import store from '@/store'

Vue.config.productionTip = false

export default new Vue({
  el: '#app',
  router,
  store,
  components: { App },
  template: '<App/>',
  render: h => h(App)
})
```

My tests run successfully, but I want to know if there is a way to no longer have the warning about #app while running my tests.

Thank you.

**Comment by Nationalcat** [comment]
try this.

```
// before loading main.js in your test case
Vue.config.silent = true;
document.body.innerHTML = '<div id="app"></div>';
require('main.js');
```

**Comment by dobromir-hristov** [comment]
Importing the main.js inside an api service is not a great idea.. if it is the main entry of Webpack, thats even a worse idea.

**Comment by Marcellofabrizio** [comment]
Any development on this? I'm facing a similar issue here, and can't seem to find a solution.

**Comment by afontcu** [comment]
> Any development on this? I'm facing a similar issue here, and can't seem to find a solution.

could you give `attachTo` a go?

```js
const div = document.createElement('div')
div.setAttribute('id', 'app')
document.body.appendChild(div)

test('whatever', () => {
  const wrapper = mount(Foo, {
    attachTo: div
  })
})
```

(not sure if it'll work)

**Comment by Marcellofabrizio** [comment]
Hey, thanks for the reply. I tried with `attachTo`, but continue to receive the warning.

**Comment by afontcu** [comment]
Can you share a minimal repro? I guess simply mounting `App.vue` instead of the whole Vue application would suffice?

**Comment by Marcellofabrizio** [comment]
Sure, I will make one as soon as possible.

**Comment by Marcellofabrizio** [comment]
Hey, sorry, I took longer than I expected to do this. I couldn't reproduce the error, so I'll try to explain it better. I have a component that I use for input mask in other components. I was getting several warnings that the custom directive wasn't registered, so I had to import the `main.js`, so I could use the global Vue, where the component was registered. With this, I stopped receiving the warnings, but now I get "Cannot find element: #app" for all tests I import `main.js`.
I register Vue like this 
```
new Vue({
  router,
  i18n,
  store,
  render: (h) => h(App),

}).$mount("#app");
```

**Comment by afontcu** [comment]
If the problem is a missing directive, you can customize the localVue instance to register it: https://vue-test-utils.vuejs.org/guides/#applying-global-plugins-and-mixins

```js
import { createLocalVue, mount } from '@vue/test-utils'

const localVue = createLocalVue()

localVue.directive('my-directive', MyDirective)

mount(Component, { localVue })
```
