### ISSUE TITLE
Outdated guide:  "Testing Single-File Components with Mocha + webpack"

### ISSUE THREAD

**Issue by FullStackAlex** [vuejs/vue-test-utils#1284]
Hey Guys, 
the current version of the guide requires the use of mocha-webpack, but this package is not maintained anymore and doesn't support Mocha 6. When following the guide as described you don't get the setup up and running. It's quite frustrating when you are new to testing in general and then have to spend hours or even days to unbundle all the information about vue testing out there and just be able to get a simple foo test function compile successfully. 

(I didn't want to go with the strongly hyped Jest as it's Facebook's kid and therefore didn't even try it)

**Comment by eddyerburgh** [comment]
Thanks for the info, and sorry for the confusion.

This will be fixed in https://github.com/vuejs/vue-test-utils/pull/1097
