### ISSUE TITLE
Unable to trigger keydown event with custom keyCode

### ISSUE THREAD

**Issue by igor-nabebin** [vuejs/vue-test-utils#1285]
### Version
1.0.0-beta.29

### Reproduction link
[https://github.com/igor-nabebin/vue-test-utils-jest-example](https://github.com/igor-nabebin/vue-test-utils-jest-example)

### Steps to reproduce
1. Clone repo
2. Run "npm install"
3. Run "npm run test"

### What is expected?
A keydown event with keyCode = 65 is fired, test passed.

### What is actually happening?
A keydown event with keyCode = 0 is fired, test failed.

**Comment by andrewvasilchuk** [comment]
Encountered the same problem.
