### ISSUE TITLE
Using @vue/cli test:unit with require('jsdom-global')() produces "Module not found: 'canvas'"

### ISSUE THREAD

**Issue by Cobertos** [vuejs/vue-test-utils#1288]
### Version
1.0.0-beta.29

### Reproduction link
[https://codesandbox.io/s/vue-template-ky6sb](https://codesandbox.io/s/vue-template-ky6sb)

### Steps to reproduce
**I was not able to repro, using jsdom-global in a CodeSandbox doesn't work like it does locally.**

* Setup a new @vue/cli project using mocha
* `require('jsdom-global')();` in the provided `example.spec.js` as referenced in https://vue-test-utils.vuejs.org/guides/#choosing-a-test-runner for "other test runners"
* The tests won't build with the error 

```
WEBPACK  Failed to compile with 1 error(s)

Error in ./node_modules/jsdom/lib/jsdom/utils.js

  Module not found: 'canvas' in 'C:\Users\cobertos\Workspace\projects\vue-contenteditable-input\node_modules\jsdom\lib\jsdom'
```

### What is expected?
For it to build

### What is actually happening?
It does not build

---
**WORKAROUND**:
I believe the error is caused because nodejs is the one that needs to evaluate the `require()` at runtime and not webpack at compile time. If you `eval('require("jsdom-global")')` instead it works and webpack won't try to include `jsdom` or `jsdom-global` in the test bundle.

Also [`__non_webpack_require__()`](https://stackoverflow.com/a/52713432/2759427) can be used too and it works.

**Comment by DannyFeliz** [comment]
This still happening even in a brand new project created with the @vue/cli

**Comment by lmiller1990** [comment]
So if I make a new project using mocha as my test running using the latest `@vue/cli`, this will happen? Or did you create a project using `@vue/cli` then install mocha (as per the guide)? 

I'm trying to narrow it down - is this an issue with the `@vue/cli` template or the guide we provided?

**Comment by Cobertos** [comment]
I believe this happens when selecting mocha in the prompts for test runner. It's been a hot second since I've used this tool.

**Comment by claudehaeberli** [comment]
I am having the same issue when I installed mocha (with the guide) after scaffolding the project with vue-cli.

**Comment by lmiller1990** [comment]
I could not repro this using vue-cli or jsdom (we have a guide with jsdom [here](https://vue-test-utils.vuejs.org/guides/#usage-without-a-build-step)). I think this is probably a configuration issue, outside the scope of VTU.

If someone can provide a reproduction I am happy to reopen and investigate this.

**Comment by ghost** [comment]
@Cobertos thanks for adding that workaround! You've unblocked me 😄
