### ISSUE TITLE
run e2e report error, about output filename, can not use chunkhash or contenthash ...

### ISSUE THREAD

**Issue by ghost** [vuejs/vue-test-utils#1291]
### Version
1.0.0-beta.29

cli-service 3.10.0

### Reproduction link
the project
[https://github.com/OuyangZq/vue_e2e](https://github.com/OuyangZq/vue_e2e)

### Steps to reproduce
just get my project， install packages and run e2e will show the error！Any other way will pass the cli-service ，but e2e not!

here the vue.config.js, jest.config.js is default

```
/* eslint-disable no-undef */
const path = require('path')
const UglifyJsPlugin = require('uglifyjs-webpack-plugin')
function resolve (dir) {
  return path.join(__dirname, dir)
}
module.exports = {
  devServer: (() => {
    if (process.env.IS_ELECTRON === true) {
      return {
        port: 8060
      }
    } else {
      return {
        hot: true,
        port: 4444,
        proxy: 'http://172.16.90.30'
      }
    }
  })(),
  chainWebpack: (config) => {
    config.resolve.alias
      .set('api', resolve('src/api'))
      .set('assets', resolve('src/assets'))
      .set('common', resolve('src/common'))
      .set('components', resolve('src/components'))
      .set('plugins', resolve('src/plugins'))
      .set('routes', resolve('src/routes'))
      .set('static', resolve('src/static'))
      .set('store', resolve('src/store'))
      .set('types', resolve('src/types'))
      .set('utils', resolve('src/utils'))
      .set('views', resolve('src/views'))
    config.plugins
      .delete('prefetch')
      .delete('preload')
    config.resolve
      .symlinks(true)
    config
      .when(process.env.NODE_ENV === 'development',
        config => config.devtool('cheap-source-map')
      )
      .when(process.env.NODE_ENV !== 'development', config => {
        config.optimization
          .minimizer([
            new UglifyJsPlugin({
              uglifyOptions: {
                compress: {
                  drop_console: true,
                  drop_debugger: true,
                  pure_funcs: ['console.log']
                }
              }
            })
          ])
      })
  }
}

```

### What is expected?
Tell my why it report error? Can run e2e success

### What is actually happening?
 error  in css/app.22164ed1.css

Cannot use [chunkhash] or [contenthash] for chunk in 'js/[name].[contenthash:8].js' (use [hash
] instead)

---
I have saw vue-cli webpack base configuration and didn't find the solution！

**Comment by ghost** [comment]
I foundd the chunkhash's problem is caused by that devServer only accept an object! Why? @yyx990803

many times I need change devServer's options not only port.In my project, I have to start web or electron by auto change devServer options! Might have a solution is create .env[mode] files. But I want to know why devServer been designed only accept object！

**Comment by eddyerburgh** [comment]
Hi, you should open an issue in the [@vue/cli repo](https://github.com/vuejs/vue-cli), rather than in this repo.
