### ISSUE TITLE
sorry,babel question?  SyntaxError: Unexpected string

### ISSUE THREAD

**Issue by ppvy** [vuejs/vue-test-utils#1294]
### Version
1.0.0-beta.29

### Reproduction link
[https://codesandbox.io/s/vue-template-rpeji?fontsize=14](https://codesandbox.io/s/vue-template-rpeji?fontsize=14)

### Steps to reproduce
In the home.vue use unit test (jest)

Other js files are referenced

This js file use the Toast component in vantUI

Unfortunately, an exception was thrown

is a problem with import used in functions

Can it only test a single file component？

Sorry if it is wrong, I will not test it.

#### axios to `src/utils/request.js`
`
import { Dialog, Toast } from 'vant'
...

...
Toast.fail('request fail');
...
`

and `vuex`  Also used

Comment out the above vant, vuex will also throw an exception

### What is expected?
ok

### What is actually happening?
`

  ● Test suite failed to run

    /Users/cssr/Desktop/nll_wap/node_modules/vant/es/toast/style/less.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import '../../style/base.less';
                                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^

    SyntaxError: Unexpected string

      10 |   timeout: 5000
      11 | });
    > 12 | 
         | ^
      13 | // request interceptor
      14 | service.interceptors.request.use(
      15 |     config => {

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (src/utils/request.js:12:1)

`

**Comment by aileelucky** [comment]
hi,Have you solved the problem?
