### ISSUE TITLE
Tests do fail if Array.flat() is used in *.spec.js or in the application

### ISSUE THREAD

**Issue by Kritten** [vuejs/vue-test-utils#1306]
### Version
1.0.0-beta.29

### Reproduction link
[https://github.com/Kritten/vue-utils-error](https://github.com/Kritten/vue-utils-error)

### Steps to reproduce
1. Create a new project with the cli and select "jest" as unit test setup.
2. Insert the statement `[].flat();` in the generated `example.spec.js`.
3. Run the tests.

Or simply use my repo and execute the tests.

### What is expected?
The tests should be valid indicating jest could properly parse the inserted statement. 

### What is actually happening?
The tests fail with `TypeError: [].flat is not a function`

---
babel-jest was setup by the cli with `'^. \\.jsx?$': 'babel-jest'` in the `jest.config.js`.

My tests failed while jest was executing/testing a method in my application containing the Array.flat function.

**Comment by eddyerburgh** [comment]
Your Node version doesn't support `Array.prototype.flat`. Support was added in Node 11. Upgrading to 12 or polyfilling will solve your issue.
