### ISSUE TITLE
Limit to number of elements that can be rendered - doesn't error just gives an empty string

### ISSUE THREAD

**Issue by CraigHarley** [vuejs/vue-test-utils#1315]
### Version
1.0.0-beta.29

### Reproduction link
[https://codesandbox.io/s/vue-template-vwtwo?fontsize=14](https://codesandbox.io/s/vue-template-vwtwo?fontsize=14)

### Steps to reproduce
On the minimal reproduction, try changing the repeat count to 400 or more.

### What is expected?
The component should be rendered.

### What is actually happening?
An empty string is returned.

---
The limit should be increased. We've hit this limit on our snapshot tests and it was really difficult to find that this is where the issue was, as there was no error thrown.

The component we were testing works fine in the browser, it was just in the tests that there is this issue.

Code Sandbox is refusing to work with these tests, but it works locally and there's only one file. Complete example is here:

```
import {renderToString} from '@vue/server-test-utils'

const getStuff = (count) => '<a></a>,'.repeat(count).split(',');

describe("limit to number of elements", () => {
    it("works", async () =>
        expect(await renderToString({template: `<div>${getStuff(399)}</div>`})).toMatchSnapshot('stuff'))
    it("does not work", async () =>
        expect(await renderToString({template: `<div>${getStuff(400)}</div>`})).toMatchSnapshot('no stuff'))
});
```

**Comment by JessicaSachs** [comment]
I wasn't able to reproduce this issue locally. I tested vue-test-utils using your example, with a snapshot of upwards of `1,000,000` elements. There was no failure. The Codesandbox example you sent is having issues transpiling and I am not able to execute either of the two tests.

If you continue to encounter this issue, I would suggest opening an issue with the Codesandbox team.
