### ISSUE TITLE
Mounted functional component has undefined context.children

### ISSUE THREAD

**Issue by rssfrncs** [vuejs/vue-test-utils#132]
Version: beta 3

Mounting a functional component passing options.context.children, results in context.children to be undefined in the components render function.

![image](https://user-images.githubusercontent.com/7808978/32097204-9e0eb56c-bb00-11e7-8dd1-9a7fa5629aa9.png)

Console output

![image](https://user-images.githubusercontent.com/7808978/32097226-b40b19d2-bb00-11e7-9eb1-e86d73681f53.png)

What is curious is that data.children contains the expected array.

**Comment by rssfrncs** [comment]
Taking a look at `lib/create-instance.js` , if options.context.children is passed as a [third argument](https://github.com/vuejs/vue-test-utils/blob/3c563d12735b8eab7529d32494f0955e0c51a294/src/lib/create-instance.js#L27) then context.children is defined, i'm not exactly sure why this works or what `h` in the functional components render context refers to?

**Comment by eddyerburgh** [comment]
h is an alias for the [createElement](https://vuejs.org/v2/guide/render-function.html#createElement-Arguments) function

Can you create a failing test?

**Comment by rssfrncs** [comment]
@eddyerburgh Ah nice. Yeah will do when i'm home from work.

**Comment by rssfrncs** [comment]
@eddyerburgh sorry for the delay, i've added a test case to this [branch](https://github.com/rssfrncs/vue-test-utils/tree/context-children-undefined) in this [file](https://github.com/rssfrncs/vue-test-utils/blob/a89c42dee7641293d46179b13bbef7512b58e119/test/unit/specs/mount/options/context.spec.js#L69).

**Comment by eddyerburgh** [comment]
Fixed in 5fc1c57bf5d14d0425b748f9a3f42d6eb59791e2

**Comment by rssfrncs** [comment]
@eddyerburgh I noticed at work this morning, that whilst _text_ children are rendered correctly, components like `h => <div>hello</div>` are not. This is partly my fault, as the [original test case](https://github.com/rssfrncs/vue-test-utils/blob/a89c42dee7641293d46179b13bbef7512b58e119/test/unit/specs/mount/options/context.spec.js#L69) I raised only included a text child.

I think the issue is [here](https://github.com/vuejs/vue-test-utils/blob/5fc1c57bf5d14d0425b748f9a3f42d6eb59791e2/src/lib/create-instance.js#L38) where the children array is passed to createElement. First, the array should be mapped and any items which are a function should be executed (as detailed [here](https://vuejs.org/v2/guide/render-function.html#createElement-Arguments)) like so,

![image](https://user-images.githubusercontent.com/7808978/33122424-1673c18c-cf6f-11e7-83d6-1562c43264ba.png)

**Comment by eddyerburgh** [comment]
It would be great if you could take care of it 🙂

**Comment by andreasvirkus** [comment]
Should also update documentation (currently it seems that `children` is an Object and directly under `options` (instead of being nested under `context`).

**Comment by eddyerburgh** [comment]
Would you be able to makr a PR @andreasvirkus ?
