### ISSUE TITLE
'disabled' attribute prevents triggering events on all HTML tags

### ISSUE THREAD

**Issue by micgro42** [vuejs/vue-test-utils#1321]
### Version
1.0.0-beta.29

### Reproduction link
[https://github.com/micgro42/vue-test-utils-disabled-bug](https://github.com/micgro42/vue-test-utils-disabled-bug)

### Steps to reproduce
1. check out minimal reproduction repository
2. run `npm install`
3. run `npm run test:unit`

### What is expected?
Test should pass, because the `disabled` attribute on a link (HTML `<a>` tag) is ignored by browsers and thus the component should handle the event (in this case: emit it to the parent component/wrapper)

### What is actually happening?
Test fails, because wrapper.trigger() does nothing 😭.

---
This was caused by #424 in order to fix #395.
Unfortunately, this solution is too far-reaching. This also disables events, for example, on links with the `disabled` attribute.
While that might be the desired final state, it is not something that is provided by the browser and thus needs to be programmed and asserted by tests. Just plainly disabling the wrapper.trigger method in that case prevents me from testing this.

**Comment by hiendv** [comment]
I'm sharing the same problem with you.
@eddyerburgh We should respect the `disabled` attribute only for [supported elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled).
