### ISSUE TITLE
Updating provide property isn't updating computed property

### ISSUE THREAD

**Issue by RyanHavoc** [vuejs/vue-test-utils#1322]
### Version
1.0.0-beta.29

### Steps to reproduce
```
      const wrapper = mount(Component, {
        provide: { monitor: { meta: { method: 'web-test' } } },
      });

      console.log(wrapper.vm.monitor.meta.method); // web-test
      console.log(wrapper.vm.capitalizedMethod); // Web
      wrapper.vm.monitor.meta.method = 'wizard';
      console.log(wrapper.vm.monitor.meta.method); // wizard
      console.log(wrapper.vm.capitalizedMethod); // Web <- Wrong!!!
```

Computed property is:

```
    capitalizedMethod() {
      switch (this.monitor.meta.method) {
        case 'cli':
          return 'CI/CLI';
        case 'web-test':
          return 'Web';
        case 'wizard':
          return 'Wizard';
        default:
          return capitalize(this.monitor.meta.method || '');
      }
    },
```

### What is expected?
I would have expected to be able to change the provided prop and the computed property to have updated to return `Wizard`. 

### What is actually happening?
The computed property returns it's original value.

---
Does `setData` and `setProp` do something internally to update state/trigger computed properties to update? Do we need a `setProvide` to do the same thing?

**Comment by dobromir-hristov** [comment]
injected properties are supposed to be like a read only I think. You shouldn't overwrite them, i think.
@afontcu am I wrong here?

**Comment by afontcu** [comment]
> injected properties are supposed to be like a read only I think. You shouldn't overwrite them, i think.
> @afontcu am I wrong here?

I'd say so! From docs:

"Note: the provide and inject bindings are NOT reactive. This is intentional. [...]" ([source](https://vuejs.org/v2/api/#provide-inject)).
