### ISSUE TITLE
Render method for snapshot tests

### ISSUE THREAD

**Issue by eddyerburgh** [vuejs/vue-test-utils#133]
We should expose a render method/ createSnapshot method for people to easily write snapshot tests:

```js
import { createSnapshot } from 'vue-test-utils'

const formattedMarkup = createSnapshot(Component)
```

**Comment by vouill** [comment]
`wrapper.html().toMatchSnapshot` does the job for me. what more would you expect from it ?

**Comment by eddyerburgh** [comment]
Ok I think that's a good enough solution, closing

**Comment by ianwalter** [comment]
@eddyerburgh Is this still the preferred API? `.html()` seems to produce a snapshot that is hard to read (for components with non-trivial markup) while the snapshot from `.element` seems much easier to read.

**Comment by eddyerburgh** [comment]
You can do both. I use `element`. also since jest-vue-serializer@2 you can pass in a wrapper object directly.

**Comment by ianwalter** [comment]
Ah good to know, thanks for the info!
