### ISSUE TITLE
Typescript definition for stubs doesnn't allow false

### ISSUE THREAD

**Issue by Robjam** [vuejs/vue-test-utils#1330]
### Version
1.0.0-beta.29

### Reproduction link
[https://github.com/Robjam/vue-test-utils-typescript-example/tree/repro/stub-false-typescript](https://github.com/Robjam/vue-test-utils-typescript-example/tree/repro/stub-false-typescript)

### Steps to reproduce
vue create with unit tests and typescript
in helloworld.spec.ts shallowmount add:

```
    const wrapper = shallowMount(HelloWorld, {
      stubs: {
        transition: false
      }
    });
```

shallowMount encounters a type error as Stubs type (https://github.com/vuejs/vue-test-utils/blob/v1.0.0-beta.29/packages/test-utils/types/index.d.ts#L30) does not allow false.

### What is expected?
that boolean is an acceptable type.

### What is actually happening?
Typescript fails to compile.

---
It appears this is addressed in [commit](https://github.com/vuejs/vue-test-utils/commit/2a4c6ef41dfc47c8fe71e0b90b65511dbe7f8c28), but not yet [released](https://github.com/vuejs/vue-test-utils/pull/1231).

Workaround is to add `// @ts-ignore` to line before shallowMount foregoing all type checks on mount.

**Comment by dobromir-hristov** [comment]
Should be merged in beta.30. please verify.

**Comment by dobromir-hristov** [comment]
Yep it's in the release notes.
