### ISSUE TITLE
stubs is failed when useing render 

### ISSUE THREAD

**Issue by cuixiaorui** [vuejs/vue-test-utils#1335]
### Version
1.0.0-beta.29

### Reproduction link
[https://github.com/cuixiaorui/test-vue-utils-bug-demo](https://github.com/cuixiaorui/test-vue-utils-bug-demo)

### Steps to reproduce
1. npm i 
2. npm run test:unit

### What is expected?
Pass the test in "tests/unit.shape.spec.js"

### What is actually happening?
get a error

TypeError: this.$refs.rect.setRect is not a function

---
Sorry, I can't speak English, the following content is obtained through the translation software
After my research, I found that stubs can be passed in the template, and this.$refs. XXX can be obtained.We can prove it in the demo.
But if the component is returned in a render style, it will fail.

**Comment by JessicaSachs** [comment]
Hi @cuixiaorui, thank you for submitting an issue.

The reproduction link (https://github.com/cuixiaorui/test-vue-utils-bug-demo) doesn't work and goes to a 404 page. If you still think there is an issue, please edit the description with a new URL.
