### ISSUE TITLE
Two independent tests connected via Vuex 

### ISSUE THREAD

**Issue by AlexanderShushunov** [vuejs/vue-test-utils#1337]
### Version
1.0.0-beta.29

### Reproduction link
[https://github.com/AlexanderShushunov/test-vuex-error](https://github.com/AlexanderShushunov/test-vuex-error)

### Steps to reproduce
There are two test in repo. They just mount ComponentUnderTest.
For each tests I created a vuex-store. 
ComponentUnderTest has a tamplate
```
  <div>
    <Init />
    <div v-if="flag" />
  </div>
```
`Init` component has `created` hook, which mutate `flag`.

Run test (`npm run test`)

### What is expected?
There are no errors

### What is actually happening?
```
TypeError: Cannot read property '$scopedSlots' of undefined
```

---

Errors can be different. It depends on template.

If I delete one test, another will pass.

If I replace `created` hook for `mounted` in `Init` tests will pass.

I do not use `flag` in `v-if` tests will pass.

**Comment by 8simsim8** [comment]
V: 1.0.0-beta.29
The same problem

**Comment by AlexanderShushunov** [comment]
Seems my issue has the same root with https://github.com/vuejs/vue-test-utils/issues/1130

**Comment by 8simsim8** [comment]
thank

**Comment by vvanpo** [comment]
As the linked issue explains, setting `sync: false` in the mount options will side-step this issue.

I can reproduce this issue without `@vue/test-utils`:

```js

test('Vue-only sync', () => {
  let error = null

  Vue.config.async = false
  Vue.config.errorHandler = e => {
    error = e
  }

  const vm = new Vue({
    ...ComponentUnderTest,
    store: createStore()
  }).$mount()

  expect(error).toBe(null)
  // Failure:
  //     Expected: null
  //     Received: [TypeError: Cannot read property '$scopedSlots' of undefined]
})
```

So the bug clearly lies somewhere in Vue.js' sync behaviour. But as @eddyerburgh mentioned in the linked issue, sync behaviour is going away in both Vue and `@vue/test-utils`, so I imagine this won't get fixed in the meantime.

**Comment by AlexanderShushunov** [comment]
@vvanpo , thx for example.
I added it in me repo https://github.com/AlexanderShushunov/test-vuex-error 

I think this issue is not actual any more.
