### ISSUE TITLE
Test .vue files are 4-space indentation

### ISSUE THREAD

**Issue by marczych** [vuejs/vue-test-utils#135]
I noticed that the `.vue` files in `test/resources/components/` are all 4-space indentation despite the `.editorconfig` being set to 2 for all files. Should the config be updated to set `*.vue` to 4 or should the vue files be reformatted?

I can open a PR if you'd like.

**Comment by eddyerburgh** [comment]
Nice catch. Yes, could you open a PR to set them all to 2 spaces?
