### ISSUE TITLE
Return VueWrapper instance If element is binding Vue Plugin instance

### ISSUE THREAD

**Issue by fcappi** [vuejs/vue-test-utils#1351]
### What problem does this feature solve?
Currently, using VueComponent Selector works with plugin components (e.g. BootstrapVue), but the return from find() method is wrapped by Wrapper instead of VueWrapper.
We need the VueWrapper so we can access the Vue instance

### What does the proposed API look like?
vCustomButton.ts
```
export default Vue.extend({
  template: `
  <div>
    <b-button>Button</b-button>
  </div>
  `
}); 
```

vCustomButton.spec.ts
```
import vCustomButton from 'vCustomButton'
import { BButton } from 'bootstrap-vue'


describe('vCustomButton', () => {
  let wrapper: Wrapper<any>;
  
  beforeEach(() => {
    wrapper = shallowMount(vCustomButton);
  })

  describe('Validation', () => {
    it('Test return from find()', () => {
      const bbuton = wrapper.find(BButton);

      // returns VueWrapper instead of Wrapper
      expect(bbuton).toBeInstanceOf(VueWrapper)
    })
  });
});
```

**Comment by dobromir-hristov** [comment]
`bbutton.vm` should be what you are looking for, no?

**Comment by lmiller1990** [comment]
This is intended behavior - the button component in VueBootstrap is a functional component. Those don't have Vue instances. See here: https://github.com/bootstrap-vue/bootstrap-vue/blob/d30c8b07840069a7891a7e0489910090698b38bc/src/components/button/button.js#L148

Another reason why we should drop `find(Comp)` - it's misleading and confusing.
