### ISSUE TITLE
Custom checkbox with v-model does not work with setChecked

### ISSUE THREAD

**Issue by alecgibson** [vuejs/vue-test-utils#1352]
### Version
1.0.0-beta.29

### Reproduction link
[https://codesandbox.io/s/vue-template-gtci0](https://codesandbox.io/s/vue-template-gtci0)

### Steps to reproduce
1. Set up a custom checkbox that uses `v-model` (see example)
2. Have a parent element wrap it and pass a value to `v-model`
3. Mount the parent element, and try to `setChecked` on the `input`
4. Would expect the checkbox to have toggled, but it hasn't

### What is expected?
I would expect `setChecked` to toggle the checkbox with `v-model`

### What is actually happening?
The checkbox isn't toggling

---
It looks like this is because under the hood, `setChecked` is calling `trigger('change')`, but `v-model` expects `trigger('input')`. A current workaround is:

```javascript
wrapper.find('input').trigger('click')
wrapper.find('input').trigger('input')
```

**Comment by dobromir-hristov** [comment]
`setChecked` is meant to work with `checkbox` html elements, thus it should trigger a change.
For custom components use `trigger`.

You can change your component to emit `change` instead - https://vuejs.org/v2/api/#model
Then this should work as intended :)

**Comment by alecgibson** [comment]
Aha! Another case of RTFM 🤦‍♂
