### ISSUE TITLE
provide/inject in composition api components

### ISSUE THREAD

**Issue by Stoom** [vuejs/vue-test-utils#1355]
### Version
1.0.0-beta.29

### Reproduction link
N/A

### Steps to reproduce
Mount a composition api component that uses injection

### What is expected?
The injection to be resolved

### What is actually happening?
The injection is unknown

---
This is an ABI issue.  In the Composition API component it is looking for the provider under `vm._provided` whereas a Vue 2.x component is looking for it under `vm.provide`

**Comment by Stoom** [comment]
Fixed in PR #1354

**Comment by JessicaSachs** [comment]
Hey @Stoom! Thank you for your PR and issue report. As soon as you make the changes, we'll merge it into the dev branch. 🙇‍♀

**Comment by Stoom** [comment]
#1354  merged
