### ISSUE TITLE
Unit tests with Mocha systematically fails to load globals on the first run after test is edited 

### ISSUE THREAD

**Issue by gterras** [vuejs/vue-test-utils#1356]
### Version
1.0.0-beta.29

### Reproduction link
[https://github.com/gterras/repro-vue-mocha-hotreload-forgets-require-option](https://github.com/gterras/repro-vue-mocha-hotreload-forgets-require-option)

### Steps to reproduce
- Clone the repo 
- run `npm run test:unit`
- Test passes 
- Add a new line to test and save 
- Test fails 

### What is expected?
Tests passes

### What is actually happening?

Every `global` defined in `setup.js` won't be loaded after a test is edited on the first test run, triggering a failed test. A second attempt will run the test as expected. 

---
Changes made in this repo : 

- Create a new project with vue-cli 
- Select Mocha Chai for unit tests 
- Create a `tests/unit/setup.js` and require `mount` inside 
- Create a tests that use mount 
- Set a `"test:unit": "vue-cli-service test:unit --require ./tests/unit/setup.js "` in package.json 
- Run unit tests

**Comment by JessicaSachs** [comment]
Hi @gterras! Thank you for the reproduction. I have it failing on my end as well.

**Comment by JessicaSachs** [comment]
However; can you try updating your spec's eslint config file to look like the below:

```js
// ~/tests/unit/.eslintrc.js
module.exports = {
  env: {
    mocha: true
  },
  globals: {
    expect: true,
    mount: true
  },
};
```

I'm having a hard time reproducing the issue after I fixed the eslint issues. I'll keep trying to break it.
