### ISSUE TITLE
Vue + Jest + Typescript Unexpected reserved word 'let' and Jest encountered an unexpected token

### ISSUE THREAD

**Issue by Maniumn** [vuejs/vue-test-utils#1357]
I get different errors by unit test for working code. With babel installed "Unexpected reserved word 'let'" and without babel installed "Jest encountered an unexpected token". What do I do wrong?

Reproduceable Projects, with babel [Vue with babel](https://github.com/Maniumn/vue-typescript-babel-unit-test), without babel [Vue without babel](https://github.com/Maniumn/vue-typescript-no-babel-unit-test)

### Steps to reproduce:
```
git clone
npm i
npm run test:unit
```

### Current behaviour: 
Errors: Unexpected reserved word 'let' and Jest encountered an unexpected token

### Expected behaviour: 
Test must be passed

**Comment by gopalakrishnanr-paypaycorp** [comment]
Is that issue was fixed or not, Is there have any solution?
