### ISSUE TITLE
v1.0.0-beta.30 completely breaks our build, but I can't open an official ticket on it

### ISSUE THREAD

**Issue by SaschaMaisel** [vuejs/vue-test-utils#1361]
Hello,

a couple days ago you pushed v1.0.0-beta.30 to npm and our CI setup duly installs the latest version of vue-test-utils at night. It turns out, it completely breaks our tests. I've already debugged a bit,
 created a minimal working/breaking repo and would like to file an official ticket for it, but the issue helper at https://new-issue.vuejs.org/?repo=vuejs/vue-test-utils doesn't allow me to select beta.30 on it.

Is it possible that you guys pushed a version to npm that isn't officially "latest" in whatever internal versioning system you use?

Best,
Sascha

PS: see shot below:

![shot](https://user-images.githubusercontent.com/15332747/70027590-c4459080-15a2-11ea-825b-5870913e7717.png)

**Comment by SaschaMaisel** [comment]
Thank you, robot-friend for kindly closing my issue. Hope some human-friend still reads this, as I can't open a helper-created issue (as outlined above).

**Comment by TayHobbs** [comment]
I'm seeing this completely break a lot of my apps tests with no changes. I do not have any code related to the `breaking changes` section of the release notes.

@eddyerburgh

**Comment by cars10** [comment]
@SaschaMaisel do you use `trigger` and snapshots? This was the problem for me. Apparently you now have to explicitly `await` the `nextTick` to check for dom updates. See [https://vue-test-utils.vuejs.org/guides/#using-nexttick](https://vue-test-utils.vuejs.org/guides/#using-nexttick) .

In my case i had something like this:

```javascript
  it('should render toggled content', () => {
    const wrapper = mount(ContentToggle)
    let activator = wrapper.find('.content-toggle__last_activator')
    activator.trigger('click')
    expect(wrapper.element).toMatchSnapshot()
  })
```

And i had to change it like this:

```javascript
  it('should render toggled content', async () => {
    const wrapper = mount(ContentToggle)
    let activator = wrapper.find('.content-toggle__last_activator')
    activator.trigger('click')
    await Vue.nextTick()
    expect(wrapper.element).toMatchSnapshot()
  })
```

**Comment by TayHobbs** [comment]
@cars10 I will give this a shot, thank you!
