### ISSUE TITLE
Wrapper.emitted() does not register events from fowarded listeners

### ISSUE THREAD

**Issue by vvanpo** [vuejs/vue-test-utils#1364]
### Version
1.0.0-beta.30

### Reproduction link
[https://gist.github.com/vvanpo/77af34a1392fae3319a42048b736acb3](https://gist.github.com/vvanpo/77af34a1392fae3319a42048b736acb3)

### Steps to reproduce
```sh
git clone https://gist.github.com/77af34a1392fae3319a42048b736acb3.git
cd 77af34a1392fae3319a42048b736acb3
yarn
yarn jest
```

### What is expected?
One expects that any event that can be captured by a listener set on a component would be observable in `Wrapper.emitted()`.

### What is actually happening?
Because listener registered with `v-on` is simply forwarded to a child, as documented in https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components, the `emitted()` object remains empty even with event listeners have been successfully invoked.

**Comment by lmiller1990** [comment]
Looks like a bug that should be fixed. Would you be interested in giving it a crack?

**Comment by vvanpo** [comment]
I would, but the more I think about it the more complicated it seems. For example, how should
```js
  const listeners = {
    click: jest.fn(),
    focus: jest.fn(),
  };
  const component = mount({
    template: `<button v-on="listeners">foo</button>`,
    computed: {
      listeners() {
        return {
          ...this.$listeners,
          click: () => {},
        }
      },
    },
  }, {
    listeners,
    localVue: createLocalVue(),
  })

  component.trigger('click');
  component.trigger('focus');
```
behave?

How would `@vue/test-utils` be able to know exactly which listener was forwarded?

**Comment by vvanpo** [comment]
Something I missed: https://vue-test-utils.vuejs.org/api/wrapper/#emitted

> Return an object containing *custom* events

So my reproduction examples are incorrect, as `emitted()` is not supposed to return DOM events.

I'm inclined to just close this, as there is distinct difference between a forwarded listener and a call to `$emit()`. Maybe the best solution here is just to add an explanation of this difference to the documentation, with an example of a mocked listener to mitigate the problem.

**Comment by JessicaSachs** [comment]
Right. I see what you mean. I’m sorry for not catching the difference in you original gist.

I’ll close this issue. Please feel free to improve the docs in a PR. Thank you for your investigation and time spent 🙏🏻🚀
