### ISSUE TITLE
 Can I check a child component destroyed with  'wrapper.find(vm).element.__vue__'?

### ISSUE THREAD

**Issue by wonsuhyun** [vuejs/vue-test-utils#1366]
### What problem does this feature solve?
I want to check if a child component has destroyed, when wrapper.destroyed()
I can't check it  this way : wrapper.contains('#DOMelement').toBeFalsy()
I can check it  in the following ways : 

vm = child component 
 expect(wrapper.find(vm).element.__vue__).not.toEqual(null)
wrapper.destroy()
 expect(wrapper.find(vm).element.__vue__).toEqual(null)

but I'm not sure this is right way
Can I get a better way  or Is this the best way?

### What does the proposed API look like?
i have no idea

**Comment by lmiller1990** [comment]
Can you do `expect(wrapper.find('#child-el').exists()).toBe(false)`?

**Comment by JessicaSachs** [comment]
I believe the above will solve your issue. Going to close this issue -- please reopen with a Github reproduction if @lmiller1990's suggestion doesn't help
