### ISSUE TITLE
[Cookbook Error]The "data" option should be a function 

### ISSUE THREAD

**Issue by asmallkite** [vuejs/vue-test-utils#1368]
### Reproduction link
[https://vuejs.org/v2/cookbook/unit-testing-vue-components.html#Real-World-Example](https://vuejs.org/v2/cookbook/unit-testing-vue-components.html#Real-World-Example)

### Steps to reproduce
1. open https://vuejs.org/v2/cookbook/unit-testing-vue-components.html#Real-World-Example
2. find the cook about "'renders a message and responds correctly to user input',"
3. i follow the cookbook as it is ,I find it does not work as expected. and there is a waring :
  console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
    [Vue warn]: The "data" option should be a function that returns a per-instance value in component definitions.

### What is expected?
    const wrapper = shallowMount(TextRender2, {
      data () {
        return {
          message: 'Hello World',
          username: ''
        }
      }
    })

### What is actually happening?
it('renders a message and responds correctly to user input', () => {
    const wrapper = shallowMount(Foo, {
      data: {
        message: 'Hello World',
        username: ''
      }
    })

---
https://cn.vuejs.org/v2/cookbook/unit-testing-vue-components.html#%E5%AE%9E%E9%99%85%E7%9A%84%E4%BE%8B%E5%AD%90
https://vuejs.org/v2/cookbook/unit-testing-vue-components.html#Real-World-Example
document or cookbook issue

**Comment by lmiller1990** [comment]
Hey, I think this issue should be opened on the docs repo here: https://github.com/vuejs/vuejs.org/tree/master/src/v2/cookbook

That's where the source for that guide is.

**Comment by afontcu** [comment]
Yep, the issue should be opened on the docs repo :)  

Closing this. Thank you for pointing this out! 🙌
