### ISSUE TITLE
Add example in documentation that show show to test Vuex Store

### ISSUE THREAD

**Issue by gkatsanos** [vuejs/vue-test-utils#137]
As in https://github.com/eddyerburgh/chapter-6/blob/master/src/store/__tests__/actions.spec.js , could you include a small use case/example on how to do simple Vuex store testing?

**Comment by lmiller1990** [comment]
I'm interested in contributing to this. I've been doing a lot of testing stuff with Vuex lately (from methods, to mocks the responses and seeing how things change in components etc), do you have anything specific in mind?

**Comment by gkatsanos** [comment]
Same here. I'm still not 100% confident I can document this as also the library is evolving but already I've built up some skills.

**Comment by lmiller1990** [comment]
If you just want help testing your store let me know @gkatsanos , I have done a lot of this kind of thing lately. I will be writing more about this in the coming weeks too, you can see [here](https://medium.com/@lachlanmiller_52885/a-pattern-for-mocking-and-unit-testing-vuex-actions-8f6672bdb255)  for more info or just get in touch and I can help you out.

**Comment by eddyerburgh** [comment]
I believe this is covered mostly in test-with-vuex. I think that section could be cleaned up though to be more clear
