### ISSUE TITLE
document.querySelectorAll call from destroyed lifecycle hook cannot find DOM elements

### ISSUE THREAD

**Issue by jpicton** [vuejs/vue-test-utils#1386]
### Version
1.0.0-beta.30

### Steps to reproduce
```
// Component
<template>
  <div id="outer">
    <div class="inner">Test</div>
  </div>
</template>

<script>
export default {
  destroyed() {
    document.querySelectorAll('#outer .inner').forEach(inner => console.log(inner));
  }
};
</script>
```

```
// Test
const wrapper = mount(Component, {
  attachToDocument: true
});

wrapper.destroy();
```

### What is expected?
When `wrapper.destroy()` is called, the HTMLDivElement will be logged out to console.

### What is actually happening?
Nothing is logged to console.

I believe the problem lies in the code at https://github.com/vuejs/vue-test-utils/blob/v1.0.0-beta.30/packages/test-utils/src/wrapper.js#L136. When `attachToDocument` is `true`, `this.element.parentNode` in the linked code will be a `HTMLBodyElement` and the component will be removed from the DOM before `vm.$destroy()` is called. This means that the subsequent call to `document.querySelectorAll()` in the `destroyed` lifecycle hook will find nothing (because the target element has already been detached from the DOM) and nothing is logged to console.

**Comment by jpicton** [comment]
I would have used the Issue Helper if the page wasn't broken (I cannot choose a version and thus can't preview my generated issue).

**Comment by afontcu** [comment]
Hi @jpicton! 👋 Just tried and I could successfully select `beta.30` as the VTU version in our [Issue Helper](https://new-issue.vuejs.org/?repo=vuejs/vue-test-utils&type=bug-report). Could you give it another go?

Thanks! 🙌
