### ISSUE TITLE
test  mapState failed. 

### ISSUE THREAD

**Issue by tolerious** [vuejs/vue-test-utils#1394]
### Version
1.0.0-beta.29

### Reproduction link
[https://codepen.io/tolerious/pen/PowEEOO](https://codepen.io/tolerious/pen/PowEEOO)

### Steps to reproduce
npm run test:unit

### What is expected?
success

### What is actually happening?
failed.
can not read 'submitLocationTotal' in  mapState.
![image](https://user-images.githubusercontent.com/2922120/71821337-d4362000-30cc-11ea-8c5f-0f71e16ac3fe.png)

**Comment by lmiller1990** [comment]
Shouldn't it be

```
beforeEach(() => {
        store = new Vuex.Store({
            state: {
                claim: { submitLocationTotal: 123 }
            },
        })
    })
```

You forgot the `claim` field. I'm fairly sure this should work fine. The repro link is also not working; can you provide one that shows the error?

**Comment by tolerious** [comment]
> Shouldn't it be
> 
> ```
> beforeEach(() => {
>         store = new Vuex.Store({
>             state: {
>                 claim: { submitLocationTotal: 123 }
>             },
>         })
>     })
> ```
> 
> You forgot the `claim` field. I'm fairly sure this should work fine. The repro link is also not working; can you provide one that shows the error?

Yeah, that's right , thank U ~

**Comment by tolerious** [comment]
@lmiller1990  another question， if I use a third  part component library like vue-antdesign in my own component, how can I test my own component?

**Comment by lmiller1990** [comment]
Same way you test any other component. If you have more questions, the best place to ask is https://vue.land/ in the #testing channel.

**Comment by alibalbars** [comment]
@tolerious like project's index.js file for example Vue.use(BootstrapVue), you should also put this line in jest setup file. it works for me
