### ISSUE TITLE
Component props are not correctly updated

### ISSUE THREAD

**Issue by JFGHT** [vuejs/vue-test-utils#1397]
### Version
1.0.0-beta.30

### Reproduction link
[https://github.com/JFGHT/vue-test](https://github.com/JFGHT/vue-test)

### Steps to reproduce
yarn
yarn test:unit

### What is expected?
Tests should pass.

### What is actually happening?
Test do not pass.

---
This test was passing in beta 29.

**Comment by dobromir-hristov** [comment]
Hey mate, I dont see in that test you setting props.
Second, why accessing raw DOM nodes instead of using the test utils helpers?
Third the library is now async, so you should `await wrapper.vm.$nextTick()` after changes, so the DOM re-renders. 

Try that and let us know.

**Comment by JFGHT** [comment]
Thanks. The awaiter worked. I'm also introducing the utils helpers now.

Closing.
