### ISSUE TITLE
emitted() does not work with trigger in beta 29 , works with 28

### ISSUE THREAD

**Issue by samgre** [vuejs/vue-test-utils#1403]
### Version
1.0.0-beta.30

### Reproduction link
[https://github.com/samgre/vue-test-utils-bug/](https://github.com/samgre/vue-test-utils-bug/)

### Steps to reproduce
To reproduce the issue, clone the repository and follow these steps:

1. Run `npm i && npm test` to run the test
2. The test fails.
3. Fix version of @vue/test-utils to older one, 1.0.0-beta.28
4. Re-run the test `npm i && npm test`
5. The test passes.

### What is expected?
The test should pass also on 1.0.0-beta.30. At least I did not see anything related to this in the change log.

### What is actually happening?
The test that used to pass, now fails.

---
I upgraded from beta 28 to beta 30.

**Comment by dobromir-hristov** [comment]
Hey there. As of v30 the tests are no longer synchronous, so after each event trigger, if you want to assert if the dom got updated, you need to wait for the `$nextTick()`.
`await wrapper.vm.$nextTick()` should do the job, just after the trigger.

**Comment by samgre** [comment]
That's it, thanks!

The issue is documented under section Common tips, but not in the api reference [1], [2]. It would be a nice improvement, if the code example in [1] could highlight this.

You may close this issue or make it a suggestion to improve docs.

[1] https://vue-test-utils.vuejs.org/api/wrapper/#trigger
[2] https://vue-test-utils.vuejs.org/api/wrapper/#emitted

**Comment by lmiller1990** [comment]
@samgre Good idea. Would you like to make a PR updating the docs? Good chance for a first PR!

Happy to do it if you haven't got the time. We should update all the documentation to reflect the need for `await wrapper.vm.$nextTick`.

**Comment by samgre** [comment]
Sure, would this do? https://github.com/vuejs/vue-test-utils/pull/1405

**Comment by lmiller1990** [comment]
yep, nice job. looks good!
