### ISSUE TITLE
wrapper.vm.$nextTick() doesn't seem to work correctly in 1.0.0-beta.30 with bootstrap-vue modal

### ISSUE THREAD

**Issue by Loremaster** [vuejs/vue-test-utils#1406]
### Version
1.0.0-beta.30

### Reproduction link
[https://github.com/Loremaster/next-tick-modal-issue](https://github.com/Loremaster/next-tick-modal-issue)

### Steps to reproduce
1. Clone repo
2. Run `$ yarn`
3. Run tests: `$ yarn run test:unit`

### What is expected?
I expect tests to pass.

### What is actually happening?
Test fails saying that modal wasn't closed. For a weird reason if I replace `await wrapper.vm.$nextTick()` with `await wrapper.vm.$nextTick` in line 29 in `tests/unit/ComposeButton.spec.js` it passes which is surprising.

**Comment by dobromir-hristov** [comment]
I suspect its because of transitions, but I am not sure. Not waiting the ticks just means it was never visible in the DOM :)
We removed the Transition stub in v 30 :/

**Comment by Loremaster** [comment]
What would be a workaround to fix it then? I want to upgrade to latest version of vue-test-utils but not sure how to tackle that issue

**Comment by dobromir-hristov** [comment]
Try stubbing the transition element globally?

**Comment by Loremaster** [comment]
I tried to stub transition like that:

```js
const wrapper = mount(Component, {
  localVue,
  stubs: { transition: false },
});
```

but it didn't work for me

**Comment by Loremaster** [comment]
I was able to achieve waiting for closing by using next set of commands:

```js
  const waitRAF = () => new Promise(resolve => requestAnimationFrame(resolve))

  it("hides modal on @error", async () => {
    const { wrapper } = await setup();
    const buttons = wrapper.find(Buttons);

    buttons.vm.$emit("upload");
    await Vue.nextTick(); // wait for modal to show
    buttons.vm.$emit("error");
    await Vue.nextTick();
    await waitRAF();
    await Vue.nextTick();
    await waitRAF();

    expect(wrapper.find(".modal").isVisible()).toBeFalsy();
  });
```

**Comment by Loremaster** [comment]
@dobromir-hristov sorry for asking here not sure what the best place would be. Can you tell me how can I stub transition and children in the same time? Let's say I have that:

```js
  const wrapper = mount(Component, { stubs: ["child1", "child2"] }
```

I want to add `transition: transitionStub()` into that but not sure what is the proper way for that. Will appreciate any help with that.

**Comment by dobromir-hristov** [comment]
https://vue-test-utils.vuejs.org/api/options.html#stubs
```js
stubs: { 
  child1: true,
  child2: true,
  transition: TransitionStubComponent
}
```

**Comment by Loremaster** [comment]
@dobromir-hristov my bad, missed that one. Thank you!
