### ISSUE TITLE
404 on script (documentation)

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs/vue-test-utils#1408]
### Version
1.0.0-beta.30

### Reproduction link
[https://vue-test-utils.vuejs.org](https://vue-test-utils.vuejs.org)

![image](https://user-images.githubusercontent.com/1668207/72562645-e442c200-3879-11ea-8e81-7953069ddb30.png)

### Steps to reproduce
Go to docs, open console, see hundreds of 404's

### What is expected?
No 404's

### What is actually happening?
It can't load the app script

**Comment by dobromir-hristov** [comment]
Sorry I cant reproduce this issue.

**Comment by lmiller1990** [comment]
Me either - might have been a caching issue. Can you hard refresh @TheDutchCoder ?

**Comment by TheDutchCoder** [comment]
Okay it seems to be working again.
The site was very slow yesterday as well, so maybe something was up with that. Will close!
