### ISSUE TITLE
Make Codesandbox with latest VTU more visible for reporting issues

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/vue-test-utils#1418]
#1417 points out there is some friction in reporting an issue. We should have a link to a codesandbox that people can use to repro their problem easily. Maybe we can include this in the issue template.

**Comment by dobromir-hristov** [comment]
I like the idea, how do we change the issue template for VTU?

**Comment by lmiller1990** [comment]
I have no idea, probably need to ask someone to do it. We can change the GH default here, though: https://github.com/vuejs/vue-test-utils/blob/dev/.github/ISSUE_TEMPLATE.md

Let's ping someone in core.

**Comment by lmiller1990** [comment]
I have realized CSB may not be ideal; you cannot access node_modules or the original git repo, it seems, which is very annoying for debugging more complex issues.

**Comment by lmiller1990** [comment]
We have updated the PR issues template to use the built-in GH one.
