### ISSUE TITLE
(docs)Update links to "get"

### ISSUE THREAD

**Issue by novellac** [vuejs/vue-test-utils#1420]
### Version
1.0.0-beta.31

### Reproduction link
[https://vue-test-utils.vuejs.org/api/wrapper/find.html](https://vue-test-utils.vuejs.org/api/wrapper/find.html)

### Steps to reproduce
- Scroll to the bottom of the page
- Click on the link "get" in the sentence "See also: get."

### What is expected?
Clicking on the link will lead to a 404.

### What is actually happening?
"https://vue-test-utils.vuejs.org/api/get.html" cant' be found, and there is no redirect.

---
The absolute URL of the correct link could be either: https://vue-test-utils.vuejs.org/api/wrapper/#get OR https://vue-test-utils.vuejs.org/api/wrapper/get.html

**Comment by dobromir-hristov** [comment]
Want to make a PR?

**Comment by novellac** [comment]
Yep, I will try to get the docs site spun up on my local and have a go at a PR. Is there a preference between `/api/wrapper/#get` and `/api/wrapper/get.html` ?

**Comment by afontcu** [comment]
Hi! I'd go with https://vue-test-utils.vuejs.org/api/wrapper/get.html since the other "See also" link points to the `.html` file.

Thanks for this! :)

**Comment by dobromir-hristov** [comment]
Hey. I updated the links, had some weird caching bugs, but got them sorted.

Thanks @novellac for finding this.
