### ISSUE TITLE
Can not find inner child element by ID

### ISSUE THREAD

**Issue by begueradj** [vuejs/vue-test-utils#1423]
### Version
1.0.0-beta.31

### Reproduction link
[https://github.com/begueradj/test-vuetify-bug2](https://github.com/begueradj/test-vuetify-bug2)

### Steps to reproduce
Have a component with an icon which displays info text on hover:
```javascript
<template>
  <v-container fill-height fluid>
    <v-card-text>
      <v-toolbar class="green--text">
        <v-app-bar-nav-icon v-if="tooltipText">
          <v-tooltip id="id1" bottom>
            <template id="id2" v-slot:activator="{ on }">
              <v-icon v-on="on" color="grey">
                help
              </v-icon>
            </template>
            <span id="id3">
              {{ tooltipText }}
            </span>
          </v-tooltip>
        </v-app-bar-nav-icon>
      </v-toolbar>
    </v-card-text>
  </v-container>
</template>

<script>
export default {
  props: {
    tooltipText: { type: String, default: '' }
  }
}
</script>
```

Try to access elements with id2 or id3, you will not be able to access them. But element with id1 is accessible:

```javascript
import Vuetify from 'vuetify'
import { mount } from '@vue/test-utils'
import ComponentTwo from '@/components/ComponentTwo.vue'

const vuetify = new Vuetify()
let wrapper = null

beforeEach(() => {
  const app = document.createElement('div');
  app.setAttribute('data-app', true);
  document.body.append(app);
  wrapper = mount(ComponentTwo, {
    vuetify,
    propsData: {
      tooltipText: 'science'
    }
  })
})

afterEach(() => {
  wrapper.destroy()
})

describe('ComponentTwo.vue:', () => {
  it('1. Mounts properly', () => {
    expect(wrapper.isVueInstance()).toBe(true) // Ok
  })

  it('2. Access elements by ID', async () => {
    const icons = wrapper.findAll('.v-icon')
    expect(icons.length).toBe(1) // Ok

    const helpIcon = icons.at(0)
    expect(helpIcon.text()).toEqual('help') // Ok

    helpIcon.trigger('mouseenter')
    await wrapper.vm.$nextTick()

    const e1 = wrapper.find('#id2') // or id3
    console.log(e1) // undefined
  })
})
```

### What is expected?
I expect to access element with `id2` and `id3`

### What is actually happening?
Vue test utils is able to find the child with `id1`, but not the children with `id2` and `id3`

**Comment by afontcu** [comment]
Hi! 👋 


For `#id2` I'm not sure you can set an `id` to a `<template>`. What about adding it to the `<v-icon>`? That appears to work.

For `#id3`,  I guess you should use the `requestAnimationFrame` as stated [here](https://github.com/vuejs/vue-test-utils/issues/1421#issuecomment-581100966):

```js
    requestAnimationFrame(() => {
      const e1 = wrapper.find("#id3");
      console.log(e1); // not undefined anymore
      done();
    });
```

If these ideas fix your test, feel free to close up the issue 😄 

Hope it helps!

**Comment by begueradj** [comment]
I think you are right in both observations.
I will test your solution in the coming hours. Thank you very much for the feedback @afontcu

**Comment by afontcu** [comment]
you welcome! 

I'll go ahead and close the issue for now, feel free to ask additional questions in the [Forum](https://forum.vuejs.org/) in the [Chat](https://discordapp.com/invite/HBherRA) 😄
