### ISSUE TITLE
Globally registered components

### ISSUE THREAD

**Issue by RyanHavoc** [vuejs/vue-test-utils#1424]
### What problem does this feature solve?
Vue documentation suggests it beneficial to globally register components prefixed with `Base`, details here: https://vuejs.org/v2/style-guide/#Base-component-names-strongly-recommended

```
var requireComponent = require.context("./src", true, /Base[A-Z]\w \.(vue|js)$/)
requireComponent.keys().forEach(function (fileName) {
  var baseComponentConfig = requireComponent(fileName)
  baseComponentConfig = baseComponentConfig.default || baseComponentConfig
  var baseComponentName = baseComponentConfig.name || (
    fileName
      .replace(/^. \//, '')
      .replace(/\.\w $/, '')
  )
  Vue.component(baseComponentName, baseComponentConfig)
})
```

This works well and greatly reduces the number of imports needing to be declared on custom components. However, Vue Test Utils doesn't appear to have a way to globally register these same components. I realise we can use `localVue` and explicitly register these components on a per test basis however the overhead we're now saving in the components has just been moved to our test suite. Is there a way to globally register these components in Vue Test Utils as well?

### What does the proposed API look like?
Perhaps something like `beforeSuite` to register components for the entire test suite?

**Comment by dobromir-hristov** [comment]
You can just register them as you normally do. That will pollute all Vue instances, but it's what you want in the end, no?
`Vue.component("name", Component)`, then it will be available everywhere.

**Comment by RyanHavoc** [comment]
Ah, I can do that in setup.js. Cool thanks.
