### ISSUE TITLE
Once again 404's on documentation site

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs/vue-test-utils#1429]
### Version
1.0.0-beta.31

### Reproduction link
[https://vue-test-utils.vuejs.org/guides/?](https://vue-test-utils.vuejs.org/guides/?)

### Steps to reproduce
When searching on the documentation site I get a bunch of 404's on scripts

### What is expected?
No 404's

### What is actually happening?
404's

---
URL: https://vue-test-utils.vuejs.org/guides/?
Search param: 'classes'.

Will try to add a screenshot

![image](https://user-images.githubusercontent.com/1668207/73782718-90cce100-4760-11ea-9456-14c61878894f.png)

**Comment by TheDutchCoder** [comment]
This keeps happening almost daily and I'm not sure what causes it or how to consistently reproduce it.

I'm sure your logs will have some more info!

**Comment by afontcu** [comment]
Hi! 👋  Looks fine from here, have you tried with another browser / private network tab / removing the installed service workers?

**Comment by TheDutchCoder** [comment]
Oh yes, it's 100% the service workers that somehow mess up occasionally. You should probably check that out.

The problem resolves when I remove them and reload the page.

**Comment by afontcu** [comment]
We'll take that into account :) Thanks for the feedback!
