### ISSUE TITLE
How to use event modifiers in tests?

### ISSUE THREAD

**Issue by dav1app** [vuejs/vue-test-utils#1433]
### Version
1.0.0-beta.29

### Reproduction link
[https://jsfiddle.net/ex0n6w53/9/](https://jsfiddle.net/ex0n6w53/9/)

### Steps to reproduce
Use the link to minimal reproduction and create a test for that module that uses `el.trigger('mousedown.right')` or `el.trigger('mousedown.left')`

### What is expected?
To have some documentation on that.

### What is actually happening?
No documentation.

---
I wasn't able to test on the latest version, since beta 31 broke almost all of my tests.

**Comment by lmiller1990** [comment]
This is documented in the example here: https://vue-test-utils.vuejs.org/api/wrapper/#trigger

You should be able to do `trigger('mousedown', { right: true })`?

Going to close this since from what I can tell, this is documented and works fine - let me know if this isn't working as expected.

**Comment by carlos22** [comment]
This does not work anymore with current versions. The correct call would be:

`trigger('click', { button: 2 })` as the docs suggest, but it does never call handler if it is registered like: `@click.right="handler"`.

**Comment by lmiller1990** [comment]
I thought we supported `trigger('click.right')` syntax too - could be wrong, would need to verify.

If you found a bug, please make a minimal example and post a new issue.

**Comment by carlos22** [comment]
Ok: https://github.com/vuejs/vue-test-utils/issues/1875
