### ISSUE TITLE
Clarify docs on how to mock $root

### ISSUE THREAD

**Issue by aantipov** [vuejs/vue-test-utils#1437]
### What problem does this feature solve?
The [docs](https://vue-test-utils.vuejs.org/api/options.html#mocks) say that I can use `mocks` mounting option to mock "global injections" like `$route`.

I considered `$root` as a "global injection" and that I can use `mocks` to mock it. Unfortunately it didn't work for me, I spent lots of time trying to make it working, without any success. In the end I came up with a [solution](https://github.com/vuejs/vue-test-utils/issues/481#issuecomment-423716430) to use `parentComponent` option to mock `$root`.

As far as I understood it's not possible to mock `$root` using `mocks` and it's not considered as a bug.

If I'm right, then the docs for `mocks` need clarification stating that clearly and providing a way to mock `$root`

### What does the proposed API look like?
The docs should say smth like this:

"One can't use `mocks` to mock `$root` though. If you need to mock `$root`, use "parentComponent" option instead."

And provide "parentComponent" section with an example how to mock `$root`

**Comment by lmiller1990** [comment]
I don't think `$root` is really a global injection in the same way Vuex and VueRouter are; global injection here really should be written as "properties injected by third party plugins, assigned to `Vue.prototype`".

I think a PR adding a note about `$root` would be a great idea.. I don't think we need a whole section dedicated to mocking `$root`; this isn't a very common use case, afaik, and the docs are already pretty bloated with a lot of information.

**Comment by aantipov** [comment]
@lmiller1990  
We, developers, all come with a different background and see at things from a different perspective.
So your point may be true for some and not for others.

Irrespective of that, I see the "Mounting Options" documentation covering all possible cases when you need to provide/mock some of the component data (arguments, data, methods, slots, components, etc.).
The only missing part is `$root`, and from the documentation it's not clear why can't one use `mocks` and should use `parentComponent` instead, it's not trivial at all.

I might agree that the need in mocking `$root` might not come often, but still it happens and it would be good for the docs to cover that use case.

I try prepare the PR, if I have time

**Comment by lmiller1990** [comment]
@aantipov I agree, everyone has different backgrounds - I can see why you might expect `mocks` to work with `$root`. Happy for a PR adding a note about this (I think under the `mocks` section in the API docs would be best). You could include a link to the issue with the work around.

Will mark this as "good first issue" so someone else can pick it up if you don't have time. Thanks!
