### ISSUE TITLE
Plaint text in default slot is lost with wrapper.html()

### ISSUE THREAD

**Issue by TheJaredWilcurt** [vuejs/vue-test-utils#1439]
### Version

1.0.0-beta.31

### Reproduction link

* [tjw-lint/jest-serializer-vue-tjw/pull/46](https://github.com/tjw-lint/jest-serializer-vue-tjw/pull/46/files)

### Steps to reproduce

```html
<template>
  <button>
    <slot></slot>
  </button>
</template>

<script>
export default {
  name: 'SlotTest'
};
</script>
```

```js
test('Slot text', () => {
  const wrapper = mount(MyComponent, {
    slots: { default: 'text' }
  });

  // Expected: <button>text</button>
  // Actually: <button></button> ❌ 
  expect(wrapper.html())
    .toEqual('<button>text</button>');
});

test('Slot markup', () => {
  const wrapper = mount(MyComponent, {
    slots: { default: '<p>text</p>' }
  });

  // Expected: <button><p>text</p></button>
  // Actually: <button><p>text</p></button> ✔️ 
  expect(wrapper.html())
    .toEqual('<button>\n  <p>text</p>\n</button>');
})
```

### What is expected?
`<button>text</button>`

### What is actually happening?
`<button></button>`

---
This was originally reported in https://github.com/vuejs/vue-test-utils/issues/718

**Comment by TheJaredWilcurt** [comment]
The example here fits within the documentation for Vue 2.6 and VTU. I feel like this should be included as part of the TODO list for VTU v1.

**Comment by afontcu** [comment]
Hi @TheJaredWilcurt! Just check and tests not relying on snapshot serializer are properly working. Is it possible that this is related to the serialization of the component in Jest snapshots rather than an issue in VTU?

**Comment by TheJaredWilcurt** [comment]
@afontcu No. This is not related to the serializer. I have updated the test case to prove this.

**Comment by afontcu** [comment]
Hum, I might be missing something here, but I couldn't seem to reproduce the issue you are facing – ran both your tests in local and got them passing instantly (beta.31):

![image](https://user-images.githubusercontent.com/9197791/75046988-5ab09080-54c6-11ea-923e-2629bf088daf.png)

Tried with a SFC too (just in case), and they still pass.

**Comment by TheJaredWilcurt** [comment]
I tried in CodeSandbox and could not reproduce the issue. So now I just need to find out what about my set up causes it to happen in my repo :confused: 

**edit:** This also occurs in the official `jest-vue-serializer`, which my set up is based on.

**Comment by afontcu** [comment]
Sure! I'm gonna close this, feel free to reopen or create a new one if you find any additional issue in VTU 😄
