### ISSUE TITLE
v1.0.0-beta.4 seems to break mock/stub/spy with sinonjs

### ISSUE THREAD

**Issue by tverhoken** [vuejs/vue-test-utils#144]
### version

v1.0.0-beta.4

### What is expected ?

When using [sinonjs](http://sinonjs.org/) to mock/stub/spy `$store`'s functions, these `$store`'s function should have the provided behavior by mock/stub/spy.

### What is actually happening ?

When I use `sinon.stub(...)` to provide a behavior on `$store`'s function, it seems like sinon can't do the function replacement. No error is thrown and tests failed because `$store`'s functions behavior do not change.
Unit tests were running well until npm update from _vue-test-utils_ v1.0.0-beta.2 to v1.0.0-beta.4

Here is an example of unit test with described behavior :

```javascript
import ...

describe('Component...', () => {
  let vm

  beforeEach(() => {
    vm = createComponentInstance()
  })

  it('Should do something when $store dispatch call throw an error.', done => {
    sinon.stub(vm.$store, 'dispatch').rejects(new Error('Something bad happens here'))

    vm.storeDispatchCallFunction()

    Vue.nextTick(() => {
      expect(vm.$toastr.called).to.be.true
      done()
    })
  })

  function getMockedStore () {
    return {
      dispatch: () => {},
      watch: sinon.spy(),
      commit: sinon.spy()
    }
  }

  function createComponentInstance () {
    const localVue = createLocalVue()
    const $store = getMockedStore()
    const $toastr = sinon.spy()
    return shallow(Component, {
      localVue,
      mocks: {
        $store,
        $toastr
      }
    }).vm
  }
})
```

and the component implementation :

```javascript
import ...

export default {
  // ...
  methods: {
    storeDispatchCallFunction () {
      this.$store.dispatch('SOME_ACTION').catch(error => {
        this.$toastr('error', error.message)
      })
    }
  }
}
```

Now my unit test fail because an error is thrown during its runtime : TypeError: Cannot read property 'catch' of undefined

Which is true because by default my mocked store dispatch function returns nothing. But I stub it just before the function call and with version change stubbing do nothing.

I fixed this by returning to previous v1.0.0-beta.2 version.

Any ideas ?

**Comment by eddyerburgh** [comment]
Hi, thanks for the bug report.

v1.0.0-beta.4 fixed a bug where mocks were not editing the localVue prototype, which meant child components weren't receiving mocks correctly. https://github.com/vuejs/vue-test-utils/issues/127

I'm not sure exactly why using the sinon.stub() method to, but you can fix the tests by using this pattern. I'm going to look into why, because I'm curious what the difference is!

Replace this line:
```js
sinon.stub(vm.$store, 'dispatch').rejects(new Error('Something bad happens here'))
```
With this:
```js
vm.$store.dispatch = sinon.stub()
vm.$store.dispatch.rejects(new Error('Something bad happens here'))
```

This behavior won't be changed, but I'll try and find out why stubbing using the method is failing.
