### ISSUE TITLE
Vue not defined in "https://vue-test-utils.vuejs.org/guides/#using-nexttick"

### ISSUE THREAD

**Issue by quriosapien** [vuejs/vue-test-utils#1444]
### Version
1.0.0-beta.31

### Reproduction link
[https://github.com/vuejs/vue-test-utils/blob/dev/docs/guides/testing-async-components.md](https://github.com/vuejs/vue-test-utils/blob/dev/docs/guides/testing-async-components.md)

### Steps to reproduce
Vue is not defined in the `testing.js` file. 

### What is expected?
Vue should be defined or there should be a reference to the $vm

### What is actually happening?
If we run `npm run test` by copying and adding the code snippet, it throws error

**Comment by lmiller1990** [comment]
You will need to do `import Vue from 'vue'` in the unit test at the top. 

If you can submit a PR, that'd be great. 

The current docs are not ideal for this reason - they do not always have complete examples. We are in the process of redoing the docs, which will be aimed at supporting Vue 3. If this is something you are in interested in contributing to, reach out on Vueland Discord.
