### ISSUE TITLE
setData has no effect starting with version 1.0.0-beta-30

### ISSUE THREAD

**Issue by rowild** [vuejs/vue-test-utils#1447]
### Version
1.0.0-beta.31

### Reproduction link
[https://github.com/rowild/vue-unit-testing](https://github.com/rowild/vue-unit-testing)

### Steps to reproduce
Please checkout the repo, which contains 2 simple tests, and run the tests like this:

1. npm i -D @vue/test-utils@1.0.0-beta.31
2. npm run test:unit

The second test, which uses `setData()`, fails. Same thing with beta.30.

Please continue with:

3. npm i -D @vue/test-utils@1.0.0-beta.29
4. npm run test:unit

Now both tests work fine.

### What is expected?
Both tests in the example repo should work.

### What is actually happening?
Starting with 1.0.0-beta.30 the test that uses "setData()" does not work anymore.

---
This is a test example that is explained in the Vuemastery "Unit testing" course (link in the readme of the repository), which is, why I assume it is the correct way of writing a test.

**Comment by dobromir-hristov** [comment]
This fixes it for you, its because this requires the template to re-render, on next tick :)

```js
test('If logged in, show Logout button.', async () => {
    const wrapper = mount(AppHeader)
    wrapper.setData({ loggedIn: true })
    await wrapper.vm.$nextTick()
    expect(wrapper.find('button').isVisible()).toBe(true)
  })
```

**Comment by rowild** [comment]
Thank you for your quick response! Is this going to be the standard behaviour in vue-test-utils? Did I miss some documentation? Could you please point me to the place, where I can read about that?

**Comment by dobromir-hristov** [comment]
https://vue-test-utils.vuejs.org/guides/#using-nexttick

We will make this process easier in the next version of VTU.

**Comment by rowild** [comment]
Wow - you are really quick! Thank you so much!

**Comment by rowild** [comment]
Need to ask once more: It was not the case with beta.29 that async/await was necessary. What was the reason to change that behaviour?

**Comment by dobromir-hristov** [comment]
https://github.com/vuejs/vue-test-utils/issues/1137
