### ISSUE TITLE
Document about `nextTick` difference between English and Chinese

### ISSUE THREAD

**Issue by zkd8907** [vuejs/vue-test-utils#1451]
### Version
1.0.0-beta.31

### Reproduction link
[https://jsbin.com/pokuluhado/edit?html,js](https://jsbin.com/pokuluhado/edit?html,js)

### Steps to reproduce
In Chinese version, it says there is no need to use `Vue.nextTick()` because Vue Test Utils has applied it. But in English Version, it says We need to use `Vue.nextTick()` to wait until Vue has performed the DOM update after we set a reactive property.
My question is, which one is correct? After my testing, I found that if I changed the data of component without using `Vue.nextTick()`, `wrapper.html()` is still the original value.

### What is expected?
As Chinese Version, there is no need to use `Vue.nextTick()`.

### What is actually happening?
Test failed.

**Comment by zkd8907** [comment]
Chinese Version: https://vue-test-utils.vuejs.org/guides/getting-started.html#using-nexttick
English Version: https://vue-test-utils.vuejs.org/zh/guides/getting-started.html#%E5%85%B3%E4%BA%8E-nexttick-%E6%80%8E%E4%B9%88%E5%8A%9E%EF%BC%9F

**Comment by lmiller1990** [comment]
You need to use `nextTick`, `sync` mode was removed a few versions ago. The translations are mostly out of date - this is a hard problem, I don't have a good way to keep them updated.

If you want to make a PR that would be much appreciated. The English docs are the "source of truth".

**Comment by zkd8907** [comment]
Thank you your reply.
I've tried to translate this part from English to Chinese again, and I will make a PR later. Besides, I noticed that there also are differences translation about `nextTick` in other parts, and may need to be re-translated.

**Comment by lmiller1990** [comment]
Yep. We need a way to track changes and either notify a dedicated translator or just flag in the docs something like "this translation could be out of date". Not sure of any tools that do this, though.

**Comment by zkd8907** [comment]
> Yep. We need a way to track changes and either notify a dedicated translator or just flag in the docs something like "this translation could be out of date". Not sure of any tools that do this, though.

lmiller, I updated the Chinese translation of the nextTick part of the document, and added some new sections in common-tips.md. I have no better idea about the multilingual translation. However, I will update Chinese version in my spare time later.

**Comment by lmiller1990** [comment]
Thanks, just need you to run the `yarn format:check && yarn lint` (see PR review)

**Comment by zkd8907** [comment]
I've re-committed after format :)

**Comment by lmiller1990** [comment]
nice job, thanks a lot!
