### ISSUE TITLE
Cannot trigger click event: "Failed to execute 'dispatchEvent' on 'EventTarget'"

### ISSUE THREAD

**Issue by axwalker** [vuejs/vue-test-utils#1453]
### Version
1.0.0-beta.31

### Reproduction link
[https://codesandbox.io/s/vue-test-utils-issue-88765?fontsize=14&hidenavigation=1&module=%2Fsrc%2Fcomponents%2FHelloWorld.spec.js&previewwindow=tests&theme=dark](https://codesandbox.io/s/vue-test-utils-issue-88765?fontsize=14&hidenavigation=1&module=%2Fsrc%2Fcomponents%2FHelloWorld.spec.js&previewwindow=tests&theme=dark)

### Steps to reproduce
Run any test with a `trigger.("click")` event in any codesandbox - eg the test in the attached sandbox.

### What is expected?
The click event is triggered successfully.

### What is actually happening?
Error is thrown:

```
Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.
```

---
I was trying to setup a codesandbox to highlight a completely unrelated issue I had with testing another library (Vuetify) and found no matter what I did, I would always run into the above issue when trying to trigger a click event.

I then tried various other people's sandboxes that used vue-test-utils and found that every time the above error occurred.

This issue is only happening in CodeSandbox for me, not locally.

**Comment by lmiller1990** [comment]
Hm... code sandbox specific issue? :thinking:

Will ping someone who knows a bit more about code sandbox than I do.

**Comment by lmiller1990** [comment]
I have had no luck reproducing this outside of some specific sandboxes. Some libs are conflicting? Anyway, I don't know this is something we can fix in VTU. If it comes up more in the future, we can reopen.
