### ISSUE TITLE
Vue does not rerender when props changed

### ISSUE THREAD

**Issue by alexey2baranov** [vuejs/vue-test-utils#1454]
### Version
1.0.0-beta.31

### Reproduction link
[https://codesandbox.io/s/vue-test-utils-reproduction-template-0irkl](https://codesandbox.io/s/vue-test-utils-reproduction-template-0irkl)

### Steps to reproduce
run test. test will fail

### What is expected?
vue should sync rerender himself after prop changed 

### What is actually happening?
vue does not rerender himself

**Comment by aholzner** [comment]
Seems to be working fine. The component was trying to access properties of an object that doesn't exist. I have modified your code and it works fine.

```Javascript
<template>
  <div>{{ dog.age }}</div>
</template>

<script>
export default {
  name: "PropsComputedBug",
  props: {
    dog: {
      type: Object,
      default: () => ({})
    }
  }
  // props: {
  //   str: String,
  //   obj: Object,
  // },
  // computed: {
  //   cStr() {
  //     return this.str;
  //   },
  //   cObjNestedValue() {
  //     return this.obj.nestedValue;
  //   }
  // }
};
</script>
```

```Javascript
import { shallowMount, createLocalVue } from "@vue/test-utils";
import TestComponent from "./TestComponent";

let localVue = createLocalVue();

describe("TestComponent.vue", () => {
  let propsData = {
    dog: { age: 2 }
  };

  const wrapper = shallowMount(TestComponent, {
    localVue: localVue,
    propsData
  });
  it("should update vue on prop change", () => {
    // wrapper.vm.$props.dog.age = 18;
    wrapper.setProps({
      dog: {
        age: 18
      }
    });
    expect(wrapper.text()).toEqual("18");
  });
});
```

**Comment by afontcu** [comment]
Suggested fix seems to be working fine :) Closing this for now, feel free to open up a new issue if you think you ran into some bug, or use our [forum](https://forum.vuejs.org/) or our [discord server](https://discordapp.com/invite/HBherRA) to ask for guidance!
