### ISSUE TITLE
slotProps are not available in scoped slot with new `v-slot` syntax

### ISSUE THREAD

**Issue by sybrendotinga** [vuejs/vue-test-utils#1457]
### Version
1.0.0-beta.31

### Reproduction link
[https://codesandbox.io/s/ecstatic-nightingale-2u1t6?fontsize=14&hidenavigation=1&previewwindow=tests&theme=dark](https://codesandbox.io/s/ecstatic-nightingale-2u1t6?fontsize=14&hidenavigation=1&previewwindow=tests&theme=dark)

### Steps to reproduce
Run tests in CodeSandbox. I have provided two tests:

1. With the deprecated `scoped-slot` syntax works: `fullName` is available.
2. With the new `v-slot`-syntax: `fullName ` is `undefined`

### What is expected?
I expected to have `fullName` available in slotProps

### What is actually happening?
`fullName` is `undefined`

---
I have searched several similar issues in this repo, but it seems that the new syntax should work in `beta.31`. Maybe I am overlooking something?

https://vuejs.org/v2/guide/components-slots.html#Scoped-Slots

**Comment by lmiller1990** [comment]
Good catch. There is one bug [here](https://github.com/vuejs/vue-test-utils/blob/ee3a93f55ca511740367059f5002805acc339fae/packages/create-instance/create-scoped-slots.js#L90)

The code should be spreading `props`, like the others, eg `res = renderFn.call({ ...helpers, ...props })`, I think.

This gets rid of the error we have. But then you end up with:

```
"<div class=\"hello\">
      <h1><template></template></h1>
      <div>
        My name:
        <input></div>
    </div>"
```

As the HTML... it's failing to use the `template` contents. hm...

**Comment by doutatsu** [comment]
I am seeing this bug as well. Can't use either `v-slot:body` syntax (Raises `Jest encountered an unexpected token`), neither the shorthand syntax `#body` (Raises `SyntaxError: Unexpected character '#'`. 

When using deprecated syntax, tests run without issues...

**Comment by lmiller1990** [comment]
Will try to get onto this soon - not sure how involved it'll be, so I can't make any promises right now. But I think this is an important one to solve, I love thew new syntax.

**Comment by sybrendotinga** [comment]
Thanks @dobromir-hristov @lmiller1990 , works great!
