### ISSUE TITLE
Vue Test Utils: [Vue warn]: Unknown custom element: <v-container> - did you register the component correctly? 

### ISSUE THREAD

**Issue by begueradj** [vuejs/vue-test-utils#1459]
### Version
1.0.0-beta.31

### Reproduction link
[https://github.com/begueradj/bug-vue-test-utils](https://github.com/begueradj/bug-vue-test-utils)

### Steps to reproduce
Have **components/MyComponent.vue** file:

```javascript
<template>
  <v-container>
    Hello
  </v-container>
</template>

<script>
export default {
  name: 'MyComponent'
}
</script>
```

Have a **test/setup.js** file as recommended by Vuetify documentation:
```javascript
import Vue from 'vue'
import Vuetify from 'vuetify'

Vue.use(Vuetify)
```

Test if the component mounts properly in **test/MyComponent.spec.js**:
```javascript
import Vuetify from 'vuetify'
import { mount } from '@vue/test-utils'

import MyComponent from '@/components/MyComponent.vue'

const vuetify = new Vuetify()
const wrapper = mount(MyComponent, {
  vuetify
})

describe('MyComponent.vue:', () => {
  it('1. Mounts properly', () => {
    expect(wrapper.isVueInstance()).toBe(true)
  })
})
```

### What is expected?
The test should pass. 

### What is actually happening?
I get this error message:

>>[Vue warn]: Unknown custom element: <v-container> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by begueradj** [comment]
I close this because it is not a bug.
I simply forgot to declare the **setup.js** file in Jest configuration file.

Hope this helps someone.
Billal BEGUERADJ

**Comment by NWRichmond** [comment]
@begueradj could you please share what you added to your Jest config?

**Comment by andersbc** [comment]
@NWRichmond 

Add this entry to your Jest config `setupFiles: ['./path/to/setup.js'],`

A full example, assuming the Jest setup lives in a `jest.config.js` in the root (it could also be in your `package.json`):

```js
// file: jest.config.js
module.exports = {
  // ... 
  setupFiles: ['./tests/setup.js'], // <- add this
}
```

```js
// file: ./tests/setup.js
import Vue from 'vue'
import Vuetify from 'vuetify'

Vue.use(Vuetify)
```

For more, see the docs: https://jestjs.io/docs/en/configuration.

**Comment by adityajain-Infobeans** [comment]
> @NWRichmond
> 
> Add this entry to your Jest config `setupFiles: ['./path/to/setup.js'],`
> 

if i add this my components fail to load 

    I get this error : TypeError: Cannot read property 'components' of undefined
    
    code:
import LoginForm from '@/components/Forms/LoginForm.vue';
.
.
describe('LoginForm', () => {
  it('Verify login form validation', () => {
const wrapper = mount(LoginForm);
.
.

**Comment by kirschbaumj** [comment]
> > @NWRichmond
> > Add this entry to your Jest config `setupFiles: ['./path/to/setup.js'],`
> 
> if i add this my components fail to load
> 
> ```
> I get this error : TypeError: Cannot read property 'components' of undefined
> 
> code:
> ```
> 
> import LoginForm from '@/components/Forms/LoginForm.vue';
> .
> .
> describe('LoginForm', () => {
> it('Verify login form validation', () => {
> const wrapper = mount(LoginForm);
> .
> .

I ran into this as well. You still need to pass Vuetify to the mount function. Like so:
```
import Vuetify from "vuetify";

describe('LoginForm', () => {

  let vuetify;

  beforeEach(() => {
    vuetify = new Vuetify();
  });

  it('Verify login form validation', () => {
    const wrapper = mount(LoginForm, { vuetify });
```


Hope this helps someone

**Comment by devzom** [comment]
This helped me 
https://stackoverflow.com/a/61815475/10900851
