### ISSUE TITLE
Simulating emitting of events from child components

### ISSUE THREAD

**Issue by imolorhe** [vuejs/vue-test-utils#1462]
### What problem does this feature solve?
I am trying to simulate an event being emitted from a child component of a component (which would trigger some method call in the parent component) I am testing. After several attempts (and searching the internet), it seems it isn't possible to simulate the emit from the child component to the parent component.

For now, I solve this by creating a stub component with a method that emits the event I expect, and I just call the method on the instance of the stub component to simulate the event being emitted.

```js
const stub = {
  template: '<div></div>',
  methods: {
    setValue(value) {
      this.$emit('input', value);
    }
  }
};
```

This seems to be to be a feature that would be essential for the testing framework (especially while writing unit tests for components while abstracting the implementation of the lower components. All I care about is that the child component emits an event, and my component does what it is meant to do when that happens).

To give more context, I was testing a component "ParentComponent" that uses a component "ChildComponent". ChildComponent has a select dropdown that users can select to change the value, and then it emits the input event to ParentComponent (which I am testing). In ParentComponent, I don't want to know about the underlying implementation of ChildComponent that it uses a select element. All I care about is: when ChildComponent emits "input" event, then perform some action.

Is it possible that something like this is provided by default with the vue test utils? Thanks

### What does the proposed API look like?
This can be added by default to all stubbed components, with the ability to call something like "simulateEmit" (to communicate to the user that it is only a simulation of the real thing) to stubbed components.

**Comment by JessicaSachs** [comment]
I think it’s possible to do this by selecting the ChildComponent and
dropping down to the vm level to call $emit.

**Comment by imolorhe** [comment]
That's one of the things I tried but it didn't work for me 🤷‍♂

**Comment by lmiller1990** [comment]
You can do `wrapper.find('whatever-stub').vm.$emit('whatever-event')`.

If you can post a reproduction of this, I can help you debug it.

As far as this API suggestion goes, I don't think we need it, when you can accomplish the same thing using `vm.$emit` (or just `mount` the simulate the event like the user would, clicking a button or whatever).

**Comment by imolorhe** [comment]
I'll create a sample repo to reproduce the issue and get back to you in a couple of hours.

**Comment by lmiller1990** [comment]
Sounds good

**Comment by imolorhe** [comment]
Tried again and it works 😣 Now I don't know why it didn't previously but I'm almost certain I tried this before. My use case involves a select component and the v-model in the parent component. I emitted the change event and it worked (again I'm sure I considered it before, perhaps not the right combinations).

Anyway thanks for helping out and the patience.

**Comment by JessicaSachs** [comment]
No problem! Thank you for opening an issue :-)
