### ISSUE TITLE
mock $el's property

### ISSUE THREAD

**Issue by hakoiko** [vuejs/vue-test-utils#1463]
### What problem does this feature solve?
I'm developing a pinterest-like image grid. and I wrote a function `setColumns` that returns drawable count of columns in vm.$el. and I run it in `mounted` hook.
```
setColumns (
  columnWidth = 180,
  gapWidth = 20,
  containerWidth = this.$el.clientWidth
) {
  return Math.floor((containerWidth - gapSize) / (columnSize   gapSize))
}
```
it runs very well in browser. but in Jest with VueTestUtils, $el.clientWidth always returns 0. because jsdom of jest dose nothing about layout calculation. is there other ways to mock $el's property in vue-test-utils?

### What does the proposed API look like?
```
import { shallowMount } from '@vue/test-utils'

const wrapper = shallowMount(Component, {
  mocks: {
    $el: {
      clientWidth: 800
    }
  }
})
```

**Comment by JessicaSachs** [comment]
I don’t believe it makes sense for Vue test utils to attempt to fill in
browser functionality for jsdom.

I suggest passing in the container width as a parameter

**Comment by lmiller1990** [comment]
What exactly does your test look like? What are you trying to test?

Can you just move the Math to another file and unit test that by passing `width` as a parameter like @JessicaSachs  suggested?

**Comment by hakoiko** [comment]
@lmiller1990  I'm trying to test a image placement method. it requires array of drawable columns which is return value of `setColumns`. and the `setColumns` runs in `mounted` hook and `window.resize` event.

actual `setColumns` look like this
```
setColumns (
  columnSize = this.columnSize,
  gapSize = this.gap,
  containerWidth = this.$el.clientWidth
) {
  let count = Math.floor((containerWidth - gapSize) / (columnSize + gapSize))
  return Array.from(new Array(count), item => 0)
}
```
if `containerWidth` is `0`, the count would be minus value. and it causes RangeError from `new Array()`

@JessicaSachs I agree. I changed my `mounted` hook and `setColumns` method work well regardless of $el's property. thanks.
