### ISSUE TITLE
setValue does not apply changes to model when lazy modifier is present

### ISSUE THREAD

**Issue by jaredmcateer** [vuejs/vue-test-utils#1465]
### Version
1.0.0-beta.32

### Reproduction link
[https://github.com/jaredmcateer/vtu-set-value](https://github.com/jaredmcateer/vtu-set-value)

### Steps to reproduce
Clone the minimal test case repo, run `npm install` once that is complete run `node test.js` The assert will fail on line 35 as the model has not updated. Commenting out line 35 will allow the remaining assert to run, which will pass because the change event has been triggered.

### What is expected?
When calling setValue the model should be updated to reflect that value

### What is actually happening?
setValue triggers an "input" event on text input/textareas. A model with the lazy modifier does not update the model until the change event is triggered (see: https://vuejs.org/v2/guide/forms.html#lazy) 

---
If the desire is for setValue to mimic typing perhaps then the documentation should indicate that setValue must be accompanied by a triggering of the change event if the lazy modifier is present or an optional parameter could be passed to setValue to force a change event.

**Comment by lmiller1990** [comment]
Good catch. I think we should support `lazy`. Not sure how we would detect that an element is `lazy`, but we might be able to get away by just calling `change` no matter what (shouldn't hurt?). The change would go [here](https://github.com/vuejs/vue-test-utils/blob/ee3a93f55ca511740367059f5002805acc339fae/packages/test-utils/src/wrapper.js#L547).

**Comment by dobromir-hristov** [comment]
I was thinking about this last night. I dont think we can detect if `lazy` modifier is used, as that just changes the event listener applied by Vue.

If we fire both events, then there is no need for that distinction between elements. Could that probably add more issues for current users?

**Comment by lmiller1990** [comment]
Turns out we can, conveniently there is a `_vModifiers` object that has things like `lazy: true`, making this easy to implement!

Please review @dobromir-hristov and @jaredmcateer : https://github.com/vuejs/vue-test-utils/pull/1467
