### ISSUE TITLE
options does not work

### ISSUE THREAD

**Issue by bichikim** [vuejs/vue-test-utils#1468]
### Version
1.0.0-beta.32

### Reproduction link
[https://codesandbox.io/s/gifted-heyrovsky-4tv8f](https://codesandbox.io/s/gifted-heyrovsky-4tv8f)

### Steps to reproduce
```
import {shallowMount, createLocalVue} from '@vue/test-utils'
const localVue = createLocalVue()
const wrapper = shallowMount(EmptyComponent, {
      localVue,
     foo: 'hi'
    })
console.log(wrapper.vm.$root.$options.foo) // undefined but it should be 'hi'
```

### What is expected?
it should be 'hi'

### What is actually happening?
undefined 

---
The actual Vue works like below
```
const vue = new Vue({
  foo: 'hi',
})
```
console.log(vue.$root.$options.foo) // hi

**Comment by JessicaSachs** [comment]
Those options are for the Vue Test Utils mount config, not necessarily for the Vue instance. We do not support this right now but I’m curious about why you’d like to do this.

To unblock you, I’d suggest using Vue.extend and maybe creating a wrapper component where the options are set. https://vue-test-utils.vuejs.org/api/options.html#context
