### ISSUE TITLE
How to test click event on a slot-wrapped component?

### ISSUE THREAD

**Issue by adi-works** [vuejs/vue-test-utils#1470]
### Version
1.0.0-beta.31

### Reproduction link
[https://github.com/adi518/vue-facebook-login-component](https://github.com/adi518/vue-facebook-login-component)

### Steps to reproduce
Clone, install and debug this [test](https://github.com/adi518/vue-facebook-login-component/blob/master/packages/vue-facebook-login-component/tests/unit/Button.spec.js#L46).

### What is expected?
To get a click event emitted and its listener called.

### What is actually happening?
None of that

**Comment by lmiller1990** [comment]
It looks like when you click the button this is called:

```
    handleClick() {
      this.$emit('click')
      this.scope.toggleLogin()
    }
```

Can we do `expect(wrapper.emitted()).toHaveBeenCalled()`

**Comment by adi-works** [comment]
Yes, so I expect it'd emit the click, but it doesn't. In this test I want to test both emit and its listener.

**Comment by lmiller1990** [comment]
Your button is disabled, so you cannot click it. This is passing for me:

```
  test('login and click event', async () => {
    const onClick = jest.fn()
    const wrapper = mount(Button, {
      propsData: { 
        appId: '966242223397117',
        disabled: false
      },
      data() {
        return {
          scope: {
            disabled: false
          }
        }
      }
    })
    wrapper.find('button').trigger('click')
    console.log(wrapper.html())
    await wrapper.vm.$nextTick()
    console.log(wrapper.emitted())
    // expect(wrapper.emitted().input.slice(-1)[0]).toEqual([
    //   {
    //     connected: true,
    //     disabled: false,
    //     disconnected: false,
    //     enabled: true,
    //     error: null,
    //     idle: true,
    //     working: false
    //   }
    // ])
  })

```

**Comment by adi-works** [comment]
My component is a button that does async operations on creation so the initial state is indeed disabled. I normally use `flushPromises` and then assert whatever, but in this case, I forgot to do it **twice**, once for the button to be enabled and clickable and another to assert the state post-click. The fix:
```js
await flushPromises()
wrapper.trigger('click')
await flushPromises()
expect(onClick).toHaveBeenCalled()
```
And it's working. 👍
