### ISSUE TITLE
triggering cancelable event causes error

### ISSUE THREAD

**Issue by sjahns** [vuejs/vue-test-utils#1472]
### Version
1.0.0-beta.32

### Reproduction link
[https://github.com/sjahns/vue-test-utils-issue-event-cancelable](https://github.com/sjahns/vue-test-utils-issue-event-cancelable)

### Steps to reproduce
npm install

npm run test:unit

### What is expected?
It should not cause an error

### What is actually happening?
It does end in an error

---
This happens due to createDOMEvent() setting all given options on the event object. But cancelable is read only.

To me it looks like the event is created correctly with cancelable:false but createDOMEvent() will also try to set the property.

I found this while testing a component which does:

if(event.cancelable) {
  event.preventDefault();
}

**Comment by lmiller1990** [comment]
I (think) we have a PR in progress for this https://github.com/vuejs/vue-test-utils/pull/1460

**Comment by dobromir-hristov** [comment]
Closing as #1460  is merged.
