### ISSUE TITLE
Watchers on computed properties not firing in tests

### ISSUE THREAD

**Issue by kierans** [vuejs/vue-test-utils#1482]
### Version
1.0.0-beta.32

### Reproduction link
[https://github.com/kierans/vue-test-utils-bug](https://github.com/kierans/vue-test-utils-bug)

### Steps to reproduce
1. Create a Component where there are some computed properties (eg: https://github.com/kierans/vue-test-utils-bug/blob/master/src/components/Company.vue)
2. Create a test that uses `shallowMount` or `mount` to mount the Component, but override the computed properties to return predefined test data (eg: https://github.com/kierans/vue-test-utils-bug/blob/master/tests/unit/company.spec.ts)
3. Run the tests, changing the test data.
4. The test will fail (eg: https://github.com/kierans/vue-test-utils-bug/blob/master/tests/unit/company.spec.ts#L72)

### What is expected?
That the watchers should fire, given the underlying data has changed.

### What is actually happening?
The watchers aren't firing

---

If you run the app (`npm run serve`) you'll see the watchers firing in response to the changes in the data and the list renders correctly. The `console.log` messages are also printed. However in the test the watchers aren't being fired.

**Comment by dobromir-hristov** [comment]
Companies and employees are not reactive, Vue can't track changes like that on plain objects.
Instantiate a vuex store with that module for a real test scenario.

**Comment by kierans** [comment]
@dobromir-hristov Reading [the Vuex source](https://github.com/vuejs/vuex/blob/dev/src/store.js#L255) I see what you mean.

Thinking about it some more, in a Unit test it's probably better to control when the watchers are fired so that we have have deterministic outcomes.
