### ISSUE TITLE
how can i check style in html head

### ISSUE THREAD

**Issue by xxholly32** [vuejs/vue-test-utils#1483]
### Version
1.0.0-beta.21

### Reproduction link
[https://github.com/xxholly32/vuec/blob/master/packages/vuec/__tests__/style.spec.js#L25](https://github.com/xxholly32/vuec/blob/master/packages/vuec/__tests__/style.spec.js#L25)

### Steps to reproduce
npm run test:unit

### What is expected?
my components would add style in html; so i need to check

https://github.com/xxholly32/vuec/blob/master/packages/vuec/__tests__/style.spec.js#L25

my components code would add style in html, here is code :

https://github.com/xxholly32/vuec/blob/master/packages/vuec/components/preview.js#L46

### What is actually happening?
just got vm in warpper, cant got htmldocument 

---
need a options to render html document

**Comment by dobromir-hristov** [comment]
If you  are running tests in node, using jsdom, you wont be able to do that.
I think the only way would e to run in a real browser and attach the components to the DOM.

Why do you want to test this? Vue will always attach these styles, you should not test if Vue works.

**Comment by xxholly32** [comment]
i got it , I was heading to a dead end, ty

[my demo](https://xxholly32.github.io/vuec/) is work just like vue. lol
