### ISSUE TITLE
Store is undefined in dynamically loaded child component

### ISSUE THREAD

**Issue by mediafreakch** [vuejs/vue-test-utils#1486]
### Version
1.0.0-beta.32

### Reproduction link
[https://github.com/mediafreakch/vue-test-utils-bug](https://github.com/mediafreakch/vue-test-utils-bug)

### Steps to reproduce
1. Clone the repository
2. run npm install
3. run npm test

### What is expected?
Tests pass.

### What is actually happening?
1 Test fails.

---
Compare to https://codesandbox.io/s/github/mediafreakch/vue-test-utils-bug 
(switch to tab "Test" and watch tests pass)

It seems I am missing something here in the build setup to make dynamic imports work, that codesandbox.io has...
But I am using the latest of @babel/core, which should include babel-plugin-dynamic-import-node.

**Comment by lmiller1990** [comment]
Maybe related... https://github.com/vuejs/vue-test-utils/issues/1279 ?

**Comment by mediafreakch** [comment]
I think this is most likely related to `vue-cli-plugin-unit-jest` that still relies on an old version of `jest` and `jest-environment-jsdom-fifteen`. If I figure out how I will make a use-caese without vue-cli-plugin.

UPDATE:
Couldn't confirm my suspicion: 
Tried with `jest@26.0.1` (which is using`jsdom@16`) and `ts-jest@25.5.0` and the test still fails.

**Comment by CodePlato3721** [comment]
vuex in dynamic import use the different vue instance.

How about using `stubs` to shallow mount `Dashboard.vue` , then test `Dashboard.vue` and `Chart.vue` separately?

For example: 

`Dashboard.test.js`:
```
mount(Dashboard, {
      stubs: {
          GenericView: true
      }
...
```

**Comment by mediafreakch** [comment]
@alexxiyang How do you figure that different vue instances are in play? And if that's the case, why only in the test environment and not when running in the browser? 

> How about using stubs to shallow mount Dashboard.vue , then test Dashboard.vue and Chart.vue separately?

My workaround for the tests to pass was indeed to using a stub for `GenericView`. But to me that's merely a workaround. I actually came here from [Vue Testing Library](https://testing-library.com/docs/vue-testing-library/intro), where working with Vue instances is discouraged. Instead I wanted to assert on actual DOM output.

**Comment by lmiller1990** [comment]
I am interested in this too

> vuex in dynamic import use the different vue instance.

I think he is saying that dynamic components are not using `localVue` - if this is the case, at least we have a clear path to look into fixing this.

**Comment by dobromir-hristov** [comment]
Can you stub out a dynamic component with `jest.mock`?

**Comment by mediafreakch** [comment]
@dobromir-hristov You can with [`jest.doMock`](https://jestjs.io/docs/en/23.x/jest-object#jestdomockmodulename-factory-options). But what I meant was that, referring to my example, I stubbed `GenericView` when testing the Dashboard like this:

```
it("should initiate dashboard tiles", () => {
    mount(GenericView, {
      stubs: ["GenericView"],
      localVue,
      store,
      props: {
        kind: "Dashboard"
      }
    });

    expect(actions.fetchViewInfo).toHaveBeenCalledTimes(1);
});
```

**Comment by huynl-96** [comment]
Is there any solution for this? 
I also ran into this problem when using vue-testing-library and my dynamic components do not have any access to `$route` as well as `$store` (they are both `undefined`)

**Comment by lmiller1990** [comment]
As far as I know there is no clean cut solution. This isn't a Test Utils specific problem, but common to anyone using dynamic imports with babel and Jest, I think. It is not something we can fix here (could be wrong, but this is my understanding). Seems there are similar issues in other code bases, [eg this one in Enzyme](https://github.com/enzymejs/enzyme/issues/1460). Looks like they arrived at a solution, maybe that can help you?
