### ISSUE TITLE
setData() doesn't trigger watcher

### ISSUE THREAD

**Issue by darrenjennings** [vuejs/vue-test-utils#149]
I have a component that watches a data object `suggestions`. When I mount the component and then call `wrapper.setData({ suggestions: [] });` the watcher does not fire, as I put a `console.log` on the watcher to verify. If I set the watcher to be "immediate: true" then it will fire once. Is there something else I should do to trigger the watcher in a testing environment? I tried `wrapper.vm.$nextTick` to no avail. 

```javascript
const defaultProps = {
  suggestions: [
    {
      data: ["clifford kits", "friendly chemistry", "phonics"]
    }
  ],
  inputProps: {
    id: "autosuggest__input"
  }
};

it("can render suggestions", async () => {
  const wrapper = mount(Autosuggest, {
    propsData: defaultProps
  });

  const input = wrapper.find("input");
  expect(input.hasAttribute("id", defaultProps.inputProps.id));

  input.trigger("click");
  wrapper.setData({
    searchInput: "G",
    suggestions: [
      {
        data: ["friendly chemistry", "phonics"]
      }
    ]
  });
  input.trigger("keydown.down");

  const renderer = createRenderer();
  renderer.renderToString(wrapper.vm, (err, str) => {
    expect(str).toMatchSnapshot();
  });
});

```

**Comment by eddyerburgh** [comment]
Thanks for the bug report 😀

I've added a fix in the dev branch. It will be released in beta.5

**Comment by disitec** [comment]
Same issue here using setComputed(). It is related?

**Comment by eddyerburgh** [comment]
Yes :P, sorry. Can you make a new issue @disitec

**Comment by blake-newman** [comment]
@eddyerburgh has the `setComputed` been fixed already?

**Comment by blake-newman** [comment]
If not then i'll open an issue

**Comment by disitec** [comment]
+1

**Comment by eddyerburgh** [comment]
Sorry for the delay guys, I saw this an forgot to reply.

I've updated setComputed to run the correct watchers. It'll be released in beta.7 in the next couple of days 🙂
