### ISSUE TITLE
Allow array values for select.setValue

### ISSUE THREAD

**Issue by bugy** [vuejs/vue-test-utils#1505]
### What problem does this feature solve?
In #775, `select.setValue('abc')` support was added (https://vue-test-utils.vuejs.org/api/wrapper/#setvalue)  
It would be nice to extend this method and support array values when it's a multiselect.  

If you don't mind, I could try making a PR

### What does the proposed API look like?
```
const wrapper = mount(Foo)
wrapper.get('select').setValue(['abc', 'def'])
```

**Comment by lmiller1990** [comment]
I thought this was already supported 🤔 

If not, sure, we should support this!

**Comment by bugy** [comment]
Hi, I finally found a time for a PR: https://github.com/vuejs/vue-test-utils/pull/1554
:)
