### ISSUE TITLE
Stub Multiple Sub-Components?

### ISSUE THREAD

**Issue by Aleksbgbg** [vuejs/vue-test-utils#1516]
### What problem does this feature solve?
If I am repeating the same component multiple times, I would like to stub each of them with separate instances.

### What does the proposed API look like?
Given a component template like this:
```pug
div
    subcomponent
    subcomponent
    subcomponent
    subcomponent
```
Stubbing like this:
```js
mount(component, {
    stubs: {
        subcomponent: [stub1, stub2, stub3, stub4]
    }
});
```

**Comment by lmiller1990** [comment]
Hi!

Thanks for the detailed feature request. We will release v1 very soon, I don't think we are looking to expand the stubs API, unfortunately.

I might be able to offer some alternatives; what exactly do you plan to test/assert against once you've stubbed the instances out differently?

**Comment by Aleksbgbg** [comment]
I have a component made up of 4 input fields, each of which have validation and formatting logic for currency. Changing one of the fields updates all the others. Thus I want to verify that input on stub1 causes stub2, 3, and 4 to have their props changed.

**Comment by lmiller1990** [comment]
Stubs should still receive props like usual - if you are passing the correct props, you can still assert that the stubs are receiving them and just finding the stubbed component and calling `props()`.

I could be misunderstanding this. If you can provide some code, maybe that would help.
