### ISSUE TITLE
Shopuld the text method trim the strings?

### ISSUE THREAD

**Issue by eddyerburgh** [vuejs/vue-test-utils#152]
At the moment the `text` method returns the textContent of a node. 

That means it will look like this:

```
'

      Hello
 '     
```

That means we need to use a contain check instead of an equal check:

```js
expect(wrapper.text()).toBe('Hello') // false
expect(wrapper.text()).toContain('Hello') // true
```

I can't see this being desired behavior. Instead we can call trim on the textContent before returning it, so that the `text` output would lose the trailing whitespace:
```
'Hello'     
```

What do people think? Is there a usecase to having trailing whitespace included?

**Comment by lmiller1990** [comment]
This would be useful. I almost always do `.text().trim()`. I can't think of a situation where I would want to check for whitespace. +1.

**Comment by wtho** [comment]
Also keep trimming every time...

Maybe we can add a `rawText()` method in case someone wants to get the original string with line breaks.

**Comment by eddyerburgh** [comment]
I've implemented it in dev branch. If anyone has a use case for untrimmed, we can add a `rawText` method as @wtho suggested

**Comment by arturshark** [comment]
Hello, 
As I see suggested `rawText` wasn't implemented. I have a use case for that. How to check if there is a bug with adding spaces in the beginning of an element's text ? 
For example, we have next:

`<a>Some Text</a>`  and  `<a>               Some Text</a>`

In both cases this test won't fail:
`expect(wrapper.find(a).text()).toEqual('Some Text')`

**Comment by lmiller1990** [comment]
If you are using Jest you can use `toContain` for this use case, I believe.

**Comment by eddyerburgh** [comment]
You can access the `textContent` directly on the element:

```js
expect(wrapper.find('a').element.textContent).toEqual('Some Text')
```

**Comment by arturshark** [comment]
`textContent` works.
Thank you!

**Comment by pieterdd** [comment]
Neither `.text().trim()` nor `.element.textContent` seem to work in my case. The element's DOM looks a bit like this:

```
<div><span>
                                $&nbsp;20
                            </span>
  <!----> <span>/month</span></div>
```

This causes the following mismatch:

```
Expected: "$ 20 /month"
Received: "$ 20
                              /month"
```

I could probably work around it by putting the entire thing on one line. But we have a lint rule against long lines and for readability's sake, I'd rather solve it in the test suite. Is there an alternative you could recommend?

Edit: solved it with a regex that trims redundant whitespace.

**Comment by lmiller1990** [comment]
Only thing that comes to mind is a regular expression.

**Comment by afontcu** [comment]
Yep. This might work:

```js
.replace(/\s\s+/g, ' ')
```

**Comment by pieterdd** [comment]
Wouldn't `.replace(/\s+/g, ' ')` suffice, given that the `+` should match one or more of the given expression?

In my scenario I ended up using `[ \n\t]` rather than `\s` because I didn't want to deduplicate any non-breaking space characters, nor did I want to convert them into regular spaces. That depends on your particular use case of course.
