### ISSUE TITLE
'Cheerio' is used, but not imported in server-test-utils/types

### ISSUE THREAD

**Issue by sk-pub** [vuejs/vue-test-utils#1526]
### Version
1.0.0-beta.33

### Steps to reproduce
1. Check the file https://github.com/vuejs/vue-test-utils/blob/dev/packages/server-test-utils/types/index.d.ts
2. It contains the usage of the Cheerio type, but the type is not defined/imported

### What is expected?
The Cheerio type must be imported from '@types/cheerio'.

### What is actually happening?
This issue prevents TypeScript compilation.

**Comment by sk-pub** [comment]
Made a fix: https://github.com/vuejs/vue-test-utils/pull/1527

**Comment by lmiller1990** [comment]
🤔 strange that this was un-noticed for so long! I will review the PR in the next day or so and give it a test. Thanks!
