### ISSUE TITLE
Deprecation warning for setChecked() is not actionable

### ISSUE THREAD

**Issue by lucaswerkmeister** [vuejs/vue-test-utils#1531]
### Version
1.0.0

### Reproduction link
[https://github.com/lucaswerkmeister/repro-vue-test-utils-setChecked-deprecation-not-actionable](https://github.com/lucaswerkmeister/repro-vue-test-utils-setChecked-deprecation-not-actionable)

### Steps to reproduce
In general: Have a test that calls `wrapper.setChecked()`.

With the reproducer repo in particular: run `npm it`.

### What is expected?
In general: I can bring the test into a shape where it will not raise a deprecation warning.

Specifically: Either there should be a working, non-deprecated replacement for `setChecked` that I can use instead, or `setChecked` should not yet be deprecated.

### What is actually happening?
Calling `setChecked` raises a deprecation warning (which makes Jest print a deep red notice by default, and in our case is [configured](https://github.com/wikimedia/mediawiki-extensions-Wikibase/blob/78fccc2da5d606ec696be411c5e105eb05a0bd63/client/data-bridge/tests/config/JestCustomEnvironment.js#L7-L12) to make the test fail). The message advises to use `setValue` instead, but that method cannot yet be called on checkbox inputs. This leaves me with no good way forward: I can only ignore that deprecation warning in various ways (disable vue-test-utils deprecation warnings altogether, disable our hook that turns those warnings into test failures, or hard-code that particular message and ignore only these specific `console.error` calls).

**Comment by lmiller1990** [comment]
`setValue` will be updated to support checkboxes soon. You can make a PR, if you like. [Code is here](https://github.com/vuejs/vue-test-utils/blob/6529d4d9da64b2e7fd7f13f8cd074fe84b3c18da/packages/test-utils/src/wrapper.js#L732).

You should be able disable those deprecation warnings with the `config.showDeprecationWarnings` flag:

```js
import { config } from '@vue/test-utils'
config.showDeprecationWarnings = false
```

I missed this when backporting features from our Vue 3 integration. I should not have missed this one. Thank you for raising this issue.

**Comment by lmiller1990** [comment]
For now I will remove this warning as it is misleading. Sorry about that.

**Comment by lmiller1990** [comment]
I removed the warning in 1.0.2. Please try that one.

I will let you know when we backport `setValue`. Thanks!

**Comment by lucaswerkmeister** [comment]
Great, thank you!
