### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by Mister-Hope** [vuejs/vue-test-utils#1540]
### Version
1.0.0

### Reproduction link
[https://this.template.got.me.sick](https://this.template.got.me.sick)

### Steps to reproduce

I think your service worker is out of date, it's good for me to unregister service worker and visit the doc then, but after a refresh, the page is broken with tons of 404

### What is expected?
............

### What is actually happening?
...............

---
..........

![image](https://user-images.githubusercontent.com/33315834/81546930-aed45e00-93ad-11ea-8ccd-b1d325bb0cc7.png)
![image](https://user-images.githubusercontent.com/33315834/81546968-bb58b680-93ad-11ea-8b04-28965608a3c7.png)

Beside, some times the template can really be annoying. Why do I **MUST** fill in a link with a issue report like this?

**Comment by lmiller1990** [comment]
Weird, not sure why this would be happening. It's working for me. I can poke around a bit and see what I can figure out.

I agree on the template, it's extremely annoying. Can you send a PR? It's in the `.github` directory.

**Comment by lmiller1990** [comment]
This seems okay to me. Are you still having problems?

**Comment by Mister-Hope** [comment]
It's working fine now
