### ISSUE TITLE
Explain what the replacement for deprecations are

### ISSUE THREAD

**Issue by Wmaarts** [vuejs/vue-test-utils#1541]
### What problem does this feature solve?
The documentation for for example [setMethods](https://vue-test-utils.vuejs.org/api/wrapper-array/#setmethods) is unclear. It simply states: "setMethods is deprecated and will be removed in future releases.". Same goes for [isVueInstance](https://vue-test-utils.vuejs.org/api/wrapper-array/#isvueinstance).

This does not explain what the replacement (if any) should be, or why this was deprecated.

These types of warnings also happens when running the tests:
"[vue-test-utils]: overwriting methods via the `methods` property is deprecated and will removed in the next major version"

Here it's also unclear what the fix should be or why this was deprecated.

### What does the proposed API look like?
Not applicable.

**Comment by afontcu** [comment]
Hi! Thanks for filling this in.

There's no clear path to replace `setMethods` or `methods` property, because it really depends on your previous usage. It will be removed because it might lead to flaky tests – your tests end up relying on implementation details. The suggestion is to rethink those tests, I believe! (more on that [on the VTU RFC](https://github.com/dobromir-hristov/rfcs/blob/vtu-2-api/active-rfcs/0000-vtu-api.md#setmethods)).

Still, if you have some ideas of guidance/suggestions to help users, we'll be more than happy to review a PR! 😃

**Comment by jimmerydad** [comment]
For  [isVueInstance](https://vue-test-utils.vuejs.org/api/wrapper-array/#isvueinstance) , if the note included at [https://github.com/dobromir-hristov/rfcs/blob/vtu-2-api/active-rfcs/0000-vtu-api.md#isvueinstance](https://github.com/dobromir-hristov/rfcs/blob/vtu-2-api/active-rfcs/0000-vtu-api.md#isvueinstance)

>  find always returns an DOMWrapper and findComponent returns a VueWrapper. Both return ErrorWrapper if failed.

were added it would have saved me a little time finding this as well (ie to use [findComponent](https://vue-test-utils.vuejs.org/api/wrapper/#findcomponent ) )

**Comment by nicojs** [comment]
> The suggestion is to rethink those tests, I believe! (more on that [on the VTU RFC](https://github.com/dobromir-hristov/rfcs/blob/vtu-2-api/active-rfcs/0000-vtu-api.md#setmethods)).

Would be awesome if this is reflected in the deprecation warning. Maybe link to that page. Right now we get 100's of deprecation warnings without a clear path on how to fix them.

**Comment by afontcu** [comment]
Makes sense, thank you all for the suggestion. Anyone fancy to open up a PR with improved deprecation messages? 😇 otherwise I will.

cheers!

**Comment by mydnic** [comment]
I have the similar problem with `isVueInstance`
Exemple, I have a very small and basic test to assert that a component is correctly mounted without error.
For that I used `expect(wrapper.isVueInstance()).toBeTruthy()`

Now that I have the deprecation notice, I do not know how I can replace this basic test.

Any idea ? 

Thanks a lot!

**Comment by mydnic** [comment]
Nevermind, looks like `expect(wrapper.exists()).toBeTruthy()` does the trick for me

**Comment by janosrusiczki** [comment]
I'm just plus one-ing the need to explain what to use to replace `isVueInstance()`. Else you'll probably have this issue pop up many times as many tutorials use this assertion as a basic example and it tends to stick in people's tests.

**Comment by lmiller1990** [comment]
For `isVueInstance`, tests. I would generally recommend just deleting those tests - it's just testing an implementation detail, which is not usually a good thing. 

You could do `expect(wrapper.find(...).vm).toBeTruthy()` if you feel very strongly about keeping those tests. `isVueInstance` just called `!!this.vm` internally, anyway, [as seen here](https://github.com/vuejs/vue-test-utils/blob/35dacdc3307a5dc5b09611593645b025c9680c9b/packages/test-utils/src/wrapper.js#L400).

`setMethods` is tricky, very much case by case! @afontcu is putting some docs together to help with this.

If anyone has a complicated test with `setMethods` that cannot wait, feel free to post it here or message me on [Twitter](https://twitter.com/Lachlan19900) or Discord (Vue-land) or email (in my GH profile) and I can help you.

If the deprecations messages are super annoying, you can temporarily silence them:

```js
import { config } from `@vue/test-utils`

config.showDeprecationWarnings = false
```

**Comment by afontcu** [comment]
Hi folks! I'm pinging everyone on this issue because #1548 is up and we'd like to receive your feedback on the updated deprecation messages 😇 

thanks!

**Comment by begueradj** [comment]
@afontcu 
You said: "your tests end up relying on implementation details." but personally I do not see how using `isVueInstance` relies on implementation details.

**Comment by begueradj** [comment]
@lmiller1990  
You said: it's just testing an implementation detail, which is not usually a good thing.



> For `isVueInstance`, tests. I would generally recommend just deleting those tests - it's just testing an implementation detail, which is not usually a good thing.
> 
> You could do `expect(wrapper.find(...).vm).toBeTruthy()` if you feel very strongly about keeping those tests. `isVueInstance` just called `!!this.vm` internally, anyway, [as seen here](https://github.com/vuejs/vue-test-utils/blob/35dacdc3307a5dc5b09611593645b025c9680c9b/packages/test-utils/src/wrapper.js#L400).
> 
> `setMethods` is tricky, very much case by case! @afontcu is putting some docs together to help with this.
> 
> If anyone has a complicated test with `setMethods` that cannot wait, feel free to post it here or message me on [Twitter](https://twitter.com/Lachlan19900) or Discord (Vue-land) or email (in my GH profile) and I can help you.
> 
> If the deprecations messages are super annoying, you can temporarily silence them:
> 
> ```js
> import { config } from `@vue/test-utils`
> 
> config.showDeprecationWarnings = false
> ```

How come it is testing an implementation detail ? I do not see that, if you can explain, thank you

**Comment by lmiller1990** [comment]
Ideally you should test the input and output of the component (or any function in general, when writing tests). 

For example, for a Vue component, the inputs might be a user filling out a form and submitting it, and the output might be the component renders a "Success" message. We don't really care *how* the component works, but that the behavior is correct.

Asserting that something is a Vue instance is not very useful and provides little value; it's much better practice to test the behavior.

**Comment by begueradj** [comment]
I agree with the behavioral testing, you explained that very well and many times on your website. However, IMHO, I like to use `isVueInstance()` because it gives me a feedback whether the component is mounted properly or not (the simplest example is when we forget to close a "tag"/component)

**Comment by afontcu** [comment]
> I agree with the behavioral testing, you explained that very well and many times on your website. However, IMHO, I like to use `isVueInstance()` because it gives me a feedback whether the component is mounted properly or not (the simplest example is when we forget to close a "tag"/component)

Given that scenario, wouldn't any other test against that Component fail, too?

**Comment by xbl** [comment]
HI!
I have features that work fine, but my unit test fails because of setMethods deprecated.
I use sinon.spy method instead. still fails.
my vue code:
```vue
<template>
  <ul>
    <li><span>用户名：</span><input type="text" class="username" v-model="user.username"></li>
    <li><span>密码：</span><input type="text" class="password" v-model="user.password"></li>
    <li><button class="submit" @click="onSubmit">提交</button></li>
  </ul>
</template>
<script>
 // ...
  methods: {
    async onSubmit() {
      const response = await Service.login(this.user);
      if (response.status === 200) {
        this.loginSuccess();
        return;
      }
      this.loginFailure();
    },
 // ...
</script>
```
my test code:
```javascript
  it.only('Given visit login page And input username and password，When click submit button，Then onSubmit called once', () => {
    const wrapper = mount(Login);
    const onSubmit = sinon.spy(wrapper.vm, 'onSubmit');

    wrapper.find('input.username').setValue('hello');
    wrapper.find('input.password').setValue('123');
    wrapper.find('button.submit').trigger('click');
    // onSubmit.called is false 
    expect(onSubmit.called).toBeTruthy();
  });
```

can you help me ?

**Comment by daniel-butler** [comment]
> > I agree with the behavioral testing, you explained that very well and many times on your website. However, IMHO, I like to use `isVueInstance()` because it gives me a feedback whether the component is mounted properly or not (the simplest example is when we forget to close a "tag"/component)
> 
> Given that scenario, wouldn't any other test against that Component fail, too?

Its a smoke test. If that test is failing you know something major with the component off. When I have a whole slew of errors I've found it is easier to look for the most simple test that failed, fix that then continue up in complexity. Basically the single responsibility principle for tests.

**Comment by afontcu** [comment]
In that (legit!) case, you might want to use  `expect((...).vm).toBeTruthy()` ([source](https://vue-test-utils.vuejs.org/upgrading-to-v1/#isvueinstance)) so the test will fail as soon as the component instance is not there

**Comment by kamalhm** [comment]
Sorry I dont get what should we put in the `...` part

> 
> 
> In that (legit!) case, you might want to use `expect((...).vm).toBeTruthy()` ([source](https://vue-test-utils.vuejs.org/upgrading-to-v1/#isvueinstance)) so the test will fail as soon as the component instance is not there

**Comment by afontcu** [comment]
whatever you were doing in the first place. for example, from:

```js
expect(wrapper.findComponent(myComponent)).isVueInstance()
```

to 

```js
expect(wrapper.findComponent(myComponent).vm).toBeTruthy()
```

**Comment by kamalhm** [comment]
@afontcu 
I usually do something like this to test for Vue instance

```javascript
import Component from '@/components/ComponentName'

beforeEach(() => {
    wrapper = shallowMount(Component, {
      i18n,
      store,
      localVue,
      router
    })
    vm = wrapper.vm
  })

  test('is a Vue instance', () => {
    expect(wrapper.isVueInstance()).toBeTruthy()
  })
```

what should I do if I want to do the same smoke test?
`wrapper.findComponent(Component).vm` ?

**Comment by lmiller1990** [comment]
`expect(wrapper.vm).toBeTruthy()`. Although why you want to write this is beyond me - it's not even really smoke testing anything, you should at least make an assertion against `wrapper.html()`.

**Comment by kamalhm** [comment]
noted, i probably wont use this in my personal project but it's work project and we have lots of `isVueInstance`, so I'm just trying to 
1. remove the warn message
2. try to find a better way to do it

thanks for the suggestion @lmiller1990 👍

**Comment by ogomaemmanuel** [comment]
@afontcu there is a place i think this is usable, especially in the created hook, to test if a method is called on component create hook . here is a sample of what I have. Since getBanks is an external call, i need to replace it's implementation 

   import SendToBank from "../SendToBank";
    import {mount} from "@vue/test-utils"

     describe("Send Money To Back Form", () => {
      it("should call getBanks methods  when component is created", () => {
        let getBanks = jest.fn();
        let wrapper = mount(SendToBank, {
            methods: {
                getBanks
            }
        });
        expect(getBanks).toBeCalledTimes(1);
       })
    })

**Comment by lmiller1990** [comment]
@ogomaemmanuel would you not just mock out the API lib (eg axios) and assert *that* was called?

**Comment by keremistan** [comment]
> @afontcu there is a place i think this is usable, especially in the created hook, to test if a method is called on component create hook . here is a sample of what I have. Since getBanks is an external call, i need to replace it's implementation
> 
> import SendToBank from "../SendToBank";
> import {mount} from "@vue/test-utils"
> 
> ```
>  describe("Send Money To Back Form", () => {
>   it("should call getBanks methods  when component is created", () => {
>     let getBanks = jest.fn();
>     let wrapper = mount(SendToBank, {
>         methods: {
>             getBanks
>         }
>     });
>     expect(getBankPays).toBeCalledTimes(1);
>    })
> })
> ```

That throws a deprecated warning though. How to do the same thing without getting a warning?

**Comment by ogomaemmanuel** [comment]
@lmiller1990 that one will work for external api's, but sometime you just want some functions to be called when a the component is created, I have been in situations where I either forget to put a function in the created hook or by accident the functions get removed. To ensure these functions aren't interfered with, I need to pass a mock that will be called during component creation

**Comment by lmiller1990** [comment]
I'm sorry, but `methods` mounting option will not be coming back at this point. If you can post a specific example of when you think you absolutely need it, happy to offer some alternatives - there is likely a better way to accomplish the same thing.

**Comment by keremistan** [comment]
I've solved it by inserting functions after the mounting completed.

```javascript
const wrapper = shallowMount(Component)
wrapper.vm.methodToBeMocked = jest.fn();
```

**Comment by ogomaemmanuel** [comment]
@lmiller1990  I have gotten how to go about it, just mocking the function before calling mount

**Comment by kaiying** [comment]
@keremistan thanks for your share!
I have a new question, this way can not solved it.
I want test this
```js
const created = function () {
  this.apiGetProducts();
};
```
old test code:
```js
    shallowMount(component, {
      localVue,
      methods: {
        apiGetProducts,
      },
    });

    /** assert */
    expect(apiGetProducts).toBeCalledTimes(1);
```

Warning was throw because `wrapper.vm` timing is late for `created`.

How can I solve it?

**Comment by lmiller1990** [comment]
What does `apiGetProducts` do? Can you just mock the API call (`axios`, etc)?

The idea is to discourage these kind of tests - your tests is not very useful, if you were to delete the `this.apiGetProducts` method your test would *still* pass.

**Comment by kaiying** [comment]
> What does `apiGetProducts` do? Can you just mock the API call (`axios`, etc)?
> 
> The idea is to discourage these kind of tests - your tests is not very useful, if you were to delete the `this.apiGetProducts` method your test would _still_ pass.

not completely API call.

```js

const created = function () {
  this.apiGetProducts();
};

const methods = {
  apiGetProducts() {
    getProduct().then(res => {
       ... do Something
    })
    .... more then
  },
}
```

**Comment by lmiller1990** [comment]
What is `getProduct`? Some API call? Is that imported from somewhere? If so, can you just mock that module (eg `jest.mock('../getProduct')`?

**Comment by kaiying** [comment]
> What is `getProduct`? Some API call? Is that imported from somewhere? If so, can you just mock that module (eg `jest.mock('../getProduct')`?

Thanks for you answer 👍 
I already mock `getProduct`.
I wanna test the flow when `createdt` was called.

I has solved this question.
This is my solution.
```js
  test('[Main] `created`  execute `apiGetProducts`、`apiGetWishListStatus` methods. ', () => {
    /** arrange */
    const apiGetProducts = jest.fn();
    const apiGetWishListStatus = jest.fn();

    // mock methods
    localMixin.methods = { ...mixin.methods, apiGetProducts, apiGetWishListStatus };

    /** act */
    shallowMount(component, {
      localVue,
      ... abort
    });

    /** assert */
    expect(apiGetProducts).toBeCalledTimes(1);
    expect(apiGetWishListStatus).toBeCalledTimes(1);
  });
```

**Comment by YBFJ** [comment]
> @afontcu there is a place i think this is usable, especially in the created hook, to test if a method is called on component create hook . here is a sample of what I have. Since getBanks is an external call, i need to replace it's implementation
> 
> import SendToBank from "../SendToBank";
> import {mount} from "@vue/test-utils"
> 
> ```
>  describe("Send Money To Back Form", () => {
>   it("should call getBanks methods  when component is created", () => {
>     let getBanks = jest.fn();
>     let wrapper = mount(SendToBank, {
>         methods: {
>             getBanks
>         }
>     });
>     expect(getBanks).toBeCalledTimes(1);
>    })
> })
> ```

I solved my problem with this method
