### ISSUE TITLE
vuex actions testing using `toHaveBeenCalledWith` (necessary since setMethods being deprecated)

### ISSUE THREAD

**Issue by An-AngryBear** [vuejs/vue-test-utils#1542]
### What problem does this feature solve?
currently when using the recommended process for testing vuex actions within a component (as detailed [here](https://vue-test-utils.vuejs.org/guides/using-with-vuex.html)), `toHaveBeenCalledWith` requires a first argument that contains 

```javascript
{
    dispatch: [Function (anonymous)],
    commit: [Function (anonymous)],
    getters: [Object],
    state: [Object],
    rootGetters: [Object],
    rootState: [Object]
},
```

a feature that automatically injects this, or provides an easy way to add this into an `toHaveBeenCalledWith` would be helpful

### What does the proposed API look like?
```javascrip
//component
this.actionName(argument)

//expect
expect(actions.actionName).toHaveBeenCalledWith(argument) 

// instead of 
expect(actions.actionName).toHaveBeenCalledWith(giantArgumentIncludingContextGettersAndState, argument)
```

**Comment by afontcu** [comment]
Hi! Not sure if there's a better approach, but currently when I test action in isolation I rely on `expect.any(Object)` for the first argument:

```js
expect(actions.actionName).toHaveBeenCalledWith(
  expect.any(Object), // The Vuex context
  { id: 1, name: 'foo' }
)
```

**Comment by afontcu** [comment]
I'm gonna close this up, feel free to reopen or fill in a new issue is the suggested solution does not cover your needs 🤗

**Comment by An-AngryBear** [comment]
@afontcu yeah this works, may be worth adding to the documentation on that page I linked above so future developers don't run into the same problem.

**Comment by afontcu** [comment]
That's a good idea! Fancy to open up a PR for docs? 😉 @An-AngryBear
