### ISSUE TITLE
False positive for deprecation warning: [vue-test-utils]: isVueInstance is deprecated and will removed in the next major version

### ISSUE THREAD

**Issue by nicojs** [vuejs/vue-test-utils#1543]
### Version
1.0.0

### Steps to reproduce
A simple setup:

* Pokemon.Vue
```html
<template>
  <div>
    <h2>{{ pokemon.name }}</h2>
    <dl>
      <dt>Type</dt>
      <dd>{{ pokemon.type }}</dd>
    </dl>
  </div>
</template>
<script lang="ts">
import Vue from 'vue';
import { pokemonService } from './pokemon.service';

export default Vue.extend({
  name: 'component-pokemon',
  props: {
    pokemon: Object
  }
});
</script>
```

* Pokemon.spec.js

```js
import { mount } from '@vue/test-utils'
import Pokemon from './Pokemon.vue';
import { expect } from 'chai';

describe('Pokemon component', () => {
  it('should render definition list', () => {
    const sut = mount(Pokemon, {
      propsData: {
        pokemon: {
          name: 'Foo',
          type: 'bar' 
        }
      }
    });
    expect(sut.find('dl').element).ok;
    sut.destroy();
  });
});
```

### What is expected?
No deprecation warning is logged.

### What is actually happening?
This deprecation message is logged twice: 
> `[vue-test-utils]: isVueInstance is deprecated and will removed in the next major version`

---
Probably `isVueInstance` is called internally in vue-test-utils. This shouldn't result in a deprecation message for end users.

**Comment by afontcu** [comment]
Hi! It was fixed in 1.0.2 ([source](https://github.com/vuejs/vue-test-utils/commit/17d336efc3c251d228de79bba97967992fec4b0f#diff-f8b21801dcf5dee76bc9f5f22e227ea8L144)). If you upgrade you should stop seeing those messages when using `.destroy()` 😄 

Feel free to open up a new issue if the problem persists!
