### ISSUE TITLE
"ParseError: Unexpected Token" when trying to mount vue component

### ISSUE THREAD

**Issue by kamalsprasad** [vuejs/vue-test-utils#1547]
### Version
1.0.0

### Reproduction link
[https://github.com/ecofriend/TestApp](https://github.com/ecofriend/TestApp)

### Steps to reproduce
run "meteor npm run cypress-gui"
select "Title.code.test.js" test
Error is displayed when the test webpage loads.

### What is expected?
test should run

### What is actually happening?
I'm getting a "ParseError: Unexpected Token" as if TitleInput.vue component is not being mounted properly by vue-test-utils.

---
This is a MeteorJS app with VueJS frontend and Cypress for testing.

**Comment by dobromir-hristov** [comment]
why are you mounting the unit test inside cypress?

**Comment by kamalsprasad** [comment]
> why are you mounting the unit test inside cypress?

I'm following the tutorial found here: https://learntdd.in/vue/

**Comment by dobromir-hristov** [comment]
Please follow it more closely. They do not advise you to mix the two types off tests.

**Comment by kamalsprasad** [comment]
> Please follow it more closely. They do not advise you to mix the two types off tests.

I'm following it exactly. I guess I'm using the wrong terminology. I doing what the tutorial refers to as the "inside" test, which I took to mean unit test.

**Comment by dobromir-hristov** [comment]
I am sorry but you are deff not 😆 Your file structure is off. You cannot put your unit tests in the folder with the e2e tests, Cypress will try to read them.

This is not a VTU issue :)

**Comment by kamalsprasad** [comment]
OK, thanks. I finally figured it out. Using cypress-vue-unit-test instead.
