### ISSUE TITLE
Cannot read property 'parentNode' of undefined

### ISSUE THREAD

**Issue by Jasmin2895** [vuejs/vue-test-utils#1560]
### Version
1.0.3

### Reproduction link
[https://jsfiddle.net/g2qrv9um/](https://jsfiddle.net/g2qrv9um/)

### Steps to reproduce
Hey,

I am using @vue/test-utils in my project and while running tests this error `Cannot read property 'parentNode' of undefined` pops up every time. This error is occurring due to the line in my plugin file where I am referencing the document and window object.

```
export default {
  install() {
    (function() {
      var wzrk = document.createElement("script");
      wzrk.type = "text/javascript";
      wzrk.async = true;
      wzrk.src =
        "https://maps.googleapis.com/maps/api/js?key="  
        GOOGLE_PLACES_KEY  
        "&libraries=places";
      var s = document.getElementsByTagName("script")[0];
      s.parentNode.insertBefore(wzrk, s);
    })();
  }
};
```

After checking out few issues on github I tried the following solutions, but none seems to help.
1.Passed the argumnet `attachToDocument: true` when mounting the component.
2. Tried adding script tag in *beforeEach* method.
``` const script = document.createElement("script");
    document.body.appendChild(script);
```

The version I am using the latest version. Please assist me in solving the issue. Thanks in advance! :)

### What is expected?
solution for mocking window object and method to render script

### What is actually happening?
unable to render the script tag used in plugin

**Comment by lmiller1990** [comment]
Your JSFiddle wasn't working as-is, but I updated the JS part like this:

```

class Plugin {

  static install() {
    console.log('installing')
    var wzrk = document.createElement("script");
    wzrk.type = "text/javascript";
    wzrk.async = true;
    wzrk.src =
      "https://maps.googleapis.com/maps/api/js?key=" +
      // GOOGLE_PLACES_API_KEY +
      "&libraries=places";
    var s = document.getElementsByTagName("script")[0];
    s.parentNode.insertBefore(wzrk, s);
  }
}

Vue.use(Plugin)

 new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue.js!'
  }
}) 
```

And it's working (in the browser).

I should clarify; do you want to just mock this dependency out entirely? One way would be to use `jest.mock` to mock the import. I am guessing you don't actually want to use Google Maps plugin in your unit tests.

If you can provide a bit more info about your goals and your project setup I can provide guidance; the code, as is, works fine in the JSFiddle you provided when changed to not use `export`.

**Comment by Jasmin2895** [comment]
Hi @lmiller1990 

Yes, you are correct I don't want to use Google Maps plugin in my unit tests. I tried to mock the plugins in the same way as we do for store in my spec file.

```javascript
import { MyPlugin } from "./MyPlugin";
localVue.use(MyPlugin);
```

This also doesn't seems to work for me. I was not importing the plugin file in the spec file previously but after importing the plugin the error remains the same.
In the plugin I am dynamically adding the script file. Can you please suggest something to resolve this issue as I am having multiple plugins in my Vue application which are dynamically importing scripts.

**Comment by lmiller1990** [comment]
If you have a plugin, when you mock it you will need to mock out any functionality it has. Eg for a minimal plugin with an `install` method, using Jest:

```
jest.mock('./MyPlugin', () => ({
  install: () => {}
}))
```

If you can post a repository with the problem you are experiencing, I will fix it for you to show you how. Without more information I can't suggest anything. Please post something I can either run or clone with the problem you are experiencing, so I can see and reproduce (original repro you posted doesn't run, it's using `export` which won't work in the browser without a build step).

**Comment by Jasmin2895** [comment]
This worked for me. Thanks a lot! 😄
