### ISSUE TITLE
props() returns the props of the mounted component instead of the root component

### ISSUE THREAD

**Issue by ianlet** [vuejs/vue-test-utils#1569]
### Steps to reproduce

Let's say I have this component:
```vue
<template>
   <MyComponent name="hello" data-test-id="my-component" />
</template>

<script>
import MyComponent from '@/components/MyComponent'

export default {
  name: 'MyWrapper'
  components: { MyComponent },
  props: {
    wrapperName: {
      type: String,
      required: true
    }
  }
  // ...
}
```

And the following test:
```js
it('should return MyComponent props', () => {
  const wrapper = shallowMount(MyWrapper, { propsData: { wrapperName: 'wrapper' } })
  const myComponent = wrapper.find('[data-test-id="my-component"]')

  expect(myComponent.props()).toBe({ name: 'hello' })
})
```

### Expected behaviour

The test should pass

### Actual behaviour

The test fails with:
```
expected: { name: 'hello' }
received: { wrapperName: 'wrapper' }
```

### Possible Solution

A possible workaround would be to wrap the root component into a `<div>` or a [fragment](https://github.com/y-nk/vue-fragment). But it would be nice if we could simply have the root component and nothing else.

This might be related to: https://github.com/vuejs/vue-test-utils/issues/1385

**Comment by dobromir-hristov** [comment]
Yeah so both your mounted component and the root share the same dom node, so it can't know which one to return to you.

Use ref or name, or the import itself to fetch by.
