### ISSUE TITLE
[vue-test-utils]: Using a string for stubs is deprecated and will be removed in the next major version.

### ISSUE THREAD

**Issue by tkd-itsuki** [vuejs/vue-test-utils#1576]
Up until now I am using a simple stub like the following.
but this morning I noticed that this is not working anymore with the current version.

`import { config, RouterLinkStub } from "@vue/test-utils"`
`config.stubs["welcomeIcon"] = "<div></div>"`

**Comment by afontcu** [comment]
Hi! You might want to provide a valid component syntax:

`config.stubs["welcomeIcon"] = { template: "<div></div> "}`

**Comment by tkd-itsuki** [comment]
@afontcu Thanks, any suggestions on how to not use these ugly empty stub if I don't want to test the template part?

**Comment by afontcu** [comment]
Glad that helped! 

Not sure what you mean by "if I don't want to test the template part". I'm assuming your `WelcomeIcon` component is somewhat large, slow or has some side effects, and that's the reason to stub it out?

**Comment by tkd-itsuki** [comment]
the welcomeIcon is actually an svg file. Apparently with **vue svg loader** I need to use it like the way I use my components. So it is just an image file and I don't want to test it.

**Comment by afontcu** [comment]
Then I'd say setting a stub the way you did is a proper solution for your use case 😄  You could decide to simply load `WelcomeIcon` and ignore its content in the test, but a stub is a valid solution, too.

I'll go ahead and close this up!
