### ISSUE TITLE
Bump deps, move to Jest, rollup 2

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/vue-test-utils#1585]
### Cleanup

**What should be cleaned up or changed**:

Working on V2 with Jest provides an incredibly fast feedback loop - it's a pleasure, I love working on it. Working on this is pretty slow at times, need to run `yarn build` to rebuild the bundle, and mocha-webpack just provides a less nice developer experience. Rollup v1 is also very old at this point.

To make the codebase maintainable for years to come, and more enjoyable to work on (thus more motivation to fix bugs) I would like to:

1. move to Jest
2. upgrade to rollup v2
3. bump dependencies in general

**Provide any links for context**:

**Comment by afontcu** [comment]
Something else that might help (but that it is probably out of scope here) is to remove any `sync` mode leftover. I feel things derailed a bit there, and a lot of code was compromised due to that (now removed) feature. Is it doable?

**Comment by afontcu** [comment]
Also: monorepo. Is it really needed?

**Comment by lmiller1990** [comment]
@afontcu Yes we should remove sync mode (different PR though). 

Re mononrepo: I do not like the monorepo setup we have; it adds little value, but lots of complexity. I think moving away from it is a pretty significant change, though, and I don't think see that many short-term benefits. We can discuss this more, but I think bumping dependencies (I can finish this week) and removing sync mode (probably not that hard?) have the most immediate value.

I also think we can consider dropping support for earlier versions of Vue 2 (maybe < v2.5) or something. Step by step! I think removing sync mode leftovers and Jest will help a lot; getting the open issues down to around 50 would be nice.

**Comment by AtofStryker** [comment]
@lmiller1990 @afontcu should we close this now? Or should we clean up the remnants of `sync` mode first or make a separate issue?

**Comment by lmiller1990** [comment]
Yes we should.

`sync` mode can probably be removed, if you are feeling motivated go for it.
