### ISSUE TITLE
Unable to trigger input on v-text-field

### ISSUE THREAD

**Issue by dodgyKnee73** [vuejs/vue-test-utils#1586]
### Subject of the issue

I am trying to test a component that takes input from a vuetify control (v-text-field) and using the wrapper trigger to simulate data entry with data commited to a vuex store.

### Steps to reproduce

Sample code:

Input.vue

```
<template>
  <div>
  <v-text-field 
    v-model="input">
  </v-text-field>
  </div>
</template>

<script>
export default {
  computed: {
    input: {
      get() {
        return this.$store.state.input;
      },
      set (value) {
        this.$store.commit("input", value);
      }
    }
  }
}
</script>

```
spec.js

```
import { mount, createLocalVue } from "@vue/test-utils";
import Vuex from "vuex";
import Vuetify from "vuetify";
import Input from "./Input";

const localVue = createLocalVue();
localVue.use(Vuex);
localVue.use(new Vuetify());

describe("Input.vue", () => {
  const sandbox = sinon.createSandbox();
  let store;
  let mutations;

  beforeEach(() => {
    mutations = {
      "input": () => {}
    };
    sandbox.spy(mutations, "input");
    store = new Vuex.Store({
      state: {
        input: null
      },
      mutations
    });
  });

  afterEach(() => {
    sandbox.restore();
  })

  it("commits input", () => {
    // arrange
    const wrapper = mount(Input, { store, localVue });
    // action
    const input = wrapper.find("input[type=\"text\"]");
    input.setValue("input");

    // assert
    expect(mutations.import.callCount).to.equal(1);
    expect(mutations.import.getCall(0).args[1]).to.equal("input");
  });

})
```

### Expected behaviour

Test should pass (or fail)

### Actual behaviour

Error: [vue-test-utils]: find did not return input[type="text"], cannot call setValue() on empty Wrapper
             at throwError (webpack:///node_modules/@vue/test-utils/dist/vue-test-utils.js:1731 <- index.js:39098:9)
             at ErrorWrapper.setValue (webpack:///node_modules/@vue/test-utils/dist/vue-test-utils.js:8932 <- index.js:46299:3)

**Comment by dodgyKnee73** [comment]
Some additional context:
Trigger uses selector as per the recommendation on this thread: https://github.com/vuejs/vue-test-utils/issues/957#issuecomment-419217970

**Comment by afontcu** [comment]
Hi!

I believe this is a configuration issue; `localVue.use(new Vuetify());` seems a bit off. I'm quite sure your console output tells you something about "Unknown custom element: <v-text-field>". That means Vuetify is not properly loaded.

You might want to check out Vuetify docs on [how to properly set up unit tests](https://vuetifyjs.com/en/getting-started/unit-testing/).

Long story short, it should be `.use(Vuetify)` (without the class instantiation), and also I think it should be attached to `Vue`,  not `localVue` to avoid warnings on readonly attributes.

Hope it helps!

**Comment by dodgyKnee73** [comment]
Thank you for the swift response @afontcu. The Vuetify setup instructions seem a little ambiguous or might be out of date, however adding vue.use(Vuetify) fixed the problem.
