### ISSUE TITLE
Wrapper/ get

### ISSUE THREAD

**Issue by AnnaYuS** [vuejs/vue-test-utils#1590]
### Documentation Feedback

This is the example from the docs.

```
expect(() => wrapper.get('.does-not-exist'))
  .to.throw()
  .with.property(
    'message',
    'Unable to find .does-not-exist within: <div>the actual DOM here...</div>'
  )

```
I cannot figure out what

```
.to.throw()
 .with.property(
```
bit does. Can there be an explanation or perhaps the example should be fixed?

**Affected documentation page:** https://vue-test-utils.vuejs.org/api/wrapper/#get

**Comment by afontcu** [comment]
Hi! 👋  `get` throws an error if nothing matching the given selector is found, so the snippet you highlighted asserts that `wrapper.get('.does-not-exist')` throws an error with the message `'Unable to find .does-not-exist within: ...'`

If you're using Jest, the syntax would be `expect(() => wrapper.get('.does-not-exist')).toThrow('Unable to find .does-not-exist within ...')`.

Hope it helps!
