### ISSUE TITLE
findAllComponents() is not a proper substitute for findAll()

### ISSUE THREAD

**Issue by adama8x** [vuejs/vue-test-utils#1594]
### Feature Description

`wrapper.findAllComponents()` should Take CSS selectors as an argument.  

Well maybe I'm doing something wrong by not throwing refs on every tiny element in my component or making sub components out of every div, but how can I safely test the amount of elements rendered to a list by referencing their `class` selector when I should not be using the findAll() method anymore? 

Am I missing something (which is definitely not unlikely)? If not, this feature would be well appreciated.

### Problem

`wrapper.findAll()`  Has a deprecation warning, the suggested substitute `wrapper.findAllComponents()` does not cover the functionality.

### Expected behaviour

As described in the Feature Description

### Alternatives

An additional `wrapper.findAllElements()` function.

**Comment by afontcu** [comment]
Hi! As stated in [Update docs](https://vue-test-utils.vuejs.org/upgrading-to-v1/#find), you can use `find`/`findAll` on DOM nodes using the querySelector syntax. On the other hand, `findComponent` and `findAllComponents` accept a component reference/instance.

So it is likely that `findAll` would suit your needs.

Hope it helps!

**Comment by adama8x** [comment]
@afontcu thanks for your answer but as I described:  _"findAll() Has a deprecation warning"_ [(docs),](https://vue-test-utils.vuejs.org/api/wrapper/#findall) so I would like to avoid using it on new projects.

**Comment by afontcu** [comment]
Hi!

The deprecation warning is only about using `findAll` to find all Components, not to find all DOM elements.

**Comment by adama8x** [comment]
Well that make sense, I forgot to distinguish between these two, sometimes my brain needs a little kick in in the ass. Thank you for your help.

**Comment by RudyOnRails** [comment]
Why do the docs here state that you can pass a selector to `findAllComponents`?

https://v1.test-utils.vuejs.org/api/wrapper/findallcomponents.html
