### ISSUE TITLE
data() is not available

### ISSUE THREAD

**Issue by codebryo** [vuejs/vue-test-utils#16]
Not sure this is on purpose, but it seems that 
`wrapper.data()` is no longer valid.

Is it preferred to use the `vm` object directly?
It's still in the API docs of `setData()` that's why I'm asking.

I checked, and it's no longer in the source code, so I guess it was removed.
Should I update the documentation accordingly?

**Comment by eddyerburgh** [comment]
Yes it's preferred to use the vm. 

Great catch 😄 , yes it would be appreciated if you could update the docs

**Comment by codebryo** [comment]
This was taken care off in https://github.com/vuejs/vue-test-utils/pull/19

**Comment by eddyerburgh** [comment]
#19 was merged into master, which means it'll be overwritten when we release. This needs to be merged into the dev branch

**Comment by posva** [comment]
I imagine it's my turn to close this 😆
