### ISSUE TITLE
Frustrating problem with conditional rendering involving child component (Jest)

### ISSUE THREAD

**Issue by geopic** [vuejs/vue-test-utils#1605]
### Subject of the issue

Testing a parent 'component' (`Home.vue`) which renders a child component only when an array's length is greater than 0, otherwise it doesn't render the child component at all. However, in the unit tests the parent component is behaving as if the array is empty no matter what. I'm using class-based component syntax with `vue-property-decorator` and `vue-class-component`.

### Steps to reproduce

This is the .vue file being tested:

```vue
<template>
  <div id="home">
    <section id="site-main" v-if="foo.length > 0"><ChildComponent/></section>
    <section id="site-intro" v-else-if="foo.length === 0">...</section>
  </div>
</template>

<script lang="ts">
import ChildComponent from '@/vue/components/ChildComponent.vue';

@Component({
  components: {
    ChildComponent
  }
})
export default class Home extends Vue {
  foo: string[] = [];

  created() {
    this.foo = JSON.parse(localStorage.getItem('bar')) || [];
  }
}
</script>
```

With the child component:

```vue
<template>
  <div id="child-component">
    Hello world
  </div>
</template>

<script lang="ts">
@Component
export default class ChildComponent extends Vue {}
</script>
```

And this is the test file itself (for the parent):

```ts
import { mount } from '@vue/test-utils';
import Home from '@/vue/pages/Home.vue';

describe('Home', () => {
  describe('no data exists', () => {
    const wrapper = mount(Home, { propsData: { foo: [] } });

    test('renders an intro element', () => {
      expect(() => wrapper.get('#site-intro')).not.toThrow();
    });
  });

  describe('data exists', () => {
    const wrapper = mount(Home, { propsData: { foo: ['hello', 'world'] } });

    test('renders child element', () => {
      expect(() => wrapper.get('#child-component')).not.toThrow();
    });
  });
});
```

### Expected behaviour

The last test not to throw, since it should render the content in the first `<section>` tag rather than the second as `foo.length` is greater than `0`.

### Actual behaviour

It does throw. I've checked the rendered HTML and it acts as if the `foo` array has no data in it at all, as if its length is `0`.

### Possible Solution

I'm not sure about any solution but I've triple-checked the docs and there was somebody here on GitHub who mentioned the `sync` option in `mount` as a solution, but `sync` is no longer a valid option. As mentioned I've checked the HTML and the test just ignores there being any content in `foo` so I'm not sure what to do to make my tests work. Thanks in advance guys.

**Comment by lmiller1990** [comment]
Hi!

You are passing `foo` as `propsData`, but you have not declared any `props`, right? `foo: string[] = [];` is like 

```
data() {
  return {
    foo: []
  }
}
```

Right?

So when you component is created, `this.foo` is set to `[]` since there is nothing in local storage - so this seems like it is the expected result, unless I am missing something.

**Comment by geopic** [comment]
Hello @lmiller1990, thanks for responding. Took another look at it and you're absolutely right on it not being a prop therefore `propsData` isn't the way to pass data in, `data` is. Reckon I have it all worked out now. :+1:  Will close this issue unless I have another related question come up.
