### ISSUE TITLE
setData does not update component

### ISSUE THREAD

**Issue by TeresaSiegmantel** [vuejs/vue-test-utils#1607]
### Subject of the issue

A call to `setData` does not update the rendered component. Neither `await wrapper.vm.$nextTick()`, nor `await wrapper.vm.$forceUpdate()` helps.

My concrete example is a form that uses `v-model` to bind the fields to parts of the components state. It is written in TypeScript as a class based component and uses Vue Bootstrap.

Debugging reveals that the internal state of the wrapper is correctly updated, but `wrapper.text()` does not show any of the values.

### Steps to reproduce
The following is a minimal example.
```
<template>
    <b-form>
        <b-form-group>
            <b-form-input id="input" v-model="input"/>
        </b-form-group>
    </b-form>
</template>

<script lang="ts">
    import {Component, Vue} from "vue-property-decorator";
    import {BButton, BForm, BFormGroup, BFormInput} from "bootstrap-vue";

    @Component({
      components: {
          BButton,
          BForm,
          BFormInput,
          BFormGroup
      }
  })
  export default class Example extends Vue {
      input: string
  }
</script>
```
```
import {createLocalVue, mount} from "@vue/test-utils";
import Example from "../Example.vue"

const localVue = createLocalVue()

describe("Example.vue", async () => {
    it("shows the rendered field", async () => {
        const wrapper = mount(Example, {
            localVue
        })
        await wrapper.setData({
            input: "foobar"
        })
        await wrapper.vm.$nextTick()
        await wrapper.vm.$forceUpdate()
        const input = wrapper.find("#input")
        expect(input.text()).toContain("foobar")

    })
})
```
### Expected behaviour

The test should pass.

### Actual behaviour

The test fails.

Output:
```
 ● Example.vue › shows the rendered field

    expect(received).toContain(expected) // indexOf

    Expected substring: "foobar"
    Received string:    ""

      15 |         await wrapper.vm.$forceUpdate()
      16 |         const input = wrapper.find("#input")
    > 17 |         expect(input.text()).toContain("foobar")
         |                              ^
      18 | 
      19 |     })
      20 | })

      at Object.<anonymous> (tests/unit/Example.spec.ts:17:30)
```

### Possible Solution

I don't know of any possible solutions.

**Comment by lmiller1990** [comment]
What is `input.text()`? If this is an `<input />`, wouldn't the way to access the value be `input.element.value` or something along these lines? `text` is just doing `innerText` I believe, which will always be empty on an `<input />` element/

**Comment by lmiller1990** [comment]
Any luck with this?

**Comment by TeresaSiegmantel** [comment]
It worked. Thank you!
