### ISSUE TITLE
Multiple file component testing

### ISSUE THREAD

**Issue by LukasGaebler** [vuejs/vue-test-utils#1609]
### Multiple file component testing impossible?

I'm trying to run unit tests on my project where the .vue file is split up in html, typescript and css. When trying to do it with jets, it seems to be impossible, as there is nothing in the vue docs or on stackoverflow. 

All there is, how to test single file components

### Steps to reproduce
I have set up a vue project with typescript, and splitted the files into html, css, and typescript. When starting with the jest test, there is always an error.

### What have I already tried?

I tried adding html to the "transform" property in the jest.config.js file like this
````
transform: {
    '.+\\.(html)$': 'jest-transform-stub'
  },
````
but when running it with this configuration like this:
````
const localVue = createLocalVue()
localVue.use(VueRouter)
const router = new VueRouter()

describe(component, () => {
    const wrapper = mount(component, {
        localVue,
        router
    });

    console.log(wrapper.html());
    
});
````
 the wrapper.html() is just an empty string

### Expected behaviour

The html string shouldn't be empty

### Possible solution

Maybe writing a transformer for jest would be helpful but I'm not sure about that

**Comment by lmiller1990** [comment]
We have the `vue-jest` transformer: https://github.com/vuejs/vue-jest. It supports this, we have a test case around it https://github.com/vuejs/vue-jest/blob/master/e2e/__projects__/basic/components/BasicSrc.vue

Have you tried using that? If you do, please make sure to use the latest version (v4, not the main one on NPM yet). You can use it with `yarn add vue-jest@4.0.0-beta.2` (I think is the current one).

If you use the vue-cli to start your project, and choose "jest" for your test runner, this should work out of the box.

If you are still having problems after trying those things, I can help a bit more (seems like you need the correct config/transformer first).
