### ISSUE TITLE
How do you use Environment Variables when using vue-test-utils with Jest?

### ISSUE THREAD

**Issue by DarynHolmes** [vuejs/vue-test-utils#161]
I would like to use the Environment Variable explained here: https://vuejs-templates.github.io/webpack/env.html

I followed the excellent vue-test-utils guide here: https://vue-test-utils.vuejs.org/en/guides/testing-SFCs-with-jest.html

Now when the tests run, the environment variables have not been setup, the config/index.js was not run.

I have the following in package.json

```
  "scripts": {
    "dev": "node build/dev-server.js",
    "start": "npm run dev",
    "build": "node build/build.js",
    "e2e": "node test/e2e/runner.js",
    "test": "npm run unit && npm run e2e",
    "unit": "jest --coverage",
    "unit-watch": "jest --watch",
    "lint": "eslint --ext .js,.vue src test/unit/specs test/e2e/specs"
  },
```
```
  "jest": {
    "testURL":"http://localhost:3000",
    "moduleFileExtensions": [
      "js",
      "json",
      "vue"
    ],
    "moduleNameMapper": {
      "^@/(.*)$": "<rootDir>/src/$1"
    },
    "snapshotSerializers": [
      "<rootDir>/node_modules/jest-serializer-vue"
    ],
    "transform": {
      ".*\\.(vue)$": "<rootDir>/node_modules/vue-jest",
      "^.+\\.js$": "<rootDir>/node_modules/babel-jest"
    },
    "testPathIgnorePatterns": [
      "/node_modules/",
      "/test/e2e/"
    ],
    "mapCoverage": true
  }
```

Do you have any advice on how I can use the environment variables?

Thanks!

**Comment by eddyerburgh** [comment]
Hey @DarynHolmes 😀

This is outside the scope of vue-test-utils. You can set `NODE_ENV=dev` or `NODE_ENV=production` or `NODE_ENV=anyvalueyouwant`, in your script. Then you can pick it up using `process.env.NODE_ENV`, or map it like they do in the webpack template.

But when you run JEST, NODE_ENV and BABEL_ENV are set to test.

`config/index.js` is run by webpack.

I'm closing this issue. If you have further questions please ask them on StackOverflow

**Comment by DarynHolmes** [comment]
Hi @eddyerburgh 

Thanks for such a speedy response and for all the good work you and the team are doing on this.
I don't know if this is an issue for this project or not, I thought I would ask one last time.
I think this is different to setting the `NODE_ENV`. 

The environment variables seem to get set from within `/config.index`. When I run `npm run dev` this get's called from `vue-loader.conf.js`

```
const config = require('../config')
```

From what I understand, `vue-loader` is not being used by `vue-test-utils` when running it with Jest. 

Could this be the problem of why I am getting undefined for custom environment variables defined in `./conf/dev/env.js`? 

Thanks

**Comment by DarynHolmes** [comment]
I have tried the example: https://github.com/vuejs/vue-test-utils-jest-example

That also does not set custom environment variables in `./config/dev.env.js`

**Comment by ssokolov1** [comment]
I am not sure, why is this out of scope. Running unit tests against the real code that expects env properties to be set is a very legit use case. Using .env.test and getting properties from it should be supported.

**Comment by DarynHolmes** [comment]
@ssokolov1 I re-raised this issue [here](https://github.com/vuejs/vue-test-utils/issues/193) and there are a few suggestions there that might help.

**Comment by ssokolov1** [comment]
Thank you, I am using a temporary solution by abstracting access to env properties in a separate module and when this module is loading I am using dotenv if node mode is test

```
if (process.env.NODE_ENV==='test') {
    require('dotenv').config();//By some reason in test mode env is not loaded
}
export default {
    /************************************************************************************************************
     *   get environment property
     ************************************************************************************************************/
    getEnv(property) {

        if (!property.startsWith("VUE_APP_")) {
            property = "VUE_APP_" + property;//add mandatory vue env prefix
        }

        if (!process.env[property]) {
            util.warn(`property not found ${property}`);
            util.warn(process.env);
        }
        return process.env[property];
    },
    /************************************************************************************************************
     * @return property as int value
     ************************************************************************************************************/
    getEnvInt(property) {
        const v = this.getEnv(property);
        if (!v) {
            return;
        } else {
            return parseInt(v);
        }
    },
}
```
