### ISSUE TITLE
Finding component stubbed using default stub

### ISSUE THREAD

**Issue by mokkabonna** [vuejs/vue-test-utils#162]
Currently if I want to find a component that is stubbed using the default stub I have to do this:

```js
wrapper.find(wrapper.vm.$options.components.myComponentName)
```
Any chance this could be simplified? Some suggestions below:

Simply allow find using string to also find components:
```js
wrapper.find('my-component-name') // or with camelCase?
wrapper.findAll(...)
```
This could possibly collide with tag names?

Shortcut:
```js
wrapper.find(wrapper.components.myComponentName)
wrapper.findAll(...)
```

By name:
```js
wrapper.findComponent('myComponentName')
wrapper.findAllComponents(...)
```

Automatic generation:
```js
wrapper.findMyComponentName()
wrapper.findAllMyComponentName()
```

**Comment by eddyerburgh** [comment]
You can also search using the component:

```js
import myComponentName from './myComponentName'

wrapper.find(myComponentName)
```

**Comment by mokkabonna** [comment]
Looking at the code it seems that the only thing that is actually needed when searching for a component is the name of the component. Is this correct? In addition to that it checks if it is a vue component. But that check only check that it is an object and that is has a render function, even though that does not seem to be used in the search process itself.

I assume (can't check right now) the following would find the right component for me:

```js
wrapper.find({
  name: 'myComponentName',
  render: function() {}
})
```

If so, I think a string based find method for components seems simpler than having to somehow get hold of the component instance and passing to find. (by import or options)

Unless it is done this way on purpose for possible future features, that requires more information from the component.

**Comment by eddyerburgh** [comment]
I think a string find for components would have a lot of bugs.

I agree, it would be a nice API, but I'm not sure it's worth the overhead of maintaining.

And yes, your example would work.

**Comment by lmiller1990** [comment]
The pattern I have been using heavily is:

``` js
```

**Comment by mokkabonna** [comment]
That gives you a wrapper with no vm property.

Then you can't call hasProp and similar methods. That is what I want to do. Related to https://github.com/vuejs/vue-test-utils/issues/163

**Comment by eddyerburgh** [comment]
I don't think we should add two extra methods for finding components, that would mean we have 4 methods for traversing the render tree.

I think the solution is to improve the selector system. 

Currently we support a name selector (although this is normally recommended as using the original component object) and a ref selector:

const nameSelector  = {
  name: 'some-name'
}

const refSelector = {
  ref: 'some-ref'
}

I'm going to remove the check for a render function from the name selector, that way you can achieve the functionality you would like without having to pass a noop render function. 

With that commit, I'll close this issue, as we won't be adding extra `findComponent` methods. If you feel strongly for adding these methods, I can reopen the issue, but I'm against adding these methods.

If you have ideas for another selector, please make a new issue.

**Comment by eddyerburgh** [comment]
You can now pass in a name selector without a render function(https://github.com/vuejs/vue-test-utils/commit/df706fe26b646fe3d53368135f6aeba19eda7b5c). This will be released in beta.9:
