### ISSUE TITLE
Using Vue/Vuetify, the DOM is not updating to show warning message after toggling checkbox

### ISSUE THREAD

**Issue by jb0071913** [vuejs/vue-test-utils#1625]
### Subject of the issue

I have a vuetify checkbox component and when it is checked, a warning message should be displayed beneath it. There is a computed property called checkBoxValue which is used as the model for the checkbox and determines if the warning message is shown. A unit test is failing because once the checkbox is selected, the warning message is not rendered in the DOM.

### Steps to reproduce

Environment:
Vue: 2.6.11
Vuetify: 2.3.6
Jest: 24.9.0
vue test utils: 1.0.3

My component:

```javascript
<template>
    <div>
        <v-checkbox id="check-box-test"
            label="checkbox label"
            v-model="checkBoxValue"
        >
        </v-checkbox>
        <div v-if="checkBoxValue" class="warning-message">
            {{warningMessage}}
        </div>
    </div>
</template>

<script>
const WARNING_MESSAGE = 'warning message';

export default {
    computed: {
        checkBoxValue: {
            get() {
                return this.value;
            },
            set(checkBoxValue) {
                this.$emit('input', checkBoxValue);
            }
        }
    },
    data() {
        return {
            warningMessage: WARNING_MESSAGE
        };
    },
    name: 'CheckboxComponent',
    props: {
        value: {
            required: false,
            type: Boolean
        }
    }
};
</script>
```

The test which is failing:

```javascript
function getCheckBox() {
        return wrapper.find('#check-box-test');
    }

    function getWarningMessage() {
        return wrapper.find('.warning-message');
    }
...
test('shows a warning message when toggled on', async () => {
        const localVue = createLocalVue();
        localVue.use(Vuetify);
        wrapper = mount(CheckboxComponent, {
            localVue,
            propsData: {
                value: false            // This will mean the checkbox is unchecked after being created
           }
        });
        const checkBox = getCheckBox();
        checkBox.setChecked();  // checkbox now checked
        await wrapper.vm.$nextTick();
        console.log(wrapper.html()); // This shows me that the input is checked="true" but the warning message is not present
        const message = getWarningMessage();
        expect(message.exists()).toBe(true);  // This should be true
    });
```
### Expected behaviour

The unit test should pass.

It is worth noting that if I pass in the value prop set to true when constructing the component, the warning message is rendered as expected.
It is also worth noting that this component works as expected when deployed in my app and running in the browser.

### Actual behaviour

The unit test fails as it cannot find the warning message in the DOM.

### Possible Solution

None at moment. I have tried using wrapper.vm.nextTick() and also used wrapper.html() to check the rendered DOM.

**Comment by lmiller1990** [comment]
This looks like it should be fine. Off the top of my head, you could try

- `await wrapper.setChecked()`
- `await flushPromisess` (install from NPM, force all promises to resolve)

If neither of those work, could post post a repo (or code sandbox) I can run?
