### ISSUE TITLE
Feature: Add hasValidProps to wrapper

### ISSUE THREAD

**Issue by mokkabonna** [vuejs/vue-test-utils#163]
I want to suggest adding a **hasRequiredProps** or **hasValidProps** (to also check not required but supplied props against type) to wrapper instances, this is useful when asserting that all required props have been passed to a child component.

I am currently doing roughly this:

```js
var childWrapper = wrapper.find(wrapper.vm.$options.components.runsList)

_.forEach(childWrapper.vm.$options.props, function (config, name) {
  if (config.required) {
    expect(childWrapper.vm.$props[name]).to.be.an.instanceOf(childWrapper.vm.$options.props[name].type)
  }
})

```

While I think this could be a commonly used feature that maybe should be added to the test utils.

```js
var childWrapper = wrapper.find(wrapper.vm.$options.components.runsList)
expect(childWrapper.hasValidProps()).to.equal(true)
```

**hasProp** is nice if I want to assert that a certain value is passed as the right prop, but if I forget to assert one of the required props of the child component, I type the wrong prop name or the required props changes, I will actually be calling the component with too few props or with the wrong type. This would not be detected before runtime.

Adding the **hasValidProps** will catch any such changes and assure that the parent component at all times passes the correct type and amount of props.

You could also take this one step further and make the default component stub automatically detect and assert that the props passed are valid, throwing if they aren't. But looking at the library it seems you want to stick to boolean checks that you manually have to assert.

----
Another approach is to allow overriding the default stub with your own and make people implement that automatic check in their own stub. I could do that now, but then I have to manually define the stub for all components. This could possibly be added anyway.

**Comment by eddyerburgh** [comment]
I think this would be a nice feature, but I'd like to get a few more opinions before I give it the OK

**Comment by mokkabonna** [comment]
If you use shallow rendering and stubs there is no rendered output to test. 

Also just to mention it: if you stub a function in a normal plain js unit test, it does not normally auto assert. Doesn't mean that we shouldn't do it here though. If you decide to add assertions, then it would behave more like a mock (in sinon.js terms: http://sinonjs.org/releases/v1.17.6/mocks/) 

> Mocks (and mock expectations) are fake methods (like spies) with pre-programmed behavior (like stubs) as well as pre-programmed expectations.

------


> So I think the best way would be to create a hasValidProps matcher and then use that internally when we are stubbing out the children or rendering them.

I like this, vue does report invalid props being passed (when no stub), but I don't think it does actually throw and fail the test? If vue-test-utils validated props both for stubs and real rendered components then that would be nice.

**Comment by robcresswell** [comment]
Is this still up for discussion? I know it's 6 weeks old or so, but it sounds like something very useful. My current example would be:

- I have a top level `notificationList` component, which contains a list that renders `notification` components, based on data in the global store (`vuex`, in this case)
- I'd like to write a test that ensures each `notification` recieves a `variant` prop. It's straightforward with the current design to check that `notificationList` gets data from the store and updates when the store is updated, and verify that the internal state of `notificationList`is correct. Equally, I can verify that `notification` renders correctly when passed a specific `variant`, or that it throws an error when passed an invalid one. The part I *can't* accomplish easily is to check that the `variant` is passed from `notificationList` to the `notification` via the template. So, for example, if it was modified to always pass in the first variant for X number of notifications, then that would still pass the tests for both component, but be incorrect.

**Comment by eddyerburgh** [comment]
I'm happy to add this feature. @mokkabonna would you like to make a PR?

**Comment by mokkabonna** [comment]
Yes I can do that. I assume `hasValidProps`? I see `hasProp` has been removed.

**Comment by eddyerburgh** [comment]
Yes, hasValidProps is good 🙂

**Comment by beyer-martin** [comment]
Is this still on development?, would like to give it a shot!

**Comment by eddyerburgh** [comment]
It's not in development, it would be great if you could add it :)

**Comment by beyer-martin** [comment]
Ok great then!, how would the implementation be?, from the discussion its kinda unclear. Thanks

**Comment by eddyerburgh** [comment]
I'm not sure what the implementation would be, since I haven't investigated.

The API would simply be `hasValidProps`, which would return a boolean.

**Comment by eddyerburgh** [comment]
I've investigated, and it will require a lot of logic to add this.

You can see [the code used in Vue to validate props](https://github.com/vuejs/vue/blob/dev/src/core/util/props.js#L21). We have access to the propsData object, but we don't have access to data on whether it was validated or not. Duplicating that amount of code leaves us open to bugs, and I don't think the benefit is worth it.

I'm closing this as something we won't implement.

One way to test this is to stub console.warn and check that it's not called.
