### ISSUE TITLE
element.style doesn’t work properly with hsl() values

### ISSUE THREAD

**Issue by ghost** [vuejs/vue-test-utils#1630]
When I try to test the color of an element by using `find()` and then `myElement.element.style.background` I’ve noticed returned value is always `rgb()`

However, if my element has a hsl() color value (for instance `<div style="background: hsl(123, 25%, 42%)">` vue-test-utils messes up the hsl to rgb conversion and returns a grey value `rgb(107 107 107)` instead of the correct value `rgb(80 134 83)`

The grey value changes when I change the color

The return color is fine for Hex and RGB… it’s just HSL that messes up

I guess this is due to jsdom not being able to deal properly with HSL but that’s annoying !

Thanks a lot for your help

**Comment by dobromir-hristov** [comment]
Hey, this is purely jsdom, nothing to do with VTU IMHO :(

**Comment by afontcu** [comment]
Hi! This is definitely related to jsdo, not VTU 😞  I'm going to close the issue as there's nothing to do on our side, you might want to try and open up an issue in jsdom repo and see if anyone can help you out.

Thanks for opening up the issue, though! 🙌
