### ISSUE TITLE
Passing trigger options fails with TypeError

### ISSUE THREAD

**Issue by vvanpo** [vuejs/vue-test-utils#1632]
### Subject of the issue

Calling `trigger()` with a specific set of options fails. I find this odd, because looking at the code it doesn't appear this should happen: https://github.com/vuejs/vue-test-utils/blob/v1.0.0-beta.31/packages/test-utils/src/create-dom-event.js#L93 You would think it just wouldn't set the property if it wasn't set-able, and not report a warning. But clearly this check is being subverted somehow.

### Steps to reproduce

In a `jsdom@16.2.2` environment:
Call `wrapper.trigger('click', { detail: 1 })`.

### Expected behaviour

The resulting UIEvent is a MouseEvent with the property `detail` equal to 1.

### Actual behaviour

`TypeError: Cannot set property detail of [object UIEvent] which has only a getter`

**Comment by vvanpo** [comment]
Ah, I think I've got it:

https://www.w3.org/TR/uievents/#event-type-click

You can see in the spec that `detail` is a property of `UIEvent`, not `MouseEvent`. But in https://github.com/vuejs/vue-test-utils/blob/v1.0.0-beta.31/packages/test-utils/src/create-dom-event.js#L83 we only look at the very first prototype in the chain, in this case `MouseEvent`. If I log `Object.getPrototypeOf($event)` to the console I can see that `detail` is not set on `MouseEvent`, but if I chain two `getPrototypeOf`'s together I can see that it _is_ set on `UIEvent`.

So I think we need to walk the entire prototype chain when determining to set a property or not. I also wonder if we shouldn't give the user a warning in that case. In any case, this still doesn't get me closer to being able to set `detail` on click events.

**Comment by lmiller1990** [comment]
Sorry I took a long time to reply to this! There are a lot of issues coming in lately. 

According to MDN https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/detail

> The UIEvent.detail **read-only** property

If this property is read-only, I guess you should not be able to set it - (even in a testing environment, read-only is read-only, right?)

If it is readonly I not sure we should allow passing it in. What test are you trying to write? If you want to track the amount of clicks, would it be better to do it yourself in a `data` property 🤔 ?

**Comment by vvanpo** [comment]
> would it be better to do it yourself in a data property

That won't work for click events that are not triggered by the user directly.

The particular use-case I had was a search-bar component with a text input and a submit button, and I wanted the component to both support native form submission when placed inside a `<form>` and also emit its own `submit` custom event in case form submission is being ignored/prevented or it is not placed inside a form.

Emitting the custom event is as simple as listening for `keydown.enter` on the input and `click` on the button, but this becomes a problem for native form submission because _some_ browsers (not all, the standard makes it optional) will trigger a separate `click` event on the nearest submit button when you press `enter` inside an input. This causes duplicate `submit` events being emitted. One solution, then, is to pass the UI event to the submit handler, and if it's a `MouseEvent`, inspect its `detail` property to see if the event was triggered by the browser or by an actual user click, ignoring it if it's the former.

`jsdom` does not set the `detail` property to any value other than 0 no matter how you trigger it, so in order to properly test this behaviour I would have to set it manually, hence this issue. I'm not sure about it being read-only, I think it should always still be possible to set it using `Object.defineProperty(..., { value: 1, writable: true })`. But you're probably right that `trigger` should not be doing this, so I'll close this.

I wanted the parent component to be able to do `@submit.prevent` on this search bar component (in case it did not have access to the parent `<form>`) so that it cancels native form submission, which means emitting the actual UI event object as the payload of the custom `submit` event. But this causes a race condition between `preventDefault()` being called on the `KeyboardEvent` and the click event being triggered by the browser, which different browsers handle differently. IIRC Chrome and FF dealt with this one way, and IE11 had opposite behaviour, although I can't remember exactly which one did what. I ended up just scrapping the whole idea and not supporting native form submission for that component at all.
