### ISSUE TITLE
Cannot install vue-test-utils with npm

### ISSUE THREAD

**Issue by mj026** [vuejs/vue-test-utils#1637]
```
$ npm install @vue/test-utils
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@vue%2ftest-utils - Not found
```

Tried on two different platforms, both with the same results.
node versions: 
- v12.16.3
- v12.18.3 

npm versions: 
- 6.14.4
- 6.14.6

### Steps to reproduce
Try to install vue-test-utils with `npm install @vue/test-utils`

### Expected behaviour
That it would install.

### Actual behaviour
It can't find the package in the npm registry.

**Comment by Max-0n** [comment]
I have same issue

**Comment by afontcu** [comment]
Looks like there's an ongoing issue with npm: https://status.npmjs.org/

**Comment by Max-0n** [comment]
It works now.

**Comment by afontcu** [comment]
Cool! closing
