### ISSUE TITLE
Error: [vue-test-utils]: enableAutoDestroy cannot be called more than once

### ISSUE THREAD

**Issue by mariadb-ThienLy** [vuejs/vue-test-utils#1638]
### enableAutoDestroy doesn't work as expected

Basically I have many ***spec.js files. There are two files that I call this helper, it prompts error immediately after I run the all tests.
### Steps to reproduce

Create two dummy unit tests files. e.g.  Hello.spec.js and  Dummy.spec.js and calls 
enableAutoDestroy(afterEach)

### Expected behaviour
Should work normal as using wrapper.destroy() in afterEach hooks

### Actual behaviour

```
Error: [vue-test-utils]: enableAutoDestroy cannot be called more than once
```

**Comment by lmiller1990** [comment]
Hi! Thanks for the issue. Which test runner are you using? I wonder if this is test-runner specific.

Are you interested in investigating making a PR by any chance?

**Comment by xanf** [comment]
@mariadb-ThienLy I believe this is intended behavior - you can register `enableAutoDestroy` only once and should do it in global setup. But I see use cases when we may benefit from suite level auto-destroy - for example in GitLab some suites are using one wrapper per test, but some do not. 

@lmiller1990 WDYT of making `enableAutoDestroy` to return "unsubscribe" function - so we can safely install and uninstall this logic per-file

**Comment by lmiller1990** [comment]
I am not sure if this intended or not 🤔 I almost forgot about this feature. 

@xanf That sounds a better way of doing this @xanf - and this would be purely additive, no breaking change, I believe?

**Comment by xanf** [comment]
@lmiller1990 exactly, I'll make a PR

**Comment by winniehell** [comment]
author of https://github.com/vuejs/vue-test-utils/pull/1245 here :wave: 

> I am not sure if this intended or not :thinking:

Yes, to some degree it was intended because you don't run into the issue in an isolated test environment such as Jest. Resetting the hook callback is a bit complicated. No test framework I know of allows to disable callbacks you once passed to `afterEach`.

We could replace this

https://github.com/vuejs/vue-test-utils/blob/6e3e4e5818eb13d03e61dd61d02eef968d044847/packages/test-utils/src/auto-destroy.js#L21-L30

with

```javascript
const callback = () = {
  // ...
}

hook(() => callback());

const disable = () => {
  callback = () => {};
  isEnabled = false;
};

return disable;
```

but it's not extremely beautiful as (the empty) callback will still be called for every test run.

**Comment by xanf** [comment]
I believe this one could be closed - there is `resetAutoDestroyState` method which is now exposed in docs in more obvious way via #1674

**Comment by winniehell** [comment]
@xanf Calling `resetAutoDestroyState` does not allow to call `enableAutoDestroy` more than once though (which is what this issue was about).

**Comment by xanf** [comment]
@winniehell correct me if I'm wrong https://github.com/vuejs/vue-test-utils/blob/dev/packages/test-utils/src/auto-destroy.js#L10 will allow me to reinstall `enableAutoDestroy` in other file

**Comment by winniehell** [comment]
@xanf yes, more precisely: It can be called more than once but the behavior would be surprising. For example

```javascript
enableAutoDestroy(afterEach);

resetAutoDestroyState();

enableAutoDestroy(afterAll);
```

would destroy the wrappers in `afterEach`.
