### ISSUE TITLE
How to skip compile error and run test?

### ISSUE THREAD

**Issue by hh54188** [vuejs/vue-test-utils#1642]
### Subject of the issue

Run vue test encounter compile error, but the component could run successfully in browser. Not sure is belongs to vue-test-utils

### Steps to reproduce

```javascript
export default {
  name: 'App',
  components: {
  },
  created() {
    let t = typeof t === 'undefined' ? {} : t; // ISSUE LINE
  }
}
```

### Expected behaviour

The *ISSUE LINE* could run success in browser without any error and pass vue-cli compile process.

### Actual behaviour

However, when I try to run this component't test in jest, it could report compile error:

> ReferenceError: Cannot access 't' before initialization

**Comment by vvanpo** [comment]
This is interesting, although I don't think it's a problem with `@vue/test-utils`. I can reproduce this without using Vue at all, just by running the following via the `node` CLI:

```
$ node -e 'let t = t'
[eval]:1
let t = t
        ^

ReferenceError: Cannot access 't' before initialization
```

Running the same in Chrome's console also produces a [`ReferenceError`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError), so this is clearly just a Javascript behaviour. Are you sure there was no error when running your code in the browser? Are you sure that codepath was being executed?

**Comment by lmiller1990** [comment]
I ran that code in my browser and got `Uncaught ReferenceError: can't access lexical declaration 't' before initialization`. 

Either way, I don't see any problem with VTU here; you won't find any test runner that is going to let you run invalid code. Vue CLI is not going to catch a runtime error, I am guessing the code just isn't executed in the browser, or if it is, you just didn't notice the error in the console.

**Comment by hh54188** [comment]
Thank you for replay. I have got the answer. I ask the same question on [stackoverflow](https://stackoverflow.com/questions/63373730/how-to-skip-jest-compile-error-and-run-test).
