### ISSUE TITLE
find is deprecated, findComponent fails

### ISSUE THREAD

**Issue by cyberalien** [vuejs/vue-test-utils#1643]
### Subject of the issue

Function `find()` was deprecated, but there is no viable alternative.

### Steps to reproduce

Replaced `find()` with `findComponent()` as per deprecation notice.

### Expected behaviour

Renaming function should not change its behavior, tests should continue to run.

### Actual behaviour

Tests started to fail with this error: `You cannot chain findComponent off a DOM element. It can only be used on Vue Components.`

How to continue testing DOM elements created by Vue component after `find()` is gone?

**Comment by afontcu** [comment]
Hi! `find` is not deprecated – only searching for a Component using `find` is 😃 

More on that: https://vue-test-utils.vuejs.org/upgrading-to-v1/#find

Hope it helps!

**Comment by cyberalien** [comment]
Sorry, my description probably was confusing. I am searching for component, but getting that error regardless:

This is a basic test:
```js
describe('Mounting component', () => {
	test('without wrapper', () => {
		const wrapper = mount(IconifyIcon, {});
		const item = wrapper.find(IconifyIcon);
		expect(item.exists()).toBe(true);
		expect(item.html()).toStrictEqual(
			'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 16 16"></svg>'
		);
	});
});
```
Function `find()` shows notice, when replaced with `findComponent()` throws error.

Component is here: https://github.com/iconify/iconify/blob/master/packages/vue/src/IconifyIcon.ts
Tests are here: https://github.com/iconify/iconify/blob/master/packages/vue/tests/icon.test.js (all fail after replacing find with findComponent, except for first test)

**Comment by cyberalien** [comment]
It is a functional component with `render()` function, if that makes difference.

**Comment by nwoltman** [comment]
I believe this was fixed by #1593. A new version of VTU just hasn't been released since that PR was merged.

**Comment by afontcu** [comment]
Yeah, that sounds about right! We'll issue a release in the upcoming days, I'll let you know!

**Comment by cyberalien** [comment]
Thank you! Looking forward to it.

**Comment by lmiller1990** [comment]
VTU new version about 2 days ago I am not sure if this is fixed there, let me know.

**Comment by cyberalien** [comment]
Yes, that fixed it. Thank you!
