### ISSUE TITLE
vue-test-utils doesn't track object props

### ISSUE THREAD

**Issue by alexey2baranov** [vuejs/vue-test-utils#1651]
### vue-test-utils doesn't track object props

**History**
This is a copy of my prev issue https://github.com/vuejs/vue-test-utils/issues/1621 which was unexpectedly closed by @dobromir-hristov . I have removed delay from `mounted`, which was simulating fetch delay, and add second component user2.js. 

**Context**

i have a `User` object which is the data model for a vue.js UserComponent. When the component is mounted the `user` has undefined fields. Then inside the `mounted() `method the `user` is fetched from the server and all its fields are setted.

**Problem**

So i found that `vue-test-utils` doesn't redraw component when user's field changed.

**Note**

On the other hand the same test works good if i change object prop `user` to scalar. I have added a second component user2.js just to show this. Into test.js file I test both of them with same test. As you can see user2.js component with scalar prop completes test successfylly, but user.js doesn't.

### Steps to reproduce
https://github.com/alexey2baranov/vue-test-utils-getting-started

### Expected behaviour

Both test should be done

### Actual behaviour

First test fails

### Possible Solution

Unfortunately i don't know any possible solution. I tried to reset user prop by `wrapper.setProp({user: user})` after its fields was fetchad. Unfortunatelly it is impossible as `vue-test-utils` prevent to set the same object to prop twice.

**Comment by dobromir-hristov** [comment]
Like I told you last time, you should not mutate a prop, in your case "value" like that.

Emit an event, handle at the parent and assert it is emitted.

Your mounted component has no parent, nothing to react to that value mutation, thus your test fails.

I will let someone else close, so there are no hard feelings 😉

**Comment by alexey2baranov** [comment]
please, i do not understand why this test fails.
If imagine i start this component inside browser, then it renders initial state of user, then fetch user data, and then rerender html according to the new state. So why it shouldn't work same inside test?

**Comment by alexey2baranov** [comment]
And I do not understand you words about throwing event and handling it in parent. Why i should do this if I just want to check that my layout is correct??

**Comment by lmiller1990** [comment]
You cannot mutate props - this is against Vue's "one way" data flow. Why are you trying to do `this.value.username = ''`? The normal way you would update a prop is update it where-ever it is defined. Eg:

```js
const A = {
  template: `<B :username="username" @update-username="updateUsername" />`,
  data() {
    return { username: '' }
  },
  methods: {
    updateUsername(val) { this.username = val }
  }
}

const B = {
  props: ['username']
  template: '<div>{{ username }}</div>
  mounted() {
    this.$emit('updateUsername', 'new username')
  }
} 
```

So you are updated it in `A` where it is defined, not `B`. This is the idea of "one way data flow".

**Comment by alexey2baranov** [comment]
Thank you for replay. I understand your question. I don,t think it really metter to this issue.  Because if `this.value.username=newValue` works well inside vue and redraws html well and works well at all , then why it should not works the same way inside tests?

Your question is more about architecture data flow. My question is about testing components. I assume it is not the right place to discuss. So let me say just this is that kind of component, which don,t go one way data flow.

**Comment by dobromir-hristov** [comment]
It gets updated because you are mutating the value in the child, so the parent passing the prop rerenders. There is no parent in your case to pass the prop and to rerender, you just pass a simple object as a top level component. 

We can't explain this any better, what you are doing is wrong in the general case. The fact that it works is a quirk of JS, and we cant spend time fixing such niche cases. 

If you wish to test this, wrap that component in a new one, define a reactive property and pass it as a prop. Then mount that wrapper instead.

**Comment by lmiller1990** [comment]
The Vue team recommends against mutating a prop. Just because you can, doesn't mean you should :) 

Read it here: https://v3.vuejs.org/guide/component-props.html#passing-the-properties-of-an-object

![image](https://user-images.githubusercontent.com/19196536/90727665-fa7c9900-e306-11ea-8a7f-3465beb1983f.png)

**Comment by alexey2baranov** [comment]
@dobromir-hristov OK/ my fault that I write test which mutates prop inside parent. I didn't think it matters so much for you. I will rewrite it again and open new issue. Or I can post it in this issue hire?

**Comment by alexey2baranov** [comment]
@lmiller1990 as I understand this is written against `this.prop= newPropValue` inside child component, don't it? This way Vue warn you as written exactly because `every time parent component is updated all props in the child component refreshed with the latest value`.  

BUT! It will not warn and will not refresh last value when you do `this.prop.property= newValue`. Don't you agree? It will not because the this.prop isn/t changed this way. It doesn't matter if I do `this.prop.property= newValue` inside child component, or outside child component. It is just architectural pattern that say don't do it because it may do your life harder. I can rewrite my test and do `this.user.name=newName` outside child component if you need so, but the result of the test will not change.
