### ISSUE TITLE
Can I use vue-test-utils with jest and vue@2.1.0

### ISSUE THREAD

**Issue by WayneWang98** [vuejs/vue-test-utils#1652]
### Subject of the issue

**I hava some trouble when I used vue-test-utils with jest and vue@2.1.0 to test vue single component.**
**Error:TypeError: Cannot read property 'child' of undefined.**

### Steps to reproduce

Tell us how to reproduce this issue. Please provide a working and simplified example.
My package.json:
{
  "name": "vue-test-utils-jest-example",
  "description": "Example project using Jest + vue-test-utils together",
  "version": "1.0.0",
  "author": "",
  "private": true,
  "scripts": {
    "dev": "cross-env NODE_ENV=development webpack-dev-server --open --hot",
    "build": "cross-env NODE_ENV=production webpack --progress --hide-modules",
    "test": "jest"
  },
  "dependencies": {
    "vue": "2.1.0"
  },
  "devDependencies": {
    "@vue/test-utils": "^1.0.0-beta.25",
    "babel-core": "^6.26.0",
    "babel-jest": "^21.2.0",
    "babel-loader": "^7.1.2",
    "babel-preset-env": "^1.6.0",
    "cross-env": "^5.0.5",
    "css-loader": "^0.28.7",
    "file-loader": "^1.1.4",
    "jest": "^21.2.1",
    "jest-serializer-vue": "^0.2.0",
    "vue-jest": "^2.6.0",
    "vue-loader": "^13.0.5",
    "vue-server-renderer": "2.1.0",
    "vue-template-compiler": "2.1.0",
    "webpack": "^3.6.0",
    "webpack-dev-server": "^2.9.1"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "vue"
    ],
    "moduleNameMapper": {
      "^@/(.*)$": "<rootDir>/src/$1"
    },
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/babel-jest",
      ".*\\.(vue)$": "<rootDir>/node_modules/vue-jest"
    },
    "snapshotSerializers": [
      "<rootDir>/node_modules/jest-serializer-vue"
    ]
  }
}

List.spec.js:
import { shallowMount } from '@vue/test-utils'
import List from '@/components/List.vue'

describe('List.vue', () => {
  it('renders li for each item in props.items', () => {
    const items = ['1', '2']
    const wrapper = shallowMount(List, {
      propsData: { items }
    })
    expect(wrapper.findAll('li')).toHaveLength(items.length)
  })

  it('matches snapshot', () => {
    const items = ['item 1', 'item 2']
    const wrapper = shallowMount(List, {
      propsData: { items }
    })
    expect(wrapper.html()).toMatchSnapshot()
  })
})

I use vue-test-utils, and run test, It can`t work and throw an Error:

    TypeError: Cannot read property 'child' of undefined

      at createWrapper (node_modules/@vue/test-utils/dist/vue-test-utils.js:11200:32)
      at Object.<anonymous> (test/List.spec.js:7:47)
          at new Promise (<anonymous>)
      at process._tickCallback (internal/process/next_tick.js:68:7)

I consoled List, it show about this:
{ name: 'list',
        props: [ 'items' ],
        render: [Function: render],
        staticRenderFns: [] }

I think 'list' haven't be mounted with shallowMount.
My jest works well when testing js files, but can't work to test vue single component.I want to use vue-test-utils with vue@2.1.0 because my company project`'s vue version is 2.1.0, and it can't upgrade.

### Expected behaviour

What should happen?
I think the vue component should be mounted with shallowMount or mount, but it throwed an Error:
Cannot read property 'child' of undefined. 

### Actual behaviour

The vue component was imported, but didn't be mounted or generate a wrapper. It throwed an Error when I use mount() or shallowMount():
Cannot read property 'child' of undefined. 

### Possible Solution

I write another simple example project with vue@2.4.4 an vue-template-compiler@2.4.4, it worked well.Howerver, the project with vue@2.1.0 couldn't be upgrade because it is a company project and it will throw much warning or error if I upgrade vue.

**Comment by WayneWang98** [comment]
I use vue@2.18 and vue @2.06, both of then worked well, why vue@2.1.0 can't work?
I feel very puzzled about this.

**Comment by afontcu** [comment]
Hi,

Vue 2.1.0 is quite old (2016!), so it would be quite hard to debug any upcoming issue.

However, I see you're using vue-test-utils beta 25. Could you try and update to latest version ([1.0.4](https://github.com/vuejs/vue-test-utils/releases/tag/v1.0.4)) and see if you have better luck?

**Comment by lmiller1990** [comment]
Might be worth updating your version of Vue as well!

**Comment by lmiller1990** [comment]
While this might be a bug (will need a repo I can pull and run without figuring out config files), I don't have any intention of going back and fixing things for Vue 2.1 compat at this point, so I am going to close this one and focus on other issues.

The answer is you should be able to use VTU with Vue 2.x onwards, we have tests running in the CI with old Vue versions, so my feel is this is problem owing to config or some specific combination of libraries/test runner.

If anyone finds this and feels very strongly about Vue 2.1 support, feel free to make a PR.

**Comment by WayneWang98** [comment]
Thanks for your reply!
I think upgrading vue version is the best way to solve this problem.
I will try to upgrade it.
