### ISSUE TITLE
findComponent is missing from the documentation

### ISSUE THREAD

**Issue by philBrown** [vuejs/vue-test-utils#1654]
### Documentation Feedback

If you search for `findComponent`, it shows up as a result but the link goes nowhere.

![image](https://user-images.githubusercontent.com/164814/90574765-1b58c780-e1fd-11ea-83a0-10b3af654be8.png)

Scrolling down the page to the `find*` methods shows that it is indeed not present.

**Affected documentation page:** https://vue-test-utils.vuejs.org/api/wrapper/#findcomponent

**Comment by afontcu** [comment]
Hi! Just gave it a go and the search result seems to be working as expected. Maybe it was due to cache?

**Comment by AtofStryker** [comment]
Looks to be working for me as well. I am guessing a cache related issue as well? We did just recently update the `vuepress` server to `v1.x`

**Comment by afontcu** [comment]
Possibly! I'm gonna go ahead and close this, feel free to reopen if the issue persists :)
