### ISSUE TITLE
Bug: watcher with string handler not called

### ISSUE THREAD

**Issue by Alex-Sokolov** [vuejs/vue-test-utils#1668]
### Subject of the issue

Watcher with string handler not called

```
'model.first': {
  handler: 'resetApiValidationErrors'
},
```
```
'model.first': 'resetApiValidationErrors'
```

### Steps to reproduce

"@vue/test-utils": "1.0.4"
I try add new test to `test\specs\mounting-options\watch.spec.js`

```
it('must call watcher handlers', async () => {
    const TestComponent = {
      template: '<div>{{ model.first }}{{ model.second }}{{ model.third }}</div>',
      data() {
        return {
          model: {
            first: '',
            second: '',
            third: ''
          }
        }
      },
      watch: {
        'model.first': {
          handler() {
            this.resetApiValidationErrors()
          }
        },
        'model.second'() {
          this.resetApiValidationErrors()
        },
        'model.third': 'resetApiValidationErrors'
      },
      methods: {
        resetApiValidationErrors() {
          // do nothing
        }
      }
    }
    const wrapper = mountingMethod(TestComponent, {})

    wrapper.vm.resetApiValidationErrors = jest.fn()
    expect(wrapper.vm.resetApiValidationErrors).toHaveBeenCalledTimes(0)

    wrapper.vm.model.first = '123'
    await wrapper.vm.$nextTick()
    expect(wrapper.vm.resetApiValidationErrors).toHaveBeenCalledTimes(1)

    wrapper.vm.model.second = '456'
    await wrapper.vm.$nextTick()
    expect(wrapper.vm.resetApiValidationErrors).toHaveBeenCalledTimes(2)

    wrapper.vm.model.third = '789'
    await wrapper.vm.$nextTick()
    expect(wrapper.vm.resetApiValidationErrors).toHaveBeenCalledTimes(3)
  })
```

### Expected behaviour

Watcher handler called & no errors happened

### Actual behaviour

```
    Received number of calls: 2

      80 |     wrapper.vm.model.third = '789'
      81 |     await wrapper.vm.$nextTick()
    > 82 |     expect(wrapper.vm.resetApiValidationErrors).toHaveBeenCalledTimes(3)
```

**Comment by xanf** [comment]
@Alex-Sokolov this is not a bug. When you mount the component, "bound handler" is created from string declaration in watcher capturing original method (I believe this was one of the reasons why `setMethods` was deprecated - there is no **reliable** way to replace method in Vue component).

I've replaced your code with following and it is all green (code is dirty, I'm avoiding using deprecated `methods` option here):
```js
  const resetApiValidationErrorsMock = jest.fn();
  const wrapper = mountingMethod({
    ...TestComponent,
    methods: {
      ...TestComponent.methods,
      resetApiValidationErrors: resetApiValidationErrorsMock,
    }, {});

  expect(resetApiValidationErrorsMock).toHaveBeenCalledTimes(0);

  wrapper.vm.model.first = '123';
  await wrapper.vm.$nextTick();
  expect(resetApiValidationErrorsMock).toHaveBeenCalledTimes(1);

  wrapper.vm.model.second = '456';
  await wrapper.vm.$nextTick();
  expect(resetApiValidationErrorsMock).toHaveBeenCalledTimes(2);

  wrapper.vm.model.third = '789';
  await wrapper.vm.$nextTick();

  expect(resetApiValidationErrorsMock).toHaveBeenCalledTimes(3);
```

In general it is a bad practice to verify method calls - you should assert against external behavior even when using shallowMount

**Comment by Alex-Sokolov** [comment]
@xanf thanks for comment!

Now I understand why "magic not happened" and mocking method not work. Although it is a bit unclear at the moment and is not described in docs (maybe need just add some details about that). I agree that such assertions is a bad practice, but when upgrading vue-test-utils to last version you want to change as little as possible and not rewrite all test codebase at once 😄 

This moment seemed to me like a bug, so this issue with small example started. In real life, in these tests some logiс with conditional $emit and after rewriting to assertion for emitted events everything passed.
