### ISSUE TITLE
Missing docs for 'sync' option in mount methods (even if deprecated)

### ISSUE THREAD

**Issue by luckylooke** [vuejs/vue-test-utils#1680]
### Documentation Feedback

First of all I a m really glad of your work and sharing with community. ❤️ 

I have some test they affect each other, when they run one by one they works but together I have got errors as "TypeError: Cannot read property '$scopedSlots' of undefined", so I found solution by mounting with option "sync: false". I wanted to get know what that option exactly is, but did not found the answer in docs.

I came over this options several times already, some examples:
https://github.com/vuejs/vue-test-utils/issues/1605#issue-650505862
https://github.com/logaretm/vee-validate/issues/1996#issuecomment-568769426
etc..

So it seems it is quite widely used, but not documented.

Some of comments mentioned that it is deprecated options... even if it is true, it should be documented as it really does fix issues, so it is working and therefore it should have some docs written. It can be heavily marked as "derprecated" if it is so. But at least I could make better decision whether look for other solutions or rely on this option.

Thank you 🙏  

**Affected documentation page:** https://vue-test-utils.vuejs.org/api/options.html#mounting-options

**Comment by winniehell** [comment]
@luckylooke The documentation has been removed because the `sync` option no longer has any effect in recent versions of vue-test-utils (https://github.com/vuejs/vue-test-utils/issues/1137). Are you using the currently released version?

**Comment by lmiller1990** [comment]
Sync mode was deprecated quite a long time ago and that's why it's removed from the docs. `sync: false` is effectively the default now. 

I don't see any value in documenting something that is not only deprecated by removed from the code base entirely.

I don't really see any actionable item here, so I will close this.
