### ISSUE TITLE
Stub custom event not executing handler.

### ISSUE THREAD

**Issue by dodgyKnee73** [vuejs/vue-test-utils#1684]
### Subject of the issue

Handler not executed when stubbed component emits event

### Steps to reproduce

Vue component:

```vue
<template>
  <test-component @custom-event="handler"></test-component>
</template>

<script>
export default {
  name: "test-container",
  methods: {
    handler() {
      console.log("handler");
    }
  }
};
</script>

```
test spec:

```js
import { mount } from "@vue/test-utils";
import TestContainer from "@/components/Test";

describe("test", () => {
  it("handlesEvent", () => {
    const wrapper = mount(TestContainer, {
      stubs: ["test-component"]
    })
    const handler = jest.spyOn(wrapper.vm, 'handler')
    wrapper.find('test-component-stub').vm.$emit('custom-event', 1);
    expect(handler).toBeCalled();
  });
})

```
### Expected behaviour

The test should pass with the jest spy registering the called handler.  "handler" should be logged to the console.

### Actual behaviour

Test fails:

`expect(jest.fn()).toBeCalled()
`
    Expected number of calls: >= 1
    Received number of calls:    0

### Possible Solution

Ultimately I want to test that a vuex mutation is called by the component when the custom-event is triggered.

**Comment by afontcu** [comment]
Hi! I'm away from my laptop right now so I cannot give it a go, but I believe this should work:


```js
import { mount } from "@vue/test-utils";
import TestContainer from "@/components/Test";

describe("test", () => {
  it("handlesEvent", () => {
    // this changed to track the component method, not its instance.
    const handler = jest.spyOn(TestContainer.methods, 'handler')

    const wrapper = mount(TestContainer, {
      stubs: ['test-component']
    });

    // this emits the event from the parent wrapper' vm, not the children'
    wrapper.vm.$children[0].$emit('custom-event');

    expect(handler).toBeCalled();
  });
})
```

However, I'd suggest mounting the "real" component tree using `mount` and interact with it (clicking or typing or whatever) to trigger the method, so that your test will be closer to what user does, and thus it'll provide better confidence.

Hope it helps!

**Comment by lmiller1990** [comment]
^ should work (or some variation; have definitely seen this issue before.

If you want to update docs to have an example of this, that'd be fine. For now I will close this, I don't think this is a bug.
