### ISSUE TITLE
Throw errors when operating on destroyed wrapper

### ISSUE THREAD

**Issue by xanf** [vuejs/vue-test-utils#1685]
A bit related to #1342 

While it is obviously impossible to "destroy" something in JavaScript it could be great help to make wrappers throw error when operating on destroyed Vue instance. I suggest making `emitted` (and deprecated `emittedByOrder`) the only exceptions, cause I can see use cases, when we want to assert instance generated certain events during destroy process.

This will help a lot when introducing `enableAutoDestroy(beforeEach)` in big codebases to track such hard-to-debug errors
I'm ready to submit PR for this one if team feels this one like a good addition

**Comment by afontcu** [comment]
Hi! I understand why this would become useful when running `enableAutoDestroy`, feel free to submit the PR :)

**Comment by lmiller1990** [comment]
fixed in #1706
