### ISSUE TITLE
Writting test in a custom block in Single Page Component

### ISSUE THREAD

**Issue by dorianamouroux** [vuejs/vue-test-utils#169]
I like the Single Page Component because you can write everything tight to your component in only one page: the logic, view and presentation.

Why not write the tests of components in a `<test>` custom block? I guess the `vue-loader` API allows it, I haven't had the time to play with it yet.

**Comment by LinusBorg** [comment]
@eddyerburgh wrote a loader for that a couple of days ago: https://github.com/eddyerburgh/vue-test-loader

**Comment by eddyerburgh** [comment]
Great timing, as @LinusBorg said I just released a loader — https://github.com/eddyerburgh/vue-test-loader. You can check out the example page to see it in action — https://github.com/eddyerburgh/vue-test-loader-example
