### ISSUE TITLE
 Can provide a similar reactRender hook test library

### ISSUE THREAD

**Issue by kevlin-sean** [vuejs/vue-test-utils#1690]
Can provide a similar reactRender hook test library for vue？

like <https://github.com/testing-library/react-hooks-testing-library>

**Comment by lmiller1990** [comment]
I am very confused, what do you actually want? Can you please share an example of a test you want to write? Vue hooks (aka composables) are just regular functions; you should not need any special things to test them.

**Comment by kevlin-sean** [comment]
How to test in the lifecycle?
