### ISSUE TITLE
Issue testing provider/inject with Vue 3 composition API 

### ISSUE THREAD

**Issue by christopherchateau** [vuejs/vue-test-utils#1698]
I am using `provide` in my App component:

```
<script lang="ts">
import { defineComponent, ref, provide } from 'vue';

export default defineComponent({
    setup () {
        const keyState = ref('boop');

        provide('keyState', keyState);

        function setKeyState (keyAction: string) {
            keyState.value = keyAction;
        }

        return {
            keyState
        };
    }
});
</script>
```

Inside a grand-child component, I am injecting that value:

`const keyState = inject<any>('keyState');`

Test spec of the grand-child component:

```
import { shallowMount } from '@vue/test-utils';
import Modal from '@/components/Modal/index.vue';

describe('Modal', () => {
    let wrapper: any;

    beforeEach(() => {
        wrapper = shallowMount(Modal, {
            provide: {
                keyState: { value: 'up-pressed' }
            }
        });
    });

    afterEach(() => {
        wrapper.unmount();
    });

    it('should render', () => {
        expect(wrapper.exists()).toBe(true);
    });
});
```

adding `provide` when mounting the wrapper causes a typescript error (TS2769). removing `provide` or using @ts-ignore to suppress the typescript error produces the warning: `[Vue warn]: injection "keyState" not found.`

@lmiller1990 Is this a current bug that stops a provided value from being injected into a mounted test wrapper in jest?

thanks!

**Comment by christopherchateau** [comment]
I was able to get it working by adding a global provide to the wrapper:

```
wrapper = shallowMount(Modal, {
    global: {
        provide: {
            keyState: 'up-pressed'
        }
    }
});
```

**Comment by lmiller1990** [comment]
Right I did not realized you were using Vue 3. Great!

**Comment by vinayakkulkarni** [comment]
@christopherchateau : How are you testing Vue 3 when `@vue/test-utils` requires `vue-template-compiler` whereas Vue 3 uses `@vue/compiler-sfc` instead?

**Comment by pabloleone** [comment]
How do you test a component on Vue 2 using the composition API with inject/provide inside the setup method?

**Comment by lmiller1990** [comment]
Should be the same - make sure you install `CompositionAPI` on `localVue`. Here's a short article: https://lmiller1990.github.io/vue-testing-handbook/composition-api.html
