### ISSUE TITLE
setData with an empty object doesn't get set

### ISSUE THREAD

**Issue by Haroenv** [vuejs/vue-test-utils#1704]
### Subject of the issue

If you call `wrapper.setData({ someKey: {} })`, it doesn't set the `someKey` to `{}`

### Steps to reproduce

this test doesn't pass

```
const wrapper = mount({
  data() {
    return {
      someKey: { someValue: true },
    };
  },
  render(h) {
    return h('span');
  },
});

expect(wrapper.vm.$data).toEqual({ someKey: { someValue: true } });

wrapper.setData({ someKey: {} });

expect(wrapper.vm.$data).toEqual({ someKey: {} });
```

### Expected behaviour

This test passes

### Actual behaviour

The test doesn't pass, it still has the previous 

### Possible Solution

In here: https://github.com/vuejs/vue-test-utils/blob/dev/packages/test-utils/src/recursively-set-data.js I think it might make sense to see if the object has keys at all, if it doesn't have keys, you could set the value.

**Comment by Ivan-dev-RED** [comment]
Why this issue closed?? 
I have the same trouble and this solution is bullshit

**Comment by lmiller1990** [comment]
Does #1705 not fix? That was the intention: https://github.com/Haroenv/vue-test-utils/commit/cda6e4b42970c6b468b13f5d62de60bf28c5a553

If you want to fork this repo and add a minimal repro, we can take a look.
