### ISSUE TITLE
`mocks` only works for top component

### ISSUE THREAD

**Issue by blake-newman** [vuejs/vue-test-utils#1707]
> I never realized `mocks` was only for the component in question - I thought it would be available to all the children, too 🤔 

> It sounds like this should be the default behavior.

_Originally posted by @lmiller1990 in https://github.com/vuejs/vue-test-utils/pull/1701#issuecomment-701956498_

---

The mocks object is only set for the first component; not it's children. This behaviour means that properties such as `$route` / `$router` are not easily mockable via integration style testing. 

There is ways around this, by using `localVue` and creating a router instance and setting on the `mount` options.

**Comment by lmiller1990** [comment]
I was not able to reproduce this (or maybe I misunderstood?) eg, I could mock `$store.state` in a child component like this:

```
import { mount, config } from '@vue/test-utils'

const Foo = {
  template: `
    <div>
      Count: {{ $store.state.count }}
    </div>
  `
}

const App = {
  components: { Foo },
  template: `
    <div>
      <Foo /> 
    </div>
  `
}

const $store = {
  state: {
    count: 1
  }
}

test('with vuex', () => {
  const wrapper = mount(App, {
    mocks: {
      $store
    }
  })

  expect(wrapper.html()).toContain('Count: 1')
})
```

**Comment by lmiller1990** [comment]
Pls lmk if my repro is wrong - this seems fine to me.
