### ISSUE TITLE
not found page 

### ISSUE THREAD

**Issue by eladnm** [vuejs/vue-test-utils#1709]
i have the following code that works fine but i get an error 

 SyntaxError: Could not resolve the given string "/page-not-found" relative to the base URL "about:blank"
this is my vue router code:

```
{
    path: '*',
    redirect: './page-not-found',
},
    {
        path: '/page-not-found',
        name: 'PageNotFound',
        component: LazyComponents.PageNotFoundComponent,
        meta: {
            breadcrumb: 'Page Not Found',
        },
    },
```

**Comment by lmiller1990** [comment]
Hi - I am going to need a repository or *something* to go on, there is no way to triage this without one.

I am going to close this until some kind of minimal repo is provided.
