### ISSUE TITLE
finding components with `find` is deprecated and will be removed in the next major version. Use `findComponent` instead.

### ISSUE THREAD

**Issue by TinyWisp** [vuejs/vue-test-utils#1711]
When I was executing my unit tests, which used the wrapper.get() method, it outputed the following content:

![image](https://user-images.githubusercontent.com/15992102/95676557-67b6f700-0bf1-11eb-839e-a470ac372174.png)

**Comment by lmiller1990** [comment]
There is `wrapper.getComponent` in V2 (for Vue.js 3). For this test, you could just use `findComponent` (same result).

We could back port `getComponent` to this library, too. That would be fairly easy to do. Would you like to make a PR?

**Comment by loiscodes** [comment]
I can take this one.

**Comment by TinyWisp** [comment]
Thanks! OK, I made a PR.

https://github.com/vuejs/vue-test-utils/pull/1714
