### ISSUE TITLE
Vuetify: Mount does not bind propsData in v-text-field

### ISSUE THREAD

**Issue by ghost** [vuejs/vue-test-utils#1713]
![Screenshot from 2020-10-13 19-18-09](https://user-images.githubusercontent.com/66945662/95873456-61f41980-0d89-11eb-8e47-44d1cec88fea.png) I am sending object in propsData and get that in Mount to update data which is bind with v-text-field but the Mounted component not showing this propsData in v-text-field. I wanted to have a Mounted component with pre-filled these v-text-fields

**Comment by lmiller1990** [comment]
Can you please a reproduction or at least your component and test? A screenshot is very useful here.

I will re-open this when you have shared a reproduction or code.
