### ISSUE TITLE
Triggering events

### ISSUE THREAD

**Issue by unematiii** [vuejs/vue-test-utils#1715]
Today I stumbled upon st I wasn't quite sure how to handle. I was trying to test event listener attached somewhere above the components tree by triggering `click` on some element that does not have any listeners attached to it at all. Dummy example:

Component:
```js
{
  methods: {
    doSomething() {
      console.log('doSomething called!');
    },
    triggerDoSomething(event) {
      if (event.target !== event.currentTarget) {
        return;
      }
      event.preventDefault();

      this.doSomething();
    },
  },
  render(h) {
    return (
      <div class="wrapper" onmousedown={this.triggerDoSomething}>
        <div class="element">Some element</div>
      </div>
    );
  }
}
```

Component.spec.js:
```js
it('prevents `doSomething` from being called ', async () => {
  const wrapper = mount(Component);
  const element = wrapper.find('.element');
    
  await element.trigger('click');

  // TODO Assert that `doSomething` was not called
});
```

But `triggerDoSomething` doesn't get called at all... (In browser if you click `.wrapper` `doSomething` gets called, and if you click `.element` it doesn't)

I ended up testing the `triggerDoSomething` method directly:

Component.spec.js:
```js
it('prevents `doSomething` from being called ', () => {
  const wrapper = mount(Component);

  const dummyEvent = new Event('click');
  wrapper.vm.triggerDoSomething({ ...dummyEvent, target: null });

  // TODO Assert that `doSomething` was not called
});
```

Is there a better way of doing this, preferably by triggering an event on a wrapper returned by test utils methods?

**Comment by lmiller1990** [comment]
I wonder if events don't bubble in jsdom by default. Can you try `trigger('click', { bubbles: true })`?

I have not tested this but this is my gut feeling; it's a jsdom vs real dom difference (maybe). Seems a few things related to this in jsdom based on a quick google.

Either way, any reason not to trigger on the `.wrapper` (and does the test work if you do?)

**Comment by JeromeDeLeon** [comment]
We encountered it and used `trigger('mousedown')` instead

**Comment by JeromeDeLeon** [comment]
I also wonder though why triggering a `click` event doesn't trigger other associated mouse events.

**Comment by lmiller1990** [comment]
Most likely because a real browser does not just dispatch a `click` event when you click, but all the other associated events, too. jsdom does not, I guess. I am not sure this is a bug in VTU or not, need to investigate more.

Is this bug in jsdom only or when running tests with test-utils in a browser, too @unematiii? That would help narrow it down.

**Comment by unematiii** [comment]
Thanks for everyone's input on this. Apparently, when using `trigger('mousedown')` on `.element`, it does bubble up and `doSomething` will not be called (and it gets called if triggered on `.wrapper`).

Doing `trigger('click', { bubbles: true })` will make the test fail with `TypeError: Cannot set property bubbles of [object Event] which has only a getter`.

The real scenario behind all of this was to test input field inside bunch of wrapper elements (there's some reasoning behind that too...). I need to trigger input focus (`doSomething` method in this example) when clicked on certain elements by attaching `onmousedown={this.triggerDoSomething}` on them, while clicking on others, input will not be focused (if already focused, it would lose focus) - the `if (event.target !== event.currentTarget) { return; }` part (equivalent to `self` modifier).

So going further with calling `trigger('mousedown')` on `.element`, the input doesn't `blur` during testing, while it does in browser... Using `click` instead of `mousedown` for that purpose doesn't seem to work, as I wasn't able to prevent input from losing focus if already focused and user clicks repeatedly on elements that trigger focus (see [this](https://codepen.io/mudassir0909/pen/eIHqB)).

@lmiller1990 I need to test the `running tests with test-utils in a browser` part yet.

**Comment by JeromeDeLeon** [comment]
yeah you should definitely call it inside `.wrapper` or else it will not call the `triggerDoSomething`

**Comment by lmiller1990** [comment]
I would say the next steps:

1. run this test in a browser with VTU
2. if it passes there, it's a jsdom bug/limitation, nothing more to be done
3. if it's a VTU bug, we can investigate more.

For now I am marking this as "needs more info". The info is if this is a environment specific bug or not.

**Comment by mokywu** [comment]
I am having the same issue, but  when I await it again ,it worked. you can add " await wrapper.vm.$nextTick();" after " await element.trigger('click');" .

**Comment by unematiii** [comment]
@mokywu `nextTick()` wasn't really useful in my case, as I was trying to simulate `click` and that simply doesn't trigger `mousedown`...

**Comment by unematiii** [comment]
@lmiller1990 Will try that, and get back if I have more info.

**Comment by unematiii** [comment]
@lmiller1990 I ended up creating a small test [repo](https://github.com/unematiii/test-vtu-mouse-events) , and the `trigger('click')` use-case was failing both with browser and jsdom. 

But, I soon came to conclusion, that in both cases it boils down to calling `dispatchEvent` on a node, which even in browser settings will not trigger either of `mousedown` and/or `mouseup`. So unless we are willing to simulate what usually happens when user interacts with mouse, we can might as well close this issue...

**Comment by lmiller1990** [comment]
Yeah, I figured the browser does a lot whole more than what jsdom/Test Utils does when we simulate an event. If you do figure out what exactly needs to happen for this to work in Test Utils, I'd love to know. Thanks for your work on this.
