### ISSUE TITLE
I don't know how mocking methods in @vue/composition-api

### ISSUE THREAD

**Issue by lizy0329** [vuejs/vue-test-utils#1717]
### Subject of the issue

I don't know how mocking methods in @vue/composition-api

eg.
```
// Component.vue
export default defineComponent({
    setup() {
        const modalState = ref(false);

        const openModal = async () => {
            modalState.value = true;
        };

        return {
            modalState,
            openModal,
        };
    },
});
```

```
// test.js
const wrapper  = mount(Component);
const mockMethodStub =  jest.fn();
wrapper.setMethods({openModal: mockMethodStub }) // error
```

and there have not methods options when checking wrapper.vm

### Steps to reproduce

Tell us how to reproduce this issue. Please provide a working and simplified example.

### Expected behaviour
await fireEvent.click(Button)
expect(mockMethodStub).toHaveBeenCall() // pass
### Actual behaviour

wrapper.setMethods({openModal: mockMethodStub }) // error

### Possible Solution

What are the alternative solutions? Please describe what else you have considered?

**Comment by lmiller1990** [comment]
You can't mock methods in the composition API. There is no way to access the methods defined in `setup`, so this is not something we can support.

If you need to test it, consider making an assertion against the DOM - eg, the modal should be rendered, etc.

**Comment by lizy0329** [comment]
Thank you for your answer! It will support @vue/composition-api or vue3 in VTU2? What time to releases?

**Comment by lmiller1990** [comment]
What do you mean?

You can use Test Utils with the @vue/composition-api right now, that will work fine. [A simple example is here](https://lmiller1990.github.io/vue-testing-handbook/composition-api.html).

Everything should work as expected in Vue 3 too. If you want to use Vue Test Utils with Vue 3 you need v2.x (eg, `yarn add @vue/test-utils@next`. This repository is for v1 - that works with Vue 2. You can [find the code for v2 (which works with Vue 3) here](https://github.com/vuejs/vue-test-utils-next).

Does that help?

**Comment by lizy0329** [comment]
That’s what I want to know. I can't find VTU@next information in VTU1 document, when I create a library use @vue/composition-api

**Comment by lmiller1990** [comment]
Here is the V2 docs: https://vue-test-utils.vuejs.org/v2/guide/introduction.html 

It's still a WIP.

**Comment by andreasvirkus** [comment]
"that will work fine" is a bit misleading, as the composition API limits testing quite a bit (especially mocking out scenarios with `setData` become impossible now, right?) 🤔

**Comment by lmiller1990** [comment]
The more I learn and improve as a develop, the less utility I'm finding for things like `setData`. Just set the data like your user does - click a button, or whatever they'd do.

`setData` is not going anywhere - just my personal experience and opinion. The vast majority of my tests nowdays are someting like

1. `mount`
2. `trigger` something
3. asset using `find` or `get` or even `wrapper.html`
