### ISSUE TITLE
Adding support for testing components using external templates (src imports)

### ISSUE THREAD

**Issue by Williams94** [vuejs/vue-test-utils#172]
Hi there, 

I asked on the discord vue-testing chat about the possibility of testing components that use external templates e.g. ```<template src="./component.html"></template>```. As I have tried to run unit tests on components where the html template is used like that, but no html gets rendered unless I put the html directly in the ```<template></template>``` tags in the ```.vue``` file. I can access the props that get rendered like this ```wrapper.vm.$props```.

And according to Edd Yerburgh, ```vue-test-utils``` hasn't taken into account these types of components yet. That is why I am opening an issue here to see if I can get support for it in this library.

I had tried using Karma & Jasmine (without ```vue-test-utils```) and gotten the same results (no html gets rendered). So now I am using ```vue-test-utils``` with Jest, which got me to the same point as Karma, but with much less config and setup. So I would prefer to continue using ```vue-test-utils``` with Jest, but if anyone has any other suggestions as to why this might not be working please let me know!

Thanks very much in advance!

**Comment by eddyerburgh** [comment]
So this isn't part of vue-test-utils, but I kept it here because a lot of people have requested it.

This feature has now been added to vue-jest 1.2.0 (without source maps).

It should also work when using mocha-webpack

**Comment by PerpetualWar** [comment]
what about Karma + Jasmine setup ?

**Comment by eddyerburgh** [comment]
If you're using webpack to compile, then components with external templates should be compiled correctly
