### ISSUE TITLE
No access to DOM API?

### ISSUE THREAD

**Issue by Mikilll94** [vuejs/vue-test-utils#1720]
### Subject of the issue

DOM API has many useful methods, like i.e. `closest()` https://developer.mozilla.org/en-US/docs/Web/API/Element/closest

Is there any possibility to use DOM API methods in `vue-test-utils`? I have tried to use `closest()` method like this:

```javascript
wrapper.vm.$el.closest()
```

but I got an error that that `$el` is undefined.

### Expected behaviour

There should be possibility to use DOM API methods in `vue-test-utils`.

### Actual behaviour

There is no be possibility to use DOM API methods in `vue-test-utils`.

**Comment by afontcu** [comment]
Hi,

`wrapper.element` ([docs](https://vue-test-utils.vuejs.org/api/wrapper/#properties)) will return the root DOM node of the wrapper.

Hope it helps! Closing this up for now :)

**Comment by Mikilll94** [comment]
@afontcu 
Thanks. That is exactly what I was looking for 😁
