### ISSUE TITLE
Current docs are out of date

### ISSUE THREAD

**Issue by mayashavin** [vuejs/vue-test-utils#1721]
### Documentation Feedback
1. Installed v1.1.0 and found out that `wrapper.contains` is going to be deprecated, and there are new `wrapper.findComponent` but nothing is mentioned on the official documentation page.
2. Documentation page should indicate the version of the package the docs are written for. 
3. Example for `throw` is not correct
4. Missing examples for spying, etc.

**Comment by afontcu** [comment]
Hi Maya! 👋 😄 


> Installed v1.1.0 and found out that wrapper.contains is going to be deprecated and there are new wrapper.findComponent but nothing is mentioned on the official documentation page.

We do have a warning on the API documentation for `contains`: (https://vue-test-utils.vuejs.org/api/wrapper/#contains). Did you land on some other page without the warning? I'd happily replicate the warning where needed :)

Same thing with findComponent: https://vue-test-utils.vuejs.org/api/wrapper/#findcomponent

> Documentation page should indicate the version of the package the docs are written for

This repo supports Vue 2.X, so this is the scope for both the code and the docs. We're under Vue 3 support development in a separate repo: https://github.com/vuejs/vue-test-utils-next/

> Example for throw is not correct

Could you point me to the wrong example? I'd like to fix that very much 😃 


> Missing examples for spying, etc

What kind of examples do you feel we're missing? AFAICT there's nothing inherently different in VTU when using spies or using them in any other test environment, but any suggestion would be appreciated.

Thanks for your input! 🚀

**Comment by mayashavin** [comment]
@afontcu 👋  😄 
 Weird, yesterday all the pages I opened for VTU don't look like what it shows today. I navigated straight from Google Search (or from Vue2.x documentation), and it doesn't have the warning, all the new syntax.
Now everything is fine. Maybe I was re-directed to an old site cache? :)

> Could you point me to the wrong example? I'd like to fix that very much 😃

This throw catch example
```
expect(() => wrapper.get('.does-not-exist'))
  .to.throw()
  .with.property(
    'message',
    'Unable to find .does-not-exist within: <div>the actual DOM here...</div>'
  )
```
doesn't seem to work for me. Using `toThrow()` works though.

> What kind of examples do you feel we're missing? AFAICT there's nothing inherently different in VTU when using spies or using them in any other test environment, but any suggestion would be appreciated.

About the examples, I would love to have some basic examples for `spyOn`, `mock`, etc. It's fine to go to Jest and get a hold about it, but it would be nicer if I don't have to go to Jest just to find out.

**Comment by afontcu** [comment]
👋  glad to hear it was just a caching issue! 🙌 

> doesn't seem to work for me. Using toThrow() works though

This is possibly because `.to.throw()` is based on [chai](https://www.chaijs.com/api/bdd/#method_throw), while `toThrow()` is a jest assertion.

> About the examples, I would love to have some basic examples for spyOn, mock, etc. It's fine to go to Jest and get a hold about it, but it would be nicer if I don't have to go to Jest just to find out.

That's true, and it is something we've been actively working on for [the new docs](https://github.com/vuejs/vue-test-utils-next-docs/). We plan on porting the best parts to VTU 1.x docs when possible, so this might end up here as well :)

Thanks for your thoughts!

**Comment by mayashavin** [comment]
So I will close this issue then :)
