### ISSUE TITLE
Cannot find module 'vue' from 'vue-test-utils.js'

### ISSUE THREAD

**Issue by ikhidebright** [vuejs/vue-test-utils#1722]
### Subject of the issue
Error:  Cannot find module 'vue' from 'vue-test-utils.js'

          at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
          at Object.<anonymous> (node_modules/@vue/test-utils/dist/vue-test-utils.js:5:11)

Im trying to run jest test but it fails every time

### .babelrc file
```
{
  "presets": [
    ["@babel/preset-env", {
      "modules": false,
      "targets": {
        "node": "10",
        "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
      }
    }],
    "jest"
  ],
  "plugins": ["@babel/plugin-transform-runtime"],
  "env": {
    "test": {
      "presets": ["@babel/preset-env"]
    }
  }
}
```

### jest.config.js file 

```
module.exports = {
  preset: '@vue/cli-plugin-unit-jest',
  "moduleFileExtensions": [
      "js",
      "json",
      // tell Jest to handle `*.vue` files
      "vue"
    ],
  "transform": {
      // process `*.vue` files with `vue-jest`
      ".*\\.(vue)$": "vue-jest",
      ".*\\.(js)$": "babel-jest"
  },
  "collectCoverage": true,
  "collectCoverageFrom": ["**/*.{js,vue}", "!**/node_modules/**"],
  "transformIgnorePatterns": ["<rootDir>/node_modules/"],
  'verbose': true,
}
```

versions

```
"vue": "^2.5.16",
"@vue/cli-plugin-unit-jest": "^4.5.8",
"@vue/test-utils": "^1.1.0",
"@babel/core": "^7.12.3",
"@babel/plugin-transform-runtime": "^7.12.1",
"@babel/preset-env": "^7.12.1",
"@vue/babel-preset-app": "^4.5.8",
```

### Expected behaviour
should run $ jest

### Actual behaviour
It breaks and cannot find vue module in vue-test-utils

**Comment by lmiller1990** [comment]
This sounds like a config issue. Did you make this project with the Vue CLI?

**Comment by mayashavin** [comment]
@lmiller1990 I actually got the same problem today. This is my configuration
```
"@vue/babel-preset-app": "^4.3.1",
    "@vue/cli-plugin-babel": "^4.3.1",
    "@vue/cli-plugin-eslint": "^4.3.1",
    "@vue/cli-plugin-unit-jest": "^4.3.0",
    "@vue/cli-service": "^4.3.1",
    "@vue/eslint-config-prettier": "^6.0.0",
    "@vue/test-utils": "^1.1.0",
    "vue-template-compiler": "^2.6.11",
"vue": "^2.6.x"
```

**Comment by lmiller1990** [comment]
Hi Maya, can you post something I can pull down and reproduce the issue. Listing the packages alone is not enough to diagnose the issue. Or, list the steps (eg, 1. create new Vue CLI project with X config, run yarn install blah, run yarn test:unit).

Could be a bug in your config, Vue CLI plugin, Test Utils, or something else.

**Comment by mayashavin** [comment]
@lmiller1990 Sorry I should have commented earlier.

It's pretty weird as the project we work on run fine up until several days ago. And we didn't change any of the configuration. All we did is to remove the dependencies of `vuepress` and `vuepress` itself from our project. Once we put `vuepress` back, everything works fine 🤷🏽‍♀️ .

To make it short, it doesn't look to me like a bug only for Vue Test Utils. It happens also for Storybook 6x in a similar manner. I will dig in a bit later to find the real culprit but it's not relevant to Test Utils :). Sorry for bothering you.

Anyway, here is the project if you want to try it out: https://github.com/vuestorefront/storefront-ui

**Comment by lmiller1990** [comment]
If adding Vuepress is causing a problem it is likely a transitive dependency problem (one of the dependencies resolved for Vuepress is messing with Test Utils). This makes very little sense because this library basically has no dependencies. 

You could diff your `yarn.lock` before/after adding Vuepress to find out what modules are changing exactly, that might give you a clue. I am kind of curious, I will take a look at the storefront-ui project and see if I can figure it out.

**Comment by Ravali359** [comment]
cannot find module 'vue' from '../node_modules/@vue/test-utils/dist/vue-test-utils.js'

    Require stack:
      C:/Users/rbyri/digitalocean/node_modules/@vue/test-utils/dist/vue-test-utils.js
      src/_tests_/app.test.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (../node_modules/@vue/test-utils/dist/vue-test-utils.js:5:11)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                  
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        15.317 s
Ran all test suites.
npm ERR! Test failed.  See above for more details.

**Comment by Ravali359** [comment]
when i am running jest testcases evertytime it fails

**Comment by lmiller1990** [comment]
You will need to post a repository with a reproduction, I cannot help without more info.

**Comment by LeonardoRick** [comment]
Would love to know what was the problem!
