### ISSUE TITLE
attachToDocument - outdated deprecation warning

### ISSUE THREAD

**Issue by Mikilll94** [vuejs/vue-test-utils#1725]
### Documentation Feedback

![Screenshot 2020-10-25 at 12 33 14](https://user-images.githubusercontent.com/17653648/97105840-43155180-16be-11eb-82d4-874ea43a8492.png)

I think this deprecation warning is outdated. After discussion in https://github.com/vuejs/vue-test-utils/issues/1578, the recommended way to replace `attachToDocument: true` should be `attachTo: document.body`.

**Affected documentation page:**

https://vue-test-utils.vuejs.org/api/options.html#attachtodocument

**Comment by afontcu** [comment]
Sounds about right! Fancy to open up a PR? 🙌

**Comment by raphaeloliveira-hotmart** [comment]
A question regarding the new way: Do we still need to call `wrapper.destroy()` when using the "special handling" of `attachTo: document.body`? I guess so but still, just confirming :-)
