### ISSUE TITLE
Unable to stub router-view and router-link

### ISSUE THREAD

**Issue by EgidioCaprino** [vuejs/vue-test-utils#1729]
### Subject of the issue

When stubbing `<router-view>` and `<router-link>` in tests this warning is reported:

```
    console.warn node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:40
      [Vue warn]: Failed to resolve component: router-link 
        at <Anonymous ref="VTU_COMPONENT" > 
        at <VTUROOT>
    console.warn node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:40
      [Vue warn]: Failed to resolve component: router-view 
        at <Anonymous ref="VTU_COMPONENT" > 
        at <VTUROOT>
```

### Steps to reproduce

```
git clone https://github.com/EgidioCaprino/vue-router-link-test-bug.git && cd vue-router-link-test-bug && npm i && npm run test:unit
```
[This](https://github.com/EgidioCaprino/vue-router-link-test-bug/blob/master/tests/unit/App.spec.ts) is the test where the warning is printed.

### Expected behaviour

It should stub `<router-view>` and `<router-link>` and print no warning.

### Actual behaviour

`<router-view>` and `<router-link>` are not stubbed and a warning is reported.

### Possible Solution

Live with the warning.

**Comment by lmiller1990** [comment]
It cannot stub what it does not know about. You will need to install Vue Router so it knows what to stub out.

Alternatively you could stub them globally yourself (something like this, did not test yet)

```js
const localVue = createLocalVue()
localVue.component('RouterView', {
  render: h => h('div')
})

mount(Foo, {
  localVue
})
```

Or something like that.

There is a few options. Let me know if you can't get any working. For now I will close this, I don't think this is an issue - you cannot stub out a component that has not been registered at some point prior.
