### ISSUE TITLE
Textarea set to blank doesn't execute bound watcher

### ISSUE THREAD

**Issue by jandroalvarez** [vuejs/vue-test-utils#1732]
In a test, I'm trying to set the value of a `textarea` to blank.
The textarea is bound to the model using `v-model.lazy`. with a `data()` property which is linked to a watcher.
If I change the textarea value using `setValue()` the watcher is executed and the test works fine.
However, if I do `setValue('')` the watcher is never executed.

**Code:**
```javascript

<template>
   <textarea id="labeling-text" v-model.lazy="myProperty"></textarea>
</template>

<script>
watch: {
    myProperty() {
      this.$emit('myEvent', this.myProperty)
    }
  }
</script>

// Test
 it('Raises an event when textarea changes', done => {
    const wrapper = mount(MyComponent)
    wrapper.find('#labeling-text').setValue('')
    wrapper.vm.$nextTick(() => {
      expect(wrapper.emitted()['myEvent']).toBeTruthy()
      done()
    })
  })
})
```

**Expected behavior:**
The watcher raised the event.

**Current behavior**
The watcher is not executed so the event is not raied.

**Comment by LinusBorg** [comment]
Seems to be expected as the `.lazy` modifier only updates `myProperty` on the `change` event, but setting the value of the textarea like that is like typing in it and therefore triggers an `input` event (which the non-lazy `v-model` would listen for).

Try calling `blur()` on the element after setting the value, that should trigger the change event.

**Comment by jandroalvarez** [comment]
Hi @LinusBorg 

Thank you for your quick reply. I had already tried you proposal and it doesn't work. Same result. The watched property is not executed.
I've even tried to remove `.lazy` modifier but the result is the same.

**Comment by LinusBorg** [comment]
I think this is just jest succing at simulating the change event.

Try https://vue-test-utils.vuejs.org/api/wrapper/#trigger

**Comment by jandroalvarez** [comment]
I didn't clarify it in my previous post. 
I tried using `trigger('blur')` and it didn't work out.

**Comment by lmiller1990** [comment]
We actually cover this case explicitly by checking for `lazy` and doing `change`: https://github.com/vuejs/vue-test-utils/blob/d7916ce82062dd0c920c8a0aebaaaa527e3b98ff/packages/test-utils/src/wrapper.js#L838

**Comment by lmiller1990** [comment]
Did you forget to declare `myProperty` in your real code, or just your repro?

Anyway, this is working fine for me (including `setValue('')`). Does this help?

Component: 

```html
<template>
  <div>
    <textarea id="labeling-text" v-model.lazy="myProperty"></textarea>
  </div>
</template>

<script>
export default {
  data() {
    return {
      myProperty: 'ok'
    }
  },
  watch: {
    myProperty() {
      this.$emit('myEvent', this.myProperty)
    }
  }
}
</script>
```

Test:

```js
import { mount } from '@vue/test-utils'
import HelloWorld from '@/components/HelloWorld.vue'

it('Raises an event when textarea changes', async () => {
  const wrapper = mount(HelloWorld)
  const $ta = wrapper.find('#labeling-text')
  await $ta.setValue('OK!!!')
  console.log(wrapper.emitted('myEvent')) // => [ [ 'OK!!!' ] ]
})
```

**Comment by jandroalvarez** [comment]
I just forgot to include the property in the repro. Sorry!
What version of vuejs are you using right now?

**Comment by lmiller1990** [comment]
I just created a new project using the Vue CLI and chose 2.x when I was trying to reproduce this issue. Should be using the latest version of 2.x.

If you are using Vue 3, you will need v2 of this library (which you can get with `yarn add @vue/test-utils@next`, or creating a new project with the Vue CLI).

Are you still having this problem? [The code above](https://github.com/vuejs/vue-test-utils/issues/1732#issuecomment-731205266) was working for me. Maybe you can post a repository with the bug so I can reproduce it?

**Comment by jandroalvarez** [comment]
@lmiller1990 I've tried again and I've found the reason why it works in your example.

Your initializing the `myProperty` to 'OK!' in the component creation. Then, in your test, you call `setValue('')`. That scenario works perfectly (in my code, too).

However, my problem is that I initialize `myProperty` through a `prop` provided to the component. I forgot to include that code in the example.  In this case, `setValue('')` doesn't work if the component is initialized through the prop.

Here the full code:
```
<textarea id="labeling-text" autofocus v-model.lazy="myProperty"></textarea>

export default {
  name: 'MyComponent',
  props: {
    label: {
      type: String,
      required: true
    },
  },
  data() {
    return {
      myProperty: ''
    }
  }
  ,
  watch: {
    myProperty() {
      this.$emit('myEvent', this.myProperty)
    }
  },
  created() {
    this.myProperty = this.label
  }
}

 it('Raises an event when labeling text is deleted', done => {
    const wrapper = mount(MyComponent, {
    propsData: { label: 'test' }
  })
    wrapper.find('#labeling-text').setValue('')
    wrapper.vm.$nextTick(() => {
      expect(wrapper.emitted().myEvent).toBeTruthy()
      expect(wrapper.emitted().myEvent[0]).toEqual([''])
      done()
    })
  })
```
