### ISSUE TITLE
Store is not an option for either mounting or shallow mounting a component

### ISSUE THREAD

**Issue by ihorbond** [vuejs/vue-test-utils#1733]
### Documentation Feedback

Examples on this [page](https://vue-test-utils.vuejs.org/guides/using-with-vuex.html) suggest that in order to test store we should mount it the following way 

```
  it('dispatches "actionInput" when input event value is "input"', () => {
    const wrapper = shallowMount(Actions, { store, localVue })
    const input = wrapper.find('input')
    input.element.value = 'input'
    input.trigger('input')
    expect(actions.actionInput).toHaveBeenCalled()
  })
``` 
e.g passing it as store:store to either mount or shallowMount methods but if we look at the mounting options for these methods [here](https://vue-test-utils.vuejs.org/api/options.html) they do not list store. They seem to suggest to use mocks object to mock $store. Which one is correct ? 

**Affected documentation page:** Insert a link to the affected page
https://vue-test-utils.vuejs.org/guides/using-with-vuex.html

**Comment by lmiller1990** [comment]
You can pass it like that - anything you would pass to `new Vue({ ... })` can also be passed to the mounting options.

Neither is correct or incorrect - you can pick which one you like. Some people like to mock the store, others use a real one. I use a real one when I can, if it is too complex I mock it.
