### ISSUE TITLE
require.context is not a function

### ISSUE THREAD

**Issue by dinglittle** [vuejs/vue-test-utils#1735]
Like title , hope help , what I need do ?

I use that
```
<component :is="type[config.type]" :config="config"/>

import components from './components/index.js'
```

index.js
```
const files = require.context('./', false, /\.vue$/) ? require.context('./', false, /\.vue$/) : {}
const modules = {}
files.keys().forEach(filename => {
  const c = files(filename).default
  modules[c.name] = c
})

export default modules

```

**Comment by afontcu** [comment]
Hi! 👋 

it looks like this is not related to Vue Test Utils, but to Jest and its ability to use webpack's `require.context` ([source](https://github.com/facebook/jest/issues/7183)). There's nothing to do from our side other than suggesting to mock `require.context` and assert on that. [Other google answers](https://stackoverflow.com/questions/38332094/how-can-i-mock-webpacks-require-context-in-jest) may help, too!

**Comment by dinglittle** [comment]
> Hi! 👋
> 
> it looks like this is not related to Vue Test Utils, but to Jest and its ability to use webpack's `require.context` ([source](https://github.com/facebook/jest/issues/7183)). There's nothing to do from our side other than suggesting to mock `require.context` and assert on that. [Other google answers](https://stackoverflow.com/questions/38332094/how-can-i-mock-webpacks-require-context-in-jest) may help, too!

Yeah , It's ok , Thanks !
