### ISSUE TITLE
wrapper.find() doesn't return the stub, but returns wrapper

### ISSUE THREAD

**Issue by gregveres** [vuejs/vue-test-utils#1736]
### Subject of the issue

I am trying to build a password component that wraps Vuetify's v-text-field component. My password component looks like this (slightly simplified)
```JS
<script lang="ts">
import { defineComponent, ref, computed } from '@vue/composition-api';
import { useVModelWrapper } from './useVModelWrapper';

export default defineComponent({
  name: 'PasswordField',
  props: {
    value: {
      type: String,
      required: true
    },
    label: {
      type: String,
      required: true
    },
    match: {
      type: String,
      required: false
    }
  }, // this is needed to ensure that vue-test-utils.mount takes this as a properly typed component
  setup(props, { emit }) {
    const input = useVModelWrapper(props, emit, 'value');

    const show = ref(false);
    return { show, input };
  }
});
</script>

<template>
  <v-text-field
    v-model="input"
    :append-icon="show ? '$eye' : '$eyeSlash'"
    @click:append="show = !show"
    :label="label"
    :type="show ? 'text' : 'password'"
  />
</template>
```

and what I am trying to do is test that when the user clicks on the appendIcon of the v-text-field, that my component reacts by switching the type from password to type and changes the appendicon from $eye to $eyeSlash. 

So after much searching on through the docs and internet questions, I came up with this test:
```JS
  beforeAll(() => {
    mountFunction = (options?: MountOptions<Instance>) => {
      return shallowMount(PasswordField, { mocks: { $vuetify: { rtl: false } }, ...options });
    };
  });
  it('should go to text mode when appendicon clicked', async () => {
    // Arrange
    const password = '';
    const wrapper = mountFunction({
      propsData: { value: password, label: 'password' }
    });
    const textField = wrapper.find('v-text-field-stub');

    // Act
    textField.vm.$emit('click:append');
    // Assert
    expect(textField.attributes('appendicon')).toBe('$eye');
    expect(textField.attributes('type')).toBe('text');
  });
```
### Steps to reproduce
run the above test and expect textField to be a wrapper around the v-text-field-stub, not a wrapper around the PasswordField component.

### Expected behaviour

I am expecting that when I call
`    const textField = wrapper.find('v-text-field-stub');`
that textField.vm is now a pointer to the stub vm so that I can call $emit on it, which then calls my @click:append handler on the PasswordField component and I can then test the results by looking at the type and appendicon attributes of the stub.

### Actual behaviour

Nothing. The handler isn't called. And as a result, the type and appendicon's stay the same. 
If I look at textField.vm in the debugger, I see that it seems to be the vm of PasswordField. I am assuming this is the case because textField.vm contains value, label, match and show. I wouldn't have expected those values to be on the vm for the stub. 

after the emit, I can see that textField.emitted contains an array of 1, so the emit is happening, it just seems to be happening on the wrong component. 

### Possible Solution

I wish I know how to work around this. I don't. I have tried putting a data-test attribute on v-text-field to find by that instead but I still received the same wrapper as doing the find on the v-text-field-stub.
I have tried changing the click handler event from @click:append to @click but it had the same result.
I have tried the inline handler as well as moving the handler out of line to a standalone method. 

I have made the test method async and added various forms of awaiting such as:
await textField.vm.$nextTick();
await Vue.$nextTick();
await flushPromises();

I know back in 2017 / 2018 there was talk about why would you want to do something like this, it seems you are testing Vue's emit code, but that is not at all the case. I am trying to test expected behaviour of the PasswordField - namely, if the user clicks on the appendicon, then it toggles the visibility of the password. I should be able to assume that Vuetify fully tested v-text-field, so as long as I define the @click:append handler correctly, then my component is good.

**Comment by lmiller1990** [comment]
I have no way to run this this - I don't know what `useVModelWrapper` - is it possible to provide a reproduction I can clone? I could try and write the test you are talking about (I would use `mount` for this - I use `mount` for everything, shallow and stubs introduce more problems than they solve imo...)

I think part of the problem is `shallowMount` here. Introducing the stubs seems to be making this complex. It might be easier to use `mount` and then find the DOM node to trigger the event.

Regarding your actual question, `find` will always find a wrapper - even if it is one that wrapped a stubbed component.

**Comment by gregveres** [comment]
@lmiller1990 Yea, sorry I should have come back here. I ended up converting the shallow mount to a mount and then went searching in Vuetify's v-text-field implementation to find the right element to do the emit from. That worked fine. 

I will go ahead and close this since I, unfortunately, can't make the time right now to setup a reproduction case for you. Sorry.

**Comment by lmiller1990** [comment]
No problem... glad you found a solution. Lmk if you have any more problems. Vuetify is a tough one, I want to provide better tooling for testing it.

**Comment by gregveres** [comment]
Yes it is. I am constantly finding myself spending way more time testing vuetify based components than I would have expected. I don't think I have been able to sit down and crank out a unit test for a component without spending copious amounts of time "figuring" something out that didn't work the way I expected it.

I have mostly given up unit testing my model based components. I use typescript so I have extracted the model logic out to a typescript class that is easy to test and tried to leave as little logic in the component as possible and then dont test the component. I really need to spend some time to get cypress running to cover testing these types of components. 

But it is  my library of reusable components that I feel I have to test. In this case it was a password text field. 

Anway, I agree with you testing vuetify with vue-test-utils is tough. Thanks for your help though.

**Comment by lmiller1990** [comment]
I've had pretty good success with `mount`. I also do what you described - complex logic in isolated, pure functions, and unit test it. Keep components simple.

Cypress is really excellent, I'm enjoying it. Another alternative is @testing-library/vue - it's an opinionated wrapper on top of test-utils, which is pretty low level, it might be useful to you.
