### ISSUE TITLE
findComponent functions return undefined

### ISSUE THREAD

**Issue by 392241868** [vuejs/vue-test-utils#1740]
### Subject of the issue

when I user wrapper.findComponent({ref: 'input'}) in two it functions, the second wrapper.findComponent({ref: 'input'}) return undefined

**Comment by afontcu** [comment]
Hi! Would you mind adding an example of the component and the failing test?

**Comment by 392241868** [comment]
![image](https://user-images.githubusercontent.com/7981126/100202695-a18f5300-2f3c-11eb-90ba-319d11d85949.png)
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by 392241868** [comment]
![Uploading image.png…]()

**Comment by 392241868** [comment]
![image](https://user-images.githubusercontent.com/7981126/100202923-e87d4880-2f3c-11eb-955c-9c5bf7ac4759.png)

**Comment by 392241868** [comment]
![image](https://user-images.githubusercontent.com/7981126/100203058-1498c980-2f3d-11eb-808a-bf207e3575c2.png)
![image](https://user-images.githubusercontent.com/7981126/100203101-237f7c00-2f3d-11eb-9a44-8add7b36f491.png)


> Hi! Would you mind adding an example of the component and the failing test?

**Comment by 392241868** [comment]
> Hi! Would you mind adding an example of the component and the failing test?

I've solved it, mainly because the component's if condition is false, thanks!
