### ISSUE TITLE
don't support <script setup>

### ISSUE THREAD

**Issue by m-yangyu** [vuejs/vue-test-utils#1743]
### Feature Description

The next version don't support <script setup>

### Problem

we use <script setup> in vue3.0 and use @vue/test-utils to do unit test, but the next version don't support <script setup>

```javascript
// this is my test example
describe('button', () => {
  test('Vue component has div tag', () => {
    const wrapper = mount(Button);
    expect(wrapper.find('div').exists()).toBeTruthy();
  });
});

// this is my Button example
<template>
  <div>
    <div>{{ buttonObject.text }}</div>
  </div>
</template>
<script setup="props" lang="ts">
import { reactive } from 'vue';

const buttonObject = reactive({
  text: '1',
  number: 2,
});
</script>
```

and my terminal show 

![image](https://user-images.githubusercontent.com/26132427/100572532-aa06d580-3310-11eb-9280-3e4b149619db.png)

### Expected behaviour

support <script setup>

no error

**Comment by lmiller1990** [comment]
Actually the next version does support `<script setup>` - in fact, I did a release today to fix this exact problem: https://github.com/vuejs/vue-test-utils-next/releases/tag/v2.0.0-beta.12. 

You want the latest of both vue-jest and test utils. `yarn add vue@next @vue/test-utils@next`.

Also you might like to check the latest [RFC](https://github.com/vuejs/rfcs/pull/227) for `<script setup>`. It has *changed* in Vue 3.0.3. You no longer access props using `<script setup props="props">`. It looks like you now get props using `defineProps`.

Prior to today's release it supported `<script setup>` using the older API - so your test should have been working just fine. Can you please upload a repository if you are still having problems after you upgrade to the latest Test Utils (beta 12) Vue Jest (5.0.0 alpha 7) and Vue 3 (3.0.3).

Please try this out and see how it goes. You will need to update your components to use the latest RFC style.

If you are still having problems I will reopen and investigate, but I think it should be okay once you update the dependencies.

**Comment by m-yangyu** [comment]
> Actually the next version does support `<script setup>` - in fact, I did a release today to fix this exact problem: https://github.com/vuejs/vue-test-utils-next/releases/tag/v2.0.0-beta.12.
> 
> You want the latest of both vue-jest and test utils. `yarn add vue@next @vue/test-utils@next`.
> 
> Also you might like to check the latest [RFC](https://github.com/vuejs/rfcs/pull/227) for `<script setup>`. It has _changed_ in Vue 3.0.3. You no longer access props using `<script setup props="props">`. It looks like you now get props using `defineProps`.
> 
> Prior to today's release it supported `<script setup>` using the older API - so your test should have been working just fine. Can you please upload a repository if you are still having problems after you upgrade to the latest Test Utils (beta 12) Vue Jest (5.0.0 alpha 7) and Vue 3 (3.0.3).
> 
> Please try this out and see how it goes. You will need to update your components to use the latest RFC style.
> 
> If you are still having problems I will reopen and investigate, but I think it should be okay once you update the dependencies.

thank you for your help
