### ISSUE TITLE
Why is name() deprecated and what is the alternative?

### ISSUE THREAD

**Issue by tim-kilian** [vuejs/vue-test-utils#1745]
### Documentation Feedback

In my test I am using name to ensure it matched the filename, why is this deprecated and what is the alternative for it? I do not see any reason nor alternative description in the docs.

**Affected documentation page:** https://vue-test-utils.vuejs.org/api/wrapper/name.html

**Comment by afontcu** [comment]
Hi!

https://vue-test-utils.vuejs.org/upgrading-to-v1/#name

**Comment by tim-kilian** [comment]
Can we link this somehow to https://vue-test-utils.vuejs.org/api/wrapper/name.html ? When you google this problem you only get the api reference.

**Comment by afontcu** [comment]
> Can we link this somehow to https://vue-test-utils.vuejs.org/api/wrapper/name.html ? When you google this problem you only get the api reference.

Sure, good idea! Fancy to open a PR? 😃

**Comment by travis5491811** [comment]
@afontcu I opened PR that updates doc.
