### ISSUE TITLE
TypeScript inference does not work by default in tests

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs/vue-test-utils#1749]
### Subject of the issue
When doing a clean vu-cli install with Vue3/TS/Jest options, vue-test-utils only exposes its wrapper as `VueWrapper<any>` which makes any mounted component have no types.

### Steps to reproduce
Do a clean vue-cli install with Vue3/TS/Jest as options.
Open the `example.spec.ts` and hover over the `wrapper.text()` method, you'll see:
![image](https://user-images.githubusercontent.com/1668207/101919894-1c8d7600-3b99-11eb-9fd9-076b8e3af2ed.png)

### Expected behaviour
Types to be correctly inferred from the Vue component and exposed on the wrapper

### Actual behaviour
It returns a `VueWrapper<any>` which loses all typings.

**Comment by lmiller1990** [comment]
You cannot get typings with SFCs, there is currently no way to extract the types from an SFC (`vue` file), it is just using a shim (`vue-shims.d.ts`).

This is not something we are able to solve in VTU (as discussed in vue-test-utils-next repo).
