### ISSUE TITLE
Error: [vue-test-utils]: isEmpty cannot be called on 0 items

### ISSUE THREAD

**Issue by aphofstede** [vuejs/vue-test-utils#175]
As described in the docs: https://vue-test-utils.vuejs.org/en/api/wrapper-array/isEmpty.html

E.g. with a component that doesn't have any `<p>`'s, test the following:
```
    it.only ('shows p conditionally', () => {
        let pArray = wrapper.findAll('p')
        expect(pArray.isEmpty()).toBe(true)
    });
```

Results in:
> Error: [vue-test-utils]: isEmpty cannot be called on 0 items

Kind of the whole point, right? I think `isEmpty()` should return `true` there.

package.json relevant snippet:
```
  "devDependencies": {
    "expect": "^21.2.1",
    "flush-promises": "^1.0.0",
    "jsdom": "^11.3.0",
    "jsdom-global": "^3.0.2",
    "laravel-mix": "^1.6.1",
    "mocha": "^4.0.1",
    "mocha-webpack": "^1.0.1",
    "moxios": "^0.4.0",
    "sinon": "^4.1.2",
    "url-search-params": "^0.10.0",
    "vue-test-utils": "^1.0.0-beta.5",
...
  },
```

**Comment by eddyerburgh** [comment]
When you call isEmpty on a WrapperArray it calls isEmpty on each Wrapper. The error thrown is because the WrapperArray is empty.

I can see how this is confusing, but it is mentioned in the docs. If you want to check a WrapperArray is empty, use the `length` property

**Comment by aphofstede** [comment]
Gotcha. I guess I assumed it would fall back to that when no results were found. 
Isn't the working of it more like `every()` on [Map/Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every)? (things might be clearer if the same naming convention was followed?)

**Comment by eddyerburgh** [comment]
Yes, the working of it is like `Array.every`

How would you suggest changing the naming convention? I appreciate that there's a bit of magic involved in the wrapper array methods

**Comment by aphofstede** [comment]
Semantics of course; and since the working is not exactly the same (as `Array.every`) it might be more confusing to some; but what I meant was: `expect(wrapper.every('p').isEmpty()).toBe(true)` reads slightly more natural to my eye in this particular case.

**Comment by mokkabonna** [comment]
I assumed the same for `.find('.does.not.exists')`, but found the method `.exists()` that return false for empty wrapper. And returns arraywrapper.length > 0 for array wrapper. 

This method is however not documented.

**Comment by eddyerburgh** [comment]
I'm closing this issue. If people have suggestions to improve the API, I'm happy to reopen.
