### ISSUE TITLE
vue-test-utils/next Cannot find module '@vue/compiler-dom' in nuxt 

### ISSUE THREAD

**Issue by huntz20** [vuejs/vue-test-utils#1753]
### Subject of the issue
im using nuxt to the project first i using test utils version  `1.1.2` 
it work fine for testing vuex and unit tetsing, then i try to test 

```
 <template>
  <button
    class="text-white uppercase text-md mx-auto py-2 w-full rounded-lg"
    :class="{
      'bg-green-600 hover:bg-green-700': color === 'success',
      'bg-blue-600 hover:bg-blue-700': color === 'info',
      'bg-yellow-600 hover:bg-yellow-700': color === 'warning',
      'bg-red-600 hover:bg-red-700': color === 'error',
    }"
    :type="buttonType"
    @click="onClick"
  >
    <svg
      class="inline animate-spin -ml-1 mr-3 h-5 w-5 text-white"
      :class="isLoading ? 'visible' : 'invisible'"
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
    >
      <circle
        class="opacity-25"
        cx="12"
        cy="12"
        r="10"
        stroke="currentColor"
        stroke-width="4"
      />
      <path
        class="opacity-75"
        fill="currentColor"
        d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
      />
    </svg>
    {{ title }}
  </button>
</template>

<script>
export default {
  props: {
    color: {
      type: String,
      default: () => ''
    },
    title: {
      type: String,
      default: () => ''
    },
    isLoading: {
      type: Boolean,
      default: () => false
    },
    buttonType: {
      type: String,
      default: () => 'button'
    }
  },
  setup (props, { emit }) {
    const onClick = () => {
      emit('ButtonClicked')
    }

    return {
      onClick
    }
  }
}
</script>
```

with this test 

```
  const factory = (propsData) => {
    const wrapper = mount(Button, {
      propsData
    })
    const button = wrapper.find('button')

    return { wrapper, button }
  }

 it('should emmit onClick event', () => {
    const { button } = factory()
    button.trigger('click')
    expect(button.emitted()).toHaveProperty('click')
  })
```

it failed and  return this instead 

>  [Vue warn]: Invalid handler for event "click": got undefined

so i decide to use @vue/utils '2.0.0-beta-x'

and it return the error 

### Steps to reproduce

jest

### Expected behaviour

it should make do test with provide case 

### Actual behaviour

 Test suite failed to run

    Cannot find module '@vue/compiler-dom' from 'node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js'

    Require stack:
      node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js
      test/store/auth.spec.js

       1 | import Vuex from 'vuex'
     2 | import { createLocalVue } from '@vue/test-utils'
        | ^
      3 | import compositionApi from '@/plugins/composition-api'
      4 | const successJson = require('../fixture/auth/login-success.json')
      5 | const failedJson = require('../fixture/auth/login-failed.json')

**Comment by lmiller1990** [comment]
Test Utils v2 is for Vue 3, so it won't work with Vue 2 (and Nuxt with Vue 2).

Are you using Vue 2? It looks like you also need the [Composition API Plugin](https://github.com/vuejs/composition-api). You can install it on createLocalVue. Here is a simple guide: https://lmiller1990.github.io/vue-testing-handbook/composition-api.html#the-composition-api. You can either install the composition API in `<script>`, or you can do

```js
import {createLocalVue } from '@vue/test-utils'
import CompAPI from '@vue/composition-api'

const localVue = createLocalVue()
localVue.use(CompAPI)

mount(Foo, { 
  localVue
})
```

If that still won't work I can reopen.

**Comment by jordanmosongo** [comment]
I had a similar problem
Cannot find module '@vue/compiler-dom' from 'node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js'

Require stack:
  node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js
  
 Dependencies  were mismatching during installation of vue-test-utils. I was using vue 2. The best way to test your vue components as recommended in docs, is to use Vue Test Utils with Jest and to proceed installation through Vue Cli

These are instructions :
 1. npm install -g @vue/cli (if not installed !)
 2.vue add unit-jest
 3. npm install --save-dev @vue/test-utils

https://v1.test-utils.vuejs.org/installation/#semantic-versioning

**Comment by jordanmosongo** [comment]
The easiest way is to select jest as test runner during your project initialization. It will install all required dependencies to write tests and configure them for you . Do not skip this phase to avoid unexpected behavior

**Comment by cawa-93** [comment]
I Faced with this too, 
Acording to [Installation section in docs](https://test-utils.vuejs.org/installation/) all you need is install `@vue/test-utils`
```
npm install --save-dev @vue/test-utils
```
I tried [play with it in RunKit](https://runkit.com/cawa-93/tried-to-play-with-vue-test-utils-but-error-cannot-find-module-vue-compiler-dom), but got error:
```
Cannot find module '@vue/compiler-dom'
```
