### ISSUE TITLE
When testing a mixin props are not passed

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [vuejs/vue-test-utils#1758]
### Subject of the issue

When testing a mixin using a fake component with this mixin attached i'm getting the error `Missing required prop: "indexRequest"`
I've tried to do this with another type of property as wel. So not just functions are failing

### Steps to reproduce

```
const fakeRequest = jest.fn();
    
const Component = {
  template: '<div></div>',
};

const wrapper = mount(Component, {
  localVue,
  propsData: {
    indexRequest: fakeRequest, //this prop is required for the Paginator mixin
  },
  mixins: [Paginator],
});
```

### Expected behaviour
No errors, indexRequest is attached to `propsData` so it should exist

### Actual behaviour

`Missing required prop: "indexRequest"` is thrown.

**Comment by afontcu** [comment]
If I'm not mistaken `mixins` should live in the component definition:

```js
const fakeRequest = jest.fn();
    
const Component = {
  template: '<div></div>',
  mixins: [Paginator],
};

const wrapper = mount(Component, {
  localVue,
  propsData: {
    indexRequest: fakeRequest,
  },
});
```

**Comment by ricardovanlaarhoven** [comment]
This works! thanks!

Perhaps this should be somewhere in the documentation
