### ISSUE TITLE
setCompued does not work correctly for mapGetters 

### ISSUE THREAD

**Issue by eddyerburgh** [vuejs/vue-test-utils#176]
```js
computed: {
    ...mapGetters([
      'isTeamAdmin'
    ]),

    placeholder() {
      return this.isTeamAdmin ? 'Leader' : 'inboxMember'
    }
  }
```

```js
test.only('placeholder computed is Leader if isTeamAdmin is true', () => {
    wrapper.setComputed({ isTeamAdmin: true });
    expect(wrapper.vm.placeholder).toContain('Leader');
  });
```

**Comment by eddyerburgh** [comment]
@lmiller1990 that would be great if you could investigate 😀

**Comment by lmiller1990** [comment]
Can confirm it does not work. Will look into tomorrow.
``` js
import { shallow } from 'vue-test-utils'
import mapGetters from './mapGetters'

test('it works', () => {
  const wrapper = shallow(mapGetters)

  wrapper.setComputed({ isTeamAdmin: true })
  expect(wrapper.vm.placeholder).toEqual('Leader')
})
```
    
TypeError: Cannot read property 'isTeamAdmin' of undefined

**Comment by lmiller1990** [comment]
Actually, of course the above fails. I would need to pass the setComputed in the shallow options.

I think there is actually no bug. Can you link the other issue? 

The below is a working example using `mapGetters`.

``` js
<template>
  <div>
    {{ placeholder }}
  </div>
</template>

<script>
  import { mapGetters } from 'vuex'
  export default {
    name: 'mapGetters',

    computed: {
      ...mapGetters([
        'isTeamAdmin'
      ]),

      placeholder () {
        return this.isTeamAdmin ? 'Leader' : 'inboxMember'
      }
    }
  }
</script>
```

``` js
import Vue from 'vue'
import Vuex from 'vuex'
import { shallow } from 'vue-test-utils'

import mapGetters from './mapGetters'

Vue.use(Vuex)

test('it works', () => {
  let store = new Vuex.Store({
    getters: {
      isTeamAdmin: () => true
    }
  })

  const wrapper = shallow(mapGetters, {
    store
  })

  expect(wrapper.vm.placeholder).toEqual('Leader') 
})
```

**Comment by wtho** [comment]
@lmiller1990 just trying to understand what you meant.

> If you do return wrapper.setComputed({ isTeamAdmin: false }) it passes

Do you run the `expect` before the `return`? Otherwise it won't be executed at all, and no expectation / assertion means no possible fail.

I might just have misunderstood you though, please clarify.

**Comment by wtho** [comment]
I think I located the [origin of the error in Vuex](https://github.com/vuejs/vuex/blob/b64766bdec963a63ac537280dc42b5e6175e51c0/src/helpers.js#L51), `this.$store` being undefined here.

This might a result of `this.$options.store` not being installed on the `$options` object, when the [Vuex init hook](https://github.com/vuejs/vuex/blob/b64766bdec963a63ac537280dc42b5e6175e51c0/src/mixin.js#L22) gets executed on `beforeCreate`, and then `this.$store` not being available to the component when calling the getter first time.

I do not understand enough about how vue-test-utils' vuex mocking works normally to go further right now.

**Comment by rayoplateado** [comment]
Hi all!
Any news on this? I'm facing the same problem.

Thank you, guys.

**Comment by lmiller1990** [comment]
@rayoplateado  can you make your test async and use something like flush promises? If you post the code you want to test I can help you in the right direction.

**Comment by eddyerburgh** [comment]
This will be fixed in beta.9 😀
