### ISSUE TITLE
Can't use findComponent with v-slot

### ISSUE THREAD

**Issue by patrykgulas** [vuejs/vue-test-utils#1766]
### Subject of the issue

I'm using **Form** component with content in the slot. There is its simplified structure (assume that imports are correct):

**Form.vue**
```vue
<template>
  <div>
    Form
    <slot :username="'John'" />
  </div>
</template>
```

**LoginForm.vue**
```vue
<template>
  <Form>
    <template>
      <FormError :show="true" />
    </template>
  </Form>
</template>
```

**LoginForm.spec.ts**
```typescript
describe('LoginForm', () => {
  test('shows error', () => {
    const wrapper = shallowMount(LoginForm, { localVue })

    expect(wrapper.findComponent(FormError).props('show')).toBeTruthy()
  })
})
```

### Steps to reproduce

Above example is working fine but when I change slot in **LoginForm.vue** to:

```vue
<template>
  <Form>
    <template v-slot="{ username }">
      <FormError :show="!!username" />
    </template>
  </Form>
</template>
```

I'm getting an error `[vue-test-utils]: find did not return Component, cannot call props() on empty Wrapper`.

It looks like adding v-slot to the template is making impossible to find component.

### Expected behaviour

It is possible to find component with using slot props.

### Actual behaviour

Cannot find component with v-slot.

I will be grateful for any kind of explaining this behaviour and providing correct solution :)

**Comment by afontcu** [comment]
Hi! Can't check on my computer, but I'd check (using `wrapper.html()`) what's being rendered. Since you're using `shallowMount` child components get stubbed, so you might see that `<formerror-stub>` is actually being rendered instead of `FormError`.

Let me know if that helps!

**Comment by lmiller1990** [comment]
Yep, @afontcu is right - `shallowMount` will stub out all the components, so there is nothing to find (well, you can find the stub, which should have the prop passed to it, I think?). Basically, I think `<Form>` is stubbed out, and along with it, all of it's children.

You could just use `mount`, that will solve your problems.

**Comment by patrykgulas** [comment]
@afontcu @lmiller1990 thank you for a reply! I tried using `mount` instead of `shallowMount` and it does not change the error. I was also mounting `FormError` in `localVue` which I missed in the example, so correct `LoginForm.spec.ts` should be:
```
const localVue = createLocalVue()

localVue.component('FormError', FormError)

describe('LoginForm', () => {
  test('shows error', () => {
    const wrapper = shallowMount(LoginForm, { localVue })

    expect(wrapper.findComponent(FormError).props('show')).toBeTruthy()
  })
})
```

The problem only occurs when I use `v-slot` in `LoginForm.vue` and that's strange for me.
I also checked what `wrapper.html()` return with `v-slot` and without.

Without `v-slot`:
```
<form>
  <formerror-stub show="true">ERROR</formerror-stub>
</form>
```

With `v-slot` used:
```
<form></form>
```

**Comment by lmiller1990** [comment]
Hm, any chance you can post a minimal repository we can run? In the meantime, there is this example here in our test suite: https://github.com/vuejs/vue-test-utils/blob/c4133d6a78cd0ad7efafdfadb4f1ae28e31079b4/test/specs/shallow-mount.spec.js#L143 seems similar to what you have, maybe that can help you debug.

**Comment by dwojtyca** [comment]
Guys, any updates on this one? I'm currently struggling with same issue, I want to use snapshot testing from `jest` and seems that it renders everything correctly instead of any template that has slot-scope attribute, e.g. `<template slot-scope="foo">`.  

Looks like `wrapper.debug()` from @testing-library/vue also doesn't render those templates.

**Comment by lmiller1990** [comment]
Can you share some code (ideally repository, or a test + component) I can run to reproduce the problem?

**Comment by lmiller1990** [comment]
Can someone share some code that reproduces the problem? I don't mean a snippet, I mean something that I can run. I copy pasted the code from OP into this repository but it's passing as far as I can tell. Here's the branch: https://github.com/vuejs/vue-test-utils/pull/new/1766

Note: using `mount` here. I don't think this will work with `shallowMount`, since we stub `<form>` so the slots are not rendered.

**Comment by dwojtyca** [comment]
@lmiller1990 sure, here you go - https://github.com/dwojtyca/vue-missing-slot-scope 

Basically, if I remove `slot-scope="anything"` from WorkflowsTable template everything works fine 

Edit: changing from shallowMount to mount doesn't seem to change anything

**Comment by dwojtyca** [comment]
@lmiller1990 any updates on this one?

**Comment by lmiller1990** [comment]
Sorry not yet, I can look at this on the weekend.

**Comment by lmiller1990** [comment]
Sry, I'm pretty caught up in many other projects now (mainly Vue Jest and VTU next...) not sure I can get to this in the immediate future. Are you interesting in trying to fix this? I could point you in the right direction.

**Comment by lou-bi** [comment]
I encountered a similar problem trying to check the presence of a component inside a `nuxt-link`.

For anyone having this issue, using `find` with an attribute (or any css selector i suppose) did the job for me.

**Comment by migfus** [comment]
I have the same issue as well, it seems findComponent() does not have .props only on shallowMount()

**Comment by alextana92** [comment]
I'm aware this has been closed, but is there a solution to this?

**Comment by lmiller1990** [comment]
Not sure. Finding a shallow mounted component seems like it'll lead to a fairly brittle and not very useful test anyway - I wonder if you can use `mount`, or perhaps describe the component + test case you'd like to write - perhaps someone can offer an alternative recommendation.

**Comment by alextana92** [comment]
@lmiller1990 thanks, my issue was actually related to slots in the end and not a VTU issue, using `mount` instead of `shallowMount` solved the problem for another file I was working on so all good in the end!

Thanks for double checking!
