### ISSUE TITLE
wrapper.find() deprecation clarification

### ISSUE THREAD

**Issue by hewIngram** [vuejs/vue-test-utils#1769]
Hi all, I was confused by this given the deprecation warnings and wanted to make sure the docs are clear.

As I understand it (mostly from digging through the issues here especially https://github.com/vuejs/vue-test-utils/issues/1498 and https://github.com/vuejs/vue-test-utils/issues/1594) `find` and `findAll` are sticking around and we're adding `findComponent` and findAllComponents` for the specific case where we're finding by component.

If that's the case should we clarify the deprecation warning here to highlight that find is staying? Multiple members of my team read this as "find is being removed and replaced by findComponent".

<img width="814" alt="Screenshot 2021-01-12 at 17 01 11" src="https://user-images.githubusercontent.com/17004905/104346933-e294f400-54f7-11eb-8b7a-68dde94afe6b.png">

**Affected documentation page:** https://vue-test-utils.vuejs.org/api/wrapper/#find

Thanks! Happy to make a tiny PR clarifying

**Comment by afontcu** [comment]
Hi! Thank you for opening up the issue.

The sentence states that `find` is only deprecated when trying to search for a Component, but I agree it could be more explicit. Happy to review a PR with a clarification 😃

**Comment by hewIngram** [comment]
You're totally right the docs are definitely not wrong I just think it could be slightly clearer: https://github.com/vuejs/vue-test-utils/pull/1770

Thanks @afontcu
