### ISSUE TITLE
Part of the installation steps are not needed if you use @vue/cli-plugin-unit-jest

### ISSUE THREAD

**Issue by The4thLaw** [vuejs/vue-test-utils#1776]
### Documentation Feedback

The installation guide suggests using `@vue/cli-plugin-unit-jest` to run Jest tests. However, it goes on to list steps that are covered by that plugin (at least as of v4.5.0), such as :
 - Installing dependences like `vue-jest`, `@babel/core`, `babel-jest`... which are transitive dependencies of `@vue/cli-plugin-unit-jest`. I come from the Maven world so I'm not sure what the practice is in npm but I would tend not to redeclare those dependencies.
 - Setting up the `moduleFileExtensions`, `moduleNameMapper` and `transform` options, which are already set up by using `preset: '@vue/cli-plugin-unit-jest'`. That option is part of the default configuration after a call to `vue add unit-jest`, so it works out of the box.

My suggestion would be to have a section containing the instructions for manual setup and one for the instruction which are applicable in all cases (like the _Code Coverage_ section).

**Affected documentation page:** https://vue-test-utils.vuejs.org/installation/#using-vue-test-utils-with-jest-recommended

**Comment by afontcu** [comment]
Hi! Yeah, we should clearly state if you use the vue-cli plugin there's no need to configure anything else 👍 

Fancy to set up a PR fixing it? 😄

**Comment by The4thLaw** [comment]
Sure, I'll find time to submit something :)
