### ISSUE TITLE
[Vue warn]: Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by UsmanJavedAttari** [vuejs/vue-test-utils#1779]
### Subject of the issue
"[Vue warn]: Failed to mount component: template or render function not defined", when importing components without `.vue` extension.

### Steps to reproduce
I am using TypeScript and made up a project with `Vue Cli 4`. Being a TypeScript fan, I don't like importing files with `.vue`, there are some reason for that, but let me get to the point. Vue by default doesn't allow to import files without `.vue` extension, so I am using [this fix](https://github.com/vuejs/vue-cli/issues/4936#issuecomment-567127166). I have `vue.config.js` with following content:
```
module.exports = {
    chainWebpack: config => {
        config.resolve.extensions
            .clear()
            .add('.vue')
            .add('.tsx')
            .add('.ts')
            .add('.mjs')
            .add('.js')
            .add('.jsx')
            .add('.json')
            .add('.wasm');
    }
};
```

This pretty much allow to import components without `.vue` extension. If you comment out the `chainWebpack` function, it will warn you as
> [Vue warn]: Failed to mount component: template or render function not defined.

I have no issues, when I run the project, but I just setup the `vue-test-utils` using `Vue Cli 4`, and tried my best to get through the above error, but it keep saying "Failed to mount ...".
Can anyone solve this weird issue? Here is the code repo [link](https://github.com/UsmanJavedAttari/vue-jest)

### Expected behaviour

It should run perfectly fine without give that weird error. What I think is the webpack configuration (from `vue.config.js`) is not working when I am mounting the component in Test file.

### Actual behaviour

It gives "Failed to mount ...".

**Comment by UsmanJavedAttari** [comment]
So, after several attempts I solved it.
Just noticed the `moduleFileExtensions: ['ts', 'js', 'json', 'vue'],` in `jest.config.js` and changed to `moduleFileExtensions: ['vue', 'ts', 'js', 'json'],`, taken `vue` to the top.
Hope it will help someone.

**Comment by MSkred** [comment]
Hi, I works with : 
```
"nuxt": "^2.15.3"
"jest": "^27.5.1",
"@vue/test-utils": "^1.3.0",
"vue-jest": "^3.0.7"
```


jest.config.js
```
module.exports = {
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
    '^~/(.*)$': '<rootDir>/$1',
    '^vue$': 'vue/dist/vue.common.js',
  },
  moduleFileExtensions: ['vue', 'js', 'json'],
  transform: {
    '^.+\\.js$': '<rootDir>/node_modules/babel-jest',
    '.*\\.(vue)$': '<rootDir>/node_modules/vue-jest',
  },
  collectCoverage: true,
  collectCoverageFrom: [
    '<rootDir>/components/**/*.vue',
    '<rootDir>/pages/**/*.vue',
  ],
  testEnvironment: 'jsdom',
}
```

lgc-button.spec.js
```
import { shallowMount } from '@vue/test-utils'
import LgcButton from 'letsgoponents'


test('LgcButton.vue Test', () => {
  const wrapper = shallowMount(LgcButton)
})
```

But when I'm running `test` I've this 
```
 ~/Documents/LetsGoCity/PROJECT/lgc-pwa   develop ●  npm run test

> lgc-pwa@1.1.0 test
> jest

  console.error
    [Vue warn]: Failed to mount component: template or render function not defined.
    
    found in
    
    ---> <Anonymous>
           <Root>

      at warn (node_modules/vue/dist/vue.common.dev.js:630:15)
      at mountComponent (node_modules/vue/dist/vue.common.dev.js:4048:9)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.common.dev.js:9084:10)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.common.dev.js:11989:16)
      at init (node_modules/vue/dist/vue.common.dev.js:3140:13)
      at createComponent (node_modules/vue/dist/vue.common.dev.js:6013:9)
      at createElm (node_modules/vue/dist/vue.common.dev.js:5960:9)

 PASS  test/lgc-button.spec.js
  LgcButton
    ✓ test (37 ms)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        3.25 s
Ran all test suites.
```

**Comment by ch3njust1n** [comment]
I'm getting this issue.

Jest config in `package.json`:
```
"jest": {
    "moduleNameMapper": {
      "^@/(.*)$": "<rootDir>/$1",
      "^~/(.*)$": "<rootDir>/$1",
      "^vue$": "vue/dist/vue.common.js"
    },
    "testEnvironment": "jsdom",
    "moduleFileExtensions": [
      "vue",
      "js",
      "json"
    ],
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/babel-jest",
      ".*\\.(vue)$": "<rootDir>/node_modules/vue-jest"
    },
    "collectCoverage": true,
    "collectCoverageFrom": [
      "<rootDir>/src/components/**/*.vue"
    ]
  }

```
