### ISSUE TITLE
Transition Group Stub is not documented

### ISSUE THREAD

**Issue by Xochi** [vuejs/vue-test-utils#1780]
### Documentation Feedback

I can't find any documentation about the TransitionGroup and TransitionGroupStub

**Comment by 599316527** [comment]
`Transition(Group)Stub` has been removed in [1.0.0-beta.30](https://github.com/vuejs/vue-test-utils/releases/tag/v1.0.0-beta.30).

[v1.0.0-beta.29...v1.0.0-beta.30](https://github.com/vuejs/vue-test-utils/compare/v1.0.0-beta.29...v1.0.0-beta.30#diff-e8c5f3f9e8d9290062db25510107917683a1f62b77b262fede4a0c3e9dfc76c3)

**Comment by afontcu** [comment]
Hey! Yep, that's right. I'll go ahead and close the issue 😄
