### ISSUE TITLE
Request: cut new release & publish to npm

### ISSUE THREAD

**Issue by marcgibbons** [vuejs/vue-test-utils#1783]
### Feature Description

Can a release (e.g. 1.1.3) be published to npm?

### Problem

Last stable release (1.1.2) is from December

Thank you!

**Comment by afontcu** [comment]
Hi! Are you waiting for a specific PR/commit? Not much has happened since 1.1.2, but we could issue a new one if needed 👍

**Comment by marcgibbons** [comment]
@afontcu Yes, specifically https://github.com/vuejs/vue-test-utils/pull/1761. Much appreciated 😀

**Comment by afontcu** [comment]
just published v1.1.3 :)

**Comment by afontcu** [comment]
I'll go ahead and close this issue! Thank you for the ping (and for the PR)!

**Comment by marcgibbons** [comment]
@afontcu Awesome, thank YOU. Keep up the good work!
