### ISSUE TITLE
How to update props after shallow render?

### ISSUE THREAD

**Issue by uponeson** [vuejs/vue-test-utils#179]
I have a beforeEach function that shallow renders my component with some initial values (set with propsData). like this:

`let settings = {}`

`beforeEach(() => {
    wrapper = shallow(cmp, {
      propsData: {
        obj: {
          items,
          settings }}})})`

If i try to add `a` to `settings` `settings.a` and set a to 1 `setProps({ a:  1}) or setProps({ settings: { a: 1 }})`, it does not let me do this with setProps or any other way except for making a new wrapper in the test with `settings: { a: 1 }` explicitly set. Is there an easier way to do this?

**Comment by LinusBorg** [comment]
I think what you are looking for is `setProps`
https://vue-test-utils.vuejs.org/en/api/wrapper/setProps.html

**Comment by uponeson** [comment]
@LinusBorg i tried for my feeling every variation with `setProps` i could think of. `wrapper.setProps({ settings:  { a: 1}})` `wrapper.setProps({ obj: { settings: { a: 1} }})` etc etc.

**Comment by uponeson** [comment]
@LinusBorg could you give an example? `setProps` hasn't worked with the wrapper set before the test.

**Comment by uponeson** [comment]
It does work trough `wrapper.setProps(wrapper.vm.obj.settings = { a: 1}` but then it does not trigger my computed function which at that point should return true instead of false.

**Comment by LinusBorg** [comment]
Then I'll let someone else continue this issue, I'm not very active in this part of our ecosystem right now, so I'll leave this to the experts working on this lib.

**Comment by LinusBorg** [comment]
Why did you close it? I reopened it so someone else can answer ...

**Comment by uponeson** [comment]
After some tinkering i found the issue being the computed prop not triggering from the data change, which allows me to look further, I should be able to figure this out.

**Comment by uponeson** [comment]
For anyone interested: Do not use Jests `beforeEach` . to mount your component with propsData if you want to use setProps in the tests to update computed methods. The value will be changed but the computed property will not update.
