### ISSUE TITLE
WrapperArray#exists is not documented

### ISSUE THREAD

**Issue by markrian** [vuejs/vue-test-utils#1793]
### Version
1.1.3

### Reproduction link
[https://vue-test-utils.vuejs.org/api/wrapper-array/](https://vue-test-utils.vuejs.org/api/wrapper-array/)

### Steps to reproduce
1. https://vue-test-utils.vuejs.org/api/wrapper-array/
1. Observe there's no entry for `exists`
1. Visit https://github.com/vuejs/vue-test-utils/blob/v1.1.3/packages/test-utils/src/wrapper-array.js#L60-L62
1. Observe the method does indeed exist

### What is expected?
That it be documented :)

### What is actually happening?
It's not documented.

**Comment by afontcu** [comment]
Hi!

You're right, looks like we're missing docs for exists. Fancy to open up a PR fixing it? :)

**Comment by markrian** [comment]
@afontcu Sure! I've added it to my todo list for the week. Unless someone beats me to it ;)

EDIT: Opened https://github.com/vuejs/vue-test-utils/pull/1795 :tada:

**Comment by afontcu** [comment]
Closed in #1795
