### ISSUE TITLE
Failure when testing component with route

### ISSUE THREAD

**Issue by MaximeAubry** [vuejs/vue-test-utils#180]
Hello.

Today i have a problem, again :D
I need help to use a route (with parameter) inside an unit test.

You can consult my project here :
[https://github.com/MaximeAubry/RouteParamsUnitTest](https://github.com/MaximeAubry/RouteParamsUnitTest)

As you can see, with axios i don't use the parameter object to send the id.
> return axios.get('/api/v1/Connector/' + id)
instead of
> get('/api/v1/Connector/', { params: { id: 'myId' } } )

I try to send a http request with id using by :
>  api.$ConnectorCtrl.getByID(this.$router.currentRoute.params.id)

My component is correctly mounted, but my http request does not fire.

could you help me please ?
Sorry for my mistakes. Tell me if my English is bad, i'll try to improve.

Thanks :)

**Comment by lmiller1990** [comment]
This doesn't appear to be an issue with the library. Vue-test-utils runs synchronously, so tests will not wait unless you declare them `async`, for example, using jest.

Either way, you don't want to use a real api or ajax call in a test, you should mock the response. I wrote about it [here](https://codeburst.io/a-pattern-for-mocking-and-unit-testing-vuex-actions-8f6672bdb255), if you are interested.

If you have more questions about _how_ to test, consider joining vue-land.js.org and posting in the testing channel.

**Comment by MaximeAubry** [comment]
Actually my test is async, and I use "await flushPromises()"
So, is it ok ?

**Comment by MaximeAubry** [comment]
Does somebody have a solution ?
Please

**Comment by MaximeAubry** [comment]
I need help, please.
here is the last version of my work :
[https://github.com/MaximeAubry/RouteParamsUnitTest](https://github.com/MaximeAubry/RouteParamsUnitTest)

**Comment by eddyerburgh** [comment]
Unfortunately, since we have limited time, we have to reserve issues for feature requests and bugs. For usage questions like this, I recommend posting to either [the forum](https://forum.vuejs.org/) or [the chat](https://chat.vuejs.org/). Both include great communities of users that should be able to help.
