### ISSUE TITLE
[Vue warn]: Error in render: "TypeError: Cannot read property 'template' of null"

### ISSUE THREAD

**Issue by sandro78** [vuejs/vue-test-utils#1805]
### Subject of the issue

Undesired errors at console during tests run:

[Vue warn]: Error in render: "TypeError: Cannot read property 'template' of null"

### Steps to reproduce

Was faced with above issue and found place at code which rises it:

function isComponentOptions(c) {
  return typeof c === 'object' && (c.template || c.render)
}

In fact typeof null in JS also returns 'object' - have you expected this guys?)))

### Expected behaviour

Suggest to change this place in way:

return !!c && typeof c === 'object' && (c.template || c.render)

### Actual behaviour

Tons of errors at console like:
[Vue warn]: Error in render: "TypeError: Cannot read property 'template' of null"

### Possible Solution

Haven't found workaround yet.

**Comment by yang-mengyue** [comment]
我也遇到此问题。是没找到解决方法
