### ISSUE TITLE
this.$i18n is undefined

### ISSUE THREAD

**Issue by zhuaiji** [vuejs/vue-test-utils#1815]
### Subject of the issue

I imported i18n in .js file
`import Vue from 'vue'
import i18n from '@/i18n/i18n'
window.__vm = new Vue({
  i18n
})
`
And then this.$i18n worked well in .vue files
`function(){
return this.$i18n.t('title')
}`
However,in test file,this.$i18n is recognized as undefined
``
import i18n from '@/i18n/i18n'
localVue.use(Vuex)
...
const wrapper = mount(Practice, {
      mocks: {
        $t: (msg) => msg,
      }
    })
...
``
It called 'TypeError: Cannot read property 't' of undefined'.
I tried to mock $i18n then,but console reported 'could not overwrite property $i18n, this is usually caused by a plugin that has added the property as a read-only value'
`   const wrapper = mount(Practice, {
      localVue,
      mocks: {
        $t: (msg) => msg,
        $i18n:{
          t:(msg) => msg,
        }
      }
    })`
### Steps to reproduce

Test a vue file using 'this.$i18n.t()'

### Expected behaviour

Unit test pass

### Actual behaviour

Reporting error 'Cannot read property 't' of undefined'

### Possible Solution

What are the alternative solutions? Please describe what else you have considered?

**Comment by skoenfaelt** [comment]
``You could do the following

first create a jest.setup.js

```
// https://github.com/nuxt/nuxt.js/issues/4115
import Vue from 'vue'
import { config } from '@vue/test-utils'

Vue.config.silent = true

// Mock Nuxt components
config.stubs['nuxt-link'] = true // not needed it you are not in nuxt
config.stubs['no-ssr'] = true // not needed it you are not in nuxt
config.mocks.$t = (i) => i
config.mocks.localePath = (i) => i
```
---

then update the jest.config.js

```
module.exports = {
  setupFiles: ['<rootDir>/test/unit/jest.setup.js'], // this line
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
    '^~/(.*)$': '<rootDir>/$1',
    '^vue$': 'vue/dist/vue.common.js',
  },
  moduleFileExtensions: ['js', 'vue', 'json'],
  transform: {
    '^.+\\.js$': 'babel-jest',
    '.*\\.(vue)$': 'vue-jest',
  },
  collectCoverage: true,
  collectCoverageFrom: ['<rootDir>/components/**/*.vue'],
}

```

After that your test should run
