### ISSUE TITLE
Request: cut new release & publish to npm

### ISSUE THREAD

**Issue by amercier** [vuejs/vue-test-utils#1818]
## Feature Description

Would it be possible to create a new release (e.g. 1.1.4) and publish it to npm, please?

## Problem

Last stable release (1.1.3) is from February, and [18 commits](https://github.com/vuejs/vue-test-utils/compare/v1.1.3...dev) are still unreleased. In particular, I'm interested in #1786.

Thank you!

**Comment by lmiller1990** [comment]
Done: https://github.com/vuejs/vue-test-utils/releases/tag/v1.1.4
