### ISSUE TITLE
Components don't emit focus when not attached to document.body during mount

### ISSUE THREAD

**Issue by GadQ** [vuejs/vue-test-utils#1819]
### Subject of the issue

After last update to 1.1.4 components don't emit focus when not attached to document.body during mount.

Is this change intentional or do I need always attach to document.body if I want to detect DOM events?

### Steps to reproduce

Here is the minimal reproduction repo: https://github.com/GadQ/vue-test-utils-focus

There are two tests: with attachTo: document.body and without 

### Expected behaviour

Both tests should pass. At least that was the behaviour in 1.1.3.

### Actual behaviour

Test without attachTo: document.body fails because input doesn't emit focus event.

**Comment by Gotos** [comment]
I'd also really like to know if this is intended. The workaround works fine, but at least to me it's not intuitive that I have to use `attachTo: document.body` and this doesn't seem to be documented.

(What I did find in the docs tho: You should call `wrapper.destroy()` if you mount it with attachTo. I figured I'd mention this for others stumbling over this issue in search for a solution for their breaking tests)

**Comment by bponomarenko** [comment]
Just stumbled upon this issue myself, and came to the same `attachTo: document.body` workaround by analyzing actual changes. Triggering `focus` event now [also focuses actual element](https://github.com/vuejs/vue-test-utils/blob/dev/packages/test-utils/src/wrapper.js#L841-L847), which make sense. However it would be useful to either document it, or implement it in a way that will have optional dependency on `attachTo` configuration – element will only be focused if `attachTo` is set.

**Comment by GadQ** [comment]
I'm closing, because it's intended and described in documentation: https://vue-test-utils.vuejs.org/api/wrapper/#trigger (TIP section)

**Comment by bponomarenko** [comment]
Thanks for adding TIP section @GadQ
