### ISSUE TITLE
Can not distinguish the update applied by Vue or asynchronous behavior outside of Vue

### ISSUE THREAD

**Issue by TrendAlan** [vuejs/vue-test-utils#1821]
### Subject of the issue
Can not distinguish the "update applied by Vue" and "asynchronous behavior outside of Vue"

### Steps to reproduce
Imagine I have a component like this:
```
<template>
  <div>
    <div>
      <div classs="loading" v-show="loading">loading...</div>
      <div class="content">{{content}}</div>
    </div>
    <button  @click="showCotent">Load Content</button>
  </div>
</template>

<script>
  export default {
    name: 'MyComponent',
    data(){
      return {
        loading:false,
        content:"0"
      }
    },
    methods: {
      showCotent() {
        this.loading = true;
        this.getData();
      },
      getData() {
        axiso.get('/api').then((res)=>{
          this.content = res.data;
          this.loading = false;
        })
      }
    }
  }
</script>
```
I have two tests:
1. Test the string "loading..." will be shown after clicking the button
2. Test the content is as the value from the async API.

test.js

```
  it('Test show loading after click', async () => {
    const wrapper = mount(Component)
    const button = wrapper.find("button")
    await button.trigger("click");
    //await flushPromises();
    expect(wrapper.find(".loading").isVisible()).toBe(true)//This test will be failed, how to make it pass?
  }) 
  it('Test content is correct after click', async () => {
    const wrapper = mount(Component)
    const button = wrapper.find("button")
    button.trigger("click");
    //await button.trigger("click");
    await flushPromises();
    expect(wrapper.find(".loading").isVisible()).toBe(false)
    expect(wrapper.text()).toContain("async content”)
  })
```

But no matter I use "await button click" or "await flushPromises", the loading div will always be hidden after clicking the button.
According to the docs, it only suggests using "await button click" for updates applied by Vue and using "await flushPromises" for something async.
https://vue-test-utils.vuejs.org/guides/#testing-asynchronous-behavior
But what if I need to do both of them together?
### Expected behaviour
1. The loading div will be shown.
2. The content is async request value. (actually, it is)

### Actual behavior
The loading div will always be hidden.

### Possible Solution
Should have a difference between "await button click" and "await flushPromises" to handle this case

**Comment by TrendAlan** [comment]
I find a way to check the loading... string to be shown, I need to do this:
But the expect inside Vue.nextTick() will not be count as a expect, even I expect("foo").toBe("bar"), this test suite still passed.
```
  it('Test show loading after click', async () => {
    const wrapper = mount(Component)
    const button = wrapper.find("button")
    button.trigger("click");
    Vue.nextTick(()=>{
        console.log(wrapper.html()) // you can find the loading string is visible here.
        expect(wrapper.find(".loading").isVisible()).toBe(true) // this expect will not be executed
        expect("foo").toBe("bar")// this expect will not be executed, so the test suite still passed.
    })
    await Vue.nextTick();
    console.log(wrapper.html()) // the loading string will be hidden again.
    expect(wrapper.find(".loading").isVisible()).toBe(true) // this expect will be executed and the test suite will be failed.
  }) 
```
what is the difference between these two statements?
```
await Vue.nextTick(); 
expect("xx").toBe("xx")
```
```
Vue.nextTick(()=>{
    expect("xx").toBe("xx")
})
```

**Comment by afontcu** [comment]
> what is the difference between these two statements?

Wow, none that I can think of, and according to docs 🤔: "_Since $nextTick() returns a promise, you can achieve the same as the above using the new ES2017 async/await syntax_". ([source](https://vuejs.org/v2/guide/reactivity.html#Async-Update-Queue))

**Comment by TrendAlan** [comment]
> > what is the difference between these two statements?
> 
> Wow, none that I can think of, and according to docs 🤔: "_Since $nextTick() returns a promise, you can achieve the same as the above using the new ES2017 async/await syntax_". ([source](https://vuejs.org/v2/guide/reactivity.html#Async-Update-Queue))

Then why the testing result was different, and the "expect statement" inside the nextTick function is ignored by the jest framework.

**Comment by afontcu** [comment]
> and the "expect statement" inside the nextTick function is ignored by the jest framework.

Well, that kinda makes sense: https://jestjs.io/docs/asynchronous#callbacks. You'd need to use the `done` parameter

**Comment by TrendAlan** [comment]
> > and the "expect statement" inside the nextTick function is ignored by the jest framework.
> 
> Well, that kinda makes sense: https://jestjs.io/docs/asynchronous#callbacks. You'd need to use the `done` parameter

**Awesome，bro!!**
You just saved my life.

I think it should be put into the guide in case someone may encounter the same issue as me.
https://vue-test-utils.vuejs.org/guides/#testing-asynchronous-behavior

**Comment by afontcu** [comment]
glad you got it solved!
