### ISSUE TITLE
Trigger postMessage does not work

### ISSUE THREAD

**Issue by Havrin** [vuejs/vue-test-utils#1825]
### Subject of the issue

Testing if a component reacts correctly to a sent window.postMessage is not possible.

### Steps to reproduce

Component
```
<template>
...
</template>

<script>
  export default {
    name: 'MyComponent',
    ...
    mounted() {
        window.addEventListener("message", this.myFunction, false);
    },
    ...
    methods: {
        myFunction(event) {
            console.log("received post message");
        }
    }
</script>
```

Test
```
describe("MyComponent.vue", () => {
    it("test query message", async () => {
        const wrapper = mount(MyComponent, {
            store: store,
            attachTo: window.document.body
        });

        window.postMessage("Test", "*"); // didn't work
        window.document.dispatchEvent(new MessageEvent("Test")); // didn't work
        await wrapper.trigger("message"); // didn't work
        await wrapper.vm.$nextTick(); // tried to wait a tick if test finishes too quickly
    });
});
```

### Expected behaviour

I should see the "received post message" text when I run my test.

### Actual behaviour

Test passes without the seeing the log statement. Nothing happens.

### Possible Solution

Other Triggers work. Switching the `window.addEventListener("message", this.myFunction, false);` to a "click" EventListener and triggering a click works. 

Is there a trick to test Messagevents? Or is it simply impossible?
Thanks!

**Comment by afontcu** [comment]
Hey!

Looks like `postMessage` is async ([source](https://github.com/facebook/jest/issues/6765#issuecomment-408361195)). Awaiting a tick might not be enough, as explainer here: https://vue-test-utils.vuejs.org/guides/#asynchronous-behavior-outside-of-vue

hope it helps!

**Comment by Havrin** [comment]
Hey @afontcu ,
thanks for your reply and the good hint.
Unfortunately I already tried `flushPromises`, forgot to mention it above.

I tried with the same result:
```
describe("MyComponent.vue", () => {
    it("test query message", async () => {
        const wrapper = mount(MyComponent, {
            store: store,
            attachTo: window.document.body
        });
        // window.postMessage("Test", "*"); // didn't work
        // window.document.dispatchEvent(new MessageEvent("Test")); // didn't work
        wrapper.trigger("message");
        await flushPromises();
        // await wrapper.vm.$nextTick(); // tried to wait a tick if test finishes too quickly
    });
});
```
Also tried nextTick with a callback. Didn't work either.

Thanks for your help tho!

**Comment by Leronez** [comment]
@Havrin, hi.

I think I managed to solve the problem

```
it('test query message', () => {
    console.log = jest.fn();

    const wrapper = mount(Test, {
      attachTo: document.body,
    });

    return new Promise((resolve) => {
      window.postMessage('Test', '*');

      window.addEventListener(
        'message',
        () => {
          expect(console.log).toHaveBeenCalledWith('received post message');
          resolve();
        },
        false,
      );
    });
  });
```
