### ISSUE TITLE
Mocking a Method for the 'created' Lifecycle Hook

### ISSUE THREAD

**Issue by jonyoder** [vuejs/vue-test-utils#184]
I'd like to stub/spy a method and ensure/test that it is called during the `created` lifecycle hook. I've discovered that I can use `wrapper.setMethods` to stub/mock the method, but the `created` hook has already run at this point; I've tried using `wrapper.update()`, but it doesn't appear to run the `created` hook again.

Am I missing something simple?

**Comment by eddyerburgh** [comment]
You can pass a `methods` object in the mounting options that will overwrite any method inside the component.

Say you had a method called `methodToStub` in your component. You would mount like this:

```js
mount(Component, {
  methods: {
    methodToStub: () => {}
  }
})
```

**Comment by wtho** [comment]
See the issue #166 and the pending PR #167 that would solve this issue.

**Comment by jonyoder** [comment]
Thanks, @eddyerburgh! Passing `methods` to mount/shallow was exactly what I needed.

**Comment by joelpro2** [comment]
> You can pass a `methods` object in the mounting options that will overwrite any method inside the component.
> 
> Say you had a method called `methodToStub` in your component. You would mount like this:
> 
> ```js
> mount(Component, {
>   methods: {
>     methodToStub: () => {}
>   }
> })
> ```

This has become deprecated
