### ISSUE TITLE
when the prop name of the component is an array, throw error from 1.1.4 and later

### ISSUE THREAD

**Issue by blusoul** [vuejs/vue-test-utils#1854]
### Subject of the issue

My unit tests started breaking from 1.1.4 and later

### Steps to reproduce

```javascript
    const wrapper = mount(
      {
        props: {
          name: ["start", "end"]
        },
        template: `<Wrapper><Inner :name="name" /></Wrapper>`
      },
      {
        stubs: {
          Wrapper,
          Inner
        }
      }
    );

    // name is array
    // from 1.1.4 throw error: TypeError: str.replace is not a function
    console.log(wrapper.findComponent(Wrapper));
```
![vue-test](https://user-images.githubusercontent.com/8167270/120175018-54b46e00-c238-11eb-817e-f0a0a6b019cf.png)
[Demo](https://codesandbox.io/s/priceless-paper-dnpkc?file=/src/demo/__tests__/demo.spec.js)

### Expected behaviour

When i downgrade to 1.1.3, it is ok, but  **findComponent({name: 'xxx'})** has error

**Comment by lmiller1990** [comment]
Thanks for the report, looks like we have a fix in #1857. I will work with the author to merge it.
