### ISSUE TITLE
How to mock scoped slot data with shallowMount

### ISSUE THREAD

**Issue by jan-novak-celtra** [vuejs/vue-test-utils#1855]
Hello I have a situation I don't know how to resolve. Bellow is an example of my component. I am using shallowMount, which crash because `item` is `{}`. How can I `mock` this item object to not crash when accessing nested properties.

```
<template>
    <my-parent-component
        :options="options"
    >
        <template v-slot:default="item">
            <some-other-component
                :id="item.option.id"
            />
        </template>
    </grouped-list>
</template>
```

**Comment by Natega** [comment]
follow

**Comment by lmiller1990** [comment]
`shallowMount` stubs other components - so won't `some-other-component` be stubbed? Can you share the entire test you'd like to write?

Generally for testing components rendered in slots, I recommend using `mount`, and make an assertion against the rendered html.
