### ISSUE TITLE
Translate docs in Korean

### ISSUE THREAD

**Issue by ChangJoo-Park** [vuejs/vue-test-utils#186]
I just finished translating in Korean. working on https://github.com/ChangJoo-Park/vue-test-utils , in dev-korean branch. It is not reviewed yet. :)

## Translate
Root
- [x] README.md
- [x] SUMMARY.md

---
Guides
- [x] 시작하기(./getting-started.md)
- [x] 일반적인 팁(./common-tis.md)
- [x] 마우스, 키 그리고 기타 DOM 이벤트(guides/dom-events.md)
- [x] 테스트 러너 선택하기(./choosing-a-test-runner.md)
- [x] Jest 사용하기(./using-with-jest.md)
- [x] Jest로 싱글 파일 컴포넌트 테스트(./testing-SFCs-with-jest.md)
- [x] Mocha + weback으로 싱글 파일 컴포넌트 테스트(./testing-SFCs-with-mocha-weback.md)
- [x] Vue Router 사용하기(./using-with-vue-router.md)
- [x] Vuex 사용하기(./using-with-vuex.md)

---
API

- [x] mount(api/mount.md)
- [x] shallow(api/shallow.md)
- [x] Mounting Options(api/options.md)
- [x] Selectors(api/selectors.md)
- [x] createLocalVue(api/createLocalVue.md)
- [x]  config(api/config.md)

- [x] Wrapper(api/wrapper/README.md)
  - [x] contains(api/wrapper/contains.md)
  - [x] emitted(api/wrapper/emitted.md)
  - [x] emittedByOrder(api/wrapper/emittedByOrder.md)
  - [x] find(api/wrapper/find.md)
  - [x] findAll(api/wrapper/findAll.md)
  - [x] hasAttribute(api/wrapper/hasAttribute.md)
  - [x] hasClass(api/wrapper/hasClass.md)
  - [x] hasProp(api/wrapper/hasProp.md)
  - [x] hasStyle(api/wrapper/hasStyle.md)
  - [x] html(api/wrapper/html.md)
  - [x] is(api/wrapper/is.md)
  - [x] isEmpty(api/wrapper/isEmpty.md)
  - [x] isVueInstance(api/wrapper/isVueInstance.md)
  - [x] name(api/wrapper/name.md)
  - [x] setComputed(api/wrapper/setComputed.md)
  - [x] setData(api/wrapper/setData.md)
  - [x] setMethods(api/wrapper/setMethods.md)
  - [x] setProps(api/wrapper/setProps.md)
  - [x] text(api/wrapper/text.md)
  - [x] trigger(api/wrapper/trigger.md)
  - [x] update(api/wrapper/update.md)
  - [x] destroy(api/wrapper/destroy.md)

- [x] WrapperArray(api/wrapper-array/README.md)
  - [x] at(api/wrapper-array/at.md)
  - [x] contains(api/wrapper-array/contains.md)
  - [x] hasAttribute(api/wrapper-array/hasAttribute.md)
  - [x] hasClass(api/wrapper-array/hasClass.md)
  - [x] hasProp(api/wrapper-array/hasProp.md)
  - [x] hasStyle(api/wrapper-array/hasStyle.md)
  - [x] is(api/wrapper-array/is.md)
  - [x] isEmpty(api/wrapper-array/isEmpty.md)
  - [x] isVueInstance(api/wrapper-array/isVueInstance.md)
  - [x] setComputed(api/wrapper-array/setComputed.md)
  - [x] setData(api/wrapper-array/setData.md)
  - [x] setMethods(api/wrapper-array/setMethods.md)
  - [x] setProps(api/wrapper-array/setProps.md)
  - [x] trigger(api/wrapper-array/trigger.md)
  - [x] update(api/wrapper-array/update.md)
  - [x] destroy(api/wrapper-array/destroy.md)

- [x]  components(api/components/README.md)
  - [x]  TransitionStub(api/components/TransitionStub.md)
  - [x]  TransitionGroupStub(api/components/TransitionGroupStub.md)

**Comment by eddyerburgh** [comment]
Great work 😀

Can you open a pull request and we can find a native speaker to review.

**Comment by ChangJoo-Park** [comment]
Sure, I'll open a PR after self review :)
