### ISSUE TITLE
Typescript error with wrapper.find('select').element.value

### ISSUE THREAD

**Issue by Mnigos** [vuejs/vue-test-utils#1870]
Hello, I'm using typescript and got error 
`
Property 'value' does not exist on type 'HTMLElement'.ts(2339)
any
`
Here is my test

```
  it('Should write a login', async () => {
    const wrapper = shallowMount(LoginForm)
    const input = wrapper.find( '[data-test="nameOrEmailInput"]')
    await input.setValue('User123')

    expect(wrapper.find('input#input-20').element.value).toBe('User123')
  })
  ```

**Comment by standbyoneself** [comment]
Property `value` really does not exist on type `HTMLElement`. You need to make thing called "type casting" / "type assertion".

`wrapper.find()` returns a {Wrapper} and an `element` property of it basically has type HTMLElement. If you target an input you need to manually assert it to the `HTMLInputElement` interface which contains a `value` property ([HTMLInputElement on MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement))

```
expect((wrapper.find('input').element as HTMLInputElement).value).toBe(...)
```

[Type Assertion in Typescript Documentation](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions)

**Comment by lmiller1990** [comment]
I think find can take a generic: `wrapper.find<HTMLInputElement>`. If not, we should update the types - we have this generic in V2 of this library, but sine V1 is written in JS (with flow), the types are not as good as they probably can be.

**Comment by standbyoneself** [comment]
@lmiller1990,
VTU 1 actually doesn't have an overloaded `find()` with a string selector that can take a generic

```js
  find<R extends Vue> (selector: VueClass<R>): Wrapper<R>
  find<R extends Vue> (selector: ComponentOptions<R>): Wrapper<R>
  find<Props = DefaultProps, PropDefs = PropsDefinition<Props>>(selector: FunctionalComponentOptions<Props, PropDefs>): Wrapper<Vue>
  find (selector: string): Wrapper<Vue>
  find (selector: RefSelector): Wrapper<Vue>
  find (selector: NameSelector): Wrapper<Vue>
```

**Comment by lmiller1990** [comment]
`find` for components is deprecated, we have `findComponent`.  Anyway, if you'd like to update the types to include something like:

```ts
find<Element> (selector: string): Wrapper<Element>
```

That would improve the types and your problem. For some inspiration, [check the types in V2](https://github.com/vuejs/vue-test-utils-next/blob/6e0904c6dc9f6e17045ad69773a33926a54bc872/src/vueWrapper.ts#L115-L121), which are really well defined (since the entire code base is written in TypeScript).
