### ISSUE TITLE
link to v3.x documentation doesn't work correctly

### ISSUE THREAD

**Issue by MartinsOnuoha** [vuejs/vue-test-utils#1880]
### Documentation Feedback

Currently, the link in the warning notification at the top of the homepage points to the wrong location.

> This doc is for Vue2.x only. If you want to see docs related to 3.x, please move to [here](https://vue-test-utils.vuejs.org/v2/guide/introduction.html)

When you click the link above in the warning, it takes you to the Vue2 documentation page, but the user sees a Netlify 404 page still.

I believe the correct link should be this https://next.vue-test-utils.vuejs.org/ instead.

**Affected documentation page:** https://vue-test-utils.vuejs.org/

**Comment by afontcu** [comment]
Hi! Yeah, you're right, link should be https://next.vue-test-utils.vuejs.org/guide/

Fancy to open up a PR? 😄

**Comment by MartinsOnuoha** [comment]
Hi @afontcu, I was about to raise a PR but Looks like it has been resolved, 😄 How odd.
I think I'll go ahead and close this issue.

Thanks!

**Comment by afontcu** [comment]
Good to hear that! Closing this up :)

**Comment by garretmh** [comment]
This is wrong again. V3 docs are now at <https://test-utils.vuejs.org/>
