### ISSUE TITLE
vue-test-unit可以挂载component组件吗？

### ISSUE THREAD

**Issue by yang-mengyue** [vuejs/vue-test-utils#1881]
### Subject of the issue

vue-test-unit可以挂载component组件吗？我遇到报错
![image](https://user-images.githubusercontent.com/78328465/126095882-b63a9ecf-5ed8-47ab-9d8d-973e63a02106.png)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/78328465/126095952-56b66b1a-02c0-4067-beb1-33ed18b8290e.png)

### Expected behaviour

参考issue
https://github.com/vuejs/vue-test-utils/issues/1805

thank you ！

**Comment by ebisbe** [comment]
This seems already fixed.
