### ISSUE TITLE
wrapper.findComponent(VueComponentInstance).exists() always returns true

### ISSUE THREAD

**Issue by zkd8907** [vuejs/vue-test-utils#1884]
I upgraded @vue/test-utils to 1.2.1 and found my tests failed. I found the similar issue at #810. Vue Component doesn't be rendered because `v-if="false"`, however `wrapper.findComponent(VueComponentInstance).exists()` always returns `true`.
I located commits at [https://github.com/vuejs/vue-test-utils/pull/768/files](https://github.com/vuejs/vue-test-utils/pull/768/files). I found `find-vue-components.js` listed in the PR was removed at dev branch. Is this file deprecated? Does `findComponent` implement as another way with the same mistake?

**Comment by standbyoneself** [comment]
Create a repository that reproduces your problem

`findComponent()` implementation is located in `packages/test-utils/src/wrapper.js`

**Comment by zkd8907** [comment]
After I tested, I found that this problem does not exist, sorry for the issue.
