### ISSUE TITLE
wrapper.emitted() does not work as expected with @vue/composition-api v1.1.0

### ISSUE THREAD

**Issue by Oleksii14** [vuejs/vue-test-utils#1895]
### wrapper.emitted() issue

When updated the deps to  @vue/composition-api v1.1.0, wrapper.emitted() method stopped working properly

Instead of emit object property, I started receiving `hook:created`, `hook:mounted` etc.

![image](https://user-images.githubusercontent.com/36737084/129142590-e1874405-a1a9-4443-b29c-d3f4bf1b73a7.png)

Can you research on this?

**Comment by standbyoneself** [comment]
Which previous version of @vue/composition-api did you use? Could you provide a repo that demonstrates this case?

**Comment by Oleksii14** [comment]
I have done small research, and it seems this bug starts from v1.1.0-beta.7

Not sure why, but I cannot reproduce that while creating a new project via `vue create`

**Comment by Oleksii14** [comment]
I've found an appropriate commit. Do you think it could be the reason? 
https://github.com/vuejs/composition-api/commit/da21873

**Comment by Oleksii14** [comment]
Sorry, my bad 😄 

In my tests, I have checked `wrapper.emitted()` result to **equal** the expected stuff. The reason why my tests failed is that the commit above introduced the additional values included to `wrapper.emitted()` result: 
![image](https://user-images.githubusercontent.com/36737084/129216807-4d00c376-d64e-4394-a852-f65f6862008d.png)

I have adjusted the test:

```
expect(wrapper.emitted().submit).toEqual(...);
```

All worked properly
I am closing the issue 👍🏻
