### ISSUE TITLE
How to pass variables from webpack.definePlugin to component tests? 

### ISSUE THREAD

**Issue by jost-s** [vuejs/vue-test-utils#1896]
I’m using feature flags in my Vue app. They are defined in `vue.config.js` as variables with the [DefinePlugin](https://webpack.js.org/plugins/define-plugin/):

```javascript
  ...
  configureWebpack: {
    plugins: [
      new webpack.DefinePlugin({
        SHOW_SOCIAL_LOGIN_BUTTONS: JSON.stringify(env === 'dev'),
        SHOW_INTEGRATIONS: JSON.stringify(env === 'dev' || env === 'feat')
      }),
  ...
```

Then in my SFC using composition API it’s returned from setup:

```typescript
<script lang="ts">
import { defineComponent, onMounted, ref } from '@vue/composition-api';
...

declare const SHOW_SOCIAL_LOGIN_BUTTONS: boolean;

export default defineComponent({
  setup() {
    ...
    return {
      SHOW_SOCIAL_LOGIN_BUTTONS,
      ...
    };
  }
});
</script>
```

When I `mount(component)` in my unit test, I get the error:

```bash
ReferenceError: SHOW_SOCIAL_LOGIN_BUTTONS is not defined
```

Mounting components from vue test utils doesn’t take webpack config into account. So how can I pass such variables to the component?

**Comment by LinusBorg** [comment]
You will have to set them. In a jest [setup file](https://jestjs.io/docs/26.x/configuration#setupfiles-array):
```js
window.SHOW_SOCIAL_LOGINS_BUTTONS = true
```

**Comment by LinusBorg** [comment]
Closing as this is unrelated to the test-utils library

**Comment by jost-s** [comment]
Thanks so much @LinusBorg, that worked. And sorry for confusing repos.
