### ISSUE TITLE
document.querySelector not work

### ISSUE THREAD

**Issue by Lhhpw0204** [vuejs/vue-test-utils#1899]
### Problem
<template>
    <div class="revenue-bar-wrapper" ref='revenueBarWrapper'></div>
</template>
<script>
export default {
    mounted() {
        const oDom = document.querySelector('.revenue-bar-wrapper');
        console.log(oDom);     but the oDom is null
    }
}
</script>

### Expected behaviour

expect oDom is the real dom

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by standbyoneself** [comment]
Are you sure this issue is about vue-test-utils? Could you provide the component and corresponding test fully?

**Comment by Lhhpw0204** [comment]
component：
![image](https://user-images.githubusercontent.com/37644477/131794549-2cc11aa2-7f7d-46fe-80bd-9a50b7ce2a19.png)

<template>
    <section class="echarts-example"></section>
</template>

<script>
import * as echarts from 'echarts';

export default {
    data() {
        return {
        }
    },
    mounted() {
        this.initChart();
    },
    methods: {
        initChart() {
            this.$nextTick(() => {
                if (!this.chartInstance) {
                    const chartDom = document.querySelector('.echarts-example');
                    this.chartInstance = chartDom && echarts.init(chartDom);
                }
                const options = {
                    xAxis: {
                        type: 'category',
                        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
                    },
                    yAxis: {
                        type: 'value'
                    },
                    series: [{
                        data: [150, 230, 224, 218, 135, 147, 260],
                        type: 'line'
                    }]
                };
                this.chartInstance && this.chartInstance.setOption(options);
            });
        }
    }
}
</script>

<style>
.echarts-example {
        width: 375px;
        height: 375px
    }
</style>

test.spec.js：
import Vue from 'vue';
import CompA from '../components/CompA/index.vue';
import { mount } from '@vue/test-utils'


describe('CompA', () => {
  let wrapper = null;

  it('should be normal show', async () => {
    wrapper = mount(CompA);
    await Vue.nextTick();
    expect(wrapper.html()).to.include('canvas');
  });
})

but result is wrong：
![wecom-temp-b3693767bdbb028021fdb6684324933f](https://user-images.githubusercontent.com/37644477/131793852-c49c94d5-33b3-4bcf-8cf0-ba81e68b1682.png)

**Comment by standbyoneself** [comment]
What exactly you will get if you simply call `wrapper.html()`? Only section? Did `echarts.init()` actually called? You need to provide a repository, not a screenshot of your code

**Comment by bponomarenko** [comment]
@Lhhpw0204 The issue might be related to the order of execution as well. `await Vue.nextTick()` will defer `expect` till the next rendering cycle after component being mounted. However `echart.init()` is also called inside the `nextTick` callback. It could be possible that chart is simply not rendered by the time `expect` is executed. Would it work if you'll remove `this.$nextTick()` wrapper inside `initChart` method? `this.$nextTick()` wrapper is not really needed there either way, since `initChart` is called in the `mounted()` hook, which guarantees that template is rendered and added to the DOM by that time.
