### ISSUE TITLE
trigger click on native HTML element trigger method but spy does not catch it

### ISSUE THREAD

**Issue by jf-niji** [vuejs/vue-test-utils#1901]
### Subject of the issue

I have a component with a simple link and I want to test that a click on it triggers a method. With Vue test util + jest, the method is called but not the spy.

Version of vue-test-utils : 1.2.0

### Steps to reproduce

```
import { shallowMount } from '@vue/test-utils'

// The component to test
const LinkComponent = {
	template: '<a href="www.google.fr" _target="_blank" @click="trackClick">My link</a>',
	methods: {
		trackClick() {
			console.log('Track click')
		},
	},
}

it('Should call trackClick when link is clicked', async () => {
	const wrapper = shallowMount(LinkComponent)
	const spyTrackClick = jest.spyOn(wrapper.vm, 'trackClick')

	const link = wrapper.find('a')

	await link.trigger('click')

	expect(spyTrackClick).toBeCalled()
})
```
### Expected behaviour

**Spy should be called**

### Actual behaviour

console.log is called and displayed in console & **spy is not called**
I can reproduce this issue with a <a>, <div> & other.

**Comment by standbyoneself** [comment]
To make it "just work", add parentheses to trackClick in your template. Vue allows both variants, but you should use this variant preferred in order to stay consistent not to have problems with tests in future.

**Comment by lobo-tuerto** [comment]
Is this documented somewhere like in BIG LETTERS, because it's very surprising that it works on Vue as is, but have you scratching your head when they don't work in tests because _optional_ parentheses are missing.
