### ISSUE TITLE
Content from require with raw-loader within a component, not being loaded

### ISSUE THREAD

**Issue by iandevlin** [vuejs/vue-test-utils#1903]
I have an Icon component that loads SVG icons dynamically based on a prop.
To load the SVG icon, it uses something like:

```
<span v-html="svg" />
```

And the prop is the icon name, and the value of `svg` above is a computed property:
```
svg() {
   const svg = require(`!raw-loader!./../../assets/svg/${this.icon}.svg`);
   return svg.default;
}
```

Now this works perfectly fine as a component, but I am completely unable to test it as the value of `svg` is always returned as `undefined`.

I am just wondering how I could go about getting this to work?

I have tried using `moduleNameMapper` in the `jest.config.js` file, to no avail.

Are there any pointers you could give me? Many thanks in advance!

**Comment by standbyoneself** [comment]
What is the regex you used in moduleNameMapper? There is the order is also important.

Another one way to use jest.mock().

**Comment by iandevlin** [comment]
Hi, thanks for the reply.
I managed to get it working in the end, although I had to use `transform` rather than `moduleNameMapper`. Now All I need to do is figure out how I can make `XMLSerializer` available in a test...

Will close this now though, thank you!
