### ISSUE TITLE
Add Computed mounted property to Mount options documentation

### ISSUE THREAD

**Issue by amirensit** [vuejs/vue-test-utils#1913]
### Documentation Feedback

Hello.

I saw using computed property as part of mount options in the [Vue Testing Handbook](https://lmiller1990.github.io/vue-testing-handbook/vuex-in-components.html#mocking-getters-using-computed).

I was confused because I didn't find computed property as mount options [here](https://vue-test-utils.vuejs.org/api/options.html).

I think It will be helpful to add it as mount options.

**Comment by bponomarenko** [comment]
Hello @amirensit The section you are looking for is all the way in the bottom: https://vue-test-utils.vuejs.org/api/options.html#other-options
It doesn't mention "computed" properties explicitly, but implies any Vue component options.

> When the options for `mount` and `shallowMount` contain the options other than the mounting options, **the component options are overwritten with those using extends**.

**Comment by bponomarenko** [comment]
@amirensit Do you think this is still an issue or it can be closed?

**Comment by amirensit** [comment]
Ok I will close it.
