### ISSUE TITLE
element toBeVisible not in the document

### ISSUE THREAD

**Issue by rodhoward** [vuejs/vue-test-utils#1915]
### element toBeVisible not in the document

Having updated jest the test .toBeVisible() in our existing tests is now failing with the error "element is not in the document".:
```
  it("modal is displayed", () => {
    expect(wrapper.find(".modal").element).toBeVisible();
  });
```
We are now getting errors like:
```
Received element is not visible (element is not in the document):
```

It seems related to this:
https://github.com/testing-library/jest-dom/issues/338
Because adding '''attachTo: document.body''' when mounting seems to work around the issue. 

However it would be nicer to have attaching to the body become the default if that's what it takes. Rather than have to add that explicitly to all my test suites. Also seems like cleaning up the dom is required, again if it became the default test utils could maybe clean it up for me.

### Steps to reproduce

upgrade jest-dom

"@testing-library/jest-dom": "^5.14.1",
"jest": "^26.6.3",
"@vue/test-utils": "^1.2.2",

### Expected behaviour

My old tests continue to work.
We don't get errors

### Actual behaviour

Received element is not visible (element is not in the document):

### Possible Solution

By default vue attaches to the dom and cleans it up.   OR push back on jest-dom..

**Comment by rodhoward** [comment]
I missed this earlier but vue test utils **isVisible** isn't deprecated anymore! 

This is actually perfectly fine workaround for us.

**Comment by ebisbe** [comment]
@rodhoward if all is fine I'll close the issue.
