### ISSUE TITLE
Question: How to globally inject components with Vue3?

### ISSUE THREAD

**Issue by ccmetz** [vuejs/vue-test-utils#1918]
I'm using `@vue/test-utils` (v2.0.0-0) with a Vue3 + TS project that uses `Vuestic-UI` as a components framework. I'm trying to figure out how to inject my `Vuestic-UI` components globally so that I don't get messages like the following when I try to run a unit test (using `jest` as the test framework btw):
```
console.warn node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6799
    [Vue warn]: Failed to resolve component: va-button 
      at <Anonymous ref="VTU_COMPONENT" > 
      at <VTUROOT>
```
In the past with Vue2, I was able to use a setup file with something like this to import all of the components of the framework I was using (at the time it was `Buefy`):
```
import Vue from 'vue'
import Buefy from 'buefy'

// We need to register Buefy so that jest recognizes their components during our tests
Vue.use(Buefy);
```

How do I go about doing this with Vue3? I haven't been able to find any documentation about it though there is this page here that looks like it might've helped: https://next.vue-test-utils.vuejs.org/guide/advanced/third-party.html. Any help is much appreciated :)

**Comment by awulkan** [comment]
I'm having the same problem with the PrimeVue component library. I'm using Vite as well, which appears to complicate things.

**Comment by ccmetz** [comment]
I've realized that the correct repo to ask this question is really here: https://github.com/vuejs/vue-test-utils-next. Sorry for cluttering up the backlog!
