### ISSUE TITLE
When running the tests, I get an error about the global variable that it is not defined

### ISSUE THREAD

**Issue by fisherspoons** [vuejs/vue-test-utils#1950]
Hi, I am using Symfony + Vue bundle in the project. Inside the twig file I have a declared global variable (localizations) and it is used inside the vue file. Everything works as it should, but when I run the test, I get an error that this variable is not declared.

<img width="486" alt="Снимок экрана 2022-01-10 в 20 14 55" src="https://user-images.githubusercontent.com/54633510/148817515-09df9526-af59-4d15-990f-15e58f16a88d.png">

<img width="259" alt="Снимок экрана 2022-01-10 в 20 15 15" src="https://user-images.githubusercontent.com/54633510/148817546-0a3767f6-6b84-483c-9804-3878dcd2b6c1.png">

<img width="766" alt="Снимок экрана 2022-01-10 в 20 15 55" src="https://user-images.githubusercontent.com/54633510/148817619-3b0e8902-1406-4c00-b973-a20d08ae76a8.png">

<img width="352" alt="Снимок экрана 2022-01-10 в 20 16 15" src="https://user-images.githubusercontent.com/54633510/148817675-212a4903-3c15-41f2-a8be-97d6e28e5567.png">

Tell me what could be the problem, maybe you need to declare this variable somehow differently or make an import?

**Comment by dschmidt** [comment]
`window.locale`?

**Comment by ebisbe** [comment]
Did you solve it @fisherspoons ?
