### ISSUE TITLE
BaseWrapper.prototype.trigger has a bad implementation

### ISSUE THREAD

**Issue by dima4p** [vuejs/vue-test-utils#1952]
### Subject of the issue

The method `Vue#$emit` accepts the name of the event an **any** number of the parameters that all being sent to the function - event handler.
But in test `BaseWrapper.prototype.trigger` accepts only one parameter after the event name.

### Steps to reproduce

in the code:
```
<template lang='pug'>
my-component(@my_signal="my_signal")
</template>

<script>
…
 methods: {
  my_signal(...args) {
      console.log(args)
  }
},
…
</script>
```

in the test:

```
wrapper.find(…).trigger('my_signal', 1, 2)
```

### Expected behaviour

it should be printed `[1, 2]`

### Actual behaviour

it is printed [1]

### Possible Solution

I think it is quite clear, there must be implemented the transfer of more than one argument.
```
BaseWrapper.prototype.trigger = function (eventString, ...args) {
```

**Comment by lmiller1990** [comment]
`trigger` is designed to work with DOM events, as opposed to custom ones. [Please see the documentation](https://vue-test-utils.vuejs.org/api/wrapper/#trigger).

If you'd like to activate a custom event, how about:

```
wrapper.vm.$emit('customEvent', 1, 2, 3)
```

That will work!

**Comment by dima4p** [comment]
> `trigger` is designed to work with DOM events, as opposed to custom ones. [Please see the documentation](https://vue-test-utils.vuejs.org/api/wrapper/#trigger).
> 
> If you'd like to activate a custom event, how about:
> 
> ```
> wrapper.vm.$emit('customEvent', 1, 2, 3)
> ```
> 
> That will work!

No, it does not. I have a component "my-component", that emits a custom event "my_signal". Please write a test for the parent component using jest that function `my_signal` is called with 2 parameters when my-component emits the signal.

**Comment by lmiller1990** [comment]
Can you fork this repo and make a PR with your minimal failing case? That would make it easier to debug and fix the problem.
