### ISSUE TITLE
cannot mount component which have named slots 

### ISSUE THREAD

**Issue by socar-grab** [vuejs/vue-test-utils#1961]
### Subject of the issue

Rendering issues with components that use named slots

### Steps to reproduce

I'm trying to test a component that uses a named-slot. If you mount in this situation, an empty value is displayed as follows.

```javascript
// Dialog.vue
...
      <div>
        <slot name="dialogForm"> </slot>
      </div>
...
```

```javascript
// FilterDialog.vue
...
<Dialog>
    <template v-slot:dialogForm>
        <p> hello </p>
    </template>
</Dialog>
...
```

```javascript
// FilterDialog.spec.js
...
const wrapper = mount(TestComponent, propsData: {...})
...
```

### Expected behaviour

```javascript
// wrapper.html() result
  <div>
      <p> hello </p>    
  </div>
```

### Actual behaviour

```javascript
// wrapper.html() result
  <div>
    <!---->
  </div>
```

### Possible Solution

I want to render a component that uses a named slot, but it comes out with an empty value like this.
There was an article saying to do a shallow mount and process it with a stub, but it was inconvenient to have to re-set the event settings in the test

**Comment by lmiller1990** [comment]
Check https://vue-test-utils.vuejs.org/api/options.html#slots

Can you do something like

```js
mount(Comp, {
  slots: {
    dialogForm: /* something, see link */
  }
])
```
