### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'devtoolsRawSetupState')

### ISSUE THREAD

**Issue by jolting** [vuejs/vue-test-utils#1962]
### Subject of the issue

Beginning with Vue 3.2.25 and the latest version of vue-test-utils I started running into this error on some calls to `wrapper.findComponent({ref}) ` . The problem isn't observed with Vue 3.2.24.
```
    TypeError: Cannot read properties of undefined (reading 'devtoolsRawSetupState')
      at new VueWrapper (node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:7611:22)
      at Object.<anonymous> (node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:7729:79)
      at createVueWrapper (node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:1721:45)
      at VueWrapper.findComponent (node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:7311:24)
```

### Steps to reproduce

I don't have an example test case yet. This happens in a larger project. I will need to narrow down the cause first.

### Expected behaviour

`findComponent` should not throw the error

### Actual behaviour

`findComponent` sometimes throws an error.

### Possible Solution

Downgrade to Vue 3.2.24

**Comment by jolting** [comment]
I'm going to look into seeing if it's related to `v-for`. There was some work around this in 3.2.25

**Comment by jolting** [comment]
Incorrectly reported to here. This is for vue3

**Comment by dwjohnston** [comment]
Just incase anyone is encountering this error in 2026 - you can also encounter this error if you do this: 

❌
```
const wrapper = mount(h('div')); 
```

instead of

✅
```
const wrapper = mount(() => h('div'));
```
