### ISSUE TITLE
Render stencil web component in vue jest unit test

### ISSUE THREAD

**Issue by BobidaHombre** [vuejs/vue-test-utils#1966]
### Subject of the issue

In my vue3 project i started to write unit tests using Jest and Vue Test Utils. I'm using web components generated by Stencil.js and here is the problem. Jest don't render them so I can't test my Vue components without logic from web components.

### Steps to reproduce

Use any stencil web component library in component and then try to test It. The component won't render, so You cant use it's events etc.

### Expected behaviour
```
// in wrapper.html() result
<ds-icon class="a-dsIcon -email hydrated" style="font-size: 20px;"></ds-icon>
```
### Actual behaviour

```
// in wrapper.html() result
<ds-icon class="mr-2" size="24px" icon="email" color="green"></ds-icon>
```

### Possible Solution

According to Stencil documentation I need to apply pollyfils and define custom components with code:
```
applyPolyfills().then(() => {
    defineCustomElements()
})
```
But here is problem is that solution of problem? Where should I add this piece of code, so Jest will render It?

**Comment by lmiller1990** [comment]
What happens if you do that before your first test (above `it`)? 

I don't know Stencil, but this seems like it's likely a config issue, and not a bug in this library.

**Comment by Marujah** [comment]
it's a bug in the library, web components won't be rendered

**Comment by lmiller1990** [comment]
You mean a bug in Test Utils or in Vue?

Also this repo is for Vue 2's Test Utils. For Vue 3, go here: https://github.com/vuejs/test-utils

**Comment by mattclough1** [comment]
@BobidaHombre did you ever figure this out? Running into this now.

**Comment by BobidaHombre** [comment]
> @BobidaHombre did you ever figure this out? Running into this now.

Not really :(
