### ISSUE TITLE
Documentation's Portuguese Translation

### ISSUE THREAD

**Issue by nazarepiedady** [vuejs/vue-test-utils#1969]
### Documentation Feedback

In this issue I look for suggestions about what approach should I take to
do the pull request of the work I did.

I already did almost translate of the documentation, and I would like to know:

- [ ] Should I do a pull request with all documentation translated?
- [ ] Should I do a pull request for each documentation section translated?

@lmiller1990 since you did comment a issue made by me in the version 3,
I would like to ear from you, what do you think?

**Comment by lmiller1990** [comment]
Hi,

Where did we talk about a Portuguese translation? Can you link me that issue?

I'm finding it very challenging to maintain translations. One alternative, I'm thinking, would be to host the translations on other repos (eg your personal fork of this repo) and we could link to it from here.

The reason this might work better is so if you want to update the docs, you don't need to make a PR here every time. I don't know Portuguese, so I can't exactly review translations.

**Comment by nazarepiedady** [comment]
> Hi,
> 
> Where did we talk about a Portuguese translation? Can you link me that issue?

Here is the link to issue where we talked about [Translating the Documentation](https://github.com/vuejs/test-utils/issues/1340)
of the version 3 of this library.

However, I will follow your suggestion about serve the documentation by my own
and only share the link in official website, but since the website present some ads,
will not it make the website lose some money that is very important to maintain the projects?

**Comment by lmiller1990** [comment]
Interesting point about the ads, I don't think they bring in much money. I have a site w/ about 1M views / year using Carbon and it pulls in about $15 a month. 

For now, if you can get your translation live and deployed on your personal GitHub (using GitHub pages) we can get someone to give it a quick look and link to it from our docs. If it ever gets a ton of traction (100K+ views / year or something) we can consider the ad situation. 

To track views, you could use Google Analytics, or a similar product.
