### ISSUE TITLE
Cannot use mocks to mock #route and $routes for unit tests

### ISSUE THREAD

**Issue by DainVerd** [vuejs/vue-test-utils#1984]
Greetings I have question. I have unit test and I want to mock $route and $router
According [docs](https://v1.test-utils.vuejs.org/guides/using-with-vue-router.html#common-gotchas) I must not use `localVue.use(VueRouter)` So I did not used it. But then I apply unit test it is not working
"compiler# throws error what
![image](https://user-images.githubusercontent.com/55252915/179512878-edceb4e0-9856-4882-a6c0-22b8e1521ecf.png)

I checked i do not anywhere added else in unit test `localVue.use(VueRouter)`

My code of unit tests
code could be found [here](https://pastebin.com/fVMcNhWZ) where `//NR means what inside those components are no $roter/$route found`

So question is how to fix that?

**Comment by lmiller1990** [comment]
I'm sorry, I'll need a minimal reproduction to help with this. There's way too much going on in your example for it to be obivous what the problem is.

It looks like you are installing the router somewhere - maybe in another module you are importing?

**Comment by DainVerd** [comment]
@lmiller1990  thanks for response. I found the solution. Problem was what in code of component was used `store` not `this.$store` so this triggered error. Code in component worked properly but in unit tests it failed then I mocked store.

**Comment by lmiller1990** [comment]
Glad you found a solution!
