### ISSUE TITLE
No documentation for how to override computed properties in test mount

### ISSUE THREAD

**Issue by MohamedAbouelwafa** [vuejs/vue-test-utils#1998]
### Vue version

v2.x

### Link to minimal reproduction

https://v1.test-utils.vuejs.org/api/options.html

### Steps to reproduce

Navigate to https://v1.test-utils.vuejs.org/api/options.html
No documentation for how to override the computed properties.

### What is expected?

See a section in the documentation for how to override the computed properties.

### What is actually happening?

No section to show how to override the computed properties.

**Comment by lmiller1990** [comment]
You cannot override the computed properties. Just set their dependencies (data, props etc) and test using the actual values.

**Comment by MetRonnie** [comment]
I'm trying to unit test one particular computed property that depends on another computed property.
The only sane way to achieve this would be to mock the other computed property. But I think it is possible using `data`?
```js
mount(MyComponent, {
  data: () => ({
    computedProperty: something
  })
})
```
