### ISSUE TITLE
setValue() does not work on select elements when value is an object

### ISSUE THREAD

**Issue by ccmetz** [vuejs/vue-test-utils#2000]
### Subject of the issue

The `setValue()` method does not seem to work when used to set the value to an object on a select element. I'm unsure of whether or not this is a limitation of select elements, but it appears to work just fine when in my regular Vue application.

Package versions:
* @vue/test-utils v1.1.3
* jest v26.6.3

### Steps to reproduce

You can reproduce this with the following example:

Vue component template:
```
<template>
  <select v-model="selectedTest" data-test="select-test">
    <option v-for="test in [{id: 1, name: 'test'}, {id: 2, name: 'test 2'}]" :key="test.id" :value="test">
      {{test.name}}
    </option>
  </select>
  <p v-if="selectedTest && selectedTest.id === 2" data-test="paragraph-test">Am I here?</p>
</template>

<script>
export default {
  data() {
    return {
      selectedTest: null
    };
  }
}
</script>
```

Unit test:

```
test('test', async () => {
  const wrapper = mount(TestComponent);

  const select = wrapper.get('[data-test="select-test"]');
  await select.setValue({id: 2, name: 'test2 '});
  expect(wrapper.find('[data-test="paragraph-test"]').exists()).toBe(true);
});
```

### Expected behaviour

I'd expect the 2nd element of the test array to be selected and for the `v-model` to be updated and trigger the rendering of the `p` element.

### Actual behaviour

The 2nd element of the array is not selected and the unit test fails. In fact the 1st element gets selected (I believe this might be because the value is always set to `[object Object]` and that "matches" the first option.

### Possible Solution

No solutions to suggest but my current workaround is to modify the data variable directly instead and use `nextTick()` to wait for an update:

```
test('test', async () => {
  const wrapper = mount(TestComponent);

  const select = wrapper.get('[data-test="select-test"]');
  wrapper.vm.selectedTest = {id: 2, name: 'test 2'};
  await wrapper.vm.$nextTick();
  expect(wrapper.find('[data-test="paragraph-test"]').exists()).toBe(true);
});
```

**Comment by ebisbe** [comment]
As explained at the docs https://v1.test-utils.vuejs.org/api/wrapper/#setvalue 

```
const select = wrapper.find('select')
await select.setValue('option value')

expect(wrapper.find('select').element.value).toBe('option value')
 ```
 
 in your case the test should be:
 
 ```
 test('test', async () => {
  const wrapper = mount(TestComponent);

  const select = wrapper.get('[data-test="select-test"]');
  await select.setValue('test2');
  expect(wrapper.find('[data-test="paragraph-test"]').exists()).toBe(true);
});
```
