### ISSUE TITLE
Getting a DOM property (not attribute!)

### ISSUE THREAD

**Issue by thany** [vuejs/vue-test-utils#2004]
### Feature Description

Getting a DOM property for a `DOMWrapper` is currently not implemented, but is extremely neccesary to check, for example, the `value` property (not attribute!) on a text input element. Same for the `checked` property on a checkbox element.

### Problem

There exists seemingly no way to do this at all. But it's very helpful to check in a unittest whether a text input is (pre)filled with the correct value, or with any value at all.

As for the `value` property specifically, I have seen some folks using `text()` for this, but this function always returns an empty string - presumably because an input element indeed doesn't (and shouldn't) have any `textContent`.

### Expected behaviour

Something like `.find('input').prop('value')` could return the `value` property.
Alternatively, provide access to the underlying actual native `HTMLElement`.

### Alternatives

I really can't think of any, other than just deciding we can't test things like this.

**Comment by freakzlike** [comment]
Isn't this already possible by accessing `wrapper.element`?

```js
expect(wrapper.find('input[type="text"]').element.value).toBe('some value')
expect(wrapper.find('select').element.value).toBe('option value')
expect(radioInput.element.checked).toBeTruthy()
```

Source:
https://vue-test-utils.vuejs.org/api/wrapper/#setvalue
https://vue-test-utils.vuejs.org/api/wrapper/#setchecked

**Comment by thany** [comment]
I couldn't find any documentation on the `element` property existing. I don't like using undocumented features, because they might go away in a future version without prior warning.

Or this property was forgotten in writing the documentation?
Or I missed it completely? In which case, where is it please?

The fact that they are in an example, doesn't mean that it's the best way to do things. It's just one way. It's not on the left side under `Wrapper` in the documentation, so it feels like a bit of a naughty example - just willy-nilly using a feature that is described nowhere, or so it seems.

**Comment by freakzlike** [comment]
It's under `Wrapper` -> `Properties`: https://vue-test-utils.vuejs.org/api/wrapper/#element

**Comment by thany** [comment]
Oh I see, they don't deserve an entry in the navigation. It looks to me like

```
Properties
(no properties listed, so no properties)
Methods
(proceed to list every method)
```

**Comment by lmiller1990** [comment]
Doc updates are always welcome!
