### ISSUE TITLE
Cannot stub multiple router-view

### ISSUE THREAD

**Issue by wadakatu** [vuejs/vue-test-utils#2009]
### Subject of the issue

Cannot stub multiple router-view.
How to stub multiple router-view which have different name attribute?

Describe your issue here.

In my component, there are two router-view which have different name attribute.

Then, I tried multiple way to stub these two router-view separately in a test case.
However, none of them work.

### Steps to reproduce

1. create vue component.
```vue
<template>
    <div class="container">
        <div class="row">
            <router-view></router-view>
            <router-view name="card"></router-view>
        </div>
    </div>
</template>
```

2. create test for the component which you created at step1
```vue
beforeEach(() => {
    const localVue = createLocalVue();
    localVue.use(VueRouter);
    const router = new VueRouter();
    wrapper = shallowMount(Component, {
        localVue,
        router,
        stubs: {
            'router-view': MainMessageComponent,
            'router-view[name="card"]': MainCardComponent, <- not working
            // 'router-view card': MainCardComponent, <- not working
        }
    });
})

describe('Testing snapshot', () => {
    test('default', () => {
        console.log(wrapper.html());
    });
});
```

3. execute test

### Expected behaviour

```
<div class="container">
      <div class="row">
          <div>[MainMessageComponent]</div>
          <div>[MainCardComponent]</div>
      </div>
</div>
```

### Actual behaviour

Both router-view are replaced by MainMessageComponent.

```
<div class="container">
      <div class="row">
          <div>[MainMessageComponent]</div>
          <div>[MainMessageComponent]</div>
      </div>
</div>
```

### Possible Solution

I haven’t found any solution yet.
Is there any way to achieve this? or is it impossible to do it?

**Comment by lmiller1990** [comment]
I didn't know you could have multiple router views in the same component. Is this even a valid use case?

Right now there isn't a way to stub multiple components in the same component, like this. What is the use case?

I don't expect to support this feature; I'm mainly focused on bug fixes and long term maintenance.
