### ISSUE TITLE
Unsafe call of an any typed using await wrapper.vm.$nextTick();

### ISSUE THREAD

**Issue by felixzapata** [vuejs/vue-test-utils#2010]
Hi, using on my tests some of the example code about how to use the `emitted` from the [documentation page](https://v1.test-utils.vuejs.org/api/wrapper/emitted.html):

```
const wrapper = mount(Component)

  wrapper.vm.$emit('foo')
  wrapper.vm.$emit('foo', 123)

  await wrapper.vm.$nextTick()
```

I have a couple of type errors when I use the `$nextTick` method:

![Captura de pantalla 2022-09-22 a las 9 21 52](https://user-images.githubusercontent.com/997038/191684241-6c1a15da-df85-4656-8d31-3741337bb195.png)

My Vue project uses version 3 with Composition API (script setup), and SFC, written in TypeScript (including the tests). I use custom ESLint rules shared between the developer team, which set us to follow some strict rules of TypeScript. 

Is there a way to set the type to avoid this error without adding a disable rule or similar? Or even removing the line or [using a _setTimeout_ to 0](https://github.com/vuejs/vue/blob/fb93c1be77f12ea1375c5e8b47d168e4d5ceb7be/src/core/util/next-tick.ts#L84)? (I know that my test works without calling the function, but it should be there to wait until all the DOM is processed [to avoid collateral problems](https://v1.test-utils.vuejs.org/guides/#testing-asynchronous-behavior)).

**Comment by ebisbe** [comment]
@felixzapata This repository is for Vue 2.
