### ISSUE TITLE
the link to the docs for Vue 3 can not be accessed

### ISSUE THREAD

**Issue by maaax0222** [vuejs/vue-test-utils#2011]
https://next.vue-test-utils.vuejs.org/guide/

**Comment by techtolentino** [comment]
Should go here

https://test-utils.vuejs.org/

there's an approved PR for it but something's happening w/ the pipeline

🤞🏼

**Comment by Nicolascrd** [comment]
+1, this is quite annoying

**Comment by lmiller1990** [comment]
Sorry guys, I am working on fixing Netlify now.

If anyone else is interested in helping maintain Test Utils, pls let me know!

**Comment by lmiller1990** [comment]
Fixed https://github.com/vuejs/vue-test-utils/pull/2049
