### ISSUE TITLE
Webpack compilation fails with "Module not found: Default condition should be last one"

### ISSUE THREAD

**Issue by 3rdvision** [vuejs/vue-test-utils#2022]
### Subject of the issue

Webpack 5.68.0 fails compilation and throws the error message "Module not found: Default condition should be last one". Affected vue-test-utils versions are 1.3.1 onwards.

### Expected behaviour

Compilation is successful.

### Actual behaviour

Compilation fails with error.

### Possible Solution

Change the order of the default import line [here](https://github.com/vuejs/vue-test-utils/blob/dev/packages/test-utils/package.json#L7). This convention is being implemented in other places [example](https://github.com/vuejs/test-utils/blob/main/package.json#L15).
I see no reason why it shouldn't be here. This was introduced [here](https://github.com/vuejs/test-utils/pull/1484) where the [issue](https://github.com/vuejs/test-utils/issues/1483) had a properly ordered example. Maybe it was done by mistake when using a prettier tool? Please @sheremet-va let us know if there's any strong reason why the default should be first instead of last.

**Comment by sheremet-va** [comment]
Yes, I think default should be last as a fallback. It’s also interesting that test-utils doesn’t bundle mjs anymore? Is there any reason for that? I explaned why it’s need in the mentioned issue.

**Comment by lmiller1990** [comment]
I tried to fix it here https://github.com/vuejs/vue-test-utils/pull/2020/files. I guess the order matters? I had no idea. I've never seen "Module not found: Default condition should be last one" before.

Would someone like to make a PR?

**Comment by lmiller1990** [comment]
Oh, there is one: https://github.com/vuejs/vue-test-utils/pull/2023

I will release this now.

**Comment by lmiller1990** [comment]
Can you give this a try? https://github.com/vuejs/vue-test-utils/releases/tag/v1.3.3

Thanks.

**Comment by 3rdvision** [comment]
@lmiller1990 I can confirm that this is now fixed and working as expected on the latest 1.3.3 :partying_face:
Thank you for the fast response!
