### ISSUE TITLE
How to test <img :src="require(...)" /> that used when importing asset to image?

### ISSUE THREAD

**Issue by frederick-offeo** [vuejs/vue-test-utils#2028]
Hi,
I have quite a simple question, when i try to console.log `require('@/assets/images/projects/facebook.png');` it will not return any value. Usually i will try something like `expect(image.attributes().src).toBe(require('@/assets/images/projects/facebook.png');)` on testing. 
Any suggestion? anything would be a great help, thanks =)

P.S - i need this as when i mouseover/mouseleave the image, the src value changes.

**Comment by MatGarreau** [comment]
Hi @frederick-offeo how did you solve this point ? Tks by advance.
