### ISSUE TITLE
Broken Link to Vue Test Utils 3 Invalid Server Certificate

### ISSUE THREAD

**Issue by gitDylanHub** [vuejs/vue-test-utils#2037]
### Broken/Invalid Link to Vue Test Utils 3

When clicking on the drop-down to go to Vue Test Utils 3 Beta, https://next.vue-test-utils.vuejs.org/guide/ you will get an invalid certificate

```
Access denied due to bad server certificate
--
You tried to visit:https://next.vue-test-utils.vuejs.org/guide/
```

Same with the Warning Input at the top of the pages to redirect.

It seems to be the `next` domain

### Steps to reproduce

Go to https://v1.test-utils.vuejs.org/api/mount.html, use the drop-down or the click the redirect on the warning.

### Expected behaviour

What should happen? 
I should navigate to https://test-utils.vuejs.org/guide/

### Actual behaviour

What happens instead?
It navigates to https://next.vue-test-utils.vuejs.org/guide/ and an invalid server certificate, or SSL/TLS certificate

### Possible Solution

What are the alternative solutions? Please describe what else you have considered?
Fix the broken link

**Comment by lmiller1990** [comment]
Fixed https://github.com/vuejs/vue-test-utils/pull/2049

At least, should be good now.
