### ISSUE TITLE
Undefined value when using named imports from vue

### ISSUE THREAD

**Issue by rMonell** [vuejs/vue-test-utils#2038]
### Subject of the issue

I recently try to upgrade my project to Vue2.7.

After creating a component using a simple usage of the composition API as below (working fine) :

```js
import { computed } from 'vue'

...
setup (props) {
  const prefix = 'icon'
  const symbolId = computed(() => `#${prefix}-${props.name}`)
  return { symbolId }
},
...
```
I’ve got the folowwing error when runnning my test :

```
TypeError: (0 , _vue.computed) is not a function
```

When I’m trying to log the computed value on the component when running the test, it return undefined but it works when using Vue.computed()

I’ve notice [this (“Notes on API exposure” section)](https://blog.vuejs.org/posts/vue-2-7-naruto.html) in the Vue2.7 migration guide.

Did I miss something ?

Thank you in advance !

### Steps to reproduce

 - Start a new project using Vue2.7 and vue test utils
- Create a cmponent that using the composition API
- Run the test

### Expected behaviour

`import { computed } from 'vue'` should return the computed method.

### Actual behaviour

It returns `undefined`

**Comment by LinusBorg** [comment]
Hard to say definitely since you did not provide a runnable reproduction, but I would assume you are using the CJS build in your test setup (jest?), which, as mentioned in the linked docs, will expose these APIs on the Vue object only. 

If so, that would be unrelated to test-utils.

**Comment by rMonell** [comment]
Thank you for yout answer @LinusBorg  !

well that's exactly my issue :/

I can't determine what is the source of this difference between my component and the vue used in the test.

Is there a specific configuration of jest or anything else that would allow the test to correctly interpret the named import ?

I have to confess I'm a little bit confused with this issue ^^


If this can give you more visibility, here is my `jest.cong.js`

```js
module.exports = {
  preset: '@vue/cli-plugin-unit-jest',
  testEnvironment: "jsdom",
  testEnvironmentOptions: {
    customExportConditions: [
      "node",
      "node-addons"
    ]
  },
  setupFiles: ['./tests/setup.js', 'jest-canvas-mock'],
  setupFilesAfterEnv: ['./tests/setup-after-env.js'],
  coverageReporters: ['text', 'jest-junit', 'cobertura', 'lcov'],
  moduleNameMapper: {
    '^tests/(.*)$': '<rootDir>/tests/$1',
  },
  moduleFileExtensions: ["js", "json", "vue"],
  transform: {
    'vee-validate/dist/rules': 'babel-jest',
    "^.+\\.js$": 'babel-jest',
    ".*\\.(vue)$": '@vue/vue2-jest',
  },
  transformIgnorePatterns: [
    '<rootDir>/node_modules/(?!vee-validate/dist/rules|vuetify|@fortawesome|vue-chartjs/legacy)',
  ],
}
```

**Comment by ebisbe** [comment]
@rMonell is your issue solved?

**Comment by rMonell** [comment]
Yep ! I close the issue, I have come to the conclusion that vue-test-utils < 2 wasn't compatible with a full Vue 2.7 intégration. So I made a custom integration of the composition API in the following way :

```js
// local-composition.js
const Vue = process.env.NODE_ENV === 'test'
  ? require('vue').default
  : require('vue')

const ref = Vue.ref
const reactive = Vue.reactive
const watch = Vue.watch
const computed = Vue.computed
...

export {
  ref,
  reactive,
  watch,
  computed,
  ...
}
```

It works pretty fine, I haven't been able to find a better solution despite my research.
