### ISSUE TITLE
[vue-test-utils]: wrapper.setValue() cannot be called on this element

### ISSUE THREAD

**Issue by Destnyl** [vuejs/vue-test-utils#2055]
[vue-test-utils]: wrapper.setValue() cannot be called on this element

Hi Im having an isue with unit testing, it says that setValue cannot be called on the element. heres my  code 

### Steps to reproduce
--component--- 
//the input element that i was trying to access was a custom component <secondary-input>
        <validation-provider
          v-slot="{ errors }"
          rules="required|email"
          class="form-item"
          name="email"
        >
          <secondary-input
            v-model="state.login.email"
            :class="{
              'form-error': errors.length > 0
            }"
            name="email"
            placeholder="Email Address"
            data-qa="email-address"
            type="email"
          />
          <form-errors :errors="errors" />
        </validation-provider>
---testing--
  it('test if it has an input for email address', async () => {
    const value = 'sample@email.com'
    const input = wrapper.get(`[data-qa='email-address']`)
    await flushAll()
    await input.setValue(value)
    expect(input.element.value).toBe(value)
  })

### Expected behaviour
expected behaviour is to assign the value in email address input

### Actual behaviour
got an error of setting the value to input email address

is there anyone here who could help me to resolve my issue.

**Comment by Destnyl** [comment]
heres the component

        <validation-provider
          v-slot="{ errors }"
          rules="required|email"
          class="form-item"
          name="email"
        >
          <secondary-input
            v-model="state.login.email"
            :class="{
              'form-error': errors.length > 0
            }"
            name="email"
            placeholder="Email Address"
            data-qa="email-address"
            type="email"
          />
          <form-errors :errors="errors" />
        </validation-provider>

**Comment by lmiller1990** [comment]
Probably same as  https://github.com/vuejs/vue-test-utils/issues/1883

`setValue` needs a DOM element - you are finding a component (Vue instance).

Your code doesn't have have a minimal reproduction - please share a repo I can run. 

To fix it, you can probably do

```js
it('test if it has an input for email address', async () => {
  const wrapper = mount(Comp)
  const value = '[sample@email.com](mailto:sample@email.com)'
  const input = wrapper.get([data-qa='email-address'])
  // Get HTMLInputElement
  await input.get('input').setValue(value)
  expect(input.element.value).toBe(value)
})
```

If it still won't work, try posting a repository I can run and debug. Thanks!

**Comment by Destnyl** [comment]
<img width="505" alt="Screenshot 2023-02-08 at 10 39 34 AM" src="https://user-images.githubusercontent.com/68534644/217414816-8a14d337-3bd4-4a31-91fb-97440273e7fb.png">
hi @lmiller1990 , still not working
got this error

 Unable to find input within: 


<secondary-input name="email" placeholder="Email Address" data-qa="email-address" type="email" class=""></secondary-input>

**Comment by Destnyl** [comment]
<secondary-input name="email" placeholder="Email Address" data-qa="email-address" type="email" class=""></secondary-input>

**Comment by lmiller1990** [comment]
Please post your entire test code and component.

I don't know what `<secondary-input>` does, I can't even see your entire code. 

Are you using `shallowMount`? If you are, that's why you cannot find the `input`. Try using `mount`. That will render the entire tree, and you can access the `HTMLInputElement`.

**Comment by Destnyl** [comment]
nope not using shallowMount, heres the component


<template>
  <fragment>
    <header>
      <img src="/images/logo-pink.svg">
      <section>
        <h1>Administrator’s Dashboard</h1>
        <p>{{ $t('loginInstruction') }}</p>
      </section>
    </header>
    <div v-if="loginTask.isError">
      <template v-if="loginTask.last.error.response.status === 401">
        <form-errors :errors="['Email or password provided is incorrect. Please try again.']" />
      </template>
      <template v-else>
        <template v-if="Array.isArray(errorMessage)">
          <form-errors :errors="errorMessage" />
        </template>
        <template v-else>
          <form-errors :errors="[errorMessage]" />
        </template>
      </template>
    </div>
    <validation-observer v-slot="{ handleSubmit, invalid }">
      <form
        autocomplete="off"
        @submit.prevent="handleSubmit(onFormSubmit)"
      >
        <validation-provider
          v-slot="{ errors }"
          rules="required|email"
          class="form-item"
          name="email"
        >
          <secondary-input
            v-model="state.login.email"
            :class="{
              'form-error': errors.length > 0
            }"
            name="email"
            placeholder="Email Address"
            data-qa="email-address"
            type="email"
          />
          <form-errors :errors="errors" />
        </validation-provider>
        <validation-provider
          v-slot="{ errors }"
          rules="required"
          class="form-item"
        >
          <secondary-input
            v-model="state.login.password"
            :class="{
              'form-error': errors.length > 0
            }"
            name="password"
            type="password"
            placeholder="Password"
          />
          <form-errors :errors="errors" />
        </validation-provider>
        <div class="forgot-password">
          <action-link @click.native="onForgotPassword">
            Forgot Password?
          </action-link>
        </div>
        <base-button
          :disabled="invalid"
          type="submit"
          :full-width="true"
          label="Sign In"
        />
      </form>
    </validation-observer>
  </fragment>
</template>

<script>
import { reactive } from '@nuxtjs/composition-api'
import { ValidationProvider, ValidationObserver } from 'vee-validate'

export default {
  components: {
    ValidationProvider,
    ValidationObserver
  },
  props: {
    loginTask: {
      type: Object,
      required: true
    },
    errorMessage: {
      type: [Array, String],
      required: false,
      default: () => ''
    }
  },
  setup (props, { emit }) {
    const state = reactive({
      login: {
        email: '',
        password: ''
      }
    })

    const onFormSubmit = () => {
      // emit('form-submit', state.login)
      props.loginTask.perform(state.login)
    }
    const onForgotPassword = () => emit('forgot-password')

    return {
      state,
      onFormSubmit,
      onForgotPassword
    }
  }
}
</script>

<style lang="scss" scoped>
  header {
    display: flex;
    flex-direction: column;
    row-gap: $margin;

    section {
      display: flex;
      flex-direction: column;
      row-gap: $base;
    }

    img {
      max-width: 179px;
      height: auto;
      width: 100%;
      display: block;
      margin: 0 auto;
    }
    h1 {
      font-size: 20px;
      line-height: 28px;
      color: $black;

      max-width: 25ch;
      margin: 0 auto;
    }
  }

  p {
    color: $darkgrey;
    font-size: 14px;
    line-height: 20px;
  }

  .forgot-password {
    padding-top: #{$multiple * 3}px;
    padding-bottom: #{$multiple * 4}px;
  }

  .form-item {
    & + & {
      margin-top: $margin;
    }

    display: block;
  }

  .form-error {
    ::v-deep input {
      border-color: $red;
    }
  }
</style>

**Comment by Destnyl** [comment]
here's the test code, not using shallowMount
```
import { mount, createLocalVue } from '@vue/test-utils'
import flushPromises from 'flush-promises'
import LoginDefault from '@/components/LoginPage/Default.vue'

const localVue = createLocalVue()
jest.useFakeTimers()

describe('LoginPage/Default.vue', () => {
  const wrapper = mount(LoginDefault, {
    localVue,
    propsData: {
      loginTask: {
        isError: false,
        last: {
          error: {
            response: {
              status: 401
            }
          }
        }
      }
    },
    beforeCreate () {
      this.$t = jest.fn(key => key)
    }
  })

  const flushAll = async () => {
    await flushPromises()
    // any delayed or debounced state computations
    jest.runAllTimers()
    // get rid of the pending rendering tick
    await flushPromises()
  }

  beforeEach(async () => {
    await flushAll()
  })

  it.skip('Login component Snapshat', () => {
    expect(wrapper.element).toMatchSnapshot()
  })

  it('test if it has an input for email address', async () => {
    const value = 'sample@email.com'
    const input = wrapper.get(`[data-qa='email-address']`)
    await flushAll()
    await input.get('input').setValue(value)
    expect(wrapper.find('input').toBe(true))
    expect(input.element.value).toBe(value)
  })
})
```

**Comment by Destnyl** [comment]
[SecondaryInput copy.txt](https://github.com/vuejs/vue-test-utils/files/10681225/SecondaryInput.copy.txt)
[Default copy.txt](https://github.com/vuejs/vue-test-utils/files/10681232/Default.copy.txt)

**Comment by lmiller1990** [comment]
Hm this looks all okay. I'd recommend some debugging - `console.log` where you emit the event, etc. I see

```js
 <input
            v-bind="{
              ...$attrs,
              disabled
            }"
            ref="input"
            :class="cssClasses"
            v-on="listeners"
          >
```

Which binds to `listeners`

```js
input: (event) => {
          this.$emit('input', event.target.value)
        },
```

I'd log in here - is this getting called?

Looking at `setValue` in Test Utils...

https://github.com/vuejs/vue-test-utils/blob/5013304e492818e050edcd609429a3161227910a/packages/test-utils/src/wrapper.js#L795-L797

```js
      this.element.value = value

      this.trigger('input')
```

So it should be working okay.

If you cannot debug it, please *share a minimal repository I can debug*. I don't have bandwidth to make a repo, copy paste your code, etc.

**Comment by Destnyl** [comment]
thanks @lmiller1990  for the ideas,

created a workaround for this issue,

  it('test if it set value for email address', async () => {
    const value = 'sample@email.com'
    await wrapper.setData({
      state: {
        login: {
          email: value
        }
      }
    })
    wrapper.vm.$emit('input', value)
    await wrapper.vm.$nextTick()
    expect(wrapper.emitted('input')[0]).toEqual([value])
  })

just checking the value that was passed from the email field from the emitted values of the custom component.

**Comment by Destnyl** [comment]
hi @lmiller1990 , follow up question about this, the reason why it can't setvalue to the custom input is that it can't find the element input in the child component(secondary-input.) 

and I tried to console log the wrapper and it doesn't show all element in the child component. 

why can't get all the elements in the child component?

made some research but can't find the answer.

**Comment by lmiller1990** [comment]
> why can't get all the elements in the child component?

You should be able to get all elements. If you can't, it's a bug. Please make a minimal reproduction showing your bug. I cannot help you until I have some code I can run - I'm basically just guessing, otherwise.

**Comment by Destnyl** [comment]
hi @lmiller1990 , added you as my collaborator, sent invite thanks.
