### ISSUE TITLE
wrapper.emitted updates previous event parameters when the event is triggered again

### ISSUE THREAD

**Issue by dmodliba** [vuejs/vue-test-utils#2057]
### Subject of the issue

I want to test if an emitted custom event works properly. `wrapper.emitted()` indeed shows one element for each time the custom event was emitted, but all of these have the same content.

### Steps to reproduce

`Component.vue`
```vue
<template>
  // ...
</template>
<script setup lang="ts">
  import { defineEmits, reactive, watch } from "vue";

  const emits = defineEmits([
    "update:modelValue"
  ]);

  const model = reactive([]);

  watch(model, () => {
    emits("update:modelValue", model);
  });
</script>
```

`Component.spec.ts`
```ts
  import Component from "@/components/Component.vue";

  import { mount } from "@vue/test-utils";

  describe("model binding", () => {
    
    it("emits 'update:modelValue' if model changes", async () => {
      const wrapper = mount(Component);

      wrapper.vm.model.push("foo");
      await wrapper.vm.$nextTick();
      console.log(wrapper.emitted()["update:modelValue"]); // CHECKPOINT A

      wrapper.vm.model.push("bar");
      await wrapper.vm.$nextTick();
      console.log(wrapper.emitted()["update:modelValue"]); // CHECKPOINT B

      wrapper.vm.model.pop();
      await wrapper.vm.$nextTick();
      console.log(wrapper.emitted()["update:modelValue"]); // CHECKPOINT C

      expect(wrapper.emitted()["update:modelValue"].length).toBe(3); // PASS
      expect(wrapper.emitted()["update:modelValue"][0]].toStrictEqual([
        ["foo"]
      ]); // PASS
      expect(wrapper.emitted()["update:modelValue"][1]).toStrictEqual([
        ["foo", "bar"]
      ]); // FAIL
      expect(wrapper.emitted()["update:modelValue"][2]).toStrictEqual([
        ["foo"]
      ]); // would PASS but not reached because previous expect already fails
    });
  });
```

### Expected behaviour

I expect the following outpouts (which in fact would make the test pass):
`// CHECKPOINT A`
```json
[
  [ [ "foo" ] ]
]
```

`// CHECKPOINT B`
```json
[
  [ [ "foo" ] ],
  [ [ "foo", "bar" ] ]
]
```

`// CHECKPOINT C`
```json
[
  [ [ "foo" ] ],
  [ [ "foo", "bar" ] ],
  [ [ "foo" ] ]
]
```

### Actual behaviour

`// CHECKPOINT A`
```json
[
  [ [ "foo" ] ]
]
```

`// CHECKPOINT B`
```json
[
  [ [ "foo", "bar" ] ],
  [ [ "foo", "bar" ] ]
]
```

`// CHECKPOINT C`
```json
[
  [ [ "foo" ] ],
  [ [ "foo" ] ],
  [ [ "foo" ] ] 
]
```

### Possible Solution

This behaviour can still be tested successfully though. For example, here is the workaround I used:
`Component.spec.ts`
```ts
  import Component from "@/components/Component.vue";

  import { mount } from "@vue/test-utils";

  describe("model binding", () => {
    
    it("emits 'update:modelValue' if model changes", async () => {
      const wrapper = mount(Component);

      wrapper.vm.model.push("foo");
      await wrapper.vm.$nextTick();
      expect(wrapper.emitted()["update:modelValue"][0]).toStrictEqual([
        ["foo"]
      ]); // PASS

      wrapper.vm.model.push("bar");
      await wrapper.vm.$nextTick();
      expect(wrapper.emitted()["update:modelValue"][1]).toStrictEqual([
        ["foo", "bar"]
      ]); // PASS

      wrapper.vm.model.pop();
      await wrapper.vm.$nextTick();
      expect(wrapper.emitted()["update:modelValue"][2]).toStrictEqual([
        ["foo"]
      ]); // PASS

      expect(wrapper.emitted()["update:modelValue"].length).toBe(3); // PASS
    });
  });
```

**Comment by lmiller1990** [comment]
What seems to be happening is `emitted` is keeping a reference to the original object (JS is pass by reference for objects). The same issue happens in v2 of this lib, for Vue 3.

What happens if you do something similar in production? I suspect the same problem. I don't think this is a bug in Test Utils - but just the side effect of JS passing by reference.

Proving this theory, it passes if you do:

```js
  watch(model, () => {
    // console.log({model})
    emits("update:modelValue", JSON.parse(JSON.stringify((model))));
  });
```

Which avoids passing by reference.

I would recommend not emitting a reactive value from `update:modelValue`, since the pass-by-reference nature of JS will likely lead to hard-to-find bugs and side effects.

I'm going to close this - I don't think deep cloning makes sense, since that isn't what Vue will do - we want to match the behavior in core, which is what's happening here - emit the object by reference, if that's what you passed to the event.

LMK if you need more pointers/have a more realistic, production scenario where you need to do something like this.

**Comment by alancortez-lumen** [comment]
@dmodliba if this holds:
"Components using <script setup> are closed by default - i.e. the public instance of the component, which is retrieved via template refs or $parent chains, will not expose any of the bindings declared inside <script setup>.

To explicitly expose properties in a <script setup> component, use the defineExpose compiler macro."
source:https://vuejs.org/api/sfc-script-setup.html#defineexpose

How are you able to even access **wrapper.vm.model**? You should be getting {} for your wrapper.vm
