### ISSUE TITLE
mount().find(component:Component) seems broken since beta-5

### ISSUE THREAD

**Issue by stasson** [vuejs/vue-test-utils#206]
This kind of test spec:

```javascript
  const localVue = createLocalVue()
  localVue.use(plugin)
  const spec = mount(ComponentWithChild, localVue)

  describe('Child', () => {
    const child= spec.find(Child)
    // expect child to be found
  })
```
see this [test.spec](https://github.com/stasson/vue-mdc-adapter/blob/master/components/drawer/test.spec.js#L19) use to work with beta-4  but stoped working on [beta-5](https://github.com/stasson/vue-mdc-adapter/issues/107) and still fail on [beta-6](https://github.com/stasson/vue-mdc-adapter/pull/118)

I have tried to inspect the code change to see if there was anything obvious, but I'm failing so-far. 
I'm not even sure the issue comes from `find`, I'm just wondering if the ComponentWithChild is being properly mounted

Any idea what I should check to debug the issue ?

**Comment by eddyerburgh** [comment]
Thanks for the bug report 😀

You're passing localVue incorrectly, it should be passed in the mounting options object:
```js
const spec = mount(ComponentWithChild, { localVue })
```

Would you be able to create a minimal reproduction. There might be an edge case caused by how you're mounting the component, but I can't tell from your example.

**Comment by stasson** [comment]
indeed everything back to [normal](https://travis-ci.org/stasson/vue-mdc-adapter/builds/308046831) when I pass the localVue properly.  
I'm now wondering if I am getting crazy: How would this even have worked before !?!  
Anyway, thanks a lot for the quick perfect answer !
