### ISSUE TITLE
SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by Ttou** [vuejs/vue-test-utils#210]
when use element-ui with **babel-plugin-compnent,** run test unit will report an error

![i18n-fs8](https://user-images.githubusercontent.com/4298437/33301123-f16a373a-d42e-11e7-98ed-e67412268421.png)
![error-fs8](https://user-images.githubusercontent.com/4298437/33301127-0182cba0-d42f-11e7-868f-1fecc2eb57ee.png)

**Comment by eddyerburgh** [comment]
This looks like you need to add a CSS loader, are you using mocha-webpack?

**Comment by Ttou** [comment]
@eddyerburgh both jest and mocha-webpack will reporting the same problem

**Comment by eddyerburgh** [comment]
I'm pretty sure this isn't a vue-test-utils issue, can you make a more detailed post on StackOverflow. I might be able to help you.

This issue tracker is reserved for bugs and feature requests only.

**Comment by Ttou** [comment]
Agree with you. I have solved it by add this code in package.json.

![solve-fs8](https://user-images.githubusercontent.com/4298437/33310911-2680ae8e-d45e-11e7-9c8c-5c1818a84de1.png)

**Comment by Nick-Hopps** [comment]
I have the same error with mochapack, is there any clue?
