### ISSUE TITLE
preventDefault:true option overwrites method

### ISSUE THREAD

**Issue by mokkabonna** [vuejs/vue-test-utils#211]
I have a listener like this:

```html
<input @keydown.enter.prevent="enter">
```
And dispatch the event like this:

```js
wrapper.trigger('keydown.enter', {
  preventDefault: true
})
```

And get the following error

```
Uncaught TypeError: $event.preventDefault is not a function
```

It iterates over all options and set them:
https://github.com/vuejs/vue-test-utils/blob/dev/src/wrappers/wrapper.js#L533

preventDefault should not be set to true. Suggest either changing the option name to a non conflicting one, or removing it from the iterated keys. Or set it to a noop function.

I know I am doing preventDefault twice, but it shouldn't fail anyway imo.

**Comment by eddyerburgh** [comment]
Thanks for the bug report, I agree that it shouldn't error.

Would you be able to make a PR to fix this?

**Comment by mokkabonna** [comment]
I can do that. 

------
I wonder though, why is that option there in the first place? Isn't it the code under test that has the responsibility to prevent the default action? Now you can have a test that passes since the test itself prevents the default, but it is no guarantee that the code under test prevents the default action.

Aren't triggering events meant to simulate user interactions? The user can't (AFAIK) prevent the default action to happen.

**Comment by eddyerburgh** [comment]
You're correct, I don't think that option should be there. 

I believe it was added in response to a user request, but I can't find the issue. I'm going to remove the code that runs preventDefault.
