### ISSUE TITLE
Feature request: Add setStubs method

### ISSUE THREAD

**Issue by disitec** [vuejs/vue-test-utils#214]
It would be great to implement a setStubs method. In most cases we use a global wrapper which is modified in specific tests with `setData`, `setProps`, `setComputed` and so on. 

I find this approach quite clean and readable but when I want to stub components I have to recreate the wrapper only for this reason.

Is there a plan to implement it? It is even possible?

Thanks!

**Comment by eddyerburgh** [comment]
This is possible.

Assuming you'd like to restore stubs, we'd need to keep track of all the stubbed components. I'd like to get other opinions on whether this would be useful for users.

**Comment by eddyerburgh** [comment]
There's a config object that you can use to set stubs—https://vue-test-utils.vuejs.org/en/api/config.html

Does this solve your problem?

**Comment by disitec** [comment]
That is the object we use. My proposal was modify a wrapper created in the beforeEach as we do with setData, setProps... 

Without this method we always have to recreate the full wrapper. Maybe is a wrong workflow. I don't know.

**Comment by eddyerburgh** [comment]
Aha, I understand. I believe this will be difficult to implement.

**Comment by disitec** [comment]
Yeah. I am always learning best practices and happy to see different points of view. But there are cases when a component always have a shared scenario. It is a bit redundant, for me, reproducing over and over again the almost same wrapper.

I am not forcing you to develop this feature. I just only thinking out loud. 😄

**Comment by LinusBorg** [comment]
> It is a bit redundant, for me, reproducing over and over again the almost same wrapper.

I understand the feeling, but can only recommend to write clean, isolated tests nontheless.

the boilerplate you have to write is not more, and it's not really a performance issue either unless the component is monstrously big and doing heavy computations in `created` or something.

**Comment by eddyerburgh** [comment]
I'm closing this. As @LinusBorg said, it would encourage reusing a wrapper between tests, which could cause leaks between tests.
