### ISSUE TITLE
Events emitted on mount not captured

### ISSUE THREAD

**Issue by fergaldoyle** [vuejs/vue-test-utils#215]
Events emitted immediately in the `mounted` hook are not captured by `wrapper.emitted()`. With something like the below
- event `something` is not captured
- event `something-else` is not captured on first emit in the immediate watcher, but is captured on subsequent watcher callbacks
- event `toggle` is captured if the `toggle` method is called after mount, e.g. on user click

```javascript
{
  mounted() {
    this.$emit('something');
    
    this.$watch('foo', (v) => {
      this.$emit('something-else');
    }, { 
      immediate: true 
    });
    
  },
  methods: {
    toggle() {
      this.$emit('toggle');
    }
  }
}
```

**Comment by wtho** [comment]
This happens, because the [wrapper attaches to the component](https://github.com/vuejs/vue-test-utils/blob/8904ddd407eade79611f6ffaaa79ad544d0a7e0f/src/mount.js#L32) **after** the component was [created and mounted](https://github.com/vuejs/vue-test-utils/blob/8904ddd407eade79611f6ffaaa79ad544d0a7e0f/src/mount.js#L20).

I do not know if there is a way to change this, but I have the feeling if we do not attach the wrapper earlier there might be more edge cases where the wrapper is not ready when the component gets created.

One possibility I see is to install the wrapper earlier is via `beforeCreate`-mixin. It would be called by the Vue-framework after the vm-object is instiated but before the Vue-component is created and mounted, and so we could do the setup then already. We might have to split the actions done in `vue-wrapper.js` in several hooks.

But maybe there are other ways as well.

**Comment by eddyerburgh** [comment]
I was thinking we could add a listener object before mount and pass it to VueWrapper when it's created and merge that listener object with the current listener object.

**Comment by wtho** [comment]
Ok, so what worked for me was this (using the `logEvents` method in `src/lib/log-events.js`):
```js
localVue.mixin({
  beforeCreate: function() {
    this.$_emitted = {}
    this.$_emittedByOrder = []
    logEvents(this, this.$_emitted, this.$_emittedByOrder)
  }
})
```
It does catch all events from `beforeCreate` on in a variable of the component (in this case `$._emitted`). In the constructor we could then copy these self-tracked events to the wrapper. The mixin could be added in every `localVue` instance when creating it.

This approach is quite naive and the first listener should be removed after the wrapper is created. It also seems a bit hacky and not too clean to use a field on the component.

Those are just my ideas. I would be interested if you know a better way to add the listener.

**Comment by eddyerburgh** [comment]
I can't think of a better way. Would you like to implement @wtho ?

**Comment by wtho** [comment]
@eddyerburgh I will submit a PR this weekend

**Comment by eddyerburgh** [comment]
Fixed in 1.0.0-beta.7, thanks @wtho!

**Comment by websmurf** [comment]
I'm having similar issues when trying to test a component that has an updated method with an emit in it. Could it be that there is an issue with this as well?

component: 
```javascript
updated () {
    this.$emit('table-updated')
}
```

in my test: 
```javascript
console.log(wrapper.emitted('table-updated'))
```

result:
```javascript
    console.log test/unit/specs/Table/Table.spec.js:73
      undefined
```

coverage documentation shows that the lines are being executed properly.

**Comment by god-of-js** [comment]
> Ok, so what worked for me was this (using the `logEvents` method in `src/lib/log-events.js`):
> 
> ```js
> localVue.mixin({
>   beforeCreate: function() {
>     this.$_emitted = {}
>     this.$_emittedByOrder = []
>     logEvents(this, this.$_emitted, this.$_emittedByOrder)
>   }
> })
> ```
> 
> It does catch all events from `beforeCreate` on in a variable of the component (in this case `$._emitted`). In the constructor we could then copy these self-tracked events to the wrapper. The mixin could be added in every `localVue` instance when creating it.
> 
> This approach is quite naive and the installed listener should be removed after the wrapper is created. It also seems a bit hacky and not too clean to use a field on the component.
> 
> Those are just my ideas. I would be interested if you know a better way to add the listener.

Hey, man.
I am trying to get this to work for me but to no avail.

I have a BaseModal component where I am emitting a close event when the esc key on the keyboard is pressed.
Let me represent it in code:
```
<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import { mapState } from "vuex";
import ModalContainer from "./ModalContainer.vue";
import ModalCard from "./ModalCard.vue";
import ModalShowUserId from "./ModalShowUserId.vue";
@Component({
  name: "BaseModal",
  components: {
    ModalContainer,
    ModalCard,
    ModalShowUserId,
  },
  computed: {
    ...mapState(["activeModal"]),
  },
})
export default class BaseModal extends Vue {
  activeModal!: string;
  mounted(): void {
    const invokeClose = () => {
      this.closeModal();
    };
    // Adding close on escape for keyboard users.
    document.addEventListener("keydown", function (event) {
      if (event.key === "Escape") {
        // Making use of invokeClose here because `this` and IIFE's are not available at this point.
        invokeClose();
        // Property 'closeModal' does not exist on type 'Document'
        // this.closeModal();
      }
    });
  }
  beforeDestroy(): void {
    document.removeEventListener("keydown", () => {
      console.log("component destroyed.");
    });
  }

  closeModal(): void {
    this.$emit("closeModal");
  }
}
</script>

<template>
  <modal-container>
    <modal-card>
      <div :class="$style['u-flex-end']">
        <base-button
          styleType="c-base-button--transparent"
          @click="closeModal"
          class="js-modal-button"
          >CLOSE or PRESS ESC</base-button
        >
      </div>
      <component :is="activeModal" />
    </modal-card>
  </modal-container>
</template>

<style module lang="scss">
.u-flex-end {
  display: flex;
  justify-content: flex-end;
}
</style>

```

The component works perfectly, but I am trying to test that it closes on escape.
I wrote this test for it, and modified it with your own:

```import {  createLocalVue, shallowMount } from "@vue/test-utils";
import BaseModal from "./_base-modal.vue";
const localVue = createLocalVue();
localVue.mixin({
  mounted: function() {
    this.$_emitted = {}
    this.$_emittedByOrder = []
    logEvents(this, this.$_emitted, this.$_emittedByOrder)
  }
})
describe("@/components/_base-modal.vue", () => {
  it("Modal close button should trigger event when clicked.", () => {

    const wrapper = shallowMount(BaseModal, {
      computed: {
        activeModal () {
          return "ModalShowUserId";
        }
      }
    });
    wrapper.find(".js-modal-button").trigger("click");
    expect(wrapper.emitted().closeModal).toBeTruthy();
  });
  it("Modal should close when the escape key is triggered", () => {
    const wrapper = shallowMount(BaseModal, {
      attachTo: document.body,
      computed: {
        activeModal () {
          return "ModalShowUserId";
        }
      }
    });
    wrapper.trigger('keydown.esc');
    expect(wrapper.emitted().closeModal).toBeTruthy();
  });
});
```

But I am getting this error: 
```
8:42 Property '$_emittedByOrder' does not exist on type 'VueConstructor<Vue> | ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<...>, Record<...>>'.
  Property '$_emittedByOrder' does not exist on type 'VueConstructor<Vue>'.
     6 |     this.$_emitted = {}
     7 |     this.$_emittedByOrder = []
  >  8 |     logEvents(this, this.$_emitted, this.$_emittedByOrder)
       |                                          ^
     9 |   }
    10 | })
    11 | describe("@/components/_base-modal.vue", () => {
```
And this error only originated because of the part of your code I added (No offense).
Except from this, my "Modal should close when the escape key is triggered" block was the only thing failing.

Can you tell me if there was something you did differently? or tell me how I could solve this issue.
Cheers!
