### ISSUE TITLE
Discussion: Best API for stubbing methods?

### ISSUE THREAD

**Issue by eddyerburgh** [vuejs/vue-test-utils#22]
Currently, to stub methods on a component you need to do this:

```js
const wrapper = mount(TestComponent)
wrapper.vm.clickHandler = sinon.stub() // Stub the method
wrapper.update() // Force the vm to update
wrapper.find('button').trigger('click')
expect(wrapper.vm.clickHandler.called).to.equal(true)
```

I think we should either add a method, or an option that stubs component methods:

```js
// Method
const wrapper = mount(TestComponent)
wrapper.stubMethod(clickHandler, sinon.stub()) // Stubs the method and forces update
wrapper.find('button').trigger('click')
expect(wrapper.vm.clickHandler.called).to.equal(true)
```
It could also be called `setMethods`, like the `setData` and `setProps` methods, and take an object.

```js
// Option
const wrapper = mount(TestComponent, {
    stubMethods: { // stubs methods before mount
        clickHandler: clickHandlerStub
    }
})
wrapper.find('button').trigger('click')
expect(wrapper.vm.clickHandler.called).to.equal(true)
```

Personally I prefer the `stubMethod`/ `setMethods` approach, but I'd like to hear peoples thoughts 🙂

**Comment by jackmellis** [comment]
I previously had a hook that was called before the component was mounted, which exposed a deep copy of the component so you could manually stub it's methods (without affecting the original component). But i actually really like your approach, I think it's really simple.

A couple of thoughts:
- would you want the option to restore a stubbed method at a later point?
- could you stub a method without having to provide an alternate function `{clickHandler:true}`
- what about computed properties? There have been times when a method relies on a computed property that is so complicated it's taken me far outside the purpose of my unit test just to get the right computed value!

**Comment by philefstat** [comment]
I prefer setMethods as it is consistent with setData and setProps. However, I think there should also be a method to retrieve them as it could be confusing that you then have to use the vm to check if it has been called. 

```
wrapper.stubMethod(clickHandler, sinon.stub())
...
expect(wrapper.vm.clickHandler.called).to.equal(true)
```

With the current way, at least the way you set and get is consistent.
```
wrapper.vm.clickHandler = sinon.stub() 
...
expect(wrapper.vm.clickHandler.called).to.equal(true)
```

**Comment by eddyerburgh** [comment]
@philefstat 

We could recommend this pattern:
```js
const clickHandlerStub = sinon.stub()

wrapper.stubMethod('clickHandler', clickHandlerStub)
...
expect(clickHandlerStub.called).to.equal(true)
```
Or this:
```js
const clickHandlerStub = sinon.stub()

wrapper.stubMethods({
  clickHandler: clickHandlerStub
})
```

**Comment by eddyerburgh** [comment]
@jackmellis 
>would you want the option to restore a stubbed method at a later point? 
I don't think so, with `stubMethod` you could save the original before stubbing and then restore it later with the same method.

>could you stub a method without having to provide an alternate function {clickHandler:true}
Yeah I think that's a good idea

>what about computed properties? 

Yes I think that a `setComputed` method would be a good idea if `setData` does not work for a use case. Would you be able to provide example where `setData` doesn't work, so I can use it as a test case?

**Comment by philefstat** [comment]
@eddyerburgh those both look great 👍 

That pattern also allows some of the useful sinon methods to be called on the stub without reaching directly into the vm.

i.e.
`clickhandlerStub.resetHistory()`

stubMethods could be quite useful for larger components with multiple methods that need to be stubbed.

```
const methods = {
  foo: sinon.stub(),
  bar: sinon.stub(),
  baz: sinon.stub()
}

wrapper.stubMethods(methods)

...

expect(methods.foo).to.be.calledOnce
expect(methods.bar).to.be.calledTwice
```

**Comment by eddyerburgh** [comment]
There's now a `setMethods` method.

We should have a setComputed method too. I've created a new issue for that:

https://github.com/vuejs/vue-test-utils/issues/55

**Comment by heygambo** [comment]
`setMethods` worked great.

like here:
```javascript
const spy = jest.spyOn(wrapper.vm, 'handleChange')
wrapper.setMethods({ handleChange: spy })
wrapper.find('.some-input').trigger('change')
expect(spy).toHaveBeenCalled()
```

**Comment by chandreshSpringer** [comment]
Hi All,

      const spy = sinon.stub()
      wrapper.setMethods({ onClickCreate: spy })
      wrapper.find('#btn-create-proposal').trigger('click')
      expect(spy.called).toBe(true)

this is not working.
In Actual the method defined in component being mounted is being called.
Thanks for help in advance

**Comment by god-of-js** [comment]
Hey guys, 
Hey guys, I have this file picker component that I am trying to test. The component receives the file through the `takeFile` method.
```
<script lang="ts">
import { defineComponent, ref } from '@nuxtjs/composition-api'
import AppButtonCard from '~/components/Button/AppButtonCard.vue'
export default defineComponent({
  components: {
    AppButtonCard
  },
  setup (_props, { emit }) {
    const isDraging = ref(false)
    const openFilePicker = () => {
      (document.querySelector('#file-upload') as any).click()
    }
    const handleSelectedFiles = (e: any) => {
      const file = takeFile(e)
      if (isValidFile(file)) {
        emit('getFile', file)
      } else {
        emit('invalidFile')
      }
    }
    const takeFile = (e: any) => {
      return e.dataTransfer ? [...e.dataTransfer.files][0] : e.target.files[0]
    }
    const isValidFile = (file: File) => {
      try {
        const acceptedSuffixTypes = ['pdf', 'epub', 'txt', 'docx', 'rtf']
        const fileName = file.name
        const dot = fileName.lastIndexOf('.')
        const suffix = fileName.substr(dot + 1)
        if (acceptedSuffixTypes.includes(suffix)) {
          return true
        } else {
          return false
        }
      } catch (_) {
        return false
      }
    }
    return {
      openFilePicker,
      handleSelectedFiles,
      isDraging
    }
  }
})
</script>
```

I am trying to mock the takeFile method so that when it is called, it uses the mocked file. I am making use of sinon. But it seems the fileis not getting into the component.

```
import { mount } from '@vue/test-utils'
import sinon from 'sinon'
import FileUpload from './FileUpload.vue'
describe('~/components/Files/FileUpload.vue', () => {
  it('it emits an error when an invalid file is picked.', () => {
    const invalidFile = {
      name: 'image.png',
      size: 2887225,
      type: 'image/jpeg',
      lastModified: 1639671510625,
      lastModifiedDate: 'Thu Dec 16 2021 17:18:30 GMT+0100 (West Africa Standard Time)'
    }
    const takeFile = sinon.fake.returns(invalidFile)
    const wrapper = mount(FileUpload, {
      mocks: {
        takeFile
      }
    })

    const fileInput = wrapper.find('input[type="file"]')
    fileInput.trigger('change')

    expect(wrapper.emitted().invalidFile).toBeDefined()
  })
  it('it emits the file when the file is valid and has been processed.', () => {
    const validFile = {
      name: 'document.pdf',
      size: 2887225,
      type: 'application/pdf',
      lastModified: 1639671510625,
      lastModifiedDate: 'Thu Dec 16 2021 17:18:30 GMT+0100 (West Africa Standard Time)'
    }
    const takeFile = sinon.fake.returns(validFile)
    const wrapper = mount(FileUpload, {
      mocks: {
        takeFile
      }
    })
    const fileInput = wrapper.find('input[type="file"]')
    fileInput.trigger('change')

    expect(wrapper.emitted().getFile).toBe([[validFile]])
  })
})
```

Please, I urgently need help with this.
I have tried this and it's not working.
I think it's because I am using the composition API and I think this should work in the options API
I have also tried accessing the takeFile method directly like this

```
wrapper.vm.takeFile = sinon.fake.returns(validFile)
```
