### ISSUE TITLE
Inputs and .value()

### ISSUE THREAD

**Issue by callumacrae** [vuejs/vue-test-utils#235]
There's `.text()` and `.html()` for elements, but is there a reason there isn't a `.value()` for inputs?

Happy to add it if it's just an oversight :)

**Comment by eddyerburgh** [comment]
We decided against it in a previous thread, although I'm happy to open up discussion.

Is this a feature that would be useful to a lot of users?

**Comment by callumacrae** [comment]
I ended up using `.hasAttribute()` in the end - I didn't realise you could use it to match against a value, but it does exactly what I wanted.

**Comment by eddyerburgh** [comment]
Ok, I'll close this issue then.

Note that `hasAttribute` has been deprecated, and will be removed before the first release. You should use `attributes` instead.

**Comment by callumacrae** [comment]
i somehow completely missed that functionality 😰
