### ISSUE TITLE
"Cannot convert a Symbol value to a string" when using testdouble.js mocks

### ISSUE THREAD

**Issue by albhilazo** [vuejs/vue-test-utils#238]
### Version
1.0.0-beta.6

### Reproduction link
[https://codepen.io/albhilazo/pen/EbBPNv](https://codepen.io/albhilazo/pen/EbBPNv)

### Steps to reproduce
Use testdouble.js mock objects with vue-test-utils version >= beta4.

Open the reproduction CodePen to see a minimal test and the `Cannot convert a Symbol value to a string` error.

### What is expected?
That testdouble mock objects as ES6 proxies work when passed to `mount` or `shallow`.
They worked until beta3.

Reproduction with beta3: https://codepen.io/albhilazo/pen/aVgvvz

### What is actually happening?
Tests break when using testdouble mock objects since beta4.

Reproduction with beta6: https://codepen.io/albhilazo/pen/EbBPNv

---
I use [testdouble.js](https://github.com/testdouble/testdouble.js) for mocking.

testdouble provides [the creation of mock objects as ES6 proxies](https://github.com/testdouble/testdouble.js/blob/master/docs/4-creating-test-doubles.md#tdobject) by calling `td.object()`.

This is really convenient since, for example, it enables us to mount a component with a mocked router and set different mocked methods for each scenario later on.

We have been using this method with vue-test-utils but it started failing since beta4.

**Comment by eddyerburgh** [comment]
We started defining properties as reactive in beta 6. The Proxy created by testdouble throws an error when we call it in defineReactive. This might well be a bug with Vue, I'll investigate it further. 

Alternatively, we could try/catch the call to defineReactive, but that wouldn't be ideal.

**Comment by eddyerburgh** [comment]
This is an issue with testdouble—https://github.com/testdouble/testdouble.js/issues/300. 

Sorry that it started throwing an error in beta.6. This is because we now call defineProperty with the mock, and that causes this error in testdouble.

I'm closing this issue, since this is something that needs to be fixed on their end.

**Comment by albhilazo** [comment]
Oops, I was wrong to assume it was an issue with vue-test-utils due to it failing with newer versions.

Thank you for your time!
