### ISSUE TITLE
testing event props 

### ISSUE THREAD

**Issue by alidcastano** [vuejs/vue-test-utils#239]
Say we can test a component like this:
```
<someComponent @wasUpdated="someFunction" />
```

How should the emitted event be tested? Based on the Vuex example found in the docs, I tried the following and it didn't work: 

```   
    const propsData = {
      onWasUpdated: jest.fn()
    }
    const wrapper = mount(someComponent, { propsData })
    expect(propsData.onWasUpdated).toHaveBeenCalled()
  })
```

Is this currently possible? If so, how should it be done? Thanks

**Comment by eddyerburgh** [comment]
For questions like this, please use StackOverflow 🙂. The issue tracker is reserved for bugs and feature requests.

You can't add a click handler to a component, you need to add it to an element inside the component.

**Comment by alidcastano** [comment]
This can defintely be done: 
```
<someComponent @wasUpdated="someFunction" />
```

I use it all the time to emit actions back up to the parent component. My issue was asking whether this is currently testable (couldn't find how in documentation), if not I'd like to file a feature request.

**Comment by eddyerburgh** [comment]
Sorry @alidcastano , I misread your example as a click handler ☺️.

You could find the component with the handler in the parent component and emit on the instance:

```js
find(someComponent).vm.$emit('wasUpdated')
```

This will trigger the `someFunction` method. There are a few ways to test that `someFunction` was called.

You can also test that someComponent emitted the someFunction method inside the component using the [`emitted` method](https://vue-test-utils.vuejs.org/en/api/wrapper/emitted.html).

What feature would you like to request?

**Comment by alidcastano** [comment]
In my specific situation, the method is not emitted directly by the nested component. For example: 

```
<rootComponent @wasUpdated="someFunction" />

<parentComponent @wasUpdated="someFunction" />

// child component
this.$emit('wasUpdated)
```
I'll try finding the nested component and see if I can trigger the emit. But ideally, this is the feature I had in mind:

```
 const wrapper = mount(someComponent, { 
   propsData: {
    onWasUpdated: jest.fn() // jsx syntax for @wasUpdated
   }
 })

expect(wrapper.vm.wasUpdated).tohaveBeenCalled()
```

**Comment by eddyerburgh** [comment]
I'm closing this issue because it's not clear to me what you would like to test. Feel free to open a new feature request with more details on what you want this API to look like, and what problem it would solve.
