### ISSUE TITLE
Add support for async components

### ISSUE THREAD

**Issue by eddyerburgh** [vuejs/vue-test-utils#245]
We need to add support for async components

**Comment by wtho** [comment]
How could [async components](https://vuejs.org/v2/guide/components.html#Async-Components) be integrated in the current test setup of this repository? Should webpack provide the possibility to split? Or should we mock statically whatever splitted bundle webpack would serve? Can we test this without extending and rewriting the setup?

Any ideas on this?

I guess this issue also includes [advanced async components](https://vuejs.org/v2/guide/components.html#Advanced-Async-Components)?

**Comment by wtho** [comment]
Looking at what the [Vue vdom does](https://github.com/vuejs/vue/blob/bd4819e6cf1c8d70d25aba2636e01f40faf59443/src/core/vdom/create-component.js#L128), my suggestion would be to still return an *AsyncWrapper*, that first contains a placeholder or nothing, and when the promise resolves or the function calls back, it becomes a normal wrapper.

The tester would then have the need of flushing promises to continue the tests. If flushing promises is not an option, we could expose a loading promise or callback from the AsyncWrapper.

If we do not directly return a wrapper from `mount`/`shallow`, we would change the whole library interface.

Does the current setup work, if the child components are async? They should be instantiated by Vue, if I am not wrong?

Any other thoughts so far?

**Comment by eddyerburgh** [comment]
I haven't investigated into this yet. 

You're right, I don't think we should change the behavior of mount and shallow to not return a wrapper. I'll add some more comments when I've had a look into it.

**Comment by McSneaky** [comment]
Any updates?

**Comment by eddyerburgh** [comment]
Closing in favor of #61
