### ISSUE TITLE
Debugger in dist files

### ISSUE THREAD

**Issue by celeryclub** [vuejs/vue-test-utils#259]
It looks like this commit added several debugger statements to the built files. https://github.com/vuejs/vue-test-utils/commit/71d2c6b73e7738e99654f731207b79a1fd1c207f
Was that intentional? It's weird to get caught in these debuggers when trying to debug my own code.

Thank you for building this great tool!

**Comment by 38elements** [comment]
The debuggers removed at #247 .
This change is not released.

**Comment by eddyerburgh** [comment]
No, sorry, that was unintentional. 

I'm going to add a linting rule to catch debugger statements, and release beta.8 today

**Comment by eddyerburgh** [comment]
Released in 1.0.0-beta.8

**Comment by celeryclub** [comment]
Thanks for addressing this so quickly!
