### ISSUE TITLE
attributes() method always return an Object{undefined: undefined}

### ISSUE THREAD

**Issue by tianyong90** [vuejs/vue-test-utils#263]
Today , I upgrade to beta.8, and I tried to using `attributes()` , but found that it always return `Object{undefined: undefined}`.

![image](https://user-images.githubusercontent.com/9278461/34002085-ab59c1e2-e12c-11e7-8831-0eabf989f8c5.png)

**Comment by eddyerburgh** [comment]
This will be released in beta.9
