### ISSUE TITLE
Unable to use method i defined in vue

### ISSUE THREAD

**Issue by MaximeAubry** [vuejs/vue-test-utils#264]
Hello.

i have a bug. I define a method into vue :
`Vue.MyNamespace.MyMethode = function () {}`

This method is called in this app.vue file. And it's called by an event, into another child component.
If i create a localvue in my unit test, it's ok, i can see my methods with console.log (localVue.MyNamespace.MyMethode). It's ok.
But, when I load a child component of App.vue and the event is called, the namespace i undefined in app.vue.

Why ? How can I revise that ?
Thanks :)

**Comment by eddyerburgh** [comment]
You need to add the method to the Vue prototype for it to persist when a new child instance is created. I recommend using the [mocks option](https://vue-test-utils.vuejs.org/en/api/options.html#mocks):

```js
const wrapper = mount(Component, {
  mocks: {
    MyNamespace: {
      MyMethode: function() {}
    }
  }
})
```

**Comment by MaximeAubry** [comment]
It does not work.
Please, don't close an issue as fast :/
This method is defined in the web page is call, but not in the parent component.

`Vue.OroneMaterial.PageloadSwitcher.start()`

In App.vue, OroneMaterial is still undefined, but is defined in the ConnectorList.vue file.

**Comment by eddyerburgh** [comment]
The issue tracker is reserved for bug reports and feature requests. From the information you've provided, this isn't a bug report, or a feature request. That's why I closed the issue.

As I said, the issue is that you need to add the method to the Vue prototype:

```js
Vue.prototype.MyNamespace.MyMethode = function () {}
```

If this doesn't solve your issue, either post a minimal reproduction if you believe it's a bug and I'll reopen the issue. Otherwise, ask a question in StackOverflow with the code of your component and I'll help you.

**Comment by MaximeAubry** [comment]
Ok it's done. And I think it's really a bug. Maybe I'm wrong...
[Here is my sample project](https://github.com/MaximeAubry/DeclareFrameworkInTests)
Thanks a lot :)

**Comment by eddyerburgh** [comment]
Thanks for making the reproduction. Can you describe what the behavior you expect is, and what you're actually gettig in the repo. Also, if you could remove as much code as possible that isn't involved in the bug, like Vue Router, it makes it a lot easier to debug 🙂

**Comment by MaximeAubry** [comment]
So. I would like the "Vue.OroneMaterial.PageloadSwitcher" service works into the app.vue each time axios interceptors will be called.
Actually, this service appear into my unit test "localVue", but is undefined when i execute my tests.
ok I am going to remove the router from the unit test.
thanks.
