### ISSUE TITLE
Ref selector for components returns wrapper which is not isVueComponent

### ISSUE THREAD

**Issue by aiankile** [vuejs/vue-test-utils#267]
Issue: When selecting a sub-component of the main wrapper by ref, e. g. via
`wrapper.find({ref: 'myRef'})`
the resulting wrapper cannot execute further `find` or `exists` methods:

`wrapper.find({ref: 'myRef'}).find({ref: 'myRefSubref'})`
> '$ref selectors can only be used on Vue component wrappers'

Possible reason: `find` returns `new Wrapper(...)` directly, without calling VueWrapper. Which in turn means, `selectorTypes.OPTIONS_OBJECT` is used for `ref` selectors no matter what the ref target is, whereas `selectorTypes.VUE_COMPONENT` should apply in the particular case if target is a component itself.

**Comment by 38elements** [comment]
https://github.com/vuejs/vue-test-utils/blob/5d0cc2e8b204d4dbdf9fa3bcd65700fd87504a4e/test/unit/specs/mount/Wrapper/find.spec.js#L173-L176

This was changed as below.

```js
  it('returns Wrapper of Vue Components matching the ref in options object', () => {
    const wrapper = mount(ComponentWithChild)
    expect(wrapper.find({ ref: 'child' })).to.be.instanceOf(VueWrapper)
  })
```

The test did not pass.

**Comment by eddyerburgh** [comment]
You're correct, this should return a new VueWrapper when using the ref selector. 

Would you like to add a PR that fixes this issue?

**Comment by aiankile** [comment]
Sure, I'll prepare a PR.

**Comment by eddyerburgh** [comment]
This will be released in beta.9
