### ISSUE TITLE
Original methods are called instead of stubs if invoke through events

### ISSUE THREAD

**Issue by phanan** [vuejs/vue-test-utils#276]
When using Sinon stubs and Vue's event system, it appears that the original, stubbed, methods are still being called instead of the stubs themselves. Consider the following example:

```js
import eventBus from '@/utils' // just a simple Vue instance
import Foo from '@/components/Foo'

const initStub = sinon.stub()
const wrapper = shallow(Foo)
wrapper.setMethods({ init: initStub })
eventBus.emit('event that invokes init()')
```

### Expected Behavior

* `Foo.init()` shouldn't be called
* `initStub.called` should be `true`

### Actual Behavior

* `Foo.init()` is called
* `initStub.called` is `false`

Notice that the bug (?) doesn't happen if `init()` is called directly i.e. `wrapper.vm.init()`.

**Comment by LinusBorg** [comment]
Hm, I'm doubtful that there's a way to fix it. Presumalby, you did something like this:
```javascript
created () {
  eventBus.$on('event that invokes init()', this.init)
}
```

When you replace the method `init` *after* the event has registered, he eventbus doesn't know about it - it still has the old method as the callback for the event listener.

And vue-test-utils doesn't know about the event bus, which is not part of the component instance.

The same would happen if you registered a "normal" event listener (e.g. `window.addEventListener('click', this.init)`, so this would be something that can happen frequentl in tests.

The only solution I see it to stub the method immediatly:
```javascript
const wrapper = shallow(Foo, {
  methods: {
    init: initStub
  }
})
```

**Comment by wtho** [comment]
I think this is, because when you call `bus.$on('event', this.init)`, the original method reference gets passed to the bus listener. Even if you replace `this.init` later on the component, the bus will still have referenced the other method. It is just how the bus is designed. I do not see how we can change that.

You could however pass a stub implementation in the test options like this to test the stubbing:
```js
const wrapper = mount(Foo, { propsData: { bus }, methods: { init: initStub }})
```

**Comment by wtho** [comment]
Another way to work around it is to wrap the passing function in another one:
```js
created() {
  this.bus.$on('event', () => { this.init() })
},
```
That way the reference to `this.init` will be determined during runtime.

In my opinion this is no issue in the vue-test-utils and could be closed.

**Comment by lmiller1990** [comment]
What exactly are you trying to test? Maybe there is a better way to do it.

I'm looking to write some documents about how/what to test for `vue-test-utils`, knowing what kind of problems people run into and what they are trying to achieve is valuable feedback @phanan .

**Comment by eddyerburgh** [comment]
I'm closing this issue since it won't be fixed, the solution is to use @LinusBorg's suggestion:

```js
const wrapper = shallow(Foo, {
  methods: {
    init: initStub
  }
})
```

**Comment by phanan** [comment]
Woot. When I think @LinusBorg's explanation does make a lot of sense, I quickly tried the suggestion and it didn't appear to work. I'll be spending a little more time when I have it, but closing can seem to be a bit too quick.
