### ISSUE TITLE
Add sleep

### ISSUE THREAD

**Issue by 38elements** [vuejs/vue-test-utils#289]
I think that when asynchronous processing is executed in `Promise`, it needs to sleep asynchronously.
This is related to #288.

```js
export default function sleep (ms) {
  return new Promise(resolve => setTimeout(resolve, ms))
}
```

**Comment by 38elements** [comment]
I think it is necessary because it is only 3 lines.

**Comment by eddyerburgh** [comment]
I don't think we should add this method to vue-test-utils.

You could create an npm package, and we could recommend its use. At the moment we recommend flushPromises, which doesn't give you the option to wait for chosen milliseconds. 

But this function is out of scope for a Vue test library in my opinion. It's not Vue specific.

**Comment by 38elements** [comment]
@eddyerburgh 
I am very sorry.
I mistook the input.
I did not enter "not".
Correctly, "I think it is __not__ necessary because it is only 3 lines."
I am sorry for hurting your feelings.
