### ISSUE TITLE
When mount the component, will error!

### ISSUE THREAD

**Issue by scq000** [vuejs/vue-test-utils#29]
I found when I mount a component, it will render a commend node.But if I change the source of `mount` function like this:
```
export function mount (component, options) {
  if ( options === void 0 ) options = {};

  if (!window) {
    throwError('window is undefined, vue-test-utils needs to be run in a browser environment.\n You can run the tests in node using JSDOM');
  }

  var componentToMount = options.clone === false ? component : lodash.cloneDeep(component);
  // Remove cached constructor
  // delete componentToMount._Ctor;
  var vm = createConstructor(componentToMount, options);

  if (options.attachToDocument) {
    vm.$mount(createElement());
  } else {
    vm.$mount();
  }

  return new VueWrapper(vm, { attachedToDocument: !!options.attachToDocument })
}
```

I remove the statement `delete componentToMount._Ctor`, it will work!

**Comment by scq000** [comment]
Oh, it's not this problem.

**Comment by 74sharlock** [comment]
@scq000 So what's the real problem? I have same question.

**Comment by maksnester** [comment]
Hey guys, what does attachedToDocument exist for? I tried to google it, but docs are uncertain about that, so I found this issue, so why not to ask right here 🤷‍♂️

**Comment by 74sharlock** [comment]
@Alendorff 

https://github.com/vuejs/vue-test-utils/issues/329

Maybe u open a new issue?

**Comment by maksnester** [comment]
@74sharlock sure, as you wish #1207 

However issue like that looks a little excess for me, probably more general issue about documentation is needed.
