### ISSUE TITLE
createLocalVue.use(VeeValidate) fails in second test file

### ISSUE THREAD

**Issue by evanb2** [vuejs/vue-test-utils#290]
I have 2 components that use the 'vee-validate' library.
I'm using the `createLocalVue()` function at the top of each file like so:
```javascript
const localVue = createLocalVue();
localVue.use(VeeValidate);
```
The second test throws:
```
WARN: '[vee-validate] already installed, Vue.use(VeeValidate) should only be called once.'
```
Even though this is just a 'WARN', it looks like it's causing the `mounted()` hook in my component to fail (the component that's being tested in the second test).

If I remove the first test, the second test passes.

**Comment by eddyerburgh** [comment]
Thanks for the report.

This is an issue with VeeValidate not allowing multiple installs. I've added an issue to their repo—https://github.com/baianat/vee-validate/issues/1064

**Comment by evanb2** [comment]
@eddyerburgh Haha ok thanks! Been bashing my head against this trying to figure out where the issue is.
