### ISSUE TITLE
`is` returning undefined when using a Component as the Selector

### ISSUE THREAD

**Issue by alexjoverm** [vuejs/vue-test-utils#30]
If you run [this test](https://github.com/alexjoverm/vue-testing-series/blob/Test-Styles-and-Structure-in-Vue-js-and-Jest/test/MessageList.test.js), by cloning the repo and running `npm i && npm t` you'll see that

```javascript
expect(cmp.is(MessageList)).toBe(true)
```

fails because it returns undefined. As I've been debugging, in `vmCtorMatchesName`, `vm.$vnode` is undefined, `vm._vnode.componentOptions` is undefined and there is no `vm._node.functionalOptions`. Although, there is a `vm.$options.name` with the right value... maybe is this the property to assert?

**Comment by eddyerburgh** [comment]
Thanks for the bug report. 

This should be fixed in the dev branch with e4f3bdc8867775d275c47fe5ac354a9d0e18e029

**Comment by alexjoverm** [comment]
Awesome @eddyerburgh, that commit seems to do the trick! Can we then close this issue?

**Comment by eddyerburgh** [comment]
Yes, I'll close it now. Thanks for confirming the fix  🙂
