### ISSUE TITLE
Incorrect coverage result

### ISSUE THREAD

**Issue by 38elements** [vuejs/vue-test-utils#302]
Since there are the tests using the files in `src` directory like `test/unit/specs/error-wrapper.spec.js`,  the coverage result is incorrect.

https://github.com/vuejs/vue-test-utils/blob/063cd8f0e24c098dc6f6eca0a86f8981d24b46f2/test/unit/specs/wrappers/error-wrapper.spec.js#L1

Since the test is executed to check `dist`, I think that using for `src` is not appropriate.

**Comment by eddyerburgh** [comment]
Agreed.

The wrapper-array test also imports from the `src` directory—https://github.com/vuejs/vue-test-utils/blob/dev/test/unit/specs/wrappers/wrapper-array.spec.js

**Comment by 38elements** [comment]
I will send the pull request for `wrapper-array.spec.js`.
