### ISSUE TITLE
hasAttribute

### ISSUE THREAD

**Issue by eddyerburgh** [vuejs/vue-test-utils#32]
Currently hasAttribute checks for DOM attributes. It doesn't check for `$attrs`. 

I can see this causing confusion. 

Should There be a separate `hasAttrs` method?

Should hasAttribute check `$attrs` if the wrapper is a component wrapper?

**Comment by callumacrae** [comment]
I'm not sure what the best solution is here, but I 100% vote against seperate `hasAttribute` and `hasAttrs` methods that do different things.

**Comment by wparad** [comment]
I'm totally sure I understand what `$attrs` is, but it sounds like it is just a convenience method/object.  In which case I would expect that that anything that this automates is also handled automatically on the opposite side.  I.e. according to [first google link](https://alligator.io/vuejs/upgrading-vue-2.4/) these are the `attributes` of the component, in which case I would expect `hasAttributes` to return also check these. (and `hasListeners` to also check `$listeners`)

Isn't it weird that while the docs say
> This allows a wrapper component to be created that simply passes all attributes and listeners down to the child.

The attributes and listeners of the child don't contain these objects and/or this repo doesn't check for them?

**Comment by nesterone** [comment]
As far as I understand Wrapper is a combination of accessors to  DOM **and** Vue instance, when it was about 'getProps', 'getData' there is no intersection with DOM node interface (it terms of terms)

Having both doesn't sound like as a good solution, at least there are some reasons to do it

I see that a lot of DOM accessors were added to [Wrapper](https://github.com/vuejs/vue-test-utils/blob/dev/flow/wrapper.js#L8). Was made an assumption that for developers it's handy to have DOM accessors shortcuts. I support it ;-)

So, my proposal is to keep `hasAttribute` as is and  provide shortcut accessor to `$attrs` only if community would constantly push for that

**Comment by wparad** [comment]
Although looking at this closer it feels that bulk passing of attributes and listeners from the parent to the child is not a great pattern, so maybe this shouldn't be support at all.

**Comment by callumacrae** [comment]
Could always call it `.has$attrs()`.

**Comment by eddyerburgh** [comment]
I'm going to close this issue as there seems to be no more discussion. Happy to reopen if people want to start the discussion back up
