### ISSUE TITLE
How to test component with inline-template?

### ISSUE THREAD

**Issue by aalyokhin** [vuejs/vue-test-utils#326]
Hi.

Already spent a few hours on this and still can't figure it out. Is there any way to test the components with inline templates (with some logic right inside those templates)? I didn't find a way to provide template to mount method. 

Thanks a lot in advance.

**Comment by aalyokhin** [comment]
Please remove this issue as ```template``` option for ```mount``` works correctly, tested on a dummy component. Looks like something is wrong with the actual component, which I'm trying to test.

**Comment by DeBelserArne** [comment]
Hello @aalyokhin 

How exactly have you solved your issue?

Kind Regards,
Arne
