### ISSUE TITLE
npm package?

### ISSUE THREAD

**Issue by jblotus** [vuejs/vue-test-utils#33]
Just tried to install via npm
https://www.npmjs.com/package/vue-test-utils

and the registered package was pointing to https://github.com/holmescn/vue-test-utils

I was able to install with yarn by doing:

yarn add https://github.com/vuejs/vue-test-utils/

Hope it helps someone!

**Comment by eddyerburgh** [comment]
This package hasn't been published yet. Currently an unrelated vue-test-utils is on the npm registry.

**Comment by dealloc** [comment]
Perhaps this should be noted somewhere in the readme, I often just look at the Github repo name or in the package.json file for the name on NPM, especially given now that there's a NPM package with the exact same name, this could cause some confusion

**Comment by eddyerburgh** [comment]
Good suggestiong @dealloc , I updated the master README - 0de2ca41d154d3ed118e954e8b353c8c8ef67f58

**Comment by KagamiChan** [comment]
@eddyerburgh Seems this project's default branch is dev, so it should be better to pick this commit to dev branch so that people could see the notice at first glance

**Comment by eddyerburgh** [comment]
@KagamiChan done 👍

**Comment by lusarz** [comment]
I want to use newest version of vue-test-utils in my application, I added this line to package dependencies:

      "vue-test-utils": "git://github.com/vuejs/vue-test-utils.git"

, but I see that `/dist/vue-test-utils.js` is out of date with src. Is there a plan to setup automatic build of dist ? Anyway I would be thankful for manual build :)

**Comment by eddyerburgh** [comment]
@lusarz I'll do a quick manual build.

We're getting ready for release, so I won't do any manual builds after this. Part of the release process is to build the dist files and push them to dev, so they will be updated with future builds.

**Comment by webfrontzhifei** [comment]
The same name package has been published to the npm，so this repository will be renamed ？？

**Comment by eddyerburgh** [comment]
We have the npm package, so when we publish it will overwrite the previous owners package

**Comment by eddyerburgh** [comment]
vue-test-utils beta is released on npm:

```
npm install --save-dev vue-test-utils@1.0.0-beta
```

Closing issue
