### ISSUE TITLE
Confusing documentation for mount and shallow

### ISSUE THREAD

**Issue by emileber** [vuejs/vue-test-utils#338]
Both [`mount`](https://vue-test-utils.vuejs.org/en/api/mount.html) and [`shallow`](https://vue-test-utils.vuejs.org/en/api/shallow.html) functions have the following usage description:

> Returns [`Wrapper`](https://vue-test-utils.vuejs.org/en/api/wrapper/) of **first** DOM node or Vue component **matching selector**.
> 
> Use any valid [selector](https://vue-test-utils.vuejs.org/en/api/selectors.html).

But they do not have a `selector` param. It looks like it's the description for the `find` function.

And neither the examples show selectors.

**Comment by eddyerburgh** [comment]
Thanks for the notice. Do you want to make a PR to improve the description?
