### ISSUE TITLE
Syntax error in nested components

### ISSUE THREAD

**Issue by stique** [vuejs/vue-test-utils#341]
Hi! 

I configurated jest for testing vue components:

 "jest": {
    "transform": {
      ".*\\.(vue)$": "<rootDir>/node_modules/vue-jest",

But imported nested components are not transformed and I've got a error:

 FAIL  src/components/card/contacts.test.js
  ● Test suite failed to run

    /www/spa/node_modules/components/b-button/b-button.vue:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){<template>
                                                                                             ^
    
    SyntaxError: Unexpected token <

What am I doing wrong?

**Comment by eddyerburgh** [comment]
Hi, thanks for the report

This should be an issue in vue-jest, but are you importing with a .vue extension? If you want to discuss further please create an issue in the vue-jest repo—https://github.com/eddyerburgh/vue-jest
