### ISSUE TITLE
NPM package does not found

### ISSUE THREAD

**Issue by re-fort** [vuejs/vue-test-utils#342]
It seems that the package has been moved to the scoped modules by the recent [commit](https://github.com/vuejs/vue-test-utils/commit/b84ec9caa5d9dca77de9f34c8dd709e4d5f551ef), but the package does not seem to be published on npm yet.
I think it would be good to reflect the docs after publishing it because there is potentially confusing for the users ;)

**Comment by eddyerburgh** [comment]
Sorry about that delay! 

It's released now 🙂
