### ISSUE TITLE
Errors when install v1.0.0-beta.10

### ISSUE THREAD

**Issue by tianyong90** [vuejs/vue-test-utils#343]
Glad to see the new release! Thank you for your great work.
I tried to upgrade to beta.10, but failed with an error.
![image](https://user-images.githubusercontent.com/9278461/34809188-655c32f8-f6ce-11e7-863c-e4be783558e7.png)

I'm using yarn in windows10.

**Comment by eddyerburgh** [comment]
Sorry about that. I've released a fixed version beta.11.

Note that vue-test-utils has been moved to @vue/test-utils:

```
npm install --save-dev @vue/test-utils
```

**Comment by tianyong90** [comment]
I am curious about the reason for changing the package name.

**Comment by eddyerburgh** [comment]
Vue is moving to scoped packages, so vue-test-utils, becomes @vue/test-utils.

Henry Zhu wrote a good article on why scoped packages are useful—https://babeljs.io/blog/2017/12/27/nearing-the-7.0-release#renames-scoped-packages-babelx

**Comment by tianyong90** [comment]
Thanks for explaining! 😄
