### ISSUE TITLE
[1.0.0-beta.10] install failed.

### ISSUE THREAD

**Issue by 74sharlock** [vuejs/vue-test-utils#344]
<h3>env:</h3>
<ul>
<li>node: v9.3.0</li>
<li>system: macOS 10.12.4</li>
</ul>

<h3>How to reappear:</h3>

```
npm install
```
or
```cli
yarn install
```

<h3>expect:</h3>
Install successfully

<h3>result:</h3>

Throw error:

```
Error: Cannot find module '/path/to/project/node_modules/vue-test-utils/build/moved-warning'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-test-utils@1.0.0-beta.10 install: `node build/moved-warning`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-test-utils@1.0.0-beta.10 install script.

```

**Comment by eddyerburgh** [comment]
Sorry about that. I've released a fixed version beta.11.

Note that vue-test-utils has been moved to @vue/test-utils:

```
npm install --save-dev @vue/test-utils
```

**Comment by 74sharlock** [comment]
@eddyerburgh Thanks!

**Comment by lambdalisue** [comment]
Note that I needed to use `import { mount } from '@vue/test-utils'` instead if I used `@vue/test-utils`. It seems it is not documented yet here https://vue-test-utils.vuejs.org/en/guides/getting-started.html

**Comment by eddyerburgh** [comment]
Thanks, I'm updating the docs now
