### ISSUE TITLE
Deprecation warning does not be displayed when using yarn

### ISSUE THREAD

**Issue by re-fort** [vuejs/vue-test-utils#347]
When installing vue-test-utils(not scoped package) with yarn, `install` command of npm scripts runs correctly, but it silences the output, so deprecation message doesn't be displayed.
IMO, it might be better to use `npm deprecate` for displaying deprecation message.

**Comment by eddyerburgh** [comment]
Would you like to make a PR? The unscoped version is in the `unscoped` branch
