### ISSUE TITLE
shallow()/mount() VS real VueJS instance

### ISSUE THREAD

**Issue by pierremanceaux** [vuejs/vue-test-utils#349]
Hello!

I'm currently facing a problem trying test my Vue instance using `shallow()` or `mount()`.

Here is my Vue instance creation:
```javascript
new Vue({
    data: {
        config,
    },
    el: '#app',
    router,
    store,
    template: '<App/>',
    components: {
        App,
    },
});
```
Please note the custom `data` object (config is just a JSON, but doesn't matter I guess, I just need my config to be globally accessible, from any component).

In my components, I access my components this way: `this.$root.config.foo`.

My `vue-test-utils` wrapper looks like the following:
```
    const wrapper = shallow(component, {
        localVue,
        store,
        mocks: {
            $route,
            $store: {
                state: {},
            },
        },
        provide: {
            $validator: Validator.create(),
        },
    });
```

but I don't know how to inject my `data` object in here. I tried different things, but it doesn't seem to work properly... Is there a clear solution to this? Or is it simply not possible with `shallow()`
 or `mount()`?

**Comment by eddyerburgh** [comment]
You need to pass an uninstantiated Vue component to `mount` or `shallow`.  

It's not possible at the moment to mount a Vue instance.

**Comment by pierremanceaux** [comment]
Hello @eddyerburgh and thanks for your time.

Yeah, so far that's what I'm doing `let localVue = createLocalVue();` and then pass my component to it, so I guess I am doing things right here. So I imagine that my `localVue` can't receive my `data` at any point?

**Comment by eddyerburgh** [comment]
you could add data to the localVue prototype:

```js
const data = {}
localVue.prototype.data = data
```

**Comment by pierremanceaux** [comment]
@eddyerburgh guess what... it did the trick. Little hack acceptable for now, until we get this "config" from an API!

Thanks a lot for your time man <3
