### ISSUE TITLE
Add a getOptions method to Wrapper

### ISSUE THREAD

**Issue by alexjoverm** [vuejs/vue-test-utils#35]
As discussed on #34, the idea of having a `getOptions` method came up, in the same line than #27 for `getAttributes` and `getProps`. This would be an abstraction to access the `wrapper.vm.$options` internal variable. One of the use cases is to test property validation specs, but there might be others.

What notation to use?
 1. Concise: `.options()`, `attributes()`, `props()`...
 2. Verbose `.getOptions()`, `getAttributes()`, `getProps()`...

Let's discuss it

**Comment by eddyerburgh** [comment]
My feelings on this is that we shouldn't add too many aliases. I don't think this a common use case, like `props` or `attributes`, and it's not much more code to access the `$options` object on the `vm`:

```js
wrapper.vm.$options
wrapper.options()
```
