### ISSUE TITLE
Add support for HTML templates

### ISSUE THREAD

**Issue by ddykhoff** [vuejs/vue-test-utils#351]
Feature request as suggested in https://github.com/vuejs/vue-test-utils/issues/271#issuecomment-356690053

Please add support for HTML templates. Main use case is Vue single file components. Example of unsupported use case:

https://jsfiddle.net/h0bnmk5d/1/

And the current work around is to refactor into component `template` property:

https://jsfiddle.net/h0bnmk5d/2/

**Comment by dennythecoder** [comment]
Is this something that's going to be included?  Testing seems to steer the way we're write code in other contexts.  Developers steering away from HTML templates and towards using a main App component is common from what I can tell.  It doesn't really seem to create that much more work either.

**Comment by eddyerburgh** [comment]
I thought it would be a nice-to-have. 

You're right, we should encourage users to use templates in components, rather than HTML templates. But HTML templates make Vue more accessible for users, and the ability to drop vue-test-utils into a codepen of a Vue instance with an HTML template might make testing more approachable to some users.

**Comment by ddykhoff** [comment]
My 2 cents is that if this is to be the official testing library of Vue, it should support all features of Vue (or at least the main ones, of which HTML templates and single file components are in my opinion).

**Comment by ganicus** [comment]
What is the work around for this? Do we have to completely refactor our html templates into a template property? Why is there documentation on testing single file components if it isn't fully supported?

**Comment by kpturner** [comment]
Having waded through mud to try to test Vue components only to hit this issue with $refs I feel rather deflated to find I have to refactor templates into properties to make this work - especially as they do not have the same editor syntax checking that html templates have.

**Comment by dobromir-hristov** [comment]
We recently merged a PR, which allows templates as a reference in the element in the DOM - #1320 
Closing for now.

**Comment by eolamisan** [comment]
It's incredible that this is not supported! Any thoughts on implementing it?
Not sure a large project (800+ components) can or should be converted to properties to add tests.
