### ISSUE TITLE
Functional template can't be mounted

### ISSUE THREAD

**Issue by ghost** [vuejs/vue-test-utils#360]
### Version
1.0.0-beta.10

### Reproduction link
[https://github.com/noamcore/functional-template](https://github.com/noamcore/functional-template)

### Steps to reproduce
```
git clone https://github.com/noamcore/functional-template.git
cd functional-template
npm install
npm run unit
```

### What is expected?
The component can be tested using `<template functional/>`.

### What is actually happening?
Error saying that mount.context can only be used when mounting a functional component

---
Functional component using `functional` attribute on template is on Vue 2.5.0 .

**Comment by LinusBorg** [comment]
Does that only happen when the functional component is a completely empty one like yours?

**Comment by LinusBorg** [comment]
Hm, I think this rather is a problem with vue-jest. vue-test-utils never gets to see the `<template>` element as that's converted when impotrting the component into the test file. So vue-jest has to make sure that `functional: true` is set on that component's options. However it seems that vue-jest does something different, namely kind of converting a functional component into a "normal" one.... 

https://github.com/eddyerburgh/vue-jest/blob/master/lib/process.js#L30-L38

/cc @eddyerburgh

**Comment by eddyerburgh** [comment]
Thanks for the bug report 🙂

Could you please open this issue in vue-jest? As @LinusBorg says, this needs to be fixed there
