### ISSUE TITLE
Wrapper.contains doesn't work with innerHTML

### ISSUE THREAD

**Issue by hiendv** [vuejs/vue-test-utils#361]
### Version
1.0.0-beta.10

### Reproduction link
[https://github.com/hiendv/vue-test-utils-contains-bug](https://github.com/hiendv/vue-test-utils-contains-bug)

### Steps to reproduce
npm install
npm test

### What is expected?
There is no error when running the test `component contains the SVG`

### What is actually happening?
The test fails

**Comment by LinusBorg** [comment]
I'm not 100% sure, but (at least until recently), `contains` does not match the root node - that's what `is` does.

```javascript
expect(wrapper.is('svg')).toBeTruthy()
```
If that's not it, I could imagine that adding html with `domProps` isn't "visible"until the next tick ...

**Comment by eddyerburgh** [comment]
@LinusBorg `contains` now matches the root node.

**Comment by hiendv** [comment]
@LinusBorg FYI, in the reproduction, it's not the root node.
