### ISSUE TITLE
Should update `wrapper.props()` value after `wrapper.setProps` ?

### ISSUE THREAD

**Issue by fimars** [vuejs/vue-test-utils#374]
### Version
1.0.0-beta.10

### Reproduction link
[https://github.com/fimars/vue-test-utils/blob/59a46bb342f924d0ff6e5e4a1af19911694a146b/test/unit/specs/mount/Wrapper/setProps.spec.js#L50-L62](https://github.com/fimars/vue-test-utils/blob/59a46bb342f924d0ff6e5e4a1af19911694a146b/test/unit/specs/mount/Wrapper/setProps.spec.js#L50-L62)

### Steps to reproduce
```javascript
  // setProps.spec.js
  it('should update after setProps', () => {
    const prop1 = {}
    const prop2 = 'val1'
    const wrapper = mount(ComponentWithProps, {
      propsData: { prop1, prop2 }
    })

    expect(wrapper.props()).to.eql({ prop1: {}, prop2: 'val1' })
    // setProps
    wrapper.setProps({ prop2: 'val2' })
    expect(wrapper.vm.prop2).to.eql('val2') // pass
    expect(wrapper.props()).to.eql({ prop1: {}, prop2: 'val2' }) // fail still prop2: 'val1'
  })
```
I write a test-case in my fork. you can try it.

### What is expected?
wrapper.props() should be updated

### What is actually happening?
no update know.

---
The props of `wrapper.vm` are updated, maybe this is deliberately designed?

**Comment by paparent** [comment]
Hi 

@eddyerburgh I ran into similar issue. But instead of looking at `.props()`, I look at the `.html()`. The styles doesn't get updated, and I wanna make sure the `color` attribute change. Even if I do a `Vue.nextTick`.

Thanks

**Comment by eddyerburgh** [comment]
Can you create new issue with a reproduction?
