### ISSUE TITLE
Unable to bind slots

### ISSUE THREAD

**Issue by hiendv** [vuejs/vue-test-utils#375]
### Version
1.0.0-beta.10

### Reproduction link
[https://github.com/hiendv/vue-test-utils-slots-bug](https://github.com/hiendv/vue-test-utils-slots-bug)

### Steps to reproduce
```bash
# install dependencies
npm install

# see the rendered markup in the browser
npm run dev

# see the tests
npm test
```

### What is expected?
There is no error when running the tests

### What is actually happening?
The tests fails

**Comment by LinusBorg** [comment]
I can't run this right now - does only the second test fail?

Because you are passing a component as the slot content, then return multiple vnodes from the component's render function, which is not allowed (by Vue, not test-utils).

**Comment by hiendv** [comment]
Unfortunately, the test with a single slot fails also. For now, I will remove the second test: https://github.com/hiendv/vue-test-utils-slots-bug/commit/762e99cc9332297c651424cabf707c078aa72b7d

**Comment by hiendv** [comment]
Ref: https://github.com/hiendv/vue-test-utils-slots-bug/commit/762e99cc9332297c651424cabf707c078aa72b7d

**Comment by hiendv** [comment]
```
> jest

 FAIL  ./test.js
  should render correct HTML markup
    ✕ with a single child (33ms)

  ● should render correct HTML markup › with a single child

    expect(received).toBe(expected)
    
    Expected value to be (using Object.is):
      "<div><div>Tags: vue-component-2-Child</div> <div>Fooes: bar</div> <div>Children: <span>bar</span></div></div>"
    Received:
      "<div><div>Tags: vue-component-3</div> <div>Fooes: </div> <div>Children: <span>bar</span></div></div>"

      23 |         expect(wrapper.emitted().loaded).toBeTruthy()
      24 |         expect(wrapper.emitted().loaded[0]).toEqual([1])
    > 25 |         expect(wrapper.html()).toBe(`<div><div>Tags: vue-component-2-Child</div> <div>Fooes: bar</div> <div>Children: <span>bar</span></div></div>`)
      26 |       })
      27 |       .then(done)
      28 |   })
      
      at test.js:25:30

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.266s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

**Comment by hiendv** [comment]
What I was trying to test should look like this
```vue
<Parent>
  <Child foo="bar"/>
</Parent>
```
But I could not find a way to mounting the slots
```js
// This won't work
const wrapper = mount(Parent, {
  slots: {
    default: {
      render (h) {
        return h(Child, { props: { foo: 'bar' } })
      }
    }
  }
})

// This won't work in spite of this example: https://vue-test-utils.vuejs.org/api/options.html#slots
const wrapper = mount(Tabs, {
  slots: {
    default: [Tab]
  }
})

// render() won't work too
```

For the second test, logging `$slots.default` returns an Array but componentOptions won't be initiated
```
componentOptions: 
 { Ctor: [Function],
   propsData: {},
   listeners: undefined,
   tag: undefined,
   children: undefined },
```

It's supposed to be
```
componentOptions: 
 { Ctor: [Function],
   propsData: {
    foo: 'default foo value'
  },
   listeners: undefined,
   tag: 'Child',
   children: undefined },
```

@eddyerburgh @LinusBorg

**Comment by hiendv** [comment]
Close because of https://github.com/vuejs/vue-test-utils/issues/41#issuecomment-360970325

**Comment by hiendv** [comment]
Workaround: https://github.com/vuejs/vue-test-utils/issues/41#issuecomment-402662080
