### ISSUE TITLE
Within 'setData' method computed variables are re-calculated, even if are not used in template

### ISSUE THREAD

**Issue by lusarz** [vuejs/vue-test-utils#377]
### Version
1.0.0-beta.10

### Reproduction link
[https://github.com/lusarz/vue-test-utils/commit/51cf7b5c10cd2010c26a21d7e9f2cca400faacd1](https://github.com/lusarz/vue-test-utils/commit/51cf7b5c10cd2010c26a21d7e9f2cca400faacd1)

### Steps to reproduce
Use `wrapper.setData(...)` method

### What is expected?
Computed properties that are not truly used in template shouldn't be re-calculated.

By 'truly used' I mean variables that are not filtered out by v-if directive.

### What is actually happening?
All computed properties are calculated. In some situations it cause `Cannot read property ${property} of null` kind of errors.

**Comment by LinusBorg** [comment]
> By 'truly used' I mean variables that are not filtered out by v-if directive.

That's not how Vue works. This computed property will be re-evaluated independent of the usage in the render function.

This is not a bug in the test-utils, it's how Vue is designed to work.

**Comment by lusarz** [comment]
@LinusBorg 
I have some doubts. Could you check here:
https://github.com/lusarz/vue/commit/9ef5946f082a5565efdd0d0794371f61bf0e73d9

Both tests pass. In second one, when `<span v-if="a">{{ b }}</span>` is evaluated to not be rendered, function that calculates `b` is not invoked.

**Comment by LinusBorg** [comment]
Can't take a look right now but reopened for someone else to check

**Comment by LinusBorg** [comment]
Edit: Quickly checked this with a fiddle: https://jsfiddle.net/tohdxapr/1/

Seems OP is right, sorry :/

**Comment by lusarz** [comment]
No problem. @LinusBorg I turned off cache for computed property in fiddle: https://jsfiddle.net/tohdxapr/2/

With cache it doesn't prove anything :)

**Comment by lusarz** [comment]
This issue seems to be related with watchers which are launched in `setData -> update` methods:
https://github.com/vuejs/vue-test-utils/blob/c095221a3a05595a4f49aaeda5e7d2e888b9e092/src/wrappers/vue-wrapper.js#L15-L17

I noticed that watcher on computed property is run here, not sure where this watcher is initialized
