### ISSUE TITLE
Default props modified between tests suites

### ISSUE THREAD

**Issue by Alex-Sokolov** [vuejs/vue-test-utils#393]
### Version
1.0.0-beta.11

### Reproduction link
[https://jsfiddle.net/bqtfqwpw/](https://jsfiddle.net/bqtfqwpw/)

### Steps to reproduce
Tested component: https://jsfiddle.net/g7s289sh/
Tests suites: https://jsfiddle.net/bqtfqwpw/

1. Install vue/test-utils 1.0.0-beta.10
2. Run tests => All ok
3. Update vue/test-utils to 1.0.0-beta.11
4. Run tests => Test fails

### What is expected?
Tests passed

### What is actually happening?
Tests failed
![image](https://user-images.githubusercontent.com/4497128/35511352-8da155d0-050c-11e8-82ab-f5e844e1b974.png)

---
Looks like vue/test-utils shared default props between test suites

**Comment by LinusBorg** [comment]
We should probably do a deep-clone here;
https://github.com/vuejs/vue-test-utils/blob/dev/src/lib/create-instance.js#L51

**Comment by eddyerburgh** [comment]
The problem with doing a deep clone is that we wouldn't be able to use stubs passed in propsData 🤔
