### ISSUE TITLE
'Disabled' attribute on buttons is ignored during testing

### ISSUE THREAD

**Issue by jamesoshea** [vuejs/vue-test-utils#395]
### Version
1.0.0-beta.11

### Reproduction link
[https://github.com/jamesoshea/vue-test-utils-button-bug](https://github.com/jamesoshea/vue-test-utils-button-bug)

### Steps to reproduce
Run npm install, then npm test. The test will fail as vue-test-utils trigger a click on a disabled element, and the element's bound method is called anyway.

### What is expected?
The method should not get called when the button is clicked.

### What is actually happening?
When testing a vue component, I will sometimes call .trigger('click') on a wrapper containing just a button. If the button is disabled and a method is bound to its click event, the button is clicked and the method called anyway.

**Comment by eddyerburgh** [comment]
Thanks for the bug report 😀

We trigger events using the `dispatchEvent` method. This [doesn't respect disabled elements](https://bugs.chromium.org/p/chromium/issues/detail?id=243199), as you found out.

To fix this, we'll need to add a check inside the trigger method.

**Comment by jamesoshea** [comment]
I'd be happy to put in a PR! Thanks to yourself and everyone behind this library, it's been a lifesaver :smile:

**Comment by eddyerburgh** [comment]
Thanks, a PR be great 😀

**Comment by fant0m** [comment]
This is not working again..
