### ISSUE TITLE
node environment support

### ISSUE THREAD

**Issue by wagerfield** [vuejs/vue-test-utils#397]
I just [posted an issue](https://github.com/vuejs/vue-test-utils-jest-example/issues/8) in the `vue-test-utils-jest-example` repo about this, but I think it needs flagging here also.

When [setting the jest environment](https://facebook.github.io/jest/docs/en/configuration.html#testenvironment-string) to `node` the following error is thrown:

```
[vue-test-utils]: window is undefined, vue-test-utils needs to be run in a browser environment.
You can run the tests in node using jsdom + jsdom-global.
See https://vue-test-utils.vuejs.org/en/guides/common-tips.html for more details.
```

For a use case for when it might be important to test vue components in a `node` environment, please see the issue referenced above.

**Comment by husayt** [comment]
We have the following problem. Has this been resolved?

**Comment by eddyerburgh** [comment]
Not yet, no —https://github.com/vuejs/vue-test-utils/issues/427
