### ISSUE TITLE
[Help wanted] Fetch data in 'created'

### ISSUE THREAD

**Issue by lusarz** [vuejs/vue-test-utils#398]
### Version
1.0.0-beta.11

### Reproduction link
[https://github.com/lusarz/vue-test-utils/commit/95b5c61e329e04f04cf48b0826c801f3c5b73b00](https://github.com/lusarz/vue-test-utils/commit/95b5c61e329e04f04cf48b0826c801f3c5b73b00)

### Steps to reproduce
In our application we fetch some data from server:

    created () {
      TestUtils
        .fetchData()
        .then(data => {
          this.data = data;
        })
    }

we want to mock `TestUtils.fetchData` in tests like:

     sinon.stub(TestUtils, 'fetchData')
      .returns(Promise.resolve('some-mocked-data'))

And we would like this promise to be resolved just after mount, but it's not:

    const wrapper = mount(ComponentWithFetch)
    expect(wrapper.text()).to.equal('some-mocked-data')

### What is expected?
I would like to mocked promises to be resolved just after mount method

### What is actually happening?
Assertion run before mocked promise is resolved.

**Comment by eddyerburgh** [comment]
You need to wait in your tests until the pending resolved promise is flushed. Adding a `setTimeout` flushes pending promises:

```js
it('should display fetched data', (done) => {
  const wrapper = mount(ComponentWithFetch)
  setTimeout(() => {
    expect(wrapper.text()).to.equal('some-mocked-data')
    done()
  })
})
```

Closing, as this isn't a bug with vue-test-utils.

**Comment by andredewaard** [comment]
@eddyerburgh 
This doesn't work for me.

My test:
```
describe('Viewing Users overview', () => {
  let wrapper: any;

  beforeEach(() => {
    wrapper = mount(UserTest);
    sinon.stub(wrapper.vm.userService, 'index').resolves(Users);
  });

  it.only('It should render users after getting users', async () => {
    expect(wrapper.find({ ref: 'users' }).exists()).toBe(false);
    await timeout(0);
    expect(wrapper.vm.users).toBe(Users);
  });

  function timeout(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
});
```
Component
```
export default class UserTest extends Vue {

  private users: User[] = [];

  private userService: UserService = new UserService();

  private created(): void {
    this.getUsers();
  }

  private async getUsers(): Promise<void> {
    const users = await this.userService.index();
    this.users = users;
  }
}
```

When i manually fire the getUsers function inside the test and removing the created function everything works fine.
