### ISSUE TITLE
VTU thinks mutations/actions are undefined.

### ISSUE THREAD

**Issue by TheJaredWilcurt** [vuejs/vue-test-utils#412]
### Version
1.0.0-beta.11

### Reproduction link
[https://codesandbox.io/s/k31v0lw3o](https://codesandbox.io/s/k31v0lw3o)

### Steps to reproduce
1. `npm install -g vue-cli`
1. `npm init webpack vuextest` (hit enter for every question)
1. `cd vuextest`
1. `npm run unit` (1 of 1 tests ran/passed)
1. `npm install --save vuex`
1. Change `vuextest/src/main.js` to
    ```js
    import Vue from 'vue'
    import App from './App'
    import router from './router'
    import store from './store';

    Vue.config.productionTip = false

    /* eslint-disable no-new */
    new Vue({
      el: '#app',
      router,
      store,
      components: { App },
      template: '<App/>'
    })
    ```
1. Create a folder `vuextest/src/store`.
1. Create these files inside the folder:
    * `state.js`
    ```js
    const state = {};
    export default state;
    ```
    * `getters.js`
    ```js
    const getters = {};
    export default getters;
    ```
    * `mutations.js`
    ```js
    const mutations = {};
    export default mutations;
    ```
    * `actions.js`
    ```js
    const actions = {};
    export default actions;
    ```
    * `index.js`
    ```js
    import Vue from 'vue';
    import Vuex from 'vuex';
    import state from './state';
    import getters from './getters';
    import mutations from './mutations';
    import actions from './actions';

    Vue.use(Vuex);

    export default new Vuex.Store({
      state,
      getters,
      mutations,
      actions
    });
    ```
1. Create this file: `vuextest/test/unit/specs/store/index.spec.js`
    ```js
    import store from '@/store';

    describe('Store', () => {
      it('should import State, Getters, Mutations, and Actions', () => {
        expect(store.state).toBeDefined();
        expect(store.getters).toBeDefined();
        expect(store.mutations).toBeDefined();
        expect(store.actions).toBeDefined();
      });
    });
    ```
1. `npm run unit`

### What is expected?
pass

### What is actually happening?
```
 FAIL  test\unit\specs\store\index.spec.js
  ● Store › should import State, Getters, Mutations, and Actions

    expect(received).toBeDefined()

    Expected value to be defined, instead received
      undefined

       5 |     expect(store.state).toBeDefined();
       6 |     expect(store.getters).toBeDefined();
    >  7 |     expect(store.mutations).toBeDefined();
       8 |     expect(store.actions).toBeDefined();
       9 |   });
      10 | });

      at Object.<anonymous> (test/unit/specs/store/index.spec.js:7:39)
```

---
This will fail saying mutations or actions is undefined (depending on which is listed first).

**Comment by eddyerburgh** [comment]
Hi, thanks for the steps to reproduce, but this isn't an issue. The store object doesn't contain an actions or mutations property—https://github.com/vuejs/vuex/blob/dev/types/index.d.ts#L8/

Regarding the reproduction. I appreciate that it's not trivial to create a reproduction in JSFiddle for vue-test-utils. I've created an issue in the vue-issue-helper to include a link in the helper—https://github.com/vuejs/vue-issue-helper/issues/22. 

For future reference, you can use this starter—https://jsfiddle.net/eddyerburgh/sghur81m/6/

**Comment by TheJaredWilcurt** [comment]
oh yeah, you're right. because if there was a `store.mutations` then people would run `store.mutations.myfunc()` instead of `store.commit('myfunc')`. That makes sense.
