### ISSUE TITLE
jest test nuxt vuex destructuring unexpected token

### ISSUE THREAD

**Issue by lenvonsam** [vuejs/vue-test-utils#426]
test result screenshot
![image](https://user-images.githubusercontent.com/10168476/36089199-99bcca3e-1015-11e8-94cb-30f13d4818b4.png)

test spec file
![image](https://user-images.githubusercontent.com/10168476/36089244-d090dbd6-1015-11e8-8cfe-01e61810905c.png)

i have added babel-jest and added .babelrc config
how to solve this problem

**Comment by eddyerburgh** [comment]
You need to use the spread operator plugin for babel—https://babeljs.io/docs/plugins/transform-object-rest-spread/
