### ISSUE TITLE
How to handle eslint with vue-test-utils?

### ISSUE THREAD

**Issue by metal-gogo** [vuejs/vue-test-utils#43]
Hi there, is any plans on releasing a eslint plugin for vue-test-utils?

Right now I'm adding some globals to my .eslintrc.js

Is there a better way?

**Comment by eddyerburgh** [comment]
What globals are you adding?

**Comment by KagamiChan** [comment]
What's the test framework / library you use? You may simply define eslint env in your `eslintrc.js` file for common test frameworks like jest, mocha, etc.

**Comment by eddyerburgh** [comment]
I'm closing this, as vue-test-utils doesn't add any globals

Like @KagamiChan said, you can add your test runner in the `env ` field of your `.eslintrc`
