### ISSUE TITLE
Move to Circle 2.0

### ISSUE THREAD

**Issue by eddyerburgh** [vuejs/vue-test-utils#448]
### What problem does this feature solve?
At the moment we're using Circle 1.0, which isn't supported from August 2018

### What does the proposed API look like?
We should move to circle 2.0, and parallelize the compatability tests—https://github.com/vuejs/vue-test-utils/blob/dev/scripts/test-compat.sh

**Comment by probil** [comment]
Resources and guides to help you make the transition [https://circleci.com/sunset1-0/](https://circleci.com/sunset1-0)

**Comment by eddyerburgh** [comment]
We're using circle 2 now, but the tests aren't paralellized—https://github.com/vuejs/vue-test-utils/blob/dev/.circleci/config.yml
