### ISSUE TITLE
Trigger 'click' with leveled slots causes "Duplicate presence of slot"

### ISSUE THREAD

**Issue by nerdcave** [vuejs/vue-test-utils#451]
### Version
1.0.0-beta.12

### Reproduction link
[https://gist.github.com/nerdcave/a76cbed0bb92bb93972f0232d9c8a1c0](https://gist.github.com/nerdcave/a76cbed0bb92bb93972f0232d9c8a1c0)

### Steps to reproduce
Run the test with Jasmine.

### What is expected?
No warnings.

### What is actually happening?
ERROR: '[Vue warn]: Duplicate presence of slot "content" found in the same render tree - this will likely cause render errors.

---
- The warning will go away if you 1) remove the `wrapper.find('div').trigger('click')` -or- 2) remove `slot-scope="props"` off the template.
- I don't have these issues in 1.0.0-beta.10.

**Comment by nerdcave** [comment]
Just an update: I don't encounter either of these issues in 1.0.0-beta.10.

**Comment by eddyerburgh** [comment]
Thanks for the bug report and the test case.

This issue has been fixed in beta.13. 

I've added a  test case to avoid future regressions
