### ISSUE TITLE
.attributes().value returns undefined

### ISSUE THREAD

**Issue by Suruat** [vuejs/vue-test-utils#457]
### Version
1.0.0-beta.11

### Reproduction link
[http://prntscr.com/inoeig](http://prntscr.com/inoeig)

### Steps to reproduce
- provide value as a prop to component
- in test use `.attributes().value` on input wrapper

### What is expected?
Get value of the wrapper

### What is actually happening?
Returns undefined
http://prntscr.com/inoeth

---
Sorry if this already known issue, or is not an issue at all. Didn't find similar problem. And on docs is no mention that it doesn't work with value attribute

**Comment by eddyerburgh** [comment]
This is expected behavior.

Setting the value with v-bind sets it as a DOM prop, not as an attribute. You can read about the difference [here](https://stackoverflow.com/questions/19246714/html-attributes-vs-properties). My advice is to check the value property:

```js
const wrapper = mount(Component)
wrapper.element.value
```
