### ISSUE TITLE
Sub-component is undefined

### ISSUE THREAD

**Issue by rndmerle** [vuejs/vue-test-utils#47]
Hi.

When mounting a component including a sub-component I get this error:
```
TypeError: Cannot convert undefined or null to object

      at node_modules/vue-test-utils/dist/vue-test-utils.js:117:33
          at Array.forEach (<anonymous>)
      at stubAllComponents (node_modules/vue-test-utils/dist/vue-test-utils.js:115:37)
      at shallow (node_modules/vue-test-utils/dist/vue-test-utils.js:991:5)
```
When stubbing, it happens the component is undefined.

I'm using vue-test-utils 0.1.0
The lib might be loaded by ts-jest.

I'm still investigating but maybe you've got an idea.

**Comment by eddyerburgh** [comment]
Hi, thanks for the issue.

I don't know what the problem is from the error message. Can you post a minimal reproduction?

**Comment by rndmerle** [comment]
Here is a reproduction:
```
git clone https://github.com/rndmerle/repro_vue-test-utils.git
cd repro_vue-test-utils
npm i
npm test
```
I guess the issue is that it's processed by Typescript, but in my project it's mandatory.

**Comment by eddyerburgh** [comment]
Thanks for the reproduction.

This is a jest-vue issue. I've made an issue over there, and released a fix. Can you on jest-vue that the release fixed your issue?
