### ISSUE TITLE
wrapper.vm.$listeners not equal the actual vueInstance.$listeners

### ISSUE THREAD

**Issue by Hanruis** [vuejs/vue-test-utils#472]
### Version
1.0.0-beta.12

### Reproduction link
[https://jsbin.com/nopulunamo/3/edit?html,console,output](https://jsbin.com/nopulunamo/3/edit?html,console,output)

### Steps to reproduce
1. create a wrapper by method mount , and pass  listeners param

       const wrapper = mount(myComponent, {
          listeners: {
            change: someFunction,
          },
        });

### What is expected?
     wrapper.vm.$listerners  = {
        change: function invoker(){}
     }

     invoker.fns  ===  someFunction

### What is actually happening?
    wrapper.vm.$listerners.change === someFunction

**Comment by eddyerburgh** [comment]
Can you provide a link to a repo with a minimal reproduction?
