### ISSUE TITLE
add info about ErrorWrapper object

### ISSUE THREAD

**Issue by iztsv** [vuejs/vue-test-utils#476]
### What problem does this feature solve?
As I can see `find` method returns `Wrapper` object if element found or `ErrorWrapper` object if not element found. Both are implement `BaseWrapper`.

I think it will be good to add this information in order to do more clear info about returning type of `find`.

Also, may be create page for `ErrorWrapper` object.

### What does the proposed API look like?
> Returns: {Wrapper}

to something like

```
Returns: {Wrapper | ErrorWrapper}

...some notes when ErrorWrapper returned and example...
```

**Comment by eddyerburgh** [comment]
I'm not sure there's value in telling users about the error wrapper. It's purpose is to handle cases when an element isn't found, and it has the same methods as the Wrapper.

What notes about the ErrorWrapper would you find useful?

**Comment by iztsv** [comment]
@eddyerburgh thanks for the reply.

Maybe enough to add something like this notes for `find` method:

```
> Example: ...

Note: you can check that at least one element is found using `exists` method:

const div = wrapper.find('div')
expect(wrapper.exists()).toBe(true)
```

Because I expect that `expect(wrapper.find('div')).toBe(false)` if no one element is found, but it's always will be `true` - maybe it's my strange logic 😄

**Comment by eddyerburgh** [comment]
That's a reasonable assumption, but the docs do say find returns a Wrapper object. I don't think we need to add more detail than that.

**Comment by iztsv** [comment]
Thanks!

**Comment by nidkil** [comment]
Hi guys, sorry to comment on a closed issue, but I have just run into the same issue. Calling find returns ErrorWrapper instead of the expected false. I needed to Google around to findout why. What is the harm of clarifying this in the documentation? It is not obvious that it can be queried with `.exists`. A short explanation explaining that if `find` does not find a match it returns an ErrorWrapper that can be checked with `.exists`?

**Comment by eddyerburgh** [comment]
Ok, we could add a sentence in the `find` docs. Would you like to write it @nidkil ?

**Comment by tomasbjerre** [comment]
I prefer naming methods like:

 * `find(x)` that will search for `x`. It may not find anything, and it is totally expected.
 * `get(x)` that will get `x`. It will always return value of `x` or it will throw exception stating that `x` could not be found.

So I am missing the `get` method here.

See #1298

**Comment by scridget** [comment]
Agreee - running into this as well. exists returns true, even when the actual component isn't found.

**Comment by Robin-Hoodie** [comment]
Testing this with `@vue/test-utils@1.0.3` and `exists()` actually returns `false` for an `ErrorWrapper` component

This can also be found in the sourcecode: https://github.com/vuejs/vue-test-utils/blob/4b0c5c94fb29885bb65e26fea64b8ca64960e301/packages/test-utils/src/error-wrapper.js#L74
