### ISSUE TITLE
Can't set data for localVue

### ISSUE THREAD

**Issue by dimensi** [vuejs/vue-test-utils#481]
### Version
1.0.0-beta.12

### Reproduction link
[https://codesandbox.io/s/n92wj49kn0](https://codesandbox.io/s/n92wj49kn0)

### Steps to reproduce
Try to set data into localVue and get this from testing env

### What is expected?
Expected testData === 'testData' 

### What is actually happening?
testData === undefined

---
I can not understand how to throw data into localVue

**Comment by eddyerburgh** [comment]
You can set `$root` on the `vm` directly:

```js
wrapper.vm.$root = { loading: true }
wrapper.vm.$forceUpdate()
```

Or you can pass in a parent component with the `parentComponent` mounting option. In VTU, the paren will be the $root:

```js
const Parent = {
  data() {
    return {
      loading: "asdas"
    };
  }
};
const wrapper = shallowMount(TestComponent, {
  parentComponent: Parent
});
```

**Comment by dimensi** [comment]
@eddyerburgh it's not help
```js
const mountComp = (data) => {
  const wrap = mount(ModeCard, {
    propsData: data,
    localVue,
  });

  wrap.setData({
    $root: {
      currentLang: 'ru',
    },
  });

  return wrap
};
```
i anyway got `currentLang === undefined`

**Comment by eddyerburgh** [comment]
If you're trying to set currenLang on your root instance, use:

```js
  wrap.setData({
      currentLang: 'ru',
  });
```

**Comment by dimensi** [comment]
@eddyerburgh yes, it's help. Thank you.

**Comment by dimensi** [comment]
@eddyerburgh after update to 1.0.0-beta.20, i can't again set data on $root.

**Comment by dimensi** [comment]
Oh, now it's work with `mocks` property...

**Comment by jgradzki** [comment]
I can't make it work neither with mocks or setData
```
mocks: {
        $root: {
          loading: true,
        },
      },
```
```
wrapper.setData({
      $root: {
        loading: true,
      },
    });
```

$root.loading is undefined in both cases + with setData i got error not to change root data dynamicly
version: 1.0.0-beta.24

**Comment by eddyerburgh** [comment]
You can set `$root` on the `vm` directly:

```js
wrapper.vm.$root = { loading: true }
wrapper.vm.$forceUpdate()
```

Or you can pass in a parent component with the `parentComponent` mounting option. In VTU, the paren will be the $root:

```js
const Parent = {
  data() {
    return {
      loading: "asdas"
    };
  }
};
const wrapper = shallowMount(TestComponent, {
  parentComponent: Parent
});
```

**Comment by scniro** [comment]
Can anyone share context of why the first solution was removed? I find this cleaner...

```javascript
mocks: {
  $root: {}
}
```

Anyways, using the above suggestion for now indeed works well

**Comment by RoelRoel** [comment]
In my mounted function $root is called so I have to mock it before mounting. Than it is not possible overwrite set wrapper.vm.$root afterwards.
So I guess a fake parent component is the only solution for me, but I can't get it to work.

**Comment by Volcano-Yang** [comment]
> You can set `$root` on the `vm` directly:
> 
> ```js
> wrapper.vm.$root = { loading: true }
> wrapper.vm.$forceUpdate()
> ```
> 
> Or you can pass in a parent component with the `parentComponent` mounting option. In VTU, the paren will be the $root:
> 
> ```js
> const Parent = {
>   data() {
>     return {
>       loading: "asdas"
>     };
>   }
> };
> const wrapper = shallowMount(TestComponent, {
>   parentComponent: Parent
> });
> ```

recommend，it‘s good!

**Comment by vivek8690** [comment]
@eddyerburgh

```JS
   const Parent = {
            template: '<div id="app">Modal Body</div>',
            data() {
                return {
                    loading: 'asdas'
                };
            }
        };
        
const wrapper = shallowMount(TestComponent, {
  parentComponent: Parent
});
```

In my TestComponent mounted I have ``

` this.$root.$el.append(this.$el)`

Which throws **HierarchyRequestError: The operation would yield an incorrect node tree.**

Here you can try https://codesandbox.io/s/quiet-snow-tzdf5?file=/src/Sample.spec.js

**Comment by ZaidRehman** [comment]
> In my mounted function $root is called so I have to mock it before mounting. Than it is not possible overwrite set wrapper.vm.$root afterwards.
> So I guess a fake parent component is the only solution for me, but I can't get it to work.

After more than 2 years I am still stuck on this issue.

**Comment by ZaidRehman** [comment]
> ```js
> const Parent = {
>   data() {
>     return {
>       loading: "asdas"
>     };
>   }
> };
> const wrapper = shallowMount(TestComponent, {
>   parentComponent: Parent
> });
> ```

ParentComponent doesn't work if the data key starts with $ 
```javascript
const Parent = {
    data() {
      return {
        $api: client
      };
    }
  };
```

Any work around for this ?

**Comment by HilalNazli** [comment]
I also have a mounted function in which $root is called and [this solution](https://stackoverflow.com/a/49447846/3800642) worked for me.
