### ISSUE TITLE
Add option to pass DOM attributes to root element

### ISSUE THREAD

**Issue by AlexandreBonneau** [vuejs/vue-test-utils#483]
### Version
1.0.0-beta.12

### Reproduction link
[https://codesandbox.io/s/n768kwm6wj](https://codesandbox.io/s/n768kwm6wj)
*note: the dummy `VueInput` component and the spec code is correct, but I can't make vue-test-utils work there*

### Steps to reproduce
1. Have a component `VueInput` that generated an `input` DOM element
2. Normally when using `<vue-input id='foo' name='bar'>` in a template, the `id` and `name` attributes are correctly added to the generated `input` element
3. With `vue-test-utils`, try to add those  `id` and `name` attributes using:

```js
describe('Dummy VueInput.vue', () => {
    it('should be generated with the `id` and `name` passed as attributes', () => {
        const id = 'theIdToUse';
        const name = 'theInputName';
        const wrapper = mount(VueInput, {
            attrs: {
                id,
                name,
            },
        });
        expect(wrapper.is('input')).toBe(true);
        expect(wrapper.attributes().id).toEqual(id); //FIXME Fails
        expect(wrapper.attributes().name).toEqual(name); //FIXME Fails
    });
});
```

### What is expected?
The `id` and `name` attributes should be correctly added to the generated `input` element

### What is actually happening?
Only the `type` and `value` attributes are found on the generated `input` element

**Comment by eddyerburgh** [comment]
The `attrs`  option adds  properties to  `vm.$attrs`. It's not intended to behave  like you're expecting.

Why do you want to add attibutes like this in your  test? If you  have a good use case we  could look at ways to include  this  feature.

**Comment by AlexandreBonneau** [comment]
Well, Vue does behave like that by default; if you add any attribute to a component, those attributes (if those are not props names) will be added to the top level element on render.

You can see this behavior on this [really simple example](https://codesandbox.io/s/v0972xlyxl).

For some context, I'm using this on the [vue-autoNumeric](https://github.com/autoNumeric/vue-autoNumeric) component, since when you declare an `id` on it, you expect to be able to later `querySelector` that `id`.

**Comment by eddyerburgh** [comment]
Sorry for the original misunderstanding. With the latest merge, `attrs` behaves like you expected. This will be released in beta.17
