### ISSUE TITLE
Use of Array.prototype.find breaks unit tests in browsers that do not support this.

### ISSUE THREAD

**Issue by rikbrowning** [vuejs/vue-test-utils#499]
### Version
1.0.0-beta.13

### Reproduction link
Run Test in IE10

### Steps to reproduce
1. Create unit test using test-utils, use mount command.
2. Run test in IE10
3. Test will fail due to TypeError: Object doesn't support property or method 'find'

### What is expected?
Test should pass

### What is actually happening?
Test is failing.

**Comment by malte-christian** [comment]
This bug was introduced with https://github.com/vuejs/vue-test-utils/pull/462.

**Comment by 38elements** [comment]
I think if this is a issue to resolve and this issue is resolved by reverting #462, 
#462 should be reverted.

**Comment by eddyerburgh** [comment]
Yes, I also think we should run tests in Phantom to stop this in the future. Currently we run in headless chrome, but we Phantom has less support for features.

**Comment by 38elements** [comment]
I think this is resolved by using [core-js](https://github.com/zloirock/core-js#ecmascript-6-array).
