### ISSUE TITLE
code puzzles

### ISSUE THREAD

**Issue by webfrontzhifei** [vuejs/vue-test-utils#51]
I do not understand the code

```js
const consoleWarnSave = console.error
  console.error = () => {}
  if (attrs) {
    vm.$attrs = attrs
  } else {
    vm.$attrs = {}
  }
  console.error = consoleWarnSave
```
why save the console.error and reset to it at the last ???

**Comment by eddyerburgh** [comment]
It's too avoid logging errors while we set the $attrs.

I'm happy to accept a PR that improves the code, or adds a comment to stop it being so puzzling 🙂

**Comment by yyx990803** [comment]
@eddyerburgh we can actually temporarily set `Vue.config.silent = true` when we need to suppress warnings.

**Comment by eddyerburgh** [comment]
That's a much nicer solution 😄
