### ISSUE TITLE
Component is not mounted correctly for testing

### ISSUE THREAD

**Issue by Menighin** [vuejs/vue-test-utils#516]
### Version
1.0.0-beta.13

### Reproduction link
[https://github.com/Menighin/vue-inline-chart](https://github.com/Menighin/vue-inline-chart)

### Steps to reproduce
- Run `npm install` to install dependencies
- Run `npm test` to execute tests with `jest`

### What is expected?
All tests to pass

### What is actually happening?
The test that checks the rendered template doesn't pass because it seems the mount function is not correctly rendering the component.

---
To give some context:

I have this component called `InlinePieChart` that renders a PieChart using SVG based on the props passed.
In my test, I am using `propsData` to pass the paremeters to the component. Testing if these parameters where set correctly, in my `received parameters` test, seems to be everything alright. 

The problem comes in my `renders 4 slices` test where I check the `html` searching for 4 `pie-slice` classes. Turns out I find only 2 classes and when checking the HTML rendered I see that the component is rendering with the default parameters values set in the `InlinePieChart` component (2 pie-slices).

I checked the documentation but in my understanding I'm not doing anything wrong.

**Comment by 38elements** [comment]
It is necessary to change as below.

https://github.com/Menighin/vue-inline-chart/blob/3ac2ed1558d4d7990f170413c7b7eb00454c26c7/test/components/InlinePieChart.test.js#L1

```js
import { mount } from 'vue-test-utils';
```

:arrow_down:

```js
import { mount } from '@vue/test-utils'
```

**Comment by Menighin** [comment]
In the [vue-test-utils-getting-started](https://github.com/vuejs/vue-test-utils-getting-started/blob/master/test.js) repository, it is imported as `vue-test-utils`.

Anyway, changing that line didn't fix the problem. In fact, I didn't notice anything different... :/

**Comment by 38elements** [comment]
I think that it is better to refer to this.
[vue-test-utils-jest-example](https://github.com/vuejs/vue-test-utils-jest-example)

I think that this line is not necessary.
https://github.com/Menighin/vue-inline-chart/blob/3ac2ed1558d4d7990f170413c7b7eb00454c26c7/package.json#L61

**Comment by Menighin** [comment]
@38elements you're right. I removed that dependency. It was not necessary.

But this didn't fix the problem. Test is still failing.

**Comment by dennythecoder** [comment]
@Menighin It looks like the test is using `pieSlices` for `propsData` but the component has `slices` as a prop.

**Comment by Menighin** [comment]
@dennythecoder  now I feel really dumb :'(
It was just this all along... Sorry I missed it guys.
Thank you both for the support!
