### ISSUE TITLE
"Failed to resolve filter" while running tests

### ISSUE THREAD

**Issue by AustinGil** [vuejs/vue-test-utils#543]
### Version
1.0.0-beta.14

### Reproduction link
[https://jsfiddle.net/50wL7mdz/323724/](https://jsfiddle.net/50wL7mdz/323724/)

### Steps to reproduce
Create a Vue project
Add a filter (like mine or a different one)
Test project with Jest and vue-test-utils

### What is expected?
Test should run without any errors

### What is actually happening?
Test are running, but throwing errors:

"[Vue warn]: Failed to resolve filter: si"

---
I have also tried importing Vue to the test spec file and setting up the filter there, but that didn't seem to help.

**Comment by eddyerburgh** [comment]
I can't reproduce this.

For me, registering a filter before mounting works as expected:

```js
Vue.filter('aFilter', () => 'foo')

test('updates computed properties', () => {
  const wrapper = shallow(App)
  expect(wrapper.text()).toContain('foo')
})
```

**Comment by AustinGil** [comment]
OK, following this example and testing on a brand new build cleared things up. I must have made a mistake on my side. Thank you very much and sorry for the false report.

**Comment by alecgerona** [comment]
If you're using Nuxt or are using modular filter imports you can do this.
```ts
import "~/plugins/filters";
```
