### ISSUE TITLE
Add setComputed method

### ISSUE THREAD

**Issue by eddyerburgh** [vuejs/vue-test-utils#55]
We should add a `setComputed` method to set the value of a computed value.

**Comment by blocka** [comment]
A computed property should be something you test...not an invariant

**Comment by eddyerburgh** [comment]
I think @jackmellis said it well:

>There have been times when a method relies on a computed property that is so complicated it's taken me far outside the purpose of my unit test just to get the right computed value!

**Comment by jonnyparris** [comment]
Only just saw this after creating a [similar issue](https://github.com/eddyerburgh/avoriaz/issues/145) on the Avoriaz repo. A setComputed method is exactly what I need.

**Comment by Austio** [comment]
I can see a pragmatism to this.

I do agree with @blocka though and think that the downside with setComputed is that it is encouraging the use of computed properties in the same way you would use something like props or data.  You could end up in a situation where you are unit tests for computed and have a component that does not work.

I'm interested in the scenario/thoughts for needing this and if it would be better to create a separate component that you pass the computed property to as a prop and then test that component?

**Comment by jonnyparris** [comment]
@Austio why not make both options available and let people decide for themselves?
Ideally I could have unit level tests for all my computed and method functions (which encourages smaller single-purpose functions) _and_ have a 'component integration test' that checks all of those unit tests playing well together.

**Comment by Austio** [comment]
@jonnyparris that is a fair point, i think with the feature we should add something to documentation with some potential gotchas with it.

**Comment by eddyerburgh** [comment]
I made a PR — https://github.com/vuejs/vue-test-utils/pull/84

**Comment by lusarz** [comment]
What do you think about adding something like `computedMock` mounting option:
`mount(Component, { computedMock: { someVariable () {return 'mocked value'}}`
and use `extends` inside mount:

    const ExtendedComponent = {
      extends: Component,
      computed: params.computed
    }
    return mount(ExtendedComponent);

It's only idea, I'm not sure if it's even possible.

**Comment by eddyerburgh** [comment]
I think we should add setComputed, because we already have `setData`, `setMethods`, and `setProps`

**Comment by kleinjm** [comment]
Can you please add this method to docs? Thank you

**Comment by eddyerburgh** [comment]
Are you able to make a PR adding it to the docs?

**Comment by jorySsense** [comment]
any hope on bringing back this feature,

What if my computed value was set by getters from vuex and im mocking the getters?  

And then i want to test a watcher that is listening for changes on that value?  

I would want a way to force update the computed value

**Comment by blocka** [comment]
Can't you just mock vuex in that case? Or at least mapGetters?

**Comment by jorySsense** [comment]
Sure the works for mounting but you can't trigger the watcher on mount. You need to update the reactive data that the watcher is observing. If it's a computed value, or a getter thats mocked from the store you can't force the computed value to update.

**Comment by nathan-kansu** [comment]
Whilst I agree a 'setComputed' method should be added, you actually don't need it.
Just add a 'computed' property along with your other mounting options, like so... 

```
const wrapper = mount(Component, {
  ...
  computed: {
    foo() {
      return 'bar'
    },
  },
})
```

**Comment by jorySsense** [comment]
@nath-codes thats great for mounting, the issue is further explained #331
