### ISSUE TITLE
Is documentation Obsolete for Vuex modules?

### ISSUE THREAD

**Issue by gplusdotgr** [vuejs/vue-test-utils#551]
While implementing we noticed that the proposed syntax for modules does not work: https://vue-test-utils.vuejs.org/en/guides/using-with-vuex.html

Instead, what we ended up doing is this:

```js
import Preferences from 'models/preferences';

  beforeEach(() => {
    store = new Vuex.Store({
      modules: {
        Preferences: {
          state: {
            panelVisible: true,
          },
          mutations: Preferences.mutations,
          getters: Preferences.getters,
          namespaced: true,
        },
      },
    });
  });
```

**Comment by gplusdotgr** [comment]
@eddyerburgh please rethink the auto-closing of tickets. It's a bit extreme.

**Comment by eddyerburgh** [comment]
@gkatsanos the issue tracker is used throughout Vue projects. I understand it can be annoying for some issues, but it encourages users to report bugs in a way that makes it easy to debug and fix.

With regards to your original issue, would you like to update the docs to include your working example?

**Comment by gplusdotgr** [comment]
I would be glad to but that would mean I have a thorough understanding of
how testing namespaced modules should be done (which apparently now isn't the case) - could you confirm my suspicion that you need a `modules` object in order to properly create a Vuex store which uses modules for testing?

**Comment by gplusdotgr** [comment]
@eddyerburgh could you confirm that my proposed structure is how we should initialize a store for testing? I will proceed to a PR then :)

**Comment by eddyerburgh** [comment]
Yep, I can confirm that that's how to intialize a store with modules :)

**Comment by eddyerburgh** [comment]
@gkatsanos are you intending to implement this?

**Comment by gkatsanos** [comment]
Yes, I will get time to do it this weekend.

**Comment by gplusdotgr** [comment]
Yep, will do this weekend.

**Comment by gplusdotgr** [comment]
https://github.com/vuejs/vue-test-utils/pull/632/files @eddyerburgh

**Comment by lmiller1990** [comment]
Nice job updating the docs. @gkatsanos 

In my experience over the last year or so of building large Vue apps, I came to the conclusion you should generally __not__ use the actual store in your tests. To see if an action is dispatched, I have been doing:


```js
const dispatch = jest.fn()
const $store = { dispatch }

wrapper  = shallow(Component, { 
  mocks: { $store }
}

// something to dispatch action

expect(dispatch).toHaveBeenCalledWith('nameOfAction', payload)
```

Now you do not need to worry about how the store is structured. You can decouple the store from the component.

The component should not even have knowledge of it - it's responsibility is simply to dispatch the correctly named action with the right payload.

Something like this might be a good fit for the docs (maybe?). We do have the Vue cookbook, but I think `vue-test-utils` could easily have it's own cookbook, considering how large and important the topic of testing is, although not sure if the team is looking to expand the guides section or not. If so I would be interesting in writing more about this.
