### ISSUE TITLE
Is it possible to selectively stub only some child components?

### ISSUE THREAD

**Issue by gplusdotgr** [vuejs/vue-test-utils#558]
### Version
1.0.0-beta.15

### Reproduction link
[https://vue-test-utils.vuejs.org/en/api/shallow.html](https://vue-test-utils.vuejs.org/en/api/shallow.html)

### Steps to reproduce
I would like to test that my child component renders a list of things properly, but when I use mount I am obliged to mock/mount all child components which is not ideal.
Is it possible to use shallow and mount fully a child a component (or the opposite, use mount and stub some child components)

### What is expected?
To be able to test a child component without having to mount all its siblings. 

### What is actually happening?
We need to mount and initialize all child components

**Comment by eddyerburgh** [comment]
Yes, you can use the `stubs` option to selectively stub components—https://vue-test-utils.vuejs.org/en/api/options.html#stubs
