### ISSUE TITLE
Impossible to edit documentation page

### ISSUE THREAD

**Issue by trollepierre** [vuejs/vue-test-utils#559]
### Version
1.0.0-beta.15

### Reproduction link
[https://vue-test-utils.vuejs.org/en/api/components/RouterLinkStub.html#](https://vue-test-utils.vuejs.org/en/api/components/RouterLinkStub.html#)

### Steps to reproduce
Go to https://vue-test-utils.vuejs.org/en/api/components/RouterLinkStub.html#
Click on Edit this page.
=> 404

### What is expected?
A possibility to edit the documentation

### What is actually happening?
404

**Comment by eddyerburgh** [comment]
Thanks for the bug report.

We're going to move our docs to Vuepress in the next few weeks, which doesn't have an edit option. So I'm closing this issue as won't fix
