### ISSUE TITLE
error to pass required prop

### ISSUE THREAD

**Issue by leonardovilarinho** [vuejs/vue-test-utils#561]
### Version
1.0.0-beta.15

### Steps to reproduce
I have a component with `item` prop:

```
<template>
  <h2>{{ item.name }}</h2>
</template>

<script>
export default {
  name: 'CaseCard',
  props: {
    item: {
      type: Object,
      required: true
    }
  }
}
</script>
```

My prop `item` should be required, my test:

```
import { mount } from '@vue/test-utils'
import CaseCard from './CaseCard'

const cardsData = [
  { name: 'A', image: 'A', route: 'A', tags: ['A', 'AA']}
]

describe('CaseCard component', () => {
  test('render case name in h2 tag', () => {
    const component = mount(CaseCard, {
      propsData: {
        item: cardsData[0]
      }
    })
    const h2Tag = component.find('h2')

    expect(h2Tag.text()).toBe(cardsData[0].name)
  })

})
```

### What is expected?
I think that it works and my test pass, but no works.

### What is actually happening?
The error returned is: `[Vue warn]: Missing required prop: "item"`

---
If I remove `required` from my prop, the test pass, but I need use `required`.

**Comment by leonardovilarinho** [comment]
Sorry, the mistake was mine, I had not realized.

**Comment by akolnati** [comment]
I get the same error. Any idea what fixed it?

**Comment by leonardovilarinho** [comment]
your code has some error, in the same component or in parent or child components of it.
