### ISSUE TITLE
Missing lodash dependency in build of 1.0.0-beta

### ISSUE THREAD

**Issue by stephane** [vuejs/vue-test-utils#57]
ERROR in ./node_modules/vue-test-utils/dist/vue-test-utils.js
Module not found: Error: Can't resolve 'lodash/cloneDeep' in '<path>/node_modules/vue-test-utils/dist'

May be lodash should be put in peerDependencies?
https://github.com/vuejs/vue-test-utils/blob/3c0881aa03fd5199ae78975fe9aa28ea7bf3c42c/package.json#L96

**Comment by eddyerburgh** [comment]
Thanks for the bug report.

I think Lodash should be in dependencies, because it's a required dependency.

I can't reproduce the issue locally, but I'll look into this later.

Can you give me some more information - npm version, node version, babel options (if any).

A small example repo would be extremely helpful.

**Comment by stephane** [comment]
Yes my bad, it's a required dependency, of course.
I'll try to provide a small example repo ASAP.

**Comment by eddyerburgh** [comment]
Hi stephane, did you mange to create a reproduction?

This is a major issue, and I'd like to resolve it, but I'm unable to replicate it.

**Comment by stephane** [comment]
I tried again in various projects (with official webpack template or without, with yarn or npm) and each time, the lodash dependency is properly fetched.

success Saved 2 new dependencies.
├─ lodash@4.17.4
└─ vue-test-utils@1.0.0-beta.1

Excepted in one of my project where lodash v3.10.1 is still used, I'm not able to figure out why and vue-test-utils works from git (package.json). The package-lock.json requires 4.17.4...

I don't think the issue is related to vue-test-utils so I close the issue.
Thank you.

**Comment by stephane** [comment]
Deleted by global npm cache and the problem is gone :/

**Comment by eddyerburgh** [comment]
I've had so many npm problems since v 5 😟

**Comment by stephane** [comment]
The issue is tied to karma 1.7.1 which depends on lodash v3.10.1 if the karma dependency is added first to `node_modules/` by NPM, `lodash` v3.10.1 is stored at the root and not inside its dir (`karma/`)
