### ISSUE TITLE
Cannot find module 'cheerio'

### ISSUE THREAD

**Issue by jledentu** [vuejs/vue-test-utils#571]
### Version
1.0.0-beta.15

### Reproduction link
None

### Steps to reproduce
After installing `@vue/server-test-utils`, import the module and call the `renderToString` function.

### What is expected?
The `renderToString` function should generate a string containing the rendered component.

### What is actually happening?

```
Cannot find module 'cheerio' from 'vue-server-test-utils.js'
      at Resolver.resolveModule (node_modules/jest-runtime/node_modules/jest-resolve/build/index.js:191:17)
      at Object.<anonymous> (node_modules/@vue/server-test-utils/dist/vue-server-test-utils.js:9:31)
```

---
Cheerio is not installed when installing `@vue/server-test-utils` since it's in the **dev** dependencies.

**Comment by eddyerburgh** [comment]
Fixed in https://github.com/vuejs/vue-test-utils/commit/f3dfb1e81f43c05d8ae871dba9184d83a3b3548e. This will be released in beta.16

**Comment by seyfer** [comment]
14 May 2020 - I just got this error. 

```
node_modules/@vue/server-test-utils/types/index.d.ts(53,125):
53:125 Cannot find name 'Cheerio'.
```
I did `yarn add -D cheerio @types/cheerio` and it did not help

`"@vue/server-test-utils": "^1.0.2",`
