### ISSUE TITLE
Not work if import some types to Vue component

### ISSUE THREAD

**Issue by yarkovaleksei** [vuejs/vue-test-utils#577]
### Version
1.0.0-beta.15

### Reproduction link
[https://gist.github.com/yarkovaleksei/86de6471378490ff57f382d3acd79f78](https://gist.github.com/yarkovaleksei/86de6471378490ff57f382d3acd79f78)

### Steps to reproduce
```html
<template>
  <li>
    <a class="user-menu__link" @click.prevent="go(item.link)">{{item.text}}</a>
  </li>
</template>

<script lang="ts">
import script from './script'
export default script
</script>

<style lang="scss" scoped>
@import 'styles';
</style>
```

```typescript
import Vue from 'vue'
import { Prop, Emit, Component } from 'vue-property-decorator'
import { IMenuItem } from '../types.d' // this import is throw error

@Component
export default class ListItem extends Vue {
  @Prop({ type: Object, required: true })
  item: IMenuItem

  @Emit('go')
  go(path: string = '/') {
    this.$router.push({ path })
  }
}
```

### What is expected?
Successful passing of the test

### What is actually happening?
The test fails with an error: Debug Failure. False expression: Output generation failed

**Comment by eddyerburgh** [comment]
Can you provide a reproduction? From your example, I don't think this is a vue-test-utils error.

**Comment by yarkovaleksei** [comment]
I'm sorry, it works. The problem was in the package jest-vue-preprocessor.
