### ISSUE TITLE
Default stubs should render slot content

### ISSUE THREAD

**Issue by johnleider** [vuejs/vue-test-utils#599]
### Version
1.0.0-beta.13

### Reproduction link
[https://github.com/johnleider/vue-test-utils-router-bug/blob/master/package.json](https://github.com/johnleider/vue-test-utils-router-bug/blob/master/package.json)

### Steps to reproduce
Run unit tests. `.html` returns undefined.

### What is expected?
Return html markup

### What is actually happening?
When stubbing `router-link` that is used by a custom component , the return is undefined. 

---
Ed checked on latest beta and is still present.

**Comment by eddyerburgh** [comment]
The problem is that stubs by default don't render slots, so because the v-card renders a router-link that is stubbed to not render children, it renders undefined.

We should change the default stubs to render slots.

**Comment by eddyerburgh** [comment]
After thinking about it, I don't think we should render slots by default. 

Currently we have a RouterLinkStub component that renders the slot content.

**Comment by johnleider** [comment]
Thank you!
