### ISSUE TITLE
@babel/core integration

### ISSUE THREAD

**Issue by nothingismagick** [vuejs/vue-test-utils#602]
### What problem does this feature solve?
I am building the "test mode" for quasar-cli (a vue-based all-in-one project), and we have already moved to @babel/core for our interface. In order for me to integrate the @vue/test-utils I need to make sure that our babel is the same as your babel. As you are using Babel 6, I am getting namespace pollution (if that is the right word) and cannot successfully integrate the vue-test-utils. Currently your package.json looks like this:

```json
"babel-core": "^6.26.0"
```

I assume you will wait until @babel/core leaves beta, but I would like to know if you have a timeline for this.

### What does the proposed API look like?

```json
"@babel/core": "7.0.0"
```

**Comment by eddyerburgh** [comment]
We only use babel to compile ES6 in the tests. I'm happy to use Babel 7 now, if someone would like to make a PR.

I'm confused about why you have problems, neither of the distributed packages have babel as a devDependency.

Can you post more details about the namespace pollution?

**Comment by nothingismagick** [comment]
Hi - I can explain, but your answer suggests that our problem lies elsewhere. We are using vue/test-utils to build a mode into quasar-cli where the user will be able to rig test-runners to do live unit/coverage testing while they work and their project is constantly rebuilt and served to the browser. That is the plan, anyway.

So when the user runs quasar-cli to start a dev server, the quasar-cli module runs webpack and uses Babel transpilers to build and serve the user’s app. If the user has babel6 installed anywhere, `@Babel` complains and exits.

**Comment by eddyerburgh** [comment]
Ok thanks for the explanation. I don't think this is a problem with vue-test-utils so I'm closing the issue
