### ISSUE TITLE
Use of Array.prototype.includes breaks unit tests in browsers that do not support this.

### ISSUE THREAD

**Issue by honeroku** [vuejs/vue-test-utils#608]
### Version
1.0.0-beta.16

### Reproduction link
[https://codesandbox.io/s/7ykvrxrw0](https://codesandbox.io/s/7ykvrxrw0)

### Steps to reproduce
1. Download codesandbox codes.
2. Run tests on IE11 with karma.

### What is expected?
Tests should pass or fail, but not be terminated.

### What is actually happening?
Test is terminated due to "TypeError: Object doesn't support property or method 'includes"

---
Same as https://github.com/vuejs/vue-test-utils/issues/499 which reports use of 'Array.prototype.find'.

The specific line is:
https://github.com/vuejs/vue-test-utils/blob/v1.0.0-beta.16/packages/test-utils/src/wrapper.js#L519

Array.prototype.includes supported browsers: 
https://caniuse.com/#search=Array.prototype.includes

**Comment by eddyerburgh** [comment]
Thanks for the issue.

Would you like to make a PR replacing `includes` with an alternative?

**Comment by honeroku** [comment]
@eddyerburgh Sure I will.

I found `findIndex` too that is not supported in IE..

**Comment by eddyerburgh** [comment]
We can't run tests against ie11 on CircleCI.

One solution would be to use [eslint-compat](https://github.com/amilajack/eslint-plugin-compat) to check for methods that aren't supported in ie11.

**Comment by 38elements** [comment]
I think it resolve this issue to use babel instead of buble.
It uses [Runtime transform](https://babeljs.io/docs/plugins/transform-runtime/).
It sets the [targets](https://babeljs.io/docs/plugins/preset-env/) is `ie == 11`.

**Comment by eddyerburgh** [comment]
The decision to use buble was because it generates more readable output.

We could revisit and compare the output to seen if babel output is readable enough.

**Comment by eddyerburgh** [comment]
This issue is fixed and will be in the next release.

I think we should keep buble for now, although we can reinvestigate when we move the repo to typescript.
