### ISSUE TITLE
Code splitting support

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vue-test-utils#61]
Theoretically we should be able to support async components imported by the tested component when using `mocha-webpack` with the following config:

- `target: 'node'` for `webpack`
- `optimizeSSR: false` for `vue-loader`

But there are still some issues right now that prevents it from working. Need to investigate a bit further.

Most of the time splitting is done at route level so this is not a high priority concern, but would be nice to figure it out down the road.

**Comment by JessicaSachs** [comment]
Hey @yyx990803, seemingly there is a working test that exercises dynamically imported components. ([link](https://github.com/vuejs/vue-test-utils/blob/dev/test/specs/mount.spec.js#L236-L252)) Am I missing something?
