### ISSUE TITLE
Move to VuePress

### ISSUE THREAD

**Issue by eddyerburgh** [vuejs/vue-test-utils#621]
### What problem does this feature solve?
We should migrate the docs to VuePress to keep it in line with the rest of the Vue org docs.

### What does the proposed API look like?
Use VuePress for the docs.

It should only host English, Japanese, and Chinese translations, due to a recent Vue policy.

**Comment by 38elements** [comment]
Would you tell me about a recent Vue policy ?

**Comment by eddyerburgh** [comment]
We're going to stop hosting translations that don't have active maintenance.

The Japanese translations are actively maintained (by you!) so we will continue to host them. I've updated my original issue which said we will only support Chinese and English translations to include Japanese translations.

**Comment by 38elements** [comment]
I see.
Thank you for reply and updating.

**Comment by Alex-Sokolov** [comment]
What about Russian? Moving to vuepress is finished?

**Comment by eddyerburgh** [comment]
@Alex-Sokolov Yes, unfortunately we can only support languages that receive regular updates. If the translations are not updated regularly, they become out of sync with the real documentation. 

I'm grateful for the work you have done translating the Russian docs, and to all the other people who have translated the docs into different languages. But it's difficult for us to keep these translations up-to-date, especially if no core team members speak the language. Some of the translations we had were ten releases out of date.

You are welcome to fork and host the translation on their own, but we no longer have the bandwidth to include them in official repos
