### ISSUE TITLE
Render only child-component name in stub, but no sub-child-component

### ISSUE THREAD

**Issue by trollepierre** [vuejs/vue-test-utils#623]
### What problem does this feature solve?
When I shallowMount a ParentComponent containing a ChildComponent containing a SubChildComponent,
I would like to see only in template <child-component-stub>.
ParentComponent should not know his SubChildComponent. 

### What does the proposed API look like?
I don't know what to write here

**Comment by eddyerburgh** [comment]
Is the proposal for stubs to render default slots in `shallowMount`?

current:
```js
const wrapper = shallowMount(TestComponent)
wrapper.html() 
// <ChildComponent-stub></ChildComponent-stub>
```

proposed:
```js
const wrapper = shallowMount(TestComponent)
wrapper.html() 
// <ChildComponent-stub><SubChildComponent-stub></SubChildComponent-stub></ChildComponent-stub>
```

**Comment by trollepierre** [comment]
Hello @eddyerburgh , 
I close this issue: that is not what I need:

=> I wrote my issue once again
https://github.com/vuejs/vue-test-utils/issues/625
