### ISSUE TITLE
Render <ChildComponent> in html with their props

### ISSUE THREAD

**Issue by trollepierre** [vuejs/vue-test-utils#625]
### What problem does this feature solve?
When I shallowMount a TestComponent containing a ChildComponent
I would like to see it in template with its props.

TestComponent :
<div id='test-component'>
  <child-component my-prop="someValue"/>
</div>

current:

const wrapper = shallowMount(TestComponent)
wrapper.html() 

generated:
< ChildComponent-stub  />

proposed:

const wrapper = shallowMount(TestComponent)
wrapper.html() 

generated:
< child-component my-prop="someValue"/> 

### What does the proposed API look like?
I don't know

**Comment by eddyerburgh** [comment]
This will be supported in beta.17
