### ISSUE TITLE
Potential bug in event handling

### ISSUE THREAD

**Issue by VPenkov** [vuejs/vue-test-utils#650]
### Version
1.0.0-beta.16

### Reproduction link
[https://codesandbox.io/s/v6o7yjpmq0](https://codesandbox.io/s/v6o7yjpmq0)

### Steps to reproduce
1. Run test.spec.js
2. See the results

### What is expected?
- The test to pass when the template is defined with `@click="testMethod()"`
- The test to pass when the template is defined with `@click="testMethod"`

### What is actually happening?
- The passes when the template is defined with `@click="testMethod()"`
- The fails when the template is defined with `@click="testMethod"`

---
Not sure if the issue is in vue-test-utils, this started happening after updating a bunch of packages recently.

**Comment by eddyerburgh** [comment]
The problem is when you spy on the method, the function in the `on` handler is not updated. You need to force Vue to update:

```js
jest.spyOn(wrapper.vm, 'someMethod')
wrapper.vm.$forceUpdate()
```

Alternatively, you can use the Wrapper `setMethods` method which takes care of this for you:

```js
wrapper.setMethods({ someMethod: jest.fn() })
```

Or pass the stub in when you mount the component:

```js
mount(Component, {
  methods: {
    someMethod: jest.fn()
   }
})
```

**Comment by hjJunior** [comment]
@eddyerburgh I've got the same issue, even using `wrapper.setMethods`

I created a reproduce link:

https://codesandbox.io/s/vue-template-ev08b
