### ISSUE TITLE
Provide a template of JSFiddle, JSBin or CodePen or CodeSandbox to help developer to provide link to minimal reproduction

### ISSUE THREAD

**Issue by trollepierre** [vuejs/vue-test-utils#660]
### What problem does this feature solve?
As a developer that wants to explain my issue, I would like to have a template with the minimum config of JSFiddle, JSBin or CodePen or CodeSandbox .
If possible, with last versions of Vue, Vuex, Vuetify, Nuxt...

### What does the proposed API look like?
...

**Comment by briwa** [comment]
@trollepierre Feel free to use [this](https://jsfiddle.net/briwa/6mfz8ber/). I stumbled upon it from Google and updated to use the latest Vue Test Utils.

If you like the Codesandbox version, theres [a few existing ones](https://github.com/vuejs/vue-test-utils/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+codesandbox) from the people who raised the issue.

**Comment by eddyerburgh** [comment]
This is something I intend to add.

There's an issue to add this in the vue issue tracker. I'm closing this in favour of that issue, which is where the work needs to be done-https://github.com/vuejs/vue-issue-helper/issues/22
