### ISSUE TITLE
`wrapper.find()` cannot resolve HTML ids containing periods

### ISSUE THREAD

**Issue by alastairs** [vuejs/vue-test-utils#667]
### Version
1.0.0-beta.16

### Reproduction link
[https://github.com/alastairs/vue-issues-repro](https://github.com/alastairs/vue-issues-repro)

### Steps to reproduce
I [reported difficulty](https://forum.vuejs.org/t/stuck-asserting-a-class-was-added-to-an-element/34983) getting tests to pass when using `wrapper.find()` with an id containing a period, such as `wrapper.find('#a.b.c')`. The GitHub repo linked to this issue provides a minimal reproduction in the `dots-in-element-ids` folder. The differences from the default `vue create` results required to reproduce the bug are in the `HEAD` commit, `ecb4674`:

```udiff
diff --git a/dots-in-element-ids/src/components/HelloWorld.vue b/dots-in-element-ids/src/components/HelloWorld.vue
index f6ded57..0d2f009 100644
--- a/dots-in-element-ids/src/components/HelloWorld.vue
    b/dots-in-element-ids/src/components/HelloWorld.vue
@@ -12,7  12,7 @@
       <li><a href="https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-typescript" target="_blank">typescript</a></li>
       <li><a href="https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-unit-mocha" target="_blank">unit-mocha</a></li>
     </ul>
-    <h3>Essential Links</h3>
+    <h3 id="hello.essential-links">Essential Links</h3>
     <ul>
       <li><a href="https://vuejs.org" target="_blank">Core Docs</a></li>
       <li><a href="https://forum.vuejs.org" target="_blank">Forum</a></li>
diff --git a/dots-in-element-ids/tests/unit/HelloWorld.spec.ts b/dots-in-element-ids/tests/unit/HelloWorld.spec.ts
index 732a277..29be89d 100644
--- a/dots-in-element-ids/tests/unit/HelloWorld.spec.ts
    b/dots-in-element-ids/tests/unit/HelloWorld.spec.ts
@@ -10,4  10,11 @@ describe('HelloWorld.vue', () => {
     });
     expect(wrapper.text()).to.include(msg);
   });
+
+  it('renders essential links', () => {
+    const wrapper = shallowMount(HelloWorld);
+
+    // tslint:disable-next-line:no-unused-expression
+    expect(wrapper.find('#hello.essential-links').exists()).to.be.true;
+  });
 });
```

### What is expected?
The element is found and a new wrapper instance is returned which can be used to interact with that element. Specifically, `wrapper.find('#my.id').exists()` returns `true`/truthy. 

### What is actually happening?
The test fails, with the element not found. If calling a method (such as `classes()`) on the resulting wrapper, vue-test-utils reports the following error:

> Error: [vue-test-utils]: find did not return #hello.essential-links, cannot call classes() on empty Wrapper

The reproduction repository contains a test utilising the `exists()` method which currently fails and should pass when the bug is fixed.

---
[This forum post](https://forum.vuejs.org/t/stuck-asserting-a-class-was-added-to-an-element/34983) provides the context for this bug; please let me know if you require further information.

**Comment by eddyerburgh** [comment]
When `find` is called with a CSS selector it uses `element.matches` to match a DOM node. 

The problem here is the selector. The selector is being parsed to match an element with an id of `a`, a class of `b` and a class of `c`.

You need to escape the periods:

```js
it('find id with period', () => {
  const TestComponent = {template: '<div><p id="some.id" /></div>'}
  const wrapper = mount(TestComponent)
  expect(wrapper.find('#some\\.id').exists()).to.equal(true)
})
```

**Comment by alastairs** [comment]
Aha, that makes sense. Thanks for the clarification, @eddyerburgh.

**Comment by guptapuja75** [comment]
incase of data-test = "someid" ,it fails too,wht needs to be done in that case ??
