### ISSUE TITLE
Broken links in console error messages

### ISSUE THREAD

**Issue by shortdiv** [vuejs/vue-test-utils#669]
### Version
1.0.0-beta.16

### Reproduction link
[https://codesandbox.io/s/ox1q0l7mm6](https://codesandbox.io/s/ox1q0l7mm6)

### Steps to reproduce
Open the test console and click on the failing test. The link specified in the error message points to the old deprecated docs url and not the updated docs url. 

### What is expected?
The link should point to the new docs url.

### What is actually happening?
The link points to the old docs url.

**Comment by ebisbe** [comment]
@eddyerburgh An error related with broken links in the console is happening to me.  
I got this message for example: 
```
[vue-test-utils]: hasProp() has been deprecated and will be removed in version 1.0.0. Use props() instead—https://vue-test-utils.vuejs.org/en/api/wrapper/props
```
I'm using "@vue/test-utils": "^1.0.0-beta.16",

Do I open another issue?

**Comment by eddyerburgh** [comment]
@ebisbe yes please, unless you would like to make a PR?

**Comment by ebisbe** [comment]
@eddyerburgh I'll search it and open a Pr during this week.
