### ISSUE TITLE
Typescript error when use wrapper.classes().includes

### ISSUE THREAD

**Issue by Yawenina** [vuejs/vue-test-utils#684]
### Version
1.0.0-beta.16

### Reproduction link
[https://github.com/Yawenina/vue-test-utils-classes](https://github.com/Yawenina/vue-test-utils-classes)

### Steps to reproduce
```
npm install

npm run serve
```

### What is expected?
no error

### What is actually happening?
In my [test file](https://github.com/Yawenina/vue-test-utils-classes/blob/master/tests/unit/HelloWorld.spec.ts#L10), I write a test like this:
```
expect(wrapper.classes().includes('a')).toBe(false);
```
but when I ran `npm run serve`, typescript yield an error:
```
ERROR in vue-test-utils-classes/tests/unit/HelloWorld.spec.ts
10:30 Property 'includes' does not exist on type 'void | string[]'.
  Property 'includes' does not exist on type 'void'.
     8 |       propsData: { msg },
     9 |     });
  > 10 |     expect(wrapper.classes().includes('a')).toBe(false);
       |                              ^
    11 |   });
    12 | });
    13 |
Version: typescript 2.9.1
```

---
I read the [source code](https://github.com/vuejs/vue-test-utils/blob/dev/packages/test-utils/types/index.d.ts#L59) and find the type definition of the `classes()` method is this:

```
classes(): Array<string> | void
```

Maybe because the return value could be void so it does not have a `includes` method.

When I change it to :
```
classes(): Array<string>
```
the error disappears and everything works ok.

**Comment by eddyerburgh** [comment]
Actually it never returns void, so the definition file is incorrect. Would you like to make a PR that removes the void? There are two definition files that need to be changed, one in packages/test-utils/ and one in packages/server-test-utils

**Comment by Yawenina** [comment]
Sure, I'd love to.

**Comment by Yawenina** [comment]
I didn't find classes definition in packages/server-test-utils, so I only changed it in packages/test-utils/.

PR [#685](https://github.com/vuejs/vue-test-utils/pull/685) solves this issue.

**Comment by eddyerburgh** [comment]
Ah sorry I forgot that we don't have Wrappers in server-test-utils 😅

Thanks for the PR 👍
