### ISSUE TITLE
setProps cannot trigger watcher

### ISSUE THREAD

**Issue by fanpenghuix** [vuejs/vue-test-utils#686]
### Version
1.0.0-beta.16

### Steps to reproduce
component.vue
```js
{
  props: {
    value: {
    default:
      false,
      type: Boolean
    }
  },
  data() {
    return {
      checked: this.value
    }
  },
  watch: {
    value(v) {
      this.checked = v;
    }
  }
  // ...
}
```

use case
```js
it('watch methods is right', done = >{
  const wrapper = mount(checkbox);
const vm = wrapper.vm;
  wrapper.setProps({
    value: true
  });
  vm.$nextTick(() = >{
    expect(vm.checked).to.be.true;
     expect(
      Array.from(vm.$el.querySelector('.box').classList).indexOf('checked')
    ).to.not.eql(-1);
     done();
  });
});
```

### What is expected?
vm.checked is true

### What is actually happening?
vm.checked is false

**Comment by Qvatra** [comment]
@cdoneshot cdoneshot I'm facing the same problem. How have you solved yours?

**Comment by fanpenghuix** [comment]
@Qvatra 
Sorry to reply so late. I forgot the reason for closing the issue. I checked the code of the unit test and found that there was no change but the unit test passed. I think I should be wrong to open the issue.
