### ISSUE TITLE
Imported un-transpiled module is not transpiled when component under test is mounted

### ISSUE THREAD

**Issue by MartinPeverelli** [vuejs/vue-test-utils#689]
### Version
1.0.0-beta.16

### Reproduction link
[https://github.com/MartinPeverelli/reproduction-component](https://github.com/MartinPeverelli/reproduction-component)

### Steps to reproduce
- git clone git@github.com:MartinPeverelli/reproduction-component.git
- npm install
- npm run test:unit

### What is expected?
Tests should pass

### What is actually happening?
Tests fail with the following:
```
(function (exports, require, module, __filename, __dirname) { import ReproductionModule from './ReproductionModule'
                                                              ^^^^^^
SyntaxError: Unexpected token import
```

---
Custom module ReproductionModule is not transpiled.
The `serve` and `build` processes work as expected, but the `test:unit` process does not transpile the imported component on the fly.

**Comment by eddyerburgh** [comment]
Thanks for the reproduction. 

This is actually an issue for the @vue/cli repo. The problem is that the modules aren't compile by babel, I'll try to look into it if I get time, but you should make an issue in the vue-cli repo so we can track it effectively.
