### ISSUE TITLE
TypeError: (0 , _testUtils.mount) is not a function when aliasing 'vue'

### ISSUE THREAD

**Issue by TheCycoONE** [vuejs/vue-test-utils#690]
### Version
1.0.0-beta.16

### Reproduction link
[https://codesandbox.io/s/6jn9p3w8kn](https://codesandbox.io/s/6jn9p3w8kn)

### Steps to reproduce
In package.json

Add `"vue": "vue/dist/vue.js"` to `jest.moduleNameMapper`
Run jest

### What is expected?
Component should mount

### What is actually happening?
TypeError: (0 , _testUtils.mount) is not a function

Oddly this doesn't seem to be happening inside codesandbox.io, but it does if I download the project and run it locally.

**Comment by eddyerburgh** [comment]
moduleNameMapper uses regex to match modules. Jest was resolving vue-test-utils to vue/dist/vue.js. You can fix it by changing the regex:

```js
{
  //
  "moduleNameMapper": {
    "vue$": "vue/dist/vue"
  }
  //
}

**Comment by TheCycoONE** [comment]
Bah, sorry for the noise :)
