### ISSUE TITLE
Functional components render slots with strings as empty divs

### ISSUE THREAD

**Issue by danielsdeboer** [vuejs/vue-test-utils#693]
### Version
1.0.0-beta.16

### Reproduction link
[https://codesandbox.io/s/j376k9jvv](https://codesandbox.io/s/j376k9jvv)

### Steps to reproduce
* Create a basic functional component that renders content from the default slot
* Attempt to mount the component with a string in the default slot

### What is expected?
Should render the string, eg `<p>Some string</p>`

### What is actually happening?
Test utils renders an empty `<div>`, eg `<p><div></div></p>`

---
The component works as expected outside of the test environment. See the repro, where slotted content renders as expected.

**Comment by kfischer-okarin** [comment]
Since version 1.0.0-beta.17 it also shows following warning:

```
[Vue warn]: Error compiling template:
    
text content
    
- Component template requires a root element, rather than just text.
```
