### ISSUE TITLE
Distribute flow types

### ISSUE THREAD

**Issue by sobolevn** [vuejs/vue-test-utils#698]
### What problem does this feature solve?
I am using `flow` for my `vue` projects. And I am also using `flow` with `jest` and `@vue/test-utils` inside test.
Here's my setup: https://github.com/wemake-services/wemake-vue-template/blob/master/template/tests/unit/components/action-bar.spec.js

The only thing that is missing `flow` types in this setup is `@vue/test-utils`. So, do you have any plans to distribute already existing `flow` types? Do they require any extra work?

Related: https://github.com/sobolevn/vue-flow-typed/issues/19

Thanks!

**Comment by eddyerburgh** [comment]
The plan is to move to TypeScript, and we would stop maintaining flow types so it would bet better for vue-flow-typed to copy the flow typings and maintain them

**Comment by sobolevn** [comment]
@eddyerburgh ok, will do.
