### ISSUE TITLE
Component template requires a root element, rather than just text

### ISSUE THREAD

**Issue by wagerfield** [vuejs/vue-test-utils#707]
### Version
1.0.0-beta.18

### Reproduction link
[https://codesandbox.io/s/o1r1qw3qq](https://codesandbox.io/s/o1r1qw3qq)

### Steps to reproduce
1. Take a look at `src/TestComponent.spec.js`
2. Look at the `Console` tab and observe the error:

```
[Vue warn]: Error compiling template:

Hello

- Component template requires a root element, rather than just text.
```

3. Look at `Tests` tab and observe that both the "mount with default slot" and "shallowMount with default slot" are failing when using the `default` slot to pass some text to the `TestComponent`

### What is expected?
All tests should pass. The two tests "with default slot" should match the expected html `<button>Hello</button>`

### What is actually happening?
The 2 failing tests are rendering the html `<button><div></div></button>`

---
If you roll back to `@vue/test-utils@1.0.0-beta.17` the tests pass, so this is clearly a bug with the latest beta release.

**Comment by cdbkr** [comment]
to me, this is similar to #693 . CompileToFunctions seems not handling text only. Since a string is not generating a valid AST and throwing errors, then maybe it makes sense to reconsider the approach and rely on the compile function only (where it makes sense).

**Comment by 38elements** [comment]
I think putting text to slots mounting option is not supported after `1.0.0-beta.17`.

**Comment by eddyerburgh** [comment]
There was a breaking change where we no longer resolve values in slots (like this.someVal).

This is a bug that we should fix
