### ISSUE TITLE
Add child-Prop in stub of ChildComponent (when using snapshot)

### ISSUE THREAD

**Issue by trollepierre** [vuejs/vue-test-utils#708]
### What problem does this feature solve?
I would like to see in my snapshot that I call my childcomponent with correct prop.

```
 <childcomponent-stub child-Prop="'some propsData that needs to be tested'"/>
````

Here is a failing test with my expected snapshot:

https://codesandbox.io/s/ql77047m9q

### What does the proposed API look like?
nothing to add here

**Comment by trollepierre** [comment]
Hey @eddyerburgh , will this feature be ready for the next release? Thx

**Comment by eddyerburgh** [comment]
No sorry, the priority for me is bug fixes, and I'm busy with writing my book. I'm happy to review a PR for this feature, but I don't have the time to implement myself at the moment.

**Comment by sobolevn** [comment]
As I get it, we now have props that are raw objects when using `shallow` mounts?
And good-old-regular props when using `mount()`?
