### ISSUE TITLE
Add Documentation Link to Project Description

### ISSUE THREAD

**Issue by Austio** [vuejs/vue-test-utils#71]
:wave:

I think we should add the link to the documentation in the project descriptions similar to the other vue repos (vue-router, vuex, vue)

Something like
```
Testing Library for Vue.js.  https://vue-test-utils.vuejs.org/
```

Example on vuex repo
```
Centralized State Management for Vue.js. https://vuex.vuejs.org
```

**Comment by eddyerburgh** [comment]
Agreed.

@yyx990803 can you add a link to the docs to the repository description?

**Comment by yyx990803** [comment]
done!
