### ISSUE TITLE
Installing a Plugin on a Local Vue Instance Does Not Work on TypeScript

### ISSUE THREAD

**Issue by jbenner-radham** [vuejs/vue-test-utils#712]
### Version
1.0.0-beta.18

### Reproduction link
[https://github.com/jbenner-radham/create-local-vue-ts-lab](https://github.com/jbenner-radham/create-local-vue-ts-lab)

### Steps to reproduce
1. Clone example repo.
2. `yarn install`
3. `yarn test:unit`

### What is expected?
The unit tests will pass.

### What is actually happening?
The unit tests are failing because the plugin installed on the `localVue` instance is not getting properly installed.

---
This isn't an issue when running on a normal Vue instance via `yarn serve`. And oddly it's not an issue in a JavaScript implementation, see [here](https://github.com/jbenner-radham/create-local-vue-js-lab) for an working JavaScript implementation example project.

**Comment by jbenner-radham** [comment]
Some additional information I came across; apparently this is happening when I try and attach a mock to the mount as well e.g.

```ts
const $eventBus = new Vue();
const wrapper = shallowMount(ExampleComponent, {
    mocks: { $eventBus }
});

expect(wrapper.vm.$eventBus).to.exist;
```

Which raises:

> AssertionError: expected undefined to exist

**Comment by eddyerburgh** [comment]
I believe this has been fixed in #709. I'll release the fix in a few hours

**Comment by jbenner-radham** [comment]
Awesome, thank you very much!

P.S. Thanks for the hard work you put in on a fantastic product for the community.

**Comment by eddyerburgh** [comment]
Thanks :)

This should be fixed in beta.19
