### ISSUE TITLE
Mounting Option `stubs` not working.

### ISSUE THREAD

**Issue by cpxPratik** [vuejs/vue-test-utils#713]
### Version
1.0.0-beta.18

### Reproduction link
[https://jsfiddle.net/cpxPratik/sa3yqznw/3/](https://jsfiddle.net/cpxPratik/sa3yqznw/3/)

### Steps to reproduce
When shallowmounting or mounting, giving `stubs` mounting option such as `stubs: ['router-link']`.

### What is expected?
Should not have any warning.

### What is actually happening?
Warning on console: `[Vue warn]: Unknown custom element: <router-link-stub> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

---
Doing `VueTestUtils.config.stubs['router-link'] = '<div />'` solves it, but mounting option should have worked too unless i am misunderstanding sth. Warning was produced after updating from 1.0.0-beta.14 to 1.0.0-beta.16, there was not warning beforehand.

**Comment by eddyerburgh** [comment]
Thanks for the bug report.

A temporary fix is to add it to the ignored elements:

```js
import Vue from 'vue'

Vue.config.ignoredElements.push('router-link-stub')
```

**Comment by sreuss** [comment]
Could the `mocks` option be affected as well? Just tried to upgrade from beta.17 to beta.18 and I am seeing some strange test failures.

**Comment by eddyerburgh** [comment]
That's a seperate issue that's been fixed in #709. I'll release this evening 👍

**Comment by cars10** [comment]
I still experience the same behaviour in beta.19.

**Comment by eddyerburgh** [comment]
Can you create an issue with a reproduction?

**Comment by lambdalisue** [comment]
@eddyerburgh @cars10 

The following codes BEFORE tests fixed the behavior in my environment with beta.20.

```javascript
import Vue from 'vue';

Vue.config.ignoreElements = [];
```

It seems `Vue.config.ignoreElements` must be assigned prior to the test?
https://github.com/vuejs/vue-test-utils/pull/714/files#diff-814c51828b90615b0a6800b1ecd862ecR67

**Comment by eddyerburgh** [comment]
Can you check if setting it in mount.js fixes the issue?
