### ISSUE TITLE
Slot with only text doesn't render in Jest snapshot

### ISSUE THREAD

**Issue by tonimc** [vuejs/vue-test-utils#718]
### Version
1.0.0-beta.18

### Reproduction link
[https://codesandbox.io/s/w72rz7wl7k](https://codesandbox.io/s/w72rz7wl7k)

### Steps to reproduce
I have a button component with a default slot (maybe the same happens with named slots), in this slot I set the text of the button. When I run my test the snapshot doesn't match with the previous snaps (generated with the previous version of `vue-test-utils` 1.0.0beta.17) because the slot not set the text provided, as If I didn't specify any slot.
In my component, more complex than what I've created on the codesadbox, on the slot, it render a `<div/>`

### What is expected?
Get a snapshot with the text in the slot area.

### What is actually happening?
the slot is empty or a `<div />` (this happen in my context, not in codesandbox, in which comes empty)

But if you see the component working on the `main.js` button it's render as I expected.

---
If in the default slot I set `<p>test</p>` it works fine (test also provided on codesandbox)

**Comment by eddyerburgh** [comment]
Thanks for the bug report and reproduction. This issue has already been reported and fixed (https://github.com/vuejs/vue-test-utils/issues/707).

It will be in the beta.19 which will be released in a few hours

**Comment by tonimc** [comment]
Thanks, @eddyerburgh and sorry because I didn't search on closed issues.

**Comment by chenxeed** [comment]
Hi,

I still find this same issue even when I already in version `1.0.0-beta-24` now.

**Comment by eddyerburgh** [comment]
Hi @chenxeed , can you create a new issue with a minimal reproduction?
