### ISSUE TITLE
Docs website syling is broken

### ISSUE THREAD

**Issue by kris-swann** [vuejs/vue-test-utils#721]
### Version
1.0.0-beta.19

### Reproduction link
[https://vue-test-utils.vuejs.org/](https://vue-test-utils.vuejs.org/)

### Steps to reproduce
Got to the website. Use your eyes to look at how it is styled wrong.

### What is expected?
It is not styled wrong

### What is actually happening?
It is styled wrong.

---
Please style the website correctly so that the docs can be referenced easily.

**Comment by kris-swann** [comment]
![screen shot 2018-06-15 at 10 17 35 am](https://user-images.githubusercontent.com/12589014/41475850-6641c026-7085-11e8-937b-76e23542a729.png)



This is what i see when I go to the website.

**Comment by eddyerburgh** [comment]
I can't replicate this on my machine, or on [webpagetest](https://www.webpagetest.org/result/180615_AM_e222fa475ab055422f2c6f9b5ef197c9/). Can you post any errors from the console?

**Comment by kris-swann** [comment]
```
Loading failed for the <script> with source “https://vue-test-utils.vuejs.org/assets/js/152.99e24a89.js”.
wrapper:250
Loading failed for the <script> with source “https://vue-test-utils.vuejs.org/assets/js/app.8a39e079.js”.
wrapper:250
```

**Comment by 38elements** [comment]
I can watch the pages which are  normal.

**Comment by kris-swann** [comment]
Website appears normally again. Closing issue.
