### ISSUE TITLE
Slots with text contents are not properly resolved in functional components.

### ISSUE THREAD

**Issue by TheAlexLichter** [vuejs/vue-test-utils#732]
### Version
1.0.0-beta.19

### Reproduction link
[https://codesandbox.io/s/ollqlyxv2y](https://codesandbox.io/s/ollqlyxv2y)

### Steps to reproduce
In beta.19, template component slots can be filled with strings easily. But functional components still cannot.

* Create a functional component with a slot (can be default or named)
* Create a test suite which fills the slot with a simple string
* See the `<div></div>` problem again.

### What is expected?
The slot should be properly filled with the string

### What is actually happening?
The `<div></div>` problem is occuring again

Related: #718, #707, #711

**Comment by Rleahy22** [comment]
I'm still seeing this issue even on 1.0.0-beta.19

**Comment by TheAlexLichter** [comment]
@Rleahy22 see #733.
Can you reproduce it with this PR merged?

**Comment by Rleahy22** [comment]
Oh my bad I think I confused that one with #711. I take it #733 isn't in 1.0.0-beta.19 then?

**Comment by TheAlexLichter** [comment]
Right, #733 isn't included in a release yet.
