### ISSUE TITLE
setProps doesn't update props in some circumstances

### ISSUE THREAD

**Issue by TheCycoONE** [vuejs/vue-test-utils#738]
### Version
1.0.0-beta.19

### Reproduction link
[https://codesandbox.io/s/1k6y65wp4](https://codesandbox.io/s/1k6y65wp4)

### Steps to reproduce
Create a component, like the one in the above reproduction, with multiple properties that are watched.
It is important that the watch function reads one of the properties (i.e. if you remove that switch statement from my test case the problem doesn't happen.)
Create a test for that component, call setProps on the property that is read in the watch.

### What is expected?
The property should be updated, the component should react to the updated property

### What is actually happening?
The property is never updated. props() shows the old value.

Note: this is a regression, it worked correctly in 1.0.0-beta.16 (I did not try other versions)

**Comment by eddyerburgh** [comment]
Sorry, this is another problem with how we've implemented synchronous renders.

There's a PR open to fix this by adding an async option to Vue—https://github.com/vuejs/vue/pull/8240.

For the moment, the workaround is to set the `sync` mounting option to false and use Vue.nextTick/ setTimeout to await DOM updates (like you're doing):

```js
test('use Vue.nextTick', (done) => {
  const wrapper = mount(TestComponent, { sync: false })
  wrapper.trigger('click')
  Vue.nextTick(() => {
    expect(wrapper.text()).toBe('updated')
    done()
  })
})
```

**Comment by TheCycoONE** [comment]
Setting sync false and waiting for Vue.nextTick doesn't appear to work around the `countingAlgo` prop not updating case that started happening after updating from beta 16 to beta 19.

It does workaround the DOM not updating when `setProp({value: 42})` is called which was needed in 16 as well.

**Comment by HcySunYang** [comment]
@TheCycoONE @eddyerburgh 
`setProps` does not work in vue@2.2.6, behaves like this issue, but works fine in the latest version of vue.

**Comment by TheCycoONE** [comment]
@HcySunYang I am on vue 2.5.16

**Comment by agriffis** [comment]
@TheCycoONE I'm hitting this too. What are you doing as a workaround?

**Comment by TheCycoONE** [comment]
Unfortunately I haven't found a workaround yet. For now I'm *.skip*ping those tests.

**Comment by agriffis** [comment]
I guess `npm i -D @vue/test-utils@1.0.0-beta.17` works. 18, 19 and 20 are broken.

**Comment by agriffis** [comment]
It's hard to pin this bug down. I finally found a minimal failing test: updating a prop that is referenced through a chain of computed and lifecycle hook. I created #820 with that test case.

With that specific configuration, here's the table:

  | sync: true | sync: false
-- | -- | --
1.0.0-beta.17 | works | works
1.0.0-beta.18 | works | works
1.0.0-beta.19 | **broken** | works
1.0.0-beta.20 | **broken** | works

I think that table changes slightly depending on the exact component configuration, but that's what I found for the minimal test case.

**Comment by eddyerburgh** [comment]
Thanks @agriffis . 

This will be fixed when Vue 2.6 is released. Until then, you will need to run tests with `sync` set to `false`.

**Comment by jcupps** [comment]
FWIW sync = false and Vue.nextTick/setTimeout doesn't seem to work for my use case either :(

**Comment by PierreTurnbull** [comment]
Hello, I have this bug on Vue 2.6.11. When using `wrapper.setProps`, the expectation that comes after doesn't work, unless I enclosed it in `nextTick`. Note that it seems like I don't need to set `sync` to `false` when mounting my component for the test to work.

**Comment by Sefriol** [comment]
> Hello, I have this bug on Vue 2.6.11. When using `wrapper.setProps`, the expectation that comes after doesn't work, unless I enclosed it in `nextTick`. Note that it seems like I don't need to set `sync` to `false` when mounting my component for the test to work.

Noticed the same with `@vue/cli 4.3.1` and `Vue 2.6.10`

**Comment by dobromir-hristov** [comment]
In my testing I have noticed it works mostly after I await `nextTick`. The current versions of VTU no longer have `sync: false`. Latest VTU version you can just `await setProps()`, should work :)

**Comment by Sefriol** [comment]
I think `await setProps` does pass the checks when trying to get the prop values etc, but it fails to update the html/text and fails `.contains` checks until you use `await nextTick()`.

**Comment by dobromir-hristov** [comment]
setProps returns nextTick if I am not mistaking :/

**Comment by manonheine** [comment]
`await nextTick()` doesn't do it for me, the props are supposedly updated (as seen from console.log) but have no effect whatsoever on the functions that are called after. 
My current work around is to re-`shallowMount` the component with updated props in `propsData` in the test, then it suddenly works.
