### ISSUE TITLE
Getting started with the vuejs-templates/webpack (& Karma)

### ISSUE THREAD

**Issue by kemalcany** [vuejs/vue-test-utils#74]
Hi guys, excellent repo and docs thanks a lot!

I was wondering, are there any plans to expand the documentation to cover getting started with the [vuejs-templates/webpack](https://github.com/vuejs-templates/webpack) since it's probably the most popular official starter out there (4500+ stars)

The starter has a nice out of the box karma / mocha / sinon / chai unit test framework. 

Current documentation doesn't mention anything about Karma. I believe it could be helpful to many to embrace the test-utils into their workflow. 

What do you think? Can it be done? Would you like help on this?

Cheers

**Comment by eddyerburgh** [comment]
Hi, thanks @kemalcany.

I would love some help on writing a getting started guide with karma. As you said, a lot of people use the karma-mocha setup provided in the webpack template. would you be able to make a PR?

The plan with vue-cli webpack template is to eventually replace karma and mocha with Jest, there's a PR open now — https://github.com/vuejs-templates/webpack/pull/824.

**Comment by eddyerburgh** [comment]
@kemalcany would you like to add a guide on using vue-test-utils with Karma/mocha/chai?

**Comment by wizardone** [comment]
Would love to write one myself, but I am having some difficulties myself with the very basic setup of such project, so I would be very happy is someone more experienced can have a look and write a good documentation on the topic.
