### ISSUE TITLE
Asynchrony in components

### ISSUE THREAD

**Issue by Ray-56** [vuejs/vue-test-utils#741]
### Version
1.0.0-beta.11

### Reproduction link
[https://github.com/vuejs/vue-test-utils/issues/740](https://github.com/vuejs/vue-test-utils/issues/740)

### Steps to reproduce
i tried the example in the document.https://vue-test-utils.vuejs.org/zh/guides/#%E6%B5%8B%E8%AF%95%E5%BC%82%E6%AD%A5%E8%A1%8C%E4%B8%BA. no problem.
but it doesn't work when you change the direct return to delay the 1s return is asynchrony.
eg there is a problem:
https://user-images.githubusercontent.com/17818179/41647496-25705cd8-74a9-11e8-99f0-0c01095d321d.png

### What is expected?
Assert that success

### What is actually happening?
Assertion failure

**Comment by eddyerburgh** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
