### ISSUE TITLE
Mocha-webpack setup, can't suppress Vue logging

### ISSUE THREAD

**Issue by rssfrncs** [vuejs/vue-test-utils#75]
Using the mocha-webpack setup, I have a required file `start.js` with the following code:

```
require('jsdom-global')();
const Vue = require('vue');

// disable Vue logging
Vue.config.productionTip = false;
Vue.config.devtools = false;
Vue.config.silent = true;

global.assert = require('chai').assert;
global.expect = require('chai').expect;
````

However, Vue is still logging out to the console,

![image](https://user-images.githubusercontent.com/7808978/31219020-f5594bba-a9b3-11e7-9465-7a8371fc0d4b.png)

Have I missed something?

**Comment by rssfrncs** [comment]
@eddyerburgh thanks for the quick turn around, will this be included in the next beta release?

**Comment by eddyerburgh** [comment]
Yes
