### ISSUE TITLE
Triggering click on a label for an element does not trigger click on that element

### ISSUE THREAD

**Issue by C-Higgins** [vuejs/vue-test-utils#760]
### Version
1.0.0-beta.19

### Reproduction link
[localhost:3000](localhost:3000)

### Steps to reproduce
```  
<label id='lbl' for='btn'>label</label>
  <button id='btn' @click='clicked'>btn</button>
```
```
const wrapper = mount(component)
wrapper.find('#lbl').trigger('click')
```
### What is expected?
Button @click will be called, mirroring browser functionality

### What is actually happening?
Click event does not follow label-for

**Comment by eddyerburgh** [comment]
`trigger` is a wrapper around creating a synthetic DOM `MouseEvent` and dispatching it on an element, so it should behave correctly.

**Comment by phobetron** [comment]
I'm having the same issue testing a checkbox input. Clicking on the label does not select the checkbox, and my use case specifically needs that to be tested.

**Comment by scottadamsmith** [comment]
Maybe not what are hoping for, but what if did this instead:

```
const wrapper = mount(component)
wrapper.find('#lbl').element.click()
```

**Comment by scottadamsmith** [comment]
> I'm having the same issue testing a checkbox input. Clicking on the label does not select the checkbox, and my use case specifically needs that to be tested.

Maybe not what are hoping for, but what if you did this instead:

```
const wrapper = mount(component)
wrapper.find('#lbl').element.click()
```

**Comment by eddyerburgh** [comment]
@phobetron can you create a minimal reproduction and open a new issue?

**Comment by dovca** [comment]
I had a similar issue where triggering a click event on the label wouldn't emit a change event from the input. The solution was to install the `jest-environment-jsdom-fifteen` npm module and add
```
testEnvironment: 'jest-environment-jsdom-fifteen'
```
to `jest.config.js`

**Comment by chhavi-khandelwal** [comment]
I am facing the same issue as shown below:
RadioComp
`<label  :class="classes" :for="name">
    <input
      :id="name"
      type="radio"
      :checked="checked"
      :disabled="disabled"
      :name="name"
      :value="value"
      @change="$emit('change', value)"
    />
</label>`

Test:

`  it("can send the value on change", () => {
    const wrapper =  mount(RadioComp, {
    propsData: {
      disabled: disabled || false,
      name: "foo",
      data: [{ text: "foo", value: "foo" }]
    },
  });
    wrapper.find(LABEL_SELECTOR).trigger("click");
    expect(wrapper.emitted("change")[0]).toStrictEqual(['foo']);
  });`
  
  Facing error: TypeError: Cannot read property '0' of undefined

**Comment by houfeng0923** [comment]
make attachTo 'body' when use `mount`

**Comment by kohaiy** [comment]
```js
mount({}, {
  attachTo: 'body',
})
```


> make attachTo 'body' when use `mount`
