### ISSUE TITLE
Create stub name using tag

### ISSUE THREAD

**Issue by lambdalisue** [vuejs/vue-test-utils#765]
### Version
1.0.0-beta.20

### Reproduction link
[https://codesandbox.io/s/zk6k1yl76m](https://codesandbox.io/s/zk6k1yl76m)

### Steps to reproduce
When a child component has a name, it seems a given custom tag name is ignored. I think the stub name should be quite similar to a given custom tag name.

### What is expected?
A tag name of a stub for `MaterialIconView` in `TestComponent` is `x-material-icon-stub`

### What is actually happening?
The tag name is `materialiconview-stub`

**Comment by lambdalisue** [comment]
it's not same issue but it seems the custom attribute is missing in the stub component in the linked example.

**Comment by ebisbe** [comment]
https://github.com/vuejs/vue-test-utils/issues/1564#issuecomment-1424857260
