### ISSUE TITLE
Are all attribute selectors supported?

### ISSUE THREAD

**Issue by davidpelayo** [vuejs/vue-test-utils#766]
I'm wondering whether it's supported all attributes selectors as specified for instance, [here](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors).

I'm trying to deal with a attribute selector similar to this:

```
[attr^=value]
Represents elements with an attribute name of attr whose value is prefixed (preceded) by value.
```

But it doesn't work.

Am I missing anything?

**Comment by eddyerburgh** [comment]
Yes for DOM elements all CSS selectors are supported

**Comment by davidpelayo** [comment]
So it does not work. Any idea why, @eddyerburgh?

**Comment by eddyerburgh** [comment]
I'm unsure, maybe the DOM you're running the tests in (JSDOM maybe?) doesn't support that selector. Under the hood we use the `Element.matches` to assert whether the node matches the selector.
