### ISSUE TITLE
Update documentation about data

### ISSUE THREAD

**Issue by trollepierre** [vuejs/vue-test-utils#769]
### Version
1.0.0-beta.20

### Steps to reproduce
https://vue-test-utils.vuejs.org/api/wrapper/#setdata-data

There is no information about passing a data function.

### What is expected?
Add a paragraph saying:

You can also pass a data function, which will initialize the Vue instance with passed values.
```
// Foo.vue
export default {
  data: () => ({
    foo: 'value'
})
```
```
import { mount } from '@vue/test-utils'
import Foo from './Foo.vue'

const wrapper = mount(Foo, {
  data: () => ({
    foo: 'bar'
  })
})

expect(wrapper.vm.foo).toBe('bar')
```

### What is actually happening?
this code works and deserves to be added, if you agreed

**Comment by eddyerburgh** [comment]
I don't think this should be added. The way Vue Test Utils works, any Vue options that aren't VTU options are passed to a component on instantiation. So you can use this to override all properties, like `methods`.

There's a section in the docs that mentions this already—https://vue-test-utils.vuejs.org/api/options.html#other-options
