### ISSUE TITLE
Feature: setSelected() with value or setValue() on select

### ISSUE THREAD

**Issue by VictorCazanave** [vuejs/vue-test-utils#775]
### What problem does this feature solve?
In my tests I often use the same value (stored in a variable) to select an option and check the assertion.

Then the current setSelect() is not very convenient :
```javascript
const values = ['value0', 'value1']
const options = wrapper.find('select').findAll('option')
const index = 1
options.at(index).setSelected()
expect(/* something */).toEqual(values[index])
```

Same when selecting an option by value :
```javascript
const newValue = 'value1'
const option = wrapper.find('select').find(`option[value="${newValue}"]`)
option.setSelected()
expect(/* something */).toEqual(newValue)
```

So I prefer to use :
```javascript
const select = wrapper.find('select')
const newValue = 'value1'
select.element.value = newValue
select.trigger('change')
expect(/* something */).toEqual(newValue)
```

### What does the proposed API look like?
```javascript
const select = wrapper.find('select')
select.setSelected('value')
// or
select.setValue('value') // Trigger 'change' event instead of 'input'
// or a new method
select.setSelectedValue('value')
```

**Comment by VictorCazanave** [comment]
@eddyerburgh if you agree with this feature, I may have time to (try to) make a PR this week 😏

**Comment by eddyerburgh** [comment]
I like the idea, but not sure how it would work when you have multiple options with the same value?

**Comment by VictorCazanave** [comment]
I always use options with unique values.
For what kind of use case do you need options with the same value?

Maybe this feature should also accept an Array as parameter to handle [multiple select](https://vuejs.org/v2/guide/forms.html#Select):
```javascript
select.setSelected(['value0', 'value1']);
```

**Comment by eddyerburgh** [comment]
Ok, how about updating setValue to set the value of a selected element. Then there's no need to handle multiple options with the same value

**Comment by VictorCazanave** [comment]
It sounds good to me

**Comment by VictorCazanave** [comment]
May I create a PR or does this feature need more discussion/approval?

**Comment by eddyerburgh** [comment]
Yes you can create a PR :)
