### ISSUE TITLE
`findAll` does not work on `name` selector or Component selector in browser

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/vue-test-utils#784]
### Version
1.0.0-beta.20

### Reproduction link
[https://github.com/lmiller1990/vue-test-utils-browser-bug](https://github.com/lmiller1990/vue-test-utils-browser-bug)

### Steps to reproduce
Open index.html.

Failing assertion is on like 98.

### What is expected?
Test passes

### What is actually happening?
Test is failing.

---

For some reason the name of the children components are `o` instead of `MustDoItem`. In a non browser env this works fine.

I added a fix to this on line 2708 of `vue-test-utils`.

I would like to make a PR with this fix if it is an appropriate way to fix the problem. I don't fully understand why this only fails in the browser. 

`find` also suffers this problem.

**Comment by eddyerburgh** [comment]
Thanks for finding the bug. Yes we should fix this. Can you replicate it in the vue-test-utils karma tests? npm run test:unit:karma? Ideally we would have a test for the fix.

**Comment by lmiller1990** [comment]
A better minimal failing example:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
  <script src="https://cdn.rawgit.com/vuejs/vue/dev/dist/vue.min.js"></script>
  <script src="https://cdn.rawgit.com/vuejs/vue/dev/packages/vue-template-compiler/browser.js"></script>
  <script src="vue-test-utils.js"></script>
  <!--<script src="https://cdn.rawgit.com/vuejs/vue-test-utils/dev/packages/test-utils/dist/vue-test-utils.iife.js"></script>-->
  <script src="https://cdn.rawgit.com/Automattic/expect.js/0.3.1/index.js"></script>
  <link href="https://cdn.rawgit.com/mochajs/mocha/2.2.5/mocha.css" rel="stylesheet" />
  <script src="https://cdn.rawgit.com/mochajs/mocha/2.2.5/mocha.js"></script>
  <script>mocha.setup('bdd')</script>
</head>

<body>
<div id="mocha"></div>

<script>
function assert(actual, expected) {
  if (actual != expected) {
    throw Error(`Error, expected ${expected} got ${actual}`)
  }
}


const { shallowMount, mount } = VueTestUtils

  it('mount returns an array of VueWrappers querying a non SFC', () => {
    const MustDoItem = Vue.component('MustDoItem', {
      name: "MustDoItem",
      template: `<div />`
    })

    const MustDoList = Vue.component('must-do-list', {
      data() {
        return {
          items: [1, 2, 3]
        }
      },
      template: `<div><must-do-item v-for="i in items" :key="i" /></div>`
    })

    const wrapper = mount(MustDoList)
    const componentArr = wrapper.findAll(MustDoItem)
    assert((componentArr.length), 3)
  })

  it('shallowMount an array of VueWrappers querying a non SFC', () => {
    const MustDoItem = Vue.component('MustDoItem', {
      name: "MustDoItem",
      template: `<div />`
    })

    const MustDoList = Vue.component('must-do-list', {
      data() {
        return {
          items: [1, 2, 3]
        }
      },
      template: `<div><must-do-item v-for="i in items" :key="i" /></div>`
    })

    const wrapper = shallowMount(MustDoList)
    const componentArr = wrapper.findAll(MustDoItem)
    assert((componentArr.length), 3)
  })

mocha.run()
</script>

</body>
</html>
```

Somehow only one case, `shallowMount`, is failing. 

However, the exact same test does not fail with `npm run test:unit:karma`, as demonstrated in this branch https://github.com/vuejs/vue-test-utils/compare/dev...lmiller1990:dev

Updating `vmCtorMatchesSelector` with this lets the browser version pass:

```js
function vmCtorMatchesSelector (component, selector) {
  /** start fix **/
  if (component.$options._componentTag) {
    const selectorName = (selector.options.name)
    const tagToName = capitalize(camelize(component.$options._componentTag))
    console.warn("Here is the workaround")
    return selectorName === tagToName
  }
  /** end fix **/

  var Ctor = selector._Ctor || (selector.options && selector.options._Ctor);
  if (!Ctor) {
    return false
  }
  var constructor = component.__proto__.constructor;
  return Object.keys(Ctor || {}).some(function (c) {
    return Ctor[c] === constructor || Ctor[c] === constructor.super
  })
}
```
passes (in browser).

I will continue to investigate.

Edit: doing `console.log(name, vm.$vnode.componentOptions.Ctor.options.name)` in `vmCtorMatchesName` in karma yields `LOG LOG: 'MustDoItem', 'must-do-list'`, but in the browser `MustDoItem o`. Seems the `options.name` is operating differently.

Edit again: `vm.$node.componentsOptins.Ctor.options.name` is always `o` in the browser, only for `shallowMount`. I will continue updating here with my notes and research. 

I think in the browser for some reason, when the child components change into `o-stub`, the `name` also is changing.

**Comment by eddyerburgh** [comment]
The repro you provided is passing now when using the dist file from GitHub 👍
