### ISSUE TITLE
How to read input value

### ISSUE THREAD

**Issue by lusarz** [vuejs/vue-test-utils#79]
I want to read input value in my tests. I can do it easily with querySelector:
`const value = wrapper.vm.$el.querySelector('input').value`

but I would like to use wrapper method, something like:
`const value = wrapper.find('input').getInputValue()`

Is it possible with current wrapper API ?

**Comment by eddyerburgh** [comment]
Yes 🙂

```js
const value = wrapper.find('input').element.value
```

`find` traverses DOM nodes and Vue instances. All Wrappers returned by `find` contain an `element` and a `vnode` property. Only Vue instance Wrappers contain a `vm` object.

**Comment by lusarz** [comment]
Yeah, it works :) Thanks!

**Comment by chlab** [comment]
What if you're using a custom form element, such as [this](https://github.com/ElemeFE/element/blob/dev/packages/input/src/input.vue)?

```
<el-input ref="emailField" name="email" v-model="form.email"></el-input>
```

I have tried giving it a `ref` and accessing it via ´vm.find({ ref: 'emailField' }).data.currentValue´ or via name `vm.find('[name=email]').text()` (and various other combinations) but I can't ever get the value.

Preferably, I'd rather go "the DOM way" as the test is about seeing if the value is rendered, not if it's around in the vue instances.

**Comment by lusarz** [comment]
`find` method returns wrapper. Could you check for: `vm.find({ ref: 'emailField' }).vm.currentValue` ?

**Comment by chlab** [comment]
That doesn't work. Also tried with `.vnode.currentValue` and `.element.value` all to no avail.

**Comment by LinusBorg** [comment]
Why use find? `wrapper.vm.$refs.emailField.currentValue`

**Comment by chlab** [comment]
Good point @LinusBorg, that works. Thanks.

**Comment by OzzyTheGiant** [comment]
To add to @eddyerburgh's comment, if using TypeScript you will need to cast the returned element as HTMLInputElement if getting type or compiler errors. This is because .element returns a generic HTMLElement object. So this code would be like the following:

```typescript
const inputField: HTMLInputElement = wrapper.find('input').element as HTMLInputElement
const value = inputField.value
```

**Comment by ProfessorTom** [comment]
> Yes 🙂
> 
> ```js
> const value = wrapper.find('input').element.value
> ```
> 
> `find` traverses DOM nodes and Vue instances. All Wrappers returned by `find` contain an `element` and a `vnode` property. Only Vue instance Wrappers contain a `vm` object.

@eddyerburgh Has this stopped working along the way? I'm having no luck reading my `input`'s `value` in a Jest test and wonder if I've hit upon a limitation of JSDom.

P.S. Your book, _Testing Vue.js Applications_ has been very helpful getting me up to speed. (Hopefully, I didn't read so fast that retention suffered and caused me to ask a question you already answered in your book.)

**Comment by Bogdan808** [comment]
> > Yes slightly_smiling_face
> > ```js
> > const value = wrapper.find('input').element.value
> > ```
> > 
> > 
> > `find` traverses DOM nodes and Vue instances. All Wrappers returned by `find` contain an `element` and a `vnode` property. Only Vue instance Wrappers contain a `vm` object.
> 
> @eddyerburgh Has this stopped working along the way? I'm having no luck reading my `input`'s `value` in a Jest test and wonder if I've hit upon a limitation of JSDom.
> 
> P.S. Your book, _Testing Vue.js Applications_ has been very helpful getting me up to speed. (Hopefully, I didn't read so fast that retention suffered and caused me to ask a question you already answered in your book.)

I have the same problem

**Comment by ivangermanov** [comment]
> > > Yes slightly_smiling_face
> > > ```js
> > > const value = wrapper.find('input').element.value
> > > ```
> > > 
> > > 
> > > `find` traverses DOM nodes and Vue instances. All Wrappers returned by `find` contain an `element` and a `vnode` property. Only Vue instance Wrappers contain a `vm` object.
> > 
> > 
> > @eddyerburgh Has this stopped working along the way? I'm having no luck reading my `input`'s `value` in a Jest test and wonder if I've hit upon a limitation of JSDom.
> > P.S. Your book, _Testing Vue.js Applications_ has been very helpful getting me up to speed. (Hopefully, I didn't read so fast that retention suffered and caused me to ask a question you already answered in your book.)
> 
> I have the same problem

Same problem here.

**Comment by afontcu** [comment]
Hi! Can you share a basic example of the scenario where you cannot access input's `value`?

**Comment by ivangermanov** [comment]
> Hi! Can you share a basic example of the scenario where you cannot access input's `value`?

Nevermind, it does return it. The problem was with my component. Maybe we should delete the messages?

**Comment by didagu** [comment]
```const value = wrapper.find('input').element.value```

This does not work in vue test utils 2 (with vue 3 support). is there any new way to do this ? @eddyerburgh @LinusBorg

**Comment by soumyadeep589** [comment]
> > > Yes slightly_smiling_face
> > > ```js
> > > const value = wrapper.find('input').element.value
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > `find` traverses DOM nodes and Vue instances. All Wrappers returned by `find` contain an `element` and a `vnode` property. Only Vue instance Wrappers contain a `vm` object.
> > 
> > 
> > @eddyerburgh Has this stopped working along the way? I'm having no luck reading my `input`'s `value` in a Jest test and wonder if I've hit upon a limitation of JSDom.
> > P.S. Your book, _Testing Vue.js Applications_ has been very helpful getting me up to speed. (Hopefully, I didn't read so fast that retention suffered and caused me to ask a question you already answered in your book.)
> 
> I have the same problem

I am also having the same problem, can anyone tell me the solution around it?

**Comment by soumyadeep589** [comment]
> To add to @eddyerburgh's comment, if using TypeScript you will need to cast the returned element as HTMLInputElement if getting type or compiler errors. This is because .element returns a generic HTMLElement object. So this code would be like the following:
> 
> ```ts
> const inputField: HTMLInputElement = wrapper.find('input').element as HTMLInputElement
> const value = inputField.value
> ```

Thanks for the solution, it is working.
