### ISSUE TITLE
Conditional child component set to false should not be included in stub

### ISSUE THREAD

**Issue by trollepierre** [vuejs/vue-test-utils#792]
### Version
1.0.0-beta.20

### Reproduction link
[https://codesandbox.io/s/oxv4nlwwky](https://codesandbox.io/s/oxv4nlwwky)

### Steps to reproduce
The snapshot generates by ```<child-component v-if="false"></child-component>```is  ```<!---->```

### What is expected?
Nothing in the template

### What is actually happening?
```<!---->```

**Comment by eddyerburgh** [comment]
That's what Vue outputs by default. We're not going to change anything in this repo, but I've created a feature request in jest-vue-serializer which formats Vue snapshot output.
