### ISSUE TITLE
<router-view/> gives <vuecomponent-stub /> instead of <routerview-stub /> in snapshot

### ISSUE THREAD

**Issue by trollepierre** [vuejs/vue-test-utils#794]
### Version
1.0.0-beta.20

### Reproduction link
[https://codesandbox.io/s/j3688pr1y](https://codesandbox.io/s/j3688pr1y)

### Steps to reproduce
The snapshot generates by : 
```<router-view/> ```is  ```<vuecomponent-stub />```
```<router-link/> ```is  ```<vuecomponent-stub />```

### What is expected?
```
<routerview-stub />
<routerlink-stub />
```
### What is actually happening?
```
<vuecomponent-stub />
```

**Comment by eddyerburgh** [comment]
Thanks for the bug report.

This has actually been fixed already and will be included in the next release.

**Comment by JiriChara** [comment]
@eddyerburgh is this going to be released anytime soon?

**Comment by eddyerburgh** [comment]
The end of this weekend

**Comment by JiriChara** [comment]
Awesome, works like a charm @eddyerburgh!
