### ISSUE TITLE
data() unreachable for components using Vuelidate

### ISSUE THREAD

**Issue by SzNagyMisu** [vuejs/vue-test-utils#795]
### Version
1.0.0-beta.18

### Reproduction link
[https://codesandbox.io/s/5lrvnoynx](https://codesandbox.io/s/5lrvnoynx)

### Steps to reproduce
When upgrading from `1.0.0-beta.17` (up to `1.0.0-beta.20` I tried), all my components that use `vuelidate` are unable to reach `data()`. If I try and test if the initial values are correctly set, I get an error message.

### What is expected?
the properties of `vm.$options.data()` should be available for testing

### What is actually happening?
`data()` cannot be reached

**Comment by LinusBorg** [comment]
I'm trying to understand your reproduction, but I can't follow. The two tests that it contains seems to be meant to pass if said error is thrown, but they fail for some other error. Not good for a reproduction.

But I tried to investigate nonetheless.

* Vuelidate adds a mixin that relies on `this` in the data function to be a component instance.
* calling the data function  on its own directly does not do that.
* calling it like this works: `vm.$options.data.call(vm)` or `data.call(vm)`

This is not related to  vue-test-utils in any way. If you do the following in main.js you get the same error:

```javascript
const main = new Vue({
  el: "#app",
  components: { App },
  template: '<App ref="app"/>'
});

console.log(main.$refs.app.$options.data())
```

![grafik](https://user-images.githubusercontent.com/1444526/42269334-2b7093ac-7f7e-11e8-84a9-b5166a32f98d.png)

...while the following works:

```javascript
const main = new Vue({
  el: "#app",
  components: { App },
  template: '<App ref="app"/>'
});

console.log(main.$refs.app.$options.data.call(main.$refs.app))
```

![grafik](https://user-images.githubusercontent.com/1444526/42269375-466ab50c-7f7e-11e8-89ca-65e7334c0d82.png)

**Comment by SzNagyMisu** [comment]
Thank you for having had a look on this issue.
Yes, I was pretty sure, it had to do mostly with `vuelidate`, the only thing intriguing me was that it does work if I use `@vue/test-utils` 1.0.0-beta.17 or below. Any idea what could have changed in `test-utils`, explaining this?

(BTW, I modified the [reproduction](https://codesandbox.io/s/rj0kklm67p) to expect the test to work)

Thanks!
