### ISSUE TITLE
data should be function

### ISSUE THREAD

**Issue by trollepierre** [vuejs/vue-test-utils#797]
### Version
1.0.0-beta.20

### Reproduction link
[https://github.com/vuejs/vue-test-utils/blob/1ee03ac2d57eccd913027ecd51ac5777eeac5c84/test/specs/mounting-options/localVue.spec.js#L20](https://github.com/vuejs/vue-test-utils/blob/1ee03ac2d57eccd913027ecd51ac5777eeac5c84/test/specs/mounting-options/localVue.spec.js#L20)

### Steps to reproduce
Open this:
https://github.com/vuejs/vue-test-utils/blob/1ee03ac2d57eccd913027ecd51ac5777eeac5c84/test/specs/mounting-options/localVue.spec.js#L20
```
 data: { test: '' } 
```
should be written as
```
data: () => ({ test: '' })
```

### What is expected?
data: () => ({ test: '' })

### What is actually happening?
 data: { test: '' } 

---
https://vuejs.org/v2/guide/components.html#data-Must-Be-a-Function

**Comment by eddyerburgh** [comment]
Would you like to open a PR to make the change?

**Comment by Mardoxx** [comment]
Does it have to be a function?

https://vuejs.org/v2/examples/

```js
new Vue({
  el: '#editor',
  data: {
    input: '# hello'
  },
  computed: {
    compiledMarkdown: function () {
      return marked(this.input, { sanitize: true })
    }
  },
  methods: {
    update: _.debounce(function (e) {
      this.input = e.target.value
    }, 300)
  }
})
```


E: Ahh I see this is a simple example which isn't a reusable component... makes sense. 😄

**Comment by eddyerburgh** [comment]
It doesn't have to be, no. ~~The test works correctly, although it will log a
warning in the latest vue version~~

I was wrong about this. The test fails when data is a function
