### ISSUE TITLE
how to work under typescript? 

### ISSUE THREAD

**Issue by printjs** [vuejs/vue-test-utils#802]
### What problem does this feature solve?
When using the vue-class-component plugin, jest do not recognize .html files and CSS files if processed?

![image](https://user-images.githubusercontent.com/17404628/42268020-139ee574-7fad-11e8-8fbf-06846aa3a79b.png)

### What does the proposed API look like?
a guide

**Comment by printjs** [comment]
@eddyerburgh @38elements

**Comment by LinusBorg** [comment]
You probably need a jest loader that knows what to do with .html files:

https://www.npmjs.com/package/html-loader-jest

I don't see how this is related to vue-test-utils.

**Comment by printjs** [comment]
@LinusBorg Can you recommend a plug-in for parsing stylus files？

**Comment by printjs** [comment]
@LinusBorg Because vue-jest can handle style and HTML. When I used vue-class-component, I split the.Vue file. So, is there any library recommended by the government to handle stylus?
