### ISSUE TITLE
@vue/server-test-utils missing vue-server-renderer dependency in package.json

### ISSUE THREAD

**Issue by karol-f** [vuejs/vue-test-utils#803]
### Version
1.0.0-beta.20

### Reproduction link
[https://github.com/vuejs/vue-test-utils/blob/dev/packages/server-test-utils/package.json](https://github.com/vuejs/vue-test-utils/blob/dev/packages/server-test-utils/package.json)

### Steps to reproduce
Installing @vue/server-test-utils and trying to use official example https://vue-test-utils.vuejs.org/api/#rendertostring causes error in renderToString method due to missing dependency 'vue-server-renderer' 

### What is expected?
Official docs example with `renderToString` (https://vue-test-utils.vuejs.org/api/#rendertostring) should work without installing additional dependencies

### What is actually happening?
When using renderToString error happens due to lack of vue-server-renderer npm dependency

**Comment by 38elements** [comment]
`vue-server-renderer`  is `peerDependencies`.


https://github.com/vuejs/vue-test-utils/blob/96f1e39478be06fbe6cee58eaacabfdccd0da966/packages/server-test-utils/package.json#L39-L44
