### ISSUE TITLE
docs: Broken links

### ISSUE THREAD

**Issue by moraveyo** [vuejs/vue-test-utils#805]
### Version
1.0.0-beta.20

### Reproduction link
[https://vue-test-utils.vuejs.org/guides/#testing-single-file-components](https://vue-test-utils.vuejs.org/guides/#testing-single-file-components)

### Steps to reproduce
Open https://vue-test-utils.vuejs.org/guides/#testing-single-file-components

Try to open  in new tab this links:
- Testing SFCs with Jest
- Testing SFCs with Mocha   webpack

### What is expected?
Open docs section in new tab

### What is actually happening?
404 error

**Comment by moraveyo** [comment]
These links open not really as I expect In the same window too. In fact, these are the sections of the same document: look at the navigation, and after all you can simply scroll down to them.

But when you click at the link - it opens as separate document.
A little confusing.

**Comment by moraveyo** [comment]
Some research.

When you just click the link, it opens with url:https://vue-test-utils.vuejs.org/guides/testing-SFCs-with-jest.html (see the upper case!) - the Vue works it out fine.

When you open it in new tab/window - the page first blinks like something is there, and then it's 404. And the url is all lowercase.

So maybe it's some deeper problem in Vue itself, I'm not so deep in it.

**Comment by eddyerburgh** [comment]
The links in the side nav and the article both work fine for me. Which link is it that you have this problem with? The links in the side nav, or the links in article?

**Comment by moraveyo** [comment]
In the article.

**Comment by moraveyo** [comment]
Some more research.

Right click the link, "Open in new window" = blink, 404.
Shift-click the link = Opens normally in new window.
AFTER THAT again Right click the link, "Open in new window" = Opens normally!
AFTER THAT Right click the link, "Open in new Private window" = blink, 404. And sometimes normally!

Firefox Linux, Chromium Linux, Chrome WinXP-32

**Comment by moraveyo** [comment]
[A screencast, Chromium](http://www.screencast.com/t/Og7ZQIim)

**Comment by folmert** [comment]
I have same problem on Windows 10 and Chrome Canary. Sometimes it works on incognito mode, though. Maybe it's a conflict with some browser extension?
