### ISSUE TITLE
Vuex example correction

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/vue-test-utils#81]
Hi,

I used avoriaz previously, now trying this. I notice in this page https://vue-test-utils.vuejs.org/en/guides/using-with-vuex.html

The example says:
```
it('calls store action actionClick when button is clicked', () => {
    const wrapper = mount(Actions, { store })
    wrapper.find('button')[0].trigger('click')
    expect(actions.actionClick.calledOnce).toBe(true)
  })
```

I didn't run this example sample, but one very similar - my component also only has one button, and two `<input>`. I had to go  `wrapper.find('button').trigger('click')`, without the `[0]` index. 

Maybe this is just a slight error -  I think avoriaz would use the `[0]` regardless, but vue-test-utils does it a little different?

**Comment by eddyerburgh** [comment]
Yes, this is an error. The page was copied over from avoriaz, and we forgot to update the code. 

Would you be able to make a PR fixing this issues?

**Comment by lmiller1990** [comment]
Ok! @eddyerburgh See above.

I will be using this lib a fair bit coming up so hoping to contribute a lot, in both docs and codebase where needed.

**Comment by eddyerburgh** [comment]
Thanks a lot @lmiller1990 🙂
