### ISSUE TITLE
Mixin properties not recognised as properties with shallowMount

### ISSUE THREAD

**Issue by miriamgreis** [vuejs/vue-test-utils#814]
### Version
1.0.0-beta.20

### Reproduction link
[https://github.com/miriamgreis/vue-test-utils-getting-started](https://github.com/miriamgreis/vue-test-utils-getting-started)

### Steps to reproduce
Run the tests using `npm test`.

### What is expected?
The `subcomponent` component contains the property `subcomponentProperty` and the mixin `exampleMixin` with the property `mixinProperty`. In our tests, we want to check whether the property `mixinProperty` is correctly passed to the subcomponent. When we shallowMount the component containing the subcomponent, it is expected that the subcomponent has the property `mixinProperty`.

### What is actually happening?
The `subcomponent` component does not have the property `mixinProperty` instead `mixinProperty` is an attribute.

**Comment by eddyerburgh** [comment]
This is a gotcha with testing at the moment. A child component must declare a prop in order for it to receive that prop.

Child components are stubbed when they are shallowMounted, so mixins registered locally to the components are not applied. The mixin isn't registered on the component, so the component doesn't declare a mixinProperty prop.

In the second example, the mixin is registered globally on localVue, so SubComponent does receive mixinProperty as a prop.

This isn't a bug, it's just a gotcha.

**Comment by miriamgreis** [comment]
Thanks for you answer. Could this be a feature request then instead? Or is there no intention on ever changing this? It makes it very complicated to test that properties of mixins are correctly passed to the subcomponent, especially if the property is a function.

**Comment by eddyerburgh** [comment]
Yes you could make a feature request. I think it would require a change in core, although I'm not sure. To be clear: the feature request is that stubbed components can receive any props even if the child component does not receive them?

**Comment by miriamgreis** [comment]
I actually wouldn't see it that globally. For me, the feature request would be that stubbed components can receive props of locally registered mixins. So not arbitrary props, but just the props the component would have if the mixin would be registered.

**Comment by eddyerburgh** [comment]
I don't think we should add that, since that would mean stubbed components would still use mixins—which means they aren't really stubbed.

**Comment by miriamgreis** [comment]
It's definitely an interesting case. Because our understanding is that a mixin is part of the component. It's not about rendering them, just having the properties in the stub as you have them for the component itself. But I can see that this leads to other problems with complex nesting of components.

I will make a feature request then for stubbed components being able to receive any props as this would solve our problems.

**Comment by eddyerburgh** [comment]
You're right, mixins can add options. But they also can add hooks, which should definitely be stubbed, for that reason I don't think they should be included in stubs
