### ISSUE TITLE
Unit testing nested components - Child's `emitted` is undefined

### ISSUE THREAD

**Issue by bugsduggan** [vuejs/vue-test-utils#819]
### Version
1.0.0-beta.20

### Reproduction link
[https://github.com/bugsduggan/vue-test-utils-bug](https://github.com/bugsduggan/vue-test-utils-bug)

### Steps to reproduce
Clone the repo and run `npm run test:unit`. There will be one failing test indicating that the `ChildComponent`'s emitted is undefined.

### What is expected?
Having used `mount` instead of `shallowMount`, I was hoping to be able to see events that have been emitted by the `ChildComponent`.

### What is actually happening?
`ChildComponent`'s `emitted` function returns undefined.

---
I appreciate that this could be seen as testing the implementation of vue but I have 2 components that are very tightly coupled in my application and it is important for us to be able to check what events are being triggered by the child component while unit testing the parent.

If someone can help me narrow down the causes of this bug (and if it's not impossible or undesirable to fix), I would be happy to devote some hours into a pull request.

**Comment by lmiller1990** [comment]
The event does seem to be triggered - however it is not added to the array returned by `emitted`. I think this is a bug. 

A long time ago, before `vue-test-utils`, I had  a similar situation. I ended up doing something like

```ts
let eventName: string = ''
let payload: Array = []

function createEventRecorder() {
  return (event: string, ...args: any[]): Vue =>
   {
     eventName = event
     payload = args
     return new Vue();
   };
}
```

```js
expect(eventName)...
expect(payload)...
```

And mocking out the `$emit` entirely. But now we have `vue-test-utils`, this should be nice and clean.

@eddyerburgh does this seem like a bug? If so, I can help isolate it with you. I made a PR against the `emitted` function a while ago, so I'm a bit familiar with how it works.

**Comment by eddyerburgh** [comment]
Yes this is a bug. 

I believe the bug is because the child component is extended from Vue before the event logging mixin is added. @lmiller1990 it would be great if you could pick this up.

**Comment by lmiller1990** [comment]
Ok thanks. Excited to work on this over the weekend. I need this in my app, too.

**Comment by lmiller1990** [comment]
Ok, I investigated this. It works fine for the non typescript case. I think the bug must be related to TypeScript, somehow. Should we add some test cases using TypeScript to be able to test this? 

`emitted` has the correct properties in the case of normal `.vue` files, and also `.vue` files using `vue-property-decorator`. Introducing TypeScript seems to cause this bug.

Here is a PR to the repro with the reproduction of the bug, with a passing test using `vue-property-decorator` syntax: https://github.com/bugsduggan/vue-test-utils-bug/pull/1

I'll keep investigating (and learning about TypeScript).

**Comment by lmiller1990** [comment]
Edit: if the child is declared using the `@Component` syntax, the test will fail. Hmm.

**Comment by lmiller1990** [comment]
I thought it was related to the mixin timing too... but maybe not. I created a test using the `@Component` syntax and `extends Vue`. See it [in this diff](https://github.com/vuejs/vue-test-utils/compare/dev...lmiller1990:dev). It's passing, oddly enough.

It fails in the reproduction repo, though, as [you can see here](https://github.com/bugsduggan/vue-test-utils-bug/pull/1). So far only using `mount`, I don't think you can emit an event from a stubbed out component (or doesn't make that much sense to be able to).

Will keep investigating.

**Comment by eddyerburgh** [comment]
The issue is that the sub component created with Vue.extend doesn't have the logEvents mixin applied. I'll fix this

**Comment by lmiller1990** [comment]
Ok, great. I'll review the PR, I would like to see how you fix this.
