### ISSUE TITLE
Add nuxt link stub component/Add more support for nuxt project

### ISSUE THREAD

**Issue by jefrydco** [vuejs/vue-test-utils#823]
### What problem does this feature solve?
Currently, creating a test for nuxt project is painful because there is still limited official documentation out there about how we test nuxt project and also I think this library is lack of support to nuxt.

### What does the proposed API look like?
Add more support to nuxt project and add more documentation about creating a test for it.

**Comment by eddyerburgh** [comment]
I don't think we should add a NuxtLink component or testing docs, since it's a third party library. 

Currently we only export stubs for vuejs projects, like Vue Router, and we only have guides for vuejs projects. I think we should keep it this way.
