### ISSUE TITLE
Can't use components defined with Vue.extend as slot content when mounting

### ISSUE THREAD

**Issue by nekosaur** [vuejs/vue-test-utils#824]
### Version
1.0.0-beta.20

### Reproduction link
[https://github.com/nekosaur/vue-test-utils-repro](https://github.com/nekosaur/vue-test-utils-repro)

### Steps to reproduce
Run `yarn test`

### What is expected?
Test should pass

### What is actually happening?
Test does not pass

```
yarn run v1.6.0
$ jest
 FAIL  test/Foo.spec.js
  Foo.vue
    ✕ it should render slot content (6ms)

  ● Foo.vue › it should render slot content

    [vue-test-utils]: slots[key] must be a Component, string or an array of Components

      at throwError (node_modules/@vue/test-utils/dist/vue-test-utils.js:11:9)
          at Array.forEach (<anonymous>)
      at Object.<anonymous> (test/Foo.spec.js:7:40)
          at new Promise (<anonymous>)
          at <anonymous>

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        4.221s
Ran all test suites.
error Command failed with exit code 1.
```

---
Looks like `isValidSlot` assumes a simple component object definition, not a Vue.extend instance

**Comment by eddyerburgh** [comment]
Thanks for the bug report.

Closed by https://github.com/vuejs/vue-test-utils/pull/825

**Comment by nekosaur** [comment]
#825 was for stubs, not slots. opened a new PR.
