### ISSUE TITLE
Allow default stubs to render slot content 

### ISSUE THREAD

**Issue by muzafarova** [vuejs/vue-test-utils#836]
### What problem does this feature solve?
Please check this example: https://codesandbox.io/s/6zmj357qrn

In my app a have pages designed with various layouts, each layout is a component composed of other tiny components (logo, profile, navigation etc.). A page itself is a component matching a route (e.g. /jobs > Jobs);  

So I decided to go with slots:  
I have a set of "layout" components describing visual wrappers. And a set of "page" components that describe app's routes. 

When I test "page" component's logic, I should not care of "layout" (should be tested separately, right?) So I'd really like to use `shallowMount` everywhere and don't stub all the children. The problem is that `shallowMount` doesn't seem to allow that, while `mount` does.

Is there any way to use this technique and still be able to go with `shallowMount` over `mount`?

### What does the proposed API look like?
Not sure

**Comment by eddyerburgh** [comment]
This is actualy already implemented by https://github.com/vuejs/vue-test-utils/pull/782!

This will be released in beta.21 which will be published within a week.
