### ISSUE TITLE
No public repository for documentation

### ISSUE THREAD

**Issue by ghost** [vuejs/vue-test-utils#849]
### What problem does this feature solve?
Please make the code repository for the documentation available, so that other users can make pull requests. If it is already the case, add a link to this repo in both the documentation, and the github repository for vue-test-utils

### What does the proposed API look like?
https://vuejs.org/v2/api/ => http://prntscr.com/k9rl8v

**Comment by LinusBorg** [comment]
The docs are right here: https://github.com/vuejs/vue-test-utils/tree/dev/docs

But I guess a link to that folder from the docs page would be helpful, yep.

**Comment by 38elements** [comment]
IMHO,
I think this is not necessary since there is no problem currently.
