### ISSUE TITLE
Render slotted content with shallow

### ISSUE THREAD

**Issue by rhythnic** [vuejs/vue-test-utils#85]
In my tests I'm not using shallow rendering on any page-level components because none of the slotted content is included in the snapshot; however, when using mount, it's necessary to mock the store for the whole component tree.  As a workaround I've been mocking many components as just a template that renders slots, and then I use jest.mock to use the mocks instead of the actual child components.

It seems beneficial to have the option for the child components of the component being tested to be shallow, in that they are stubbed, but also render the content passed to them in slots.

**Comment by eddyerburgh** [comment]
You can pass custom components as stubs using the [`stubs` option](https://vue-test-utils.vuejs.org/en/api/options.html#stubs):

```
const wrapper = mount(Component, {
  stubs: {
    componentWithSlots: {
      render: h => h('div', this.$slots.default)
    }
  }
})
```

I'd like to hear others opinions about rendering slots and children in stubbed components

**Comment by rhythnic** [comment]
Ok great!  That wasn't working for me yesterday, but I must have been using it wrong.  It's working now.  I did need to modify your example to avoid using an arrow function so that 'this' refers to the vue instance.  I made a utility to make it easier.  I'm happy with this solution, but I think it would be useful for shallow rendering to include slotted content.

```
// stub util
export function stub ({ slots = [] } = {}) {
  return {
    render: function (h) {
      return h('div', slots.map(x => this.$slots[x]))
    }
  }
}
```

**Comment by gaastonsr** [comment]
Agreed here! I think shallow rendering should render the slotted content. And keep the "external" components as tags. For example

```html
<div>
  <p>I'm a component being tested</p>

  <external-component>
    <p>External component wasn't rendered, but the slotted content (me) was rendered!</p>
    <p>This is so good 😎</p>
  </external-component>
</div>
```

**Comment by eddyerburgh** [comment]
I'm closing this. There doesn't appear to be a big demand for this feature, and it's possible to achieve the behavior by passing custom stubs: 

```js
const ExtenalComponentStub = {
  render: function(h) {
      return h('div', slots.map(x => this.$slots[x]))
  }
}

shallow(TestComponent, {
  stubs: {
    'external-component': ExternalComponentStub
  }
})
```

**Comment by marinona** [comment]
`config.renderStubDefaultSlot` can be configured so that the default slot content renders (even when using shallow).
Complete documentation: https://test-utils.vuejs.org/guide/advanced/stubs-shallow-mount.html#default-slots-and-shallow
