### ISSUE TITLE
Slot testing fails for component.

### ISSUE THREAD

**Issue by trashpanda001** [vuejs/vue-test-utils#851]
### Version
1.0.0-beta.21

### Reproduction link
[https://github.com/sickp/vue-test-slots](https://github.com/sickp/vue-test-slots)

### Steps to reproduce
yarn install
yarn test:unit

### What is expected?
- named slot "header" to receive 'Hello There'
- default slot to receive 'Content Goes Here'

### What is actually happening?
default slot receives 'Hello There'

---
This worked in 1.0.0-beta.20

**Comment by bost-h** [comment]
It does not seem related to functional components to me, it also fails when the component is not functional.
It think it comes from `createSlotVNodes` https://github.com/vuejs/vue-test-utils/blob/dev/packages/create-instance/create-slot-vnodes.js#L41 which receive good values, but returns an array with duplicated VNodes. It looks like a reference/value issue, where VNodes having already been created are overwritten by the creation of a new VNode
