### ISSUE TITLE
Wrapper emit events are not detected in beta 22

### ISSUE THREAD

**Issue by C-Higgins** [vuejs/vue-test-utils#880]
### Version
1.0.0-beta.22

### Steps to reproduce
- Mount anything in wrapper
- Emit an event inside of the wrapped component
- Notice that wrapper.emitted() returns undefined

### What is expected?
Events are detected as emitted

### What is actually happening?
No event is ever detected

---
I have hundreds of tests that all pass in beta 21, while in beta 22 anything involving emitting an event fails.

**Comment by eddyerburgh** [comment]
This should be fixed in beta.23
