### ISSUE TITLE
Render props with original key names, not camel case

### ISSUE THREAD

**Issue by trollepierre** [vuejs/vue-test-utils#886]
### Version
1.0.0-beta.22

### Reproduction link
[https://codesandbox.io/s/23k4r45q0y](https://codesandbox.io/s/23k4r45q0y)

### Steps to reproduce
When I set some props to my child component that are written in kebab-case, I can see them written in onewordcase in the generated snapshot
```
<template>
  <child-component :my-prop="true"/>
</template>
```

### What is expected?
```
<child-component :my-prop="true"/> 
```

### What is actually happening?
```
<child-component :myprop="true"/>
```

**Comment by eddyerburgh** [comment]
Internally props are normalized to camel case. When the component renders, we don't have access to the original prop key on the component.

I think this will be difficult to workaround.

**Comment by eddyerburgh** [comment]
I'm going to close this as something we won't implement, since we don't have access to the original prop key
