### ISSUE TITLE
Doesn't properly handle props of functional components

### ISSUE THREAD

**Issue by riophae** [vuejs/vue-test-utils#903]
### Version
1.0.0-beta.24

### Reproduction link
[https://github.com/riophae/vue-test-utils-bug](https://github.com/riophae/vue-test-utils-bug)

### Steps to reproduce
Clone the repo, install dependencies, and run `npm test`.

### What is expected?
vue-test-utils should generate the same markup as what vue does, i.e., all tests should pass.

### What is actually happening?
vue-test-utils generates different markup than vue.

```
Test
props: { a: undefined }
    1) vue-test-utils
props: { a: 'aaaa' }
    ✓ vue


  1 passing (275ms)
  1 failing

  1) Test
       vue-test-utils:

      AssertionError: expected '<div a="aaaa"></div>' to equal '<div>aaaa</div>'
      + expected - actual

      -<div a="aaaa"></div>
      +<div>aaaa</div>

      at Context.it (dist/webpack:/tests/unit/Test.spec.js:24:1)
```

**Comment by eddyerburgh** [comment]
You need to pass props in a [`context`](https://vue-test-utils.vuejs.org/api/options.html#context) object when you mount functional components:

```js
const wrapper = mount(TestComponent, {
  context: {
    props: {
      'a': 'aaaa'
    }
  },
})
```

**Comment by eddyerburgh** [comment]
Note there's a feature request to support `propsData` in functional components #918
