### ISSUE TITLE
Timeout when running bunch of tests on Docker

### ISSUE THREAD

**Issue by trollepierre** [vuejs/vue-test-utils#908]
### Version
1.0.0-beta.24

### Reproduction link
[https://en.wiktionary.org/wiki/nope](https://en.wiktionary.org/wiki/nope)

### Steps to reproduce
On an image Docker node:8.11.3, my 1000 tests (using Jest) lasts for hour (until timeout) whereas they last 2 minutes in local.
=> It appears time is multiplied by 4 (or even more)

### What is expected?
fix that issue

### What is actually happening?
timeout

**Comment by LinusBorg** [comment]
That doesn't really give us anything to work with. We can't analyze your report without a chance to reproduce what you are doing.

**Comment by trollepierre** [comment]
That issue is just a consequence of https://github.com/vuejs/vue-test-utils/issues/892

**Comment by trollepierre** [comment]
Other solutions is here: https://jestjs.io/docs/en/troubleshooting#tests-are-extremely-slow-on-docker-and-or-continuous-integration-ci-server
