### ISSUE TITLE
wrapper.classes() only shows 1 class in array

### ISSUE THREAD

**Issue by thehendrix** [vuejs/vue-test-utils#914]
### Version
1.0.0-beta.24

### Reproduction link
[https://jsfiddle.net/50wL7mdz/593094/](https://jsfiddle.net/50wL7mdz/593094/)

### Steps to reproduce
Make a test in Jest using vue-utils to get all the classes in the template of the Vue.js SFC.
Just test a simple console.log on wrapper.classes().

### What is expected?
Should return an array containing 7 classes.

### What is actually happening?
 Only returns an array with 1 class 'procedure-card'

**Comment by eddyerburgh** [comment]
`classes` only returns the classes of the wrapper root element.
