### ISSUE TITLE
renderToString cannot work properly

### ISSUE THREAD

**Issue by kazupon** [vuejs/vue-test-utils#916]
### Version
1.0.0-beta.24

### Reproduction link
[https://github.com/kazupon/vue-i18n-extensions/tree/moving](https://github.com/kazupon/vue-i18n-extensions/tree/moving)

### Steps to reproduce
- `git clone git@github.com:kazupon/vue-i18n-extensions.git`
- `cd vue-i18n-extensions`
- `git branch moving origin/moving`
- `git checkout moving`
- `yarn`
- `yarn test:unit`

### What is expected?
pass the test in `src/__tests__/repro.test.js`

### What is actually happening?
cannot pass the test in `src/__tests__/repro.test.js`:

```
 FAIL  src/__tests__/repro.test.js
  ● cannot work correctly

    expect(string).not.toContain(value)

    Expected string:
      ""
    Not to contain value:
      ""

      18 |     }
      19 |   })
    > 20 |   expect(str).not.toContain('')
         |                   ^
      21 | })
      22 |

      at Object.<anonymous>.it (src/__tests__/repro.test.js:20:19)
```

---
I notice `renderToString`  have the critical issue.
See the bellow:
https://github.com/vuejs/vue-test-utils/blob/dev/packages/server-test-utils/src/renderToString.js#L40-L46

`renderedString` cannot return the correctly string, depending on the implementation of the component.

Vue SSR docs have been saying `renderToString`(vue-server-renderer) return the Promise.
https://ssr.vuejs.org/api/#renderer-rendertostring

I think `renderToStrnig` API should be re-designed.

I propose the below the API.

- `renderToString`: return the Promise
- `renderToString`: provide the callback argument

**Comment by eddyerburgh** [comment]
Yes, we should fix this.

What do you think about handling it through the `sync` option?

```js
const str = renderToString(TestComponent)

const str = await renderToString(TestComponent, {
  sync: false
})
```

**Comment by kazupon** [comment]
sound good to me. 👍

**Comment by eddyerburgh** [comment]
Do you have an example component that won't won't render correctly?

**Comment by kazupon** [comment]
Sorry for my late reply.
That's is here
https://github.com/kazupon/vue-i18n-extensions/commit/cc85456c74663d3af8ae9299b304b372d4c17424#diff-0a45b66d57da4b0f77d1825941f54e4b

**Comment by jerryni** [comment]
Same error when the component content is too large to execute.
