### ISSUE TITLE
Use docsearch for the search

### ISSUE THREAD

**Issue by Haroenv** [vuejs/vue-test-utils#920]
### What problem does this feature solve?
Able to find everything in the docs, with typo tolerance and especially also search in the content. 

### What does the proposed API look like?
apply on https://community.algolia.com/docsearch and change over in VuePress to use that one

**Comment by Haroenv** [comment]
@eddyerburgh if you need my help for that, I'd be able to :)

**Comment by eddyerburgh** [comment]
Yes, that would be great. I began to apply on the link you posted, but I'm not the owner of the domain so I didn't go any further

**Comment by Haroenv** [comment]
Who’s the owner of the domain? Is it Evan?

**Comment by eddyerburgh** [comment]
Yep

**Comment by Haroenv** [comment]
I think since other Vue projects use docsearch, it's fine if you apply as part of the core team :)

**Comment by eddyerburgh** [comment]
I've applied, and added my API key to the VuePress docs, but the site isn't using algolia search. Do I need to add something else to enable algolia?
