### ISSUE TITLE
Wrong Typescript signature for Wrapper.emitted(str)

### ISSUE THREAD

**Issue by krissrex** [vuejs/vue-test-utils#924]
https://github.com/vuejs/vue-test-utils/blob/dev/packages/test-utils/types/index.d.ts#L107

### Version
1.0.0-beta.24

### Steps to reproduce
```ts
const wrapper = shallowMount(MyVueComponent);
wrapper.trigger('click'); // any event

const myEvent: string = wrapper.emitted('click')[0][0]; // Issue here!!
```

### What is expected?
`wrapper.emitted('click')[0][0];` should have signature `any`.

### What is actually happening?
It has signature `any[]`.

---
The fix would be 2 method signatures:

```ts
emitted (): { [name: string]: Array<Array<any>> }
emitted (event: string): { [name: string]: Array<any> }
```
https://jsfiddle.net/1b68eLdr/55727/

This would make typescript happy.   

*Note:* If you were to actually implement this signature using typescript, you can't (because of 2 methods with the same name, but different signatures). You could cast the right hand side to `any` though, and it will work.

**Comment by krissrex** [comment]
As a workaround until this is fixed, put this in a `vue-test-utils.d.ts`:

```ts
import { Wrapper } from '@vue/test-utils'
import Vue from 'vue';

declare module '@vue/test-utils' {
  interface Wrapper<V extends Vue> {
    emitted(): { [name: string]: Array<Array<any>> };
    emitted(event: string): Array<Array<any>>;
  }
}
```

**Comment by eddyerburgh** [comment]
Thanks for the bug report.

Would you like to make a PR implementing the fix?

**Comment by krissrex** [comment]
@eddyerburgh I made a mistake in my **actual** paragraph: the signature should still be a nested array.

https://github.com/vuejs/vue-test-utils/pull/933/commits/f51c7cce88192e48803efa322ad4f1d8199d9095#diff-b801fc35a5096ae10463a20e928fb818R108

The Jsfiddle and workaround comment have it correctly:

```
emitted(): { [name: string]: Array<Array<any>> };
emitted(event: string): Array<Array<any>>;
```
