### ISSUE TITLE
Change instance wrapper vnode relationship

### ISSUE THREAD

**Issue by eddyerburgh** [vuejs/vue-test-utils#932]
Currently we store the root vnode of an instance vnode tree in the wrapper:

```js
const TestComponent = {
  template: '<div></div>'
}
const wrapper = mount(TestComponent)
wrapper.is('div') // true
wrapper.is(TestComponent) // true
wrapper.isEmpty() // true
```

![untitled diagram 1](https://user-images.githubusercontent.com/13196123/44297306-09b74f00-a2c7-11e8-920a-42bc3a78ff1a.png)

This can result in unexpected behavior:

```js
const wrapper = mount(TestComponent)
wrapper.find('div').is('div') // true
wrapper.find('div').is(TestComponent) // false
```

I don't think this is the best way going forward. It makes the instance and the root vnode appear the same. I propose changing the wrapper vnode to be the parent vnode of the instance:

```js
const TestComponent = {
  template: '<div></div>'
}
const wrapper = mount(TestComponent)
wrapper.is('div') // false
wrapper.isEmpty() // false
```

![untitled diagram](https://user-images.githubusercontent.com/13196123/44297310-1340b700-a2c7-11e8-93ed-4f2c46cb7edf.png)

The main benefit of this would be to make the distinction between an instance and an element vnode clear.

Changing the behavior would result in lots of breaking API changes, which is why I'd like to add it before we move to 1.0.

**Comment by lmiller1990** [comment]
I think this makes more sense. I intuitively expect the `vnode` of a `vm` to refer to the "top" of the tree.

The main question is what are the main APIs this breaks? `find` and `findAll` and `is` will likely need 
significant changes (but that shouldn't change the public API?).

I can't think of which APIs would break - `vnode` is used a lot internally, but not that much by the public API?

I wonder if this would help fix https://github.com/vuejs/vue-test-utils/issues/784.

**Comment by eddyerburgh** [comment]
On reflection I believe we should keep the existing behavior. With the existing behavior, users can trigger events on a root element of an external component (if listeners are added to the root element) without knowing the implementation detail:

```js
wrapper.find(VIcon).trigger('click')
```
