### ISSUE TITLE
shallowMount render router-view component

### ISSUE THREAD

**Issue by Senasiko** [vuejs/vue-test-utils#935]
### What problem does this feature solve?
when I use `vue-router` to render the Component, like this
```
const wrapper = shallowMount({
      render: h => h('router-view'),
}, {
      localVue,
      router,
});
router.push({ name: 'app' }),
```
Now the snapshot is `<router-view-stub name="default"></router-view-stub>`,
I want to render the App component and not render the App's children components.
What should I do?
Thanks

### What does the proposed API look like?
```
shallowMount({
    render: h => h('router-view')
}, {
    renderRouterView: true
})
```

**Comment by eddyerburgh** [comment]
Does using `mount` instead of `shallowMount` solve your issue?

I don't think we should provide a way to conditionally render router-view components explicitly. We are intending to add a `depth` option to `shallowMount`, so you could choose to render a component 2 levels deep.

**Comment by Senasiko** [comment]
Thanks，that's exactly what I need
