### ISSUE TITLE
Improve Japanese document(単一ファイルコンポーネント)

### ISSUE THREAD

**Issue by 38elements** [vuejs/vue-test-utils#950]
### Version
1.0.0-beta.24

### Reproduction link
[https://vue-test-utils.vuejs.org/ja/](https://vue-test-utils.vuejs.org/ja/)

### Steps to reproduce
https://vue-test-utils.vuejs.org/ja/

### What is expected?
`Single-File Component`は`シングルファイルコンポーネント`とした方がいいと思います。

### What is actually happening?
`Single-File Component`を`単一ファイルコンポーネント`と翻訳することは適切ではないと思います。
Single-Fileは1つのファイルを意味すると思います。

**Comment by Haroenv** [comment]
Hey, I don't understand Japanese, but you should probably make a PR, so the change can be discussed there? 

You've already contributed, so you know how that goes. 

In all cases, cc @kazupon

**Comment by 38elements** [comment]
> Hey, I don't understand Japanese, but you should probably make a PR, so the change can be discussed there?

No.
Making this issue is right.
The people can discuss in this issue.

Since this issue is about expression,
It is difficult to find an explicit correct word.
I will send a pull request if there is not reasonable objection within some days.

**Comment by kazupon** [comment]
@38elements
そのまま訳すと確かにそうですね。

vuejs/jp.vuejs.org の公式ドキュメントの翻訳したときは、翻訳ガイドに従って訳しました。

最初は’シングルファイル’と訳してたのですが、’SPOF(single point of failure)’、’単一障害点’という訳からこの訳にしました。

https://github.com/vuejs-jp/012-jp.vuejs.org/commit/89a3f8cfb472473054ecd25a5d65623a083b4c30#diff-2446295dc5f5a599654d2bbbd270dc12

‘Single’の訳、’単一’の意味を確認しても私的には問題ないかなあと思っています。

- single  
https://ejje.weblio.jp/content/single

- 単一
https://dictionary.goo.ne.jp/jn/139609/meaning/m0u/

**Comment by 38elements** [comment]
@kazupon

ご意見ありがとうございます。
私は以下の3点からシングルファイルコンポーネントが適切だと思います。

* 少なくとも私の周りではシングルファイルコンポーネントと言う人が多いと思います。
シングルという単語は日本語の中で一般的に使用されていると思います。(例: CDのシングルチャート)

* 単一はmonoを連想させます。
Mono-File Componentなら単一ファイルコンポーネントが適切だと思います。

* Single-File Componentは単一ではないと思います。
Single-File ComponentはJavaScriptとCSSとHTMLなど複数の要素が合わさった複合的なものではないかと思います。

シングルのほうが分かりやすいと思います。

**Comment by ktsn** [comment]
2つの観点があります。

## Single の訳語として単一が適切なのかどうか

Single の訳語として単一は間違いではないように見えます。

https://www.ldoceonline.com/jp/dictionary/single
-> only one

https://dictionary.goo.ne.jp/jn/139609/meaning/m0u/
-> ただ一つであること。単独であること。また、そのさま。

確かに SFC 内のコンテンツは複数の要素が合わさったものですが、SFC の single はファイルが1つであることを意味していて、単一もそれにかかっているので適切だと思っています。

## シングルと表記すべきか、単一と表記すべきか

個人的にはシングルでも単一でもどちらでもいいと思いますが、単一ファイルコンポーネントで広まってるものを今からシングルファイルコンポーネントにするのは難しいと思います。SFC の訳語は vue-test-utils だけの問題じゃなくて Vue.js まわりの日本語ドキュメント全体に関わってきますし、それを基にした書籍とかも出てきているので。

単一ファイルコンポーネントという言葉にすることで原文の意味からかけ離れてしまうなど、致命的な不都合があるのであれば変えるべきだとは思いますが、上で述べたように単一という訳は適切だと考えているので、変える必要性はないと思います。

**Comment by 38elements** [comment]
@ktsn 

ご意見ありがとうございます。
単一の訳が正しいことは分かりました。
しかし、シングルのほうが単一よりも良いと思っています。

**Comment by ledsun** [comment]
単一ファイルコンポーネントは、単語をどこで区切るかの解釈が揺れやすいと思います。

単一ファイルコンポーネントは単一/ファイルコンポーネントと単一ファイル/コンポーネントの二つの区切り方ができます。個人的な経験では単一/ファイルコンポーネントと解釈することが多いです。

シングルファイルコンポーネントはシングルファイル/コンポーネントと解釈することが多いです。

**Comment by 38elements** [comment]
@ledsun 

ご意見ありがとうございます。
単語の区切りは新しい視点ですね。
参考にさせていただきます。

**Comment by kazupon** [comment]
みなさん、ご意見ありがとうございます。

ktsnさんもコメントされていましたが、

- 現状、`単一ファイルコンポーネント`という訳は、原文の意味から大きくかけ離れていない
- 日本語訳でドキュメントを公開してから、大分経っているが、特に日本の他の方から、訳した単語が原文からかけ離れていてよく分からないという声は、Twitter等のSNS、Meetupを通して聞いていない
- `単一ファイルコンポーネント`から`シングルファイルコンポーネント`に変更すると混乱する人がでてくる可能性がある

ということから、Vue.js関連の日本語ドキュメントではこのままとしたいです。

**Comment by 38elements** [comment]
SFCの正式な綴りはSingle-File Componentです。
https://github.com/vuejs/vue-loader/blob/master/docs/spec.md
個人的な意見ですが@ledsunさんの指摘が正しいと思います。
単一ファイルコンポーネントだと単一/ファイル/コンポーネントと分けると思います。

**Comment by ktsn** [comment]
単一/ファイルコンポーネントで区切るとファイルがどこにかかってくるかよくわからなくなるのですが、そういうふうに読む人が結構いるのでしょうか？個人的にはシングルでも単一でもファイルの方が修飾される意味でしか読めないのですが……。

また、シングルと単一で区切る場所が変わってくるというのもちょっと自分にはそういう感覚がないですね。

この辺の話は結局主観なので、議題にするなら https://jp.vuejs.org のメンテしてる人たち含めてどう感じるのかを確認したほうがいい気もします。

ただ、繰り返しになりますが、すでに広まってるものを、表記揺れで混乱させてしまう可能性を冒してまで変えるべきなのか？という感じはあります。

**Comment by 38elements** [comment]
私はこのレポジトリのSingle-File Componentの訳を変更したいだけでjp.vue.orgの訳も変更することは求めていません。
また、この変更の影響が重大だとは思いません。
シングルのほうが単一よりも良いと思っているので変更したいと思っているだけです。

**Comment by 38elements** [comment]
@kazupon @ktsn

合意することが難しいようなのでVue Test Utilsの日本語ドキュメントを削除して
各自が適切だと思う場所で翻訳してホストすることはいかがでしょうか。
これはVueの方針にも合致していると思います。
https://gist.github.com/yyx990803/628143350cc7ff705d1364ecc70e2cca
Vue Test Utilsのメンテナンスコストも下がります。
また、これを提案することは問題ないと思います。
https://github.com/vuejs/vue-test-utils/issues/621
お手数ですが、この提案に反対の場合はご返答いただけないでしょうか。
よろしくお願いします。

**Comment by potato4d** [comment]
私個人の意見としては、 **「シングルファイルコンポーネント」という呼称については、この議論とは別に自分の中で多少納得感がある** ものの、 **ドキュメントについては歴史もあわせて「単一ファイルコンポーネント」が適切** という判断です。

これまであげられている観点については既に十分議論されていますし、私個人としては据え置きに賛成ですが、一応判断指標として補足を書いておきます。

## `.vue` ファイルについての呼称と利用ケース

この Issue で議論されている `.vue` ファイルについての呼称ですが、現時点では「単一ファイルコンポーネント」が口語・文語両方の言葉として、「SFC」が文語調の言葉として利用されている現状があるかと思います。単純にSFCがショートハンドとして機能している現状ですね。

ここについて、「SFC」が「シングルファイルコンポーネント」の略なのに「単一ファイルコンポーネント」という呼称が正式名称となっていることによる混乱というのが懸念点であれば、ある程度の妥当性はあると思います。

## Vue.js の公式ツールとしての翻訳の統一性

@38elements さんの主張と相反する内容となってしまい恐縮ですが、 Vue およびその周辺ツールの日本語訳の基準がぶれていることについて、個人的には問題意識を抱えています。
細かなケースについての言及はここでは省きますが、全体的な傾向として jp.vuejs.org はすべての用語を翻訳するように、その他はカタカナにする傾向があります。

翻訳時期とメンバーの違いによって行っているある意味で必然的な事象ではある反面、例えば今回のような変更があった場合に困る可能性があります。初学者には、 A と B 二つののドキュメントで言及されている同じものについて、呼称が違う場合にそれが同一の概念かどうかを判断できる能力を持ち合わせていません。その状態で、無闇に呼称を増やし、表記ゆれを生み出すよりは、統一されるべきであると思います。

ドキュメントはそこから情報を学ぶ人のためにあるため、混乱を産まないことが第一だと考えています。そういった意味では、やるのであれば中途半端なことはすべきでないと考えています。

逆に言えば、はじめからいままで継続して「シングルファイルコンポーネント」であったのであれば、私は「シングルファイルコンポーネント」であることについての違和感はありません。

## 最終的な結論について

上記の理由から、前提として大きな変更となるため相応の理由が必要である。今回の変更はある程度の妥当性は見受けられるものの、それに見合うだけのものでは現状ないというのが私見です。

また、ドキュメントを分離すること自体は悪いことではないかもしれませんが、各自のレポジトリ単位では、こちらも混乱を招くだけかと思いますので、行うとしても Vue.js JP あたりの粒度でしょうか。どちらにせよあまりにも飛躍した話かと思います。

**Comment by ktsn** [comment]
@38elements 

すみません、前提の共有ができてなかったようなので説明します。

### Single File Component の訳を統一したい理由

僕が Single File Component の訳を統一したいと考えているのは、同じ概念に複数の呼び方が存在すると、混乱を招きますし、それによって読者がドキュメントを理解するコストがかかってしまうと考えているからです。

例えばですが、公式では Single File Component と呼ばれているものが、別の場所ではこっちのほうがわかりやすいからと One File Component と呼ばれていたり、またあるところでは正確にはこう呼ぶべきだということで Mono File Component と呼ばれていたら、よくわからなくなりますよね？

これは訳でも同じことが言えると思います。僕たちは元の表現とその訳を知っているので、複数の表現が存在していても同じものだと理解できるのですが、本当に初めて Vue.js を学ぶ人は異なる概念があるととらえてしまうと思います。

### 単一 → シングル に変える影響を懸念している理由

(以下の主張は訳文を変えるならすべて統一すべきだというのを前提にしています)

公式ドキュメントの表現を変えるということは、それまで公式ドキュメントのとおりに記述していた、ブログ記事、書籍、StackOverflow やフォーラムの回答がすべて最新のドキュメントとは異なる表現になってしまうことを意味します。

僕たちの手の届く範囲 (vuejs organization 配下のドキュメントなど) ならそれをすべて変えればよいですが (それもけっこう大変な作業ですが)、外部のフォーラムや、もう印刷されてしまった書籍は変えることができません。

こうなると、Single File Component の日本語表現が2つ存在することになってしまい、そこで混乱を招いてしまうかもということを懸念しています (訳を統一したい理由にも掛かってきます)。

### Vue Test Utilsの日本語ドキュメントを各自でホストする件について

申し訳ないのですが、Single File Component の訳を変えたいという理由でこれをするのには反対です。理由は上で書いたように統一すべきだと考えているからです。

### 本題

@38elements さんが単一よりもシングルのほうがわかりやすいと考えているのは理解しています。

僕もドキュメントを良くしたいと思っているので、それが本当にいいことであれば変えてもいいと思っています。これが Vue.js の日本語ドキュメントができる前であれば、上で説明したような懸念もないですし、シングルファイルコンポーネントでいいかもね、となったと思います。

しかし、今はもう公式で単一ファイルコンポーネントという表現にしてからかなりの時間が経っていますし、多くのユーザーがそれを読んでいます。

このことを考慮したときに、上で書いた懸念と、単一からシングルに変えることによるメリットを天秤にかけたとき、現状だとメリットの方には傾かないかなというのが正直なところです。

というのも、シングルの方がわかりやすいという根拠が僕の目には主観的に映ってしまい、どうにも判断できないのです (そして、僕の**主観**ではそんなに変わらないというのもあります)。なので、前のコメントで他の人にも確認してもらいたいという発言をしました。

**Comment by kazupon** [comment]
@potato4d さん、 @ktsn さん、ご意見ありがとうございました。

私の方から意見します。

> 合意することが難しいようなのでVue Test Utilsの日本語ドキュメントを削除して
> 各自が適切だと思う場所で翻訳してホストすることはいかがでしょうか。
> これはVueの方針にも合致していると思います。
> https://gist.github.com/yyx990803/628143350cc7ff705d1364ecc70e2cca
> Vue Test Utilsのメンテナンスコストも下がります。

@38elementsさんがコメントされた上記の引用部分についてですが、確かに、Vue.jsコアを除くドキュメントの翻訳においては、gistのリンク先にある通りEvan氏の決めた翻訳ポリシーに従うようになっています。
なので、#621 でもあったように、コアチームに対応できるメンバーいない、もしくアクティブなコントリビューターによって翻訳が著しく続けられていない(できなくなってきている)場合は、原則翻訳ドキュメントは受け付けない(削除する)という方針です。

ただ、合意することが難しいから、Vue Test Utilsの日本語ドキュメントを削除して問題解決というのは Single-File Componentの訳の問題からあまりにも飛躍している話かと思います。

翻訳ポリシーの方は、メンテナンス問題の話なので、別の問題です。

Single-File Componentの訳の問題についてですが、@ktsnさん、@potato4dさんも既にコメントされていますが、Vue Test Utilsだけ、`シングルファイルコンポーネント`という訳にするは、Vue.js翻訳ドキュメントの一貫性がなくなり、Vue.jsのユーザー、特に初心者の方に混乱を招くため、私も反対です。

現状、Vue Test Utilsの日本語翻訳ドキュメントは、@38elementsさんはもちろん、他の方もコントリビュートして翻訳しており、また日本語ドキュメントを読んでいる方もいます。

これまでの@ktsnさんのご意見、
Vue.js公式ドキュメントをメンテしている@potato4dさんのご意見、
このissuesの各コメントのリアクションの状況、
最後にVue.jsコアチームとして、現状存在するVue.js日本語ドキュメントをメンテしている自分の立場から、
Vue Test Utilsから日本語翻訳ドキュメントを削除せず、本題であるSingle-File Componentの訳は、これまで通り`単一ファイルコンポーネント`のままにするという帰結にしたいと思います。

**Comment by 38elements** [comment]
そうですか。
各自がホストするアイディアはいいアイディアだと思ったので残念です。

誤解が生じるかもしれないのでコメントさせていただきたいのですが
Evan氏のgistには`In the future, we are limiting officially hosted langauges to English only.`とあるので
将来的にはVue Test Utilsの日本語ドキュメントは削除されると思っていました。
#621 はある一定期間に限って条件を満たせばこのレポジトリにホストされることを意味していると思っていました。

**Comment by kazupon** [comment]
> `In the future, we are limiting officially hosted langauges to English only.`

Evan氏のgistには上記のように書いてありますが、本人はそうしたいようなんですが、具体的にまだ動いていないです。現状、先のコメントにあった

>コアチームに対応できるメンバーいない、もしくアクティブなコントリビューターによって翻訳が著しく続けられていない(できなくなってきている)場合は、原則翻訳ドキュメントは受け付けない(削除する)

の状態な感じです。

英語のみホストするように動き始めた場合は、私としては、現状ある日本語ドキュメントは、[vuejs-jp](https://github.com/vuejs-jp)にアーカイブする形でホストしておきたいと思っています。ただ、新規に書き起こされるドキュメントは、私としてはVue.js本体以外は翻訳しない方針です。実際、私のリソースも限界が来ていて、最近書き起こされたvue-loaderやvue-cliのドキュメントは翻訳しないようにしています。

私として現状ある日本語ドキュメントの追随で精一杯です。新規のものは、他の方にやって頂きたいです。

**Comment by 38elements** [comment]
互換性を重視するグループ(単一ファイルコンポーネントを支持する人々)と互換性を軽視するグループ(@38elements)があります。
Vue Test Utilsの日本語ドキュメントを削除して各グループが日本語ドキュメントを提供する必要はないと思います。
単一ファイルコンポーネントのままでいいと思います。
今後、私はVue Test Utilsの日本語ドキュメントを更新しないので
互換性を重視するグループの人がVue Test Utilsの日本語ドキュメントを更新していただきと思います。
よろしくお願いします。
