### ISSUE TITLE
`props([string])` not working properly

### ISSUE THREAD

**Issue by FrontendSophie** [vuejs/vue-test-utils#955]
### Version
1.0.0-beta.24

### Reproduction link
[https://codepen.io/FrontendSophie/pen/RYgzRO](https://codepen.io/FrontendSophie/pen/RYgzRO)

##### Description:  
According to the documentation: https://vue-test-utils.vuejs.org/api/wrapper/#props-key      
`expect(wrapper.props('bar')).toBe('baz')` is supposed to work but it didn't.     
##### code example:      
```
 it ('test props method', () => {
    const testProp = 'test'
    const wrapper = shallowMount(List, {
      propsData: { testProp }
    })
    // expect(wrapper.props('testProp')).toBe('test')  // fail
    expect(wrapper.props()['testProp']).toBe('test') // pass
  })
```

### What is expected?
`props([string])` should work as documented.

### What is actually happening?
```
FAIL test\List.spec.js
  ● List.vue › test props method

    expect(received).toBe(expected)

    Expected value to be (using ===):
      "test"
    Received:
      {"items": undefined, "testProp": "test"}

    Difference:

      Comparing two different types of values. Expected string but received object.

      at Object.<anonymous> (test/List.spec.js:29:39)
          at new Promise (<anonymous>)
      at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by eddyerburgh** [comment]
Sorry, this is an issue where the docs were updated before the feature has been published. I'll publish a new beta version in the next few days.

**Comment by FrontendSophie** [comment]
@eddyerburgh  I see
