### ISSUE TITLE
[Feature Idea] `isReactive`

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/vue-test-utils#97]
Hi,

Vue's reactivity system is great, and almost ~magic~ except for a few caveats. I think a lot of them will go away with Vue 3 introducing es6 proxies.

Anyway, for the longest time I couldn't figure out why 

``` js
const state = {
  tasks: {}
}

const mutations = {
  ADD_TASK (state, { task}) {
    state.tasks[task.id] = task
  }
}
```

wasn't making my `task[0]` object included in Vue's reactivity. My test passed, I wanted to know if `ADD_TASK` added a task, however doing this doesn't allow the new task to be included in Vue's reactivity, so the test was not really doing what I intended the mutation to do. 

You need to do:

`state.tasks = {...state.tasks, [task[id]]: task }`

So my proposal would be something like:

``` js
import { isReactive } from 'vue-test-utils'

describe('ADD_TASK', () => {
  it('adds a new task to the state that is reactive', () => {
    const state = { tasks: {} }
    ADD_TASK(state, { task: { id: 0, name: '...' } }
    expect(state).toHaveProperty(0)
    expect(isReactive(state[0]).toBe(true)
  })
})
```
Since more often than just adding something with a mutation, for example, you want to add it and have it be reactive (or in some cases, not reactive maybe?).

Although knowledge of Vue's and Vuex reactivity works around this, sometimes you might have an important feature that absolutely relies on a property being reactive, so it might be useful.

I'd be interested in implementing something like this, once/if we think of a good API and use case. ATM it's mainly for Vuex mutation tests.

**Comment by callumacrae** [comment]
I've mostly found that I've accidentally not made stuff reactive, and it has led to bugs later on elsewhere - I'm not sure how adding a test case would have helped, given that the issue was noticing that something wasn't reactive, not figuring out what wasn't reactive.

**Comment by lmiller1990** [comment]
I was thinking to have a crack at this, but it looks like there probably isn't much interest/it isn't a feature that is really worth implementing? Thoughts @eddyerburgh  ? If not, feel free to close - no point leaving an issue open with nothing being done.

**Comment by eddyerburgh** [comment]
I haven't found the need to use isReactive. But I'm happy to leave the issue open until we get some more feedback

**Comment by blocka** [comment]
personally, I think it's fine to just have your test fail, realize it's
because something wasn't reactive, fix it and move on. This sounds like way
to brittle a feature.

**Comment by lmiller1990** [comment]
I have arrived at the decision this is not a necessary feature, and this should be the responsibility of e2e tests. Going to close.
