### ISSUE TITLE
trigger('click') does not work with custom checkboxes

### ISSUE THREAD

**Issue by nemtsov** [vuejs/vue-test-utils#971]
### Version
1.0.0-beta.25

### Reproduction link
[https://codesandbox.io/s/oxw0nk954z](https://codesandbox.io/s/oxw0nk954z)

### Steps to reproduce
1. Click on the `use wrapper.trigger('click')` button. Notice that nothing happens.
2. Click on the `use element.click()` button. Notice that the second checkbox gets selected.

The first one is using `boxes.at(1).trigger("click")` and the second uses `boxes.at(1).element.click()`. If I understood the docs correctly, both should have exactly the same behavior. But, as the repro demonstrates, only the latter works.

### What is expected?
Clicking on the `use wrapper.trigger('click')` button would select the first checkbox.

### What is actually happening?
Nothing.

Additionally, `attachToDocument: true` must be set for this to work with `element.click()`.

**Comment by dietergeerts** [comment]
I see this being closed, but I experience this issue currently, on v.1.0.0-beta.28

**Comment by JessicaSachs** [comment]
Can you open a new issue with your reproduction?
