### ISSUE TITLE
text() is stripping wrapping html tags

### ISSUE THREAD

**Issue by joelworsham** [vuejs/vue-test-utils#981]
### Version
1.0.0-beta.21

### Reproduction link
[https://jsfiddle.net/joelworsham/hn8bxyd7/](https://jsfiddle.net/joelworsham/hn8bxyd7/)

### Steps to reproduce
`shallowMount()` a component that has a named slot in it, where the named slot has some html wrapper, let's say it's just `div.wrapper` and your slot contains something like `<p>Some content</p>` (note the wrapping `<p>` tags).
call `expect(wrapper.find('.wrapper').text()).toBe('<p>Some content</p>')`

### What is expected?
I expect it to receive `<p>Some content</p>` and to properly validate`

### What is actually happening?
the `<p>` tags are stripped when calling `text()` so it does not validate.

---
Sorry, I don't know how to get jsfiddle to run an actual test.

Here is the full testing code:
```
const wrapper = shallowMount(Component, {slots: {mySlot: '<p>Some content</p>'}});
it('should contain the proper slot html', () => {
  expect(wrapper.find('.wrapper').text()).toBe('<p>Some content</p>');
});
```
And imagine the component template is something like this:
```
<template>
  <div class="my-componet">
    <div class="wrapper">
      <slot name="mySlot"/>
    </div>
  </div>
</template>
```

**Comment by eddyerburgh** [comment]
`text` uses `textContent` under the hood, which returns the text context of all child nodes, not the HTML. To see the HTML, use `html`:

```js
wrapper.find('.wrapper').html()
```

**Comment by joelworsham** [comment]
~~Gotcha, thank you for the clarification. Is there a way to just grab the children node(s) via `html()`? Because I notice `html()` includes the `.wrapper` in its result.~~

Update: I suppose I could just do so via the CSS immediate child selector. Nevermind. Thanks again for the clarification!
