### ISSUE TITLE
Access $refs Methods

### ISSUE THREAD

**Issue by blaadje** [vuejs/vue-test-utils#983]
### Version
1.0.0-beta.25

### Reproducible link
https://codesandbox.io/s/6x9mw60nkr

### Steps to reproduce
When using jest:

```js
-- Component A.js

export default {
    methods: {
      _onClick () {
        this.$refs.foo.reset()
      }
    },
    render () {
       return (
         <div className='Button' onClick={this._onClick}>Click me</div>
         <ComponentB ref="foo" />
       )
    }
}

-- Component B.js

export default {
    methods: {
      reset () {
        // do something
      }
    },
    render () {
       return (
         <div>Im component B</div>
       )
    }
}

-- test.js

describe('<Component A>', () => {
  it('should trigger reset function', () => {
    const wrapper = mount(ComponentA)
	const spyMethodClick = jest.spyOn(wrapper.vm.$refs.foo.reset())

    const button = wrapper.find('.Button')

    button.trigger('click')
    expect(spyMethodClick).toHaveBeenCalled(1)
  })
})
```

### What is expected?
i expect `wrapper.vm.$refs.foo.reset()` to have been called

### What is actually happening?
`wrapper.vm.$refs.foo` is `undefined`

---
Any idea?

**Comment by eddyerburgh** [comment]
In this example, I believe you are calling `spyOn` incorrectly, and then reassigning an undefined value to the instance. `spyOn` accepts [an object and a string](https://jestjs.io/docs/en/jest-object.html#jestspyonobject-methodname), but you're calling it with the result of a function call.

The second issue is that when you stub a components methods you need to re render the component. You can do that with `$forceUpdate` , or use the `wrapper.setMethods` method.

**Comment by blaadje** [comment]
Okay thanks, by doing those it works fine 😃

**Comment by kamalhm** [comment]
I stumbled upon this problem too and I don't understand eddy's explanation, do you mind showing me the code after the fix? @blaadje

**Comment by blaadje** [comment]
Hey @kamalhm, you can find the updated code [here](https://codesandbox.io/embed/6x9mw60nkr?previewwindow=tests) hopefully it can help you.
