### ISSUE TITLE
Added vue test utils to existing projects

### ISSUE THREAD

**Issue by fsqshadow** [vuejs/vue-test-utils#986]
✗ should render correct contents
        undefined is not a constructor (evaluating 'converted.findIndex(function (item) {
                return equals(item, value, [iterableEquality]);
              })')
        webpack:///node_modules/expect/build-es5/index.js:8572 <- index.js:27942:139
        getMessage@webpack:///node_modules/expect/build-es5/index.js:15115 <- index.js:34485:28
        processResult@webpack:///node_modules/expect/build-es5/index.js:15192 <- index.js:34562:33
        throwingMatcher@webpack:///node_modules/expect/build-es5/index.js:15250 <- index.js:34620:29
        webpack:///test/unit/specs/helloWorld.spec.js:8:40 <- index.js:9602:55

**Comment by fsqshadow** [comment]
Added vue test utils to existing projects

**Comment by eddyerburgh** [comment]
Can you please create an issue using the  [issue helper](https://new-issue.vuejs.org/?repo=vuejs/vue-test-utils) with a minimal reproduction
