### ISSUE TITLE
Send event in a `catch()`

### ISSUE THREAD

**Issue by blaadje** [vuejs/vue-test-utils#989]
### Version
1.0.0-beta.25

### Reproduction link
[https://codesandbox.io/s/2z7y8rok6p](https://codesandbox.io/s/2z7y8rok6p)

### Steps to reproduce
I got a component which triggers some functions when `created`. There's a promise which will return `fetched` Event or `fail`. (the `fetched` event works great)

### What is expected?
`failed` event to be triggered in tests

### What is actually happening?
event is `undefined`

**Comment by eddyerburgh** [comment]
`shallowMount` only returns a wrapper, so using `await` will not wait for any pending Promise callback.

To wait for a pending promise callback, you can use a helper function:

```js
const wrapper = shallowMount(TestComponent)
// flush pending promise callbacks
await new Promise(resolve => setTimeout(resolve))
// free to assert here 
```

Or use a helper library:

```js
import flushPromises from 'flush-promises'

const wrapper = shallowMount(TestComponent)
// flush pending promise callbacks
await flushPromises()
// free to assert here 
```

**Comment by blaadje** [comment]
Thanks once again it works 😄 Good to know
