### ISSUE TITLE
Directives : Access to directives of a wrapper

### ISSUE THREAD

**Issue by sbenyoub-accor** [vuejs/vue-test-utils#993]
**What problem ?**

I wanted to test the content of v-tooltip directive. I faced the following problem : 

`const cmp = shallowMount(Component, defaultParams);`
`expect(cmp.find('div').?????).toEqual('Hello'))`

I don't know how to access the content of the directive.

I wonder if that's possible to access to it in some way like that:

`const cmp = shallowMount(Component, defaultParams);`
`expect(cmp.find('div').directives('tooltip').content).toEqual('Hello'))`

**Comment by HongYangHT** [comment]
@sbenyoub-accor Did you get the right way to deal with it, and I has the same problem.

**Comment by HongYangHT** [comment]
@sbenyoub-accor Did you get the right way to deal with it, and I has the same problem.

**Comment by sbenyoub-accor** [comment]
nop :/
