### ISSUE TITLE
Warnings: Cannot find element app; using runttme-only build when the tested component imports the event bus

### ISSUE THREAD

**Issue by pdagosto** [vuejs/vue-test-utils#997]
### Version
1.0.0-beta.25

### Reproduction link
[https://github.com/pdagosto/vue_minimal](https://github.com/pdagosto/vue_minimal)

### Steps to reproduce
npm run test

### What is expected?
The tests should pass and no warnings should appear.

### What is actually happening?
The tests pass but the following warnings appear:

    console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: Cannot find element: #app
    console.error node_modules/vue/dist/vue.runtime.common.js:589
      [Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.
      
      (found in <Root>)

---
If the following line in src/App.vue is commented out, the warnings will not appear:

import { eventBus } from './main.js';

**Comment by aholzner** [comment]
@pdagosto remove `export const eventBus = new Vue();` from 'main.js' and create a separate file and add this export statement into it and then import it in your App.vue component.

**Comment by pdagosto** [comment]
That did the trick! Thank you sir.

**Comment by pdagosto** [comment]
aholzners suggestion fixed this issue for me.
